### PR TITLE
AF-1799: Upgrade JDK 11 + GWT 2.9

### PR DESCRIPTION
**Pull request by caponetto**
**Upgrade JDK 11 + GWT 2.9**

Feel free to comment and/or raise any concerns.

This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039

Thanks guys for that!

**JIRA**:

[AF-1799](https://issues.redhat.com/browse/AF-1799)

**Parent Pull Request**:
- https://github.com/kiegroup/lienzo-core/pull/134

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins retest this

**Review by mariofusco — APPROVED** [review]

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Review by yesamer — APPROVED** [review]

**Comment by mareknovotny** [comment]
i think you need to change artifactId here too https://github.com/kiegroup/drools/blob/2b65d147e6c244d7eab6f2af4f625c33350518a7/kie-memory-compiler/pom.xml#L35-L39 as in droolsjbpm-build-bootstrap repository https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1488/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R4117 is changed that to powermock-api-mockito2 this is shown as missing 
```
[2021-01-15T07:56:29.146Z] + tee /home/jenkins/workspace/KIE/master/fdb/droolsjbpm-build-bootstrap-master.fdb/kiegroup_drools.maven.log
[2021-01-15T07:56:30.518Z] [INFO] Error stacktraces are turned on.
[2021-01-15T07:56:30.518Z] [INFO] Scanning for projects...
[2021-01-15T07:56:33.824Z] [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[2021-01-15T07:56:33.824Z] [ERROR] 'dependencies.dependency.version' for org.powermock:powermock-api-mockito:jar is missing. @ line 35, column 17
[2021-01-15T07:56:33.824Z]  @ 
[2021-01-15T07:56:33.824Z] [ERROR] The build could not read 1 project -> [Help 1]
[2021-01-15T07:56:33.824Z] org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[2021-01-15T07:56:33.824Z] [ERROR] 'dependencies.dependency.version' for org.powermock:powermock-api-mockito:jar is missing. @ line 35, column 17
[2021-01-15T07:56:33.824Z] 
[2021-01-15T07:56:33.824Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:397)
[2021-01-15T07:56:33.824Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[2021-01-15T07:56:33.824Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[2021-01-15T07:56:33.824Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[2021-01-15T07:56:33.824Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[2021-01-15T07:56:33.824Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[2021-01-15T07:56:33.824Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2021-01-15T07:56:33.824Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2021-01-15T07:56:33.824Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2021-01-15T07:56:33.824Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2021-01-15T07:56:33.824Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2021-01-15T07:56:33.824Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2021-01-15T07:56:33.824Z]     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2021-01-15T07:56:33.824Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2021-01-15T07:56:33.824Z]     at java.lang.reflect.Method.invoke (Method.java:498)
[2021-01-15T07:56:33.824Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2021-01-15T07:56:33.824Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2021-01-15T07:56:33.825Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2021-01-15T07:56:33.825Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2021-01-15T07:56:33.825Z] [ERROR]   
[2021-01-15T07:56:33.825Z] [ERROR]   The project org.kie:kie-memory-compiler:7.49.0-SNAPSHOT (/home/jenkins/workspace/KIE/master/fdb/droolsjbpm-build-bootstrap-master.fdb/kiegroup_drools/kie-memory-compiler/pom.xml) has 1 error
[2021-01-15T07:56:33.825Z] [ERROR]     'dependencies.dependency.version' for org.powermock:powermock-api-mockito:jar is missing. @ line 35, column 17
[2021-01-15T07:56:33.825Z] [ERROR] 
[2021-01-15T07:56:33.825Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[2021-01-15T07:56:33.825Z] [ERROR] 
[2021-01-15T07:56:33.825Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[2021-01-15T07:56:33.825Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[2021-01-15T07:56:33.825Z] + test 1 -eq 0
```

**Comment by caponetto** [comment]
Thanks, @mareknovotny for pointing this out!
This was recently introduced so I'll fix it accordingly on my next sync with the master branch.

**EDIT**: Fixed in https://github.com/kiegroup/drools/pull/3135/commits/ab28cb14c9d5e8e2e950f1ce028b694014b0fc06

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins run cdb

**Review by Srihari1192 — APPROVED** [review]

**Pull request merged**
