### PR TITLE
Decision service null pointer exception fix

### PR DESCRIPTION
**Pull request by SimonRinguette**
@tarilabs There was a small issue with your modification if you have a model without extensions. Can you have a look at this fix please.

### CODE REVIEW

**Comment by tarilabs** [comment]
Ok to test

**Comment by baldimir** [comment]
@SimonRinguette @tarilabs hello, do we have a test for this NPE case? If not, we should create one, so we have this covered for future regression testing.

**Comment by tarilabs** [comment]
@baldimir 

> @SimonRinguette @tarilabs hello, do we have a test for this NPE case? If not, we should create one, so we have this covered for future regression testing.

Proposed here: https://github.com/SimonRinguette/drools/pull/2

**Pull request merged**
