### PR TITLE
DROOLS-5684 DMN DT Analysis Misleading rule definition refinements

### PR DESCRIPTION
**Pull request by tarilabs**
**JIRA**: https://issues.redhat.com/browse/DROOLS-5684

**referenced Pull Requests**: none

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins run cdb

**Comment by tarilabs** [comment]
image

>  0 failed.

yet is red because:

```
Setting status of 25b21c80d78487a7dcdd0c8a2c28cd37dafa785d to FAILURE with url https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/drools-master.pr/13/ and message: 'Build finished. 21111 tests run, 177 skipped, 0 failed.'
Using context: Linux - Pull Request
java.nio.file.NoSuchFileException: /home/jenkins/workspace/KIE/master/pullrequest/drools-master.pr/droolsjbpm-build-bootstrap/sonarAnalysis.stages
```

🤷‍♂️ 🎱 

Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
image

🤷‍♂️ 🎱 🎱 

Jenkins run cdb

**Comment by tarilabs** [comment]
the downstream cdb reports
```
16:44:11  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack (unpack) on project optaweb-employee-rostering-standalone: Unable to find/resolve artifact. Could not find artifact org.optaweb.employeerostering:optaweb-employee-rostering-frontend:zip:7.45.0-SNAPSHOT in mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/) -> [Help 1]
16:44:11  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack (unpack) on project optaweb-employee-rostering-standalone: Unable to find/resolve artifact.
```

I would conclude is unrelated.

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
