### PR TITLE
[7.5.x] DROOLS-2252: (RHDM-83) "Unable to expand" error with accumulate in Guided Rule Editor with DSL

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2252

(https://issues.jboss.org/browse/RHDM-83)

This is the corollary of https://github.com/kiegroup/drools/pull/1700 for 7.5.x

(cherry picked from commit 407aea1fab547ac3f5ce34c0111b0f40deb5b8a6)

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Review by Rikkola — APPROVED** [review]

**Review by jomarko — APPROVED** [review]
@manstis thanks.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
@manstis it seems to me that there is still failing the same test `org.drools.testcoverage.regression.AbstractCompositeRestrictionTest.test`, or?

**Comment by manstis** [comment]
@jomarko Yes, I believe @ryanzhang is fixing.

**Comment by ryanzhang** [comment]
Yes, Will merge the fix soon after test finished at https://github.com/kiegroup/drools/pull/1707.

**Comment by ryanzhang** [comment]
@manstis  I have removed the drools-verifier in testsuite now. Could you please rebase it base on the latest 7.5.x and retest it.
Sorry for blocking your PR.

**Comment by manstis** [comment]
Thanks @ryanzhang

**Pull request merged**
