### PR TITLE
[DROOLS-4522] Add an "expression" property for every complex type in Scenario Testing

### PR DESCRIPTION
**Pull request by yesamer**
@jomarko @gitgabrio @danielezonca can you please test and review it?

This represents the first step of development for https://issues.jboss.org/browse/BAPL-1402

Basically, with the changes introduced in this PR, every complex type object in Scenario has an additional property ("expression") where it will be possible to add expression logic to the referred object (fact). At the moment, the changes involve only front-end side.

https://issues.jboss.org/browse/DROOLS-4522

Related PR: https://github.com/kiegroup/drools-wb/pull/1232

### CODE REVIEW

**Review by gitgabrio — APPROVED** [review]
@yesamer 
Thanks! One of your most brilliant job!

**Comment by jomarko** [comment]
On the first sight, PR seems really simple, however I have concern about I18N. Shouldn't we use GWT Constants as my understanding is this **expression** will appear in UI. Am I missing something? Does new scenarios hardcode everything in code and do not support any other language?

**Review by jomarko — COMMENTED** [review]
@yesamer hello, thanks for the PR. On the first sight, PR seems really simple, however I have concern about I18N. Shouldn't we use GWT Constants as my understanding is this expression will appear in UI. Am I missing something? Does new scenarios hardcode everything in code and do not support any other language?

**Comment by gitgabrio** [comment]
> @yesamer hello, thanks for the PR. On the first sight, PR seems really simple, however I have concern about I18N. Shouldn't we use GWT Constants as my understanding is this expression will appear in UI. Am I missing something? Does new scenarios hardcode everything in code and do not support any other language?

@jomarko @danielezonca 
Hi. This constants are meant to be used only inside code, to replace all the strings we have used (e.g inside switch). They have nothing to do with i18n/client - they are not shown to users. Progressively we'll move all such strings here.

**Review by jomarko — APPROVED** [review]

**Comment by yesamer** [comment]
@jomarko @dupliaka @gitgabrio Please consider this PR on hold, because the UI introduced needs a review from UX/UI team. Thanks

**Pull request closed without merging**
