### PR TITLE
DROOLS-2243_7_5_x - Backport to get kie-pmml visibility for the execu…

### PR DESCRIPTION
**Pull request by lanceleverich**
Backport of kie-pmml code to allow building from pmml resources in workbench

### CODE REVIEW

**Comment by lanceleverich** [comment]
Jenkins retest this

**Comment by mariofusco** [comment]
@lanceleverich Jenkins reports 2 failures for the following test cases

org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testReturnNullNoTrueChildPredictionStrategy
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testNullPredictionMissingValueStrategy

Please give it a look and let me know what to do about this.

**Comment by lanceleverich** [comment]
The PR at https://github.com/kiegroup/droolsjbpm-knowledge/pull/299 needs to be merged so that these failing test cases will pass

**Comment by mariofusco** [comment]
ok to test

**Pull request merged**
