### PR TITLE
[JBPM-9178] Immutable SpringBoot Deployment

### PR DESCRIPTION
**Pull request by elguardian**
Jira 
https://issues.redhat.com/browse/JBPM-9178

### CODE REVIEW

**Comment by elguardian** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1440
https://github.com/kiegroup/droolsjbpm-knowledge/pull/456
https://github.com/kiegroup/kie-soup/pull/152
https://github.com/kiegroup/drools/pull/3043
https://github.com/kiegroup/droolsjbpm-integration/pull/2198

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by elguardian** [comment]
failure not related. Jenkins retest this please.

**Review by afalhambra — APPROVED** [review]
LGTM

**Pull request merged**
