### PR TITLE
[DROOLS-6744] refactor timer service creation and call it only in str…

### PR DESCRIPTION
**Pull request by mariofusco**
…eam mode

**JIRA**: https://issues.redhat.com/browse/DROOLS-6744

### CODE REVIEW

**Comment by mariofusco** [comment]
@triceo this should fix the native compilation in `optaplanner-quarkus-integration` please double check.

**Comment by triceo** [comment]
@mariofusco Thank you! Any idea why `optaplanner-quickstarts` doesn't have the issue?

**Comment by mariofusco** [comment]
> @mariofusco Thank you! Any idea why `optaplanner-quickstarts` doesn't have the issue?

I didn't check, but probably it brings in some kogito dependency?

**Comment by tkobayas** [comment]
@mariofusco  Regarding failed tests in drools repo are NPE which you will likely fix quickly.

Btw, Drools 8 doesn't allow `timer` attribute in DRL unless STREAM mode? 

https://docs.jboss.org/drools/release/latest/drools-docs/html_single/#drl-timers-calendars-con_drl-rules

We don't have tests with `timer` and CLOUD mode (so tests passed) but anyway, Drools 7 can use `timer` with CLOUD mode (and no restriction is written in drools docs for now).

Regarding failed tests in kogito-runtimes, I see that jbpm depends on TimerService:

https://github.com/kiegroup/kogito-runtimes/blob/main/jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java#L89

So we will ask jBPM team to use STREAM mode?

**Comment by mariofusco** [comment]
@tkobayas You're right, my assumption that timers are only used in stream mode was too strong and breaks some tests even in drools. I'll review this and make it lazy regardless of the event processing mode.

**Review by tkobayas — APPROVED** [review]
Approved. But probably you still need to fix `MultipleKbasesExampleTest` which I see test failures.
```
[ERROR] Failures: 
[ERROR]   MultipleKbasesExampleTest.testEditSessionModel:118 expected:<class org.drools.kiesession.session.StatefulKnowledgeSessionImpl$DummySessionClock> but was:<class org.drools.core.time.impl.PseudoClockScheduler>
[ERROR]   MultipleKbasesExampleTest.testEditSessionModelAfterFirstCreatedKieSession:137 expected:<class org.drools.kiesession.session.StatefulKnowledgeSessionImpl$DummySessionClock> but was:<class org.drools.core.time.impl.JDKTimerService>
```

**Pull request merged**
