### PR TITLE
DROOLS-6478 xls2dmn refactor of code review feedback

### PR DESCRIPTION
**Pull request by tarilabs**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6478

**referenced Pull Requests**: none

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
```
07:59:27  [INFO]  Executing pull request flow for https://github.com/kiegroup/drools/pull/3717 in bc
07:59:27  [ERROR]  version 2.0 is not allowed in definition file. Allowed versions: 2.1
```

🤷‍♂️ 

Jenkins retest this

**Comment by tarilabs** [comment]
```
08:00:11  [INFO]  Executing pull request flow for https://github.com/kiegroup/drools/pull/3717 in bc
08:00:11  [ERROR]  version 2.0 is not allowed in definition file. Allowed versions: 2.1
```

🤷‍♂️ 

Jenkins execute cdb

**Review by pibizza — APPROVED** [review]

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins execute cdb

**Comment by tarilabs** [comment]
all Jenkins is green. Thanks again @Ginxo for having fixed the CI settings

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
