### PR TITLE
[7.67.x][DROOLS-7001] Update KeyStoreHelper signature (#4448)

### PR DESCRIPTION
**Pull request by tkobayas**
**Ports** 
This is a backport-PR of https://github.com/kiegroup/drools/pull/4448 for 7.67.x

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4461

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
Hmm, Jenkins doesn't trigger fdb. Could you kindly revive it? @mbiarnes

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Comment by mbiarnes** [comment]
Jenkins run cdb

**Comment by tkobayas** [comment]
Jenkins run cdb

**Comment by tkobayas** [comment]
https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.67.x/job/compile/job/drools-7.67.x.compile/3 results in timeout but I can download https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.67.x/job/compile/job/drools-7.67.x.compile/3/consoleText
```
[2022-07-29T02:17:34.411Z] org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0082: Failed to create backup copies of configuration file /home/jenkins/workspace/KIE/7.67.x/compile/drools-7.67.x.compile/bc/kiegroup_kie_wb_distributions/business-central-parent/business-central-webapp/target/bootable-jar-build-artifacts/wildfly/standalone/configuration/standalone.xml
[2022-07-29T02:17:34.411Z]      at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.persistence.ConfigurationFile.successfulBoot(ConfigurationFile.java:545)
[2022-07-29T02:17:34.411Z]      at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.persistence.BackupXmlConfigurationPersister.successfulBoot(BackupXmlConfigurationPersister.java:95)
[2022-07-29T02:17:34.411Z]      at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.AbstractControllerService.finishBoot(AbstractControllerService.java:580)
[2022-07-29T02:17:34.411Z]      at org.jboss.as.server@15.0.1.Final//org.jboss.as.server.ServerService.finishBoot(ServerService.java:445)
[2022-07-29T02:17:34.411Z]      at org.jboss.as.server@15.0.1.Final//org.jboss.as.server.ServerService.boot(ServerService.java:415)
[2022-07-29T02:17:34.411Z]      at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:416)
[2022-07-29T02:17:34.411Z]      at java.base/java.lang.Thread.run(Thread.java:829)
[2022-07-29T02:17:34.411Z] Caused by: java.nio.file.NoSuchFileException: /home/jenkins/workspace/KIE/7.67.x/compile/drools-7.67.x.compile/bc/kiegroup_kie_wb_distributions/business-central-parent/business-central-webapp/target/bootable-jar-build-artifacts/wildfly/standalone/configuration/standalone.xml
[2022-07-29T02:17:34.411Z]      at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[2022-07-29T02:17:34.411Z]      at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[2022-07-29T02:17:34.411Z]      at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
[2022-07-29T02:17:34.411Z]      at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
[2022-07-29T02:17:34.411Z]      at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
[2022-07-29T02:17:34.411Z]      at java.base/java.nio.file.Files.copy(Files.java:1295)
[2022-07-29T02:17:34.411Z]      at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.persistence.FilePersistenceUtils.copyFile(FilePersistenceUtils.java:104)
[2022-07-29T02:17:34.411Z]      at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.persistence.ConfigurationFile.successfulBoot(ConfigurationFile.java:539)
[2022-07-29T02:17:34.411Z]      ... 6 more
...
[2022-07-29T02:17:34.411Z] [INFO] FAILURE build of project org.kie:business-central-webapp
...
[2022-07-29T02:18:25.103Z] [INFO] Business Central - Webapp .......................... FAILURE [ 51.260 s]
```
The failure is not related to this PR. As FDB is green, I think it's okay to merge.

**Comment by tkobayas** [comment]
@mariofusco Please merge this backport PR, thanks!

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
