### PR TITLE
[7.52.x] DROOLS-6265 : Guided Rule Editor: Formula with contains does not reopen correctly

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**: 

[DROOLS-6265](https://issues.redhat.com/browse/DROOLS-6265)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by yesamer — APPROVED** [review]

**Review by jomarko — APPROVED** [review]
Thank you for a cherry-pick.

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
camel 

jenkins run fdb

**Comment by Rikkola** [comment]
`[2021-04-15T06:56:26.153Z] [ERROR]  You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.`

jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Kafka tests failing.

Jenkins run fdb

**Comment by Rikkola** [comment]
` [ERROR] /home/jenkins/workspace/KIE/7.52.x/fdb/drools-7.52.x.fdb/bc/kiegroup_droolsjbpm_integration/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/QueryDataServiceBaseTest.java:[59,53] no suitable constructor found for UserTaskInstanceWithPotOwnerDesc(java.lang.String,java.lang.String,java.util.Date,java.util.Date,java.lang.Long,java.lang.String,java.lang.String,int,java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)`


Jenkins run fdb

**Comment by Rikkola** [comment]
`[ERROR]  You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.`

Jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins do cdb

**Comment by mareknovotny** [comment]
jenkins do cdb

**Comment by mareknovotny** [comment]
closing as the jira was retargeted to master branch only

**Pull request closed without merging**
