### PR TITLE
drools-pmml: don't print unnecessary info to sysout during tests

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by sotty** [comment]
Agree it should not go to sysout.
The test should make some assertions though:
- validate against the xsd schema
- check that the NN parameters in the XML matches the expected content

**Comment by psiroky** [comment]
@sotty I agree about the assertions, but I am afraid I don't have the knowledge to add those (at least not without some non-trivial time spent studying the pmml module). I merely tracked down the source of those messages and disabled them. Would it be possible for you to take a look at adding those assertions?

**Comment by sotty** [comment]
I have created a PR with an improved version of this test

**Comment by psiroky** [comment]
Thanks @sotty, I am closing this PR in favor of #484

**Pull request closed without merging**
