### PR TITLE
DROOLS-2927 DMN DecisionTable inputClause importing ItemDefinition ...

### PR DESCRIPTION
**Pull request by tarilabs**
... throws NPE at compilation

/cc @etirelli @baldimir @jiripetrlik

### CODE REVIEW

**Comment by tarilabs** [comment]
```
Test Result (2 failures / -10)
org.drools.persistence.session.JpaOptLockPersistentStatefulSessionTest.testOptimisticLockInterceptor
org.drools.scorecards.ScorecardReasonCodeTest.testReasonCodesCombinations
```
unrelated.

Jenkins test again

**Comment by tarilabs** [comment]
```
org.drools.persistence.session.JpaOptLockPersistentStatefulSessionTest.testOptimisticLockInterceptor
```

unrelated.

Jenkins test again

**Comment by tarilabs** [comment]
```
org.drools.persistence.session.JpaOptLockPersistentStatefulSessionTest.testOptimisticLockInterceptor
```

Jenkins test again

**Comment by tarilabs** [comment]
@AntStephenson can you kindly merge this PR for me before kicking-off the tag on 2018-08-26, please?

**Comment by mswiderski** [comment]
@MarianMacik looks like jpa optimistic lock is randomly failing, but only the first one. The other that check max retries seems ro be stable so maybe we can keep only that one as it tests the feature any way, wdyt?

**Comment by mbiarnes** [comment]
@tarilabs @mswiderski I will merge this PR as it is needed for Trisotech tag

**Pull request merged**
