### PR TITLE
[DROOLS-6486] avoid creating a FactHandle for an object already prese…

### PR DESCRIPTION
**Pull request by mariofusco**
…nt in the working memory while evaluating a FromNode

**JIRA**: https://issues.redhat.com/browse/DROOLS-6486

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute fdb

**Review by lucamolteni — APPROVED** [review]

**Comment by lucamolteni** [comment]
@mariofusco I'm not sure I got the fix, is this something that wasn't needed in DRL?

**Comment by mariofusco** [comment]
> @mariofusco I'm not sure I got the fix, is this something that wasn't needed in DRL?

@lucamolteni this is both an improvement for the whole engine and a fix for the executable model. It's an improvement because in all cases it avoids to create a duplicated FactHandle for a fact that is already present in the working memory. 

As for the fix, the drl in its generated consequence has a resolution mechanism that eventually checks for the existence of the duplicated FactHandle and retrieves the "right one" to be used with a modify. This mechanism doesn't exist for the executable model consequence and I didn't want to add it also there (also for performance reasons), so avoiding to create the duplicated FactHandle at all indirectly also solves the problem for the executable model.

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
The only failing test is `org.kie.wb.test.rest.functional.ProjectIntegrationTest.testGetBranches` which is clearly unrelated to this.

**Review by hellowdan — APPROVED** [review]

**Review by pibizza — APPROVED** [review]
Change is good, but we are still missing proper unit testing.

**Pull request merged**
