### PR TITLE
DROOLS-7139 - FEEL context functions `get value` and `get entries` should support Java POJO as argument

### PR DESCRIPTION
**Pull request by vpiyanov**
Proposed fix for defect https://issues.redhat.com/browse/DROOLS-7139

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
Hi @vpiyanov thank you for reporting the JIRA and providing the fix!
I quickly skimmed this and overall I believe is okay, I will just seize the chance for some small improvements --will add to this PR keeping your attributions over the next days

**Comment by tarilabs** [comment]
added just a couple of refactoring considering existing test/code.
/cc @baldimir this is a gap covered which I will later fwd port to main once merged here.

**Review by baldimir — APPROVED** [review]

**Comment by baldimir** [comment]
Thank you very much for your contribution, I approved. Let's see if the builds are green.

**Comment by tarilabs** [comment]
Jenkins retest this

**Review by hellowdan — APPROVED** [review]

**Review by tarilabs — APPROVED** [review]
Thanks again @vpiyanov 

All green, merging and fwd porting to main

**Pull request merged**
