### PR TITLE
DROOLS-4697 Simple toString() for RuleImpl

### PR DESCRIPTION
**Pull request by triceo**
@mariofusco This is the PR we talked about last week. I think it will be enough for us. Let me know if it works for you, or if you need me to change something.

### CODE REVIEW

**Review by baldimir — COMMENTED** [review]
Could you please add some tests for this so no one breaks this for you in the future?

**Review by mariofusco — APPROVED** [review]

**Comment by triceo** [comment]
@baldimir Will do.

**Comment by triceo** [comment]
Test added. I discussed this with Mario in DM yesterday and, when green, I will merge.

**Comment by triceo** [comment]
Red because Jenkins failed to contact Sonar. No test failures. Since I've seen Sonar results with a previous commit, I'm going to merge when the compile downstream job finishes.

**Review by baldimir — APPROVED** [review]

**Pull request merged**
