### PR TITLE
DROOLS-2506 Lexical scope for FEEL Function invocation

### PR DESCRIPTION
**Pull request by tarilabs**
/cc @etirelli the issue is confirmed also at FEEL layer and this should fix.

Unfortunately, it does not automatically reflect in a resolution at DMN layer :( will explain later

### CODE REVIEW

**Review by etirelli — APPROVED** [review]

**Comment by etirelli** [comment]
Excellent @tarilabs! I think it is fine to use the root object for this, so go ahead!

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by manstis** [comment]
@tarilabs Jenkins is broken. Dead. Please see @pszubiak email to BSIG-ALL.

**Comment by tarilabs** [comment]
I know but just now is resumed with limits hence I want to be there in the early queue :)

**Comment by tarilabs** [comment]
Jenkins test again please me first thanks :)

**Comment by tarilabs** [comment]
Jenkins test again

**Review by baldimir — APPROVED** [review]

**Pull request merged**
