### PR TITLE
[7.44.x] DROOLS-5696 : Guided Rule Editor: Call method on XYZ with formula containing quotes does not re-open correctly

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit fd5253ebf9af647b187dc4871bc3342c54d0fc48)

**JIRA**: 

[link](https://issues.redhat.com/browse/DROOLS-5696)
 

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
@karreiro @jstastny-cz Hi, the same PR as here for 7.44.x.
https://github.com/kiegroup/drools/pull/3141

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Review by karreiro — APPROVED** [review]
Thank you, @Rikkola.

**Comment by mareknovotny** [comment]
FDB failures are related to docker hub rate limit policy :(

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by jstastny-cz** [comment]
I can reproduce the original issue when I have following rule:
* the argument is Literal and value `"$value,$value"` (I assume that's a valid Literal value)
* when I put same input as Formula all works well.
Screenshot from 2020-11-12 11-01-48

**Comment by Rikkola** [comment]
@jstastny-cz Let's see if this fixes it https://github.com/kiegroup/drools/pull/3238

**Comment by karreiro** [comment]
Good catch, @jstastny-cz. The solution proposed by https://github.com/kiegroup/drools/pull/3238 seems fine to me ;-)

**Review by jstastny-cz — APPROVED** [review]
We've reached an agreement that the issue reported during PR review can be handled separately as it is not directly linked to the reported issue (formula vs. literal).
We should go ahead with the fix for formula (this PR) and create a separate issue for the Literal.

**Comment by Rikkola** [comment]
Jenkins run cdb

**Comment by Rikkola** [comment]
Jenkins run cdb

**Comment by Rikkola** [comment]
> [2020-11-18T09:38:14.998Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kie-server-services-common: Compilation failure: Compilation failure: 
> [2020-11-18T09:38:14.998Z] [ERROR] /home/jenkins/workspace/KIE/7.44.x/compileDownstream/drools-7.44.x.compile/kiegroup_droolsjbpm-integration/kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java:[1057,20] incompatible types: org.kie.server.api.model.ServiceResponse<org.kie.server.api.model.KieServerStateInfo> cannot be converted to org.kie.server.api.model.KieServerStateInfo
> [2020-11-18T09:38:14.998Z] [ERROR] /home/jenkins/workspace/KIE/7.44.x/compileDownstream/drools-7.44.x.compile/kiegroup_droolsjbpm-integration/kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java:[1062,20] incompatible types: org.kie.server.api.model.ServiceResponse<org.kie.server.api.model.KieServerStateInfo> cannot be converted to org.kie.server.api.model.KieServerStateInfo

Jenkins run cdb

**Comment by Rikkola** [comment]
> [2020-11-18T10:18:09.872Z] + /home/jenkins/workspace/KIE/7.44.x/compileDownstream/drools-7.44.x.compile/trace.sh
> [2020-11-18T10:18:09.872Z] /home/jenkins/workspace/KIE/7.44.x/compileDownstream/drools-7.44.x.compile@tmp/durable-eb733bc3/script.sh: line 1: /home/jenkins/workspace/KIE/7.44.x/compileDownstream/drools-7.44.x.compile/trace.sh: No such file or directory
> Error when executing failure post condition:
> hudson.AbortException: script returned exit code 1
> 	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:569)
> 	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:515)
> 	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:461)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

Jenkins run cdb

**Comment by Rikkola** [comment]
> [2020-11-18T14:25:38.981Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kie-server-services-common: Compilation failure: Compilation failure: 
> [2020-11-18T14:25:38.981Z] [ERROR] /home/jenkins/workspace/KIE/7.44.x/compileDownstream/drools-7.44.x.compile/kiegroup_droolsjbpm-integration/kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java:[1057,20] incompatible types: org.kie.server.api.model.ServiceResponse<org.kie.server.api.model.KieServerStateInfo> cannot be converted to org.kie.server.api.model.KieServerStateInfo
> [2020-11-18T14:25:38.981Z] [ERROR] /home/jenkins/workspace/KIE/7.44.x/compileDownstream/drools-7.44.x.compile/kiegroup_droolsjbpm-integration/kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java:[1062,20] incompatible types: org.kie.server.api.model.ServiceResponse<org.kie.server.api.model.KieServerStateInfo> cannot be converted to org.kie.server.api.model.KieServerStateInfo

Jenkins run cdb

**Comment by mareknovotny** [comment]
the failures are related to container images limit or timed out jbpm integration tests

**Pull request merged**
