### PR TITLE
[DROOLS-6493] put kie conf files in different folders

### PR DESCRIPTION
**Pull request by mariofusco**
JIRA: https://issues.redhat.com/browse/DROOLS-6493

Related PRs:
droolsjbpm-knowledge: https://github.com/kiegroup/droolsjbpm-knowledge/pull/535
drools: https://github.com/kiegroup/drools/pull/3741
jbpm: https://github.com/kiegroup/jbpm/pull/1979
droolsjbpm-integration: https://github.com/kiegroup/droolsjbpm-integration/pull/2545
kie-jpmml-integration: https://github.com/kiegroup/kie-jpmml-integration/pull/60

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Review by lucamolteni — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Review by danielezonca — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins retest this

**Pull request merged**
