### PR TITLE
[7.3.x] PLANNER-828: Workbench: ScoreHolder support in GuidedRuleEditor shows error in server log

### PR DESCRIPTION
**Pull request by mcimbora**
Just a backport of the fix from https://github.com/kiegroup/drools/pull/1422.

### CODE REVIEW

**Comment by mcimbora** [comment]
@manstis Could you please ack/merge the PR once green? Thanks.

**Review by manstis — APPROVED** [review]

**Comment by manstis** [comment]
@mcimbora Sure.. it's easier for you to monitor when your PRs are green though.. so please ping me when good to merge. Thanks.

**Comment by mcimbora** [comment]
@manstis I see, sounds like a deal.

**Comment by mcimbora** [comment]
@manstis The build succeeded. Thanks.

**Pull request merged**
