### PR TITLE
[DO-NOT-MERGE] [DROOLS-7413] Evaluate remote fire store configuration

### PR DESCRIPTION
**Pull request by tkobayas**
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7413

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

 - for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by mariofusco** [comment]
@tkobayas can we close this pull request or is there still some ongoing work on it?

**Comment by kie-ci4** [comment]
**(tests) - kie-jpmml-integration job** `#7` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kie-jpmml-integration -u https://github.com/kiegroup/drools/pull/5188 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kie-jpmml-integration/7/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.3'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh3446186733317448648.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision b5386f62f60a67bebb165b63bfb1da07eeae98b5<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/drools/jobs/main/jobs/pullrequest/jobs/drools.tests.downstream.kie-jpmml-integration/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.3'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/drools/jobs/main/jobs/pullrequest/jobs/drools.tests.downstream.kie-jpmml-integration/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh15537301513200254406.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision b5386f62f60a67bebb165b63bfb1da07eeae98b5 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f b5386f62f60a67bebb165b63bfb1da07eeae98b5 # timeout=10<br/>Commit message: "KOGITO-9692 Add method githubscm.getPreviousTagFromVersion (#296)"<br/> > git rev-list --no-walk b5386f62f60a67bebb165b63bfb1da07eeae98b5 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Still waiting to schedule task<br/>Waiting for next available executor on ‘kie-rhel8&&docker&&kie-mem16g&&!built-in’<br/>Running on rhos-01-kie-rhel8-xlarge-docker-1267 in /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kie-jpmml-integration<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci4<br/>Cloning the remote Git repository<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kie-jpmml-integration # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.3'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci4 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Avoid second fetch<br/>Checking out Revision e4ca54768237b244281f1afb11a8b872df840e9a (origin/main)<br/>Commit message: "KOGITO-9725 DSL cleanup: Remove 'kogito-bdd' check (#1044)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-08-21T13:36:21.963Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2023-08-21T13:36:22.059Z] Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-01-kie-rhel8-xlarge-docker-1267<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f e4ca54768237b244281f1afb11a8b872df840e9a # timeout=10<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-08-21T13:36:24.250Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-08-21T13:36:24.275Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-08-21T13:36:24.925Z] Running in /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kie-jpmml-integration<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-08-21T13:36:24.957Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-08-21T13:36:25.234Z] + df -h<br/>[2023-08-21T13:36:25.235Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-08-21T13:36:25.235Z] devtmpfs        7.7G     0  7.7G   0% /dev<br/>[2023-08-21T13:36:25.235Z] tmpfs           7.7G     0  7.7G   0% /dev/shm<br/>[2023-08-21T13:36:25.235Z] tmpfs           7.7G   17M  7.7G   1% /run<br/>[2023-08-21T13:36:25.235Z] tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup<br/>[2023-08-21T13:36:25.235Z] /dev/vda3        80G   22G   59G  28% /<br/>[2023-08-21T13:36:25.235Z] /dev/vda2       100M  5.8M   95M   6% /boot/efi<br/>[2023-08-21T13:36:25.235Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2023-08-21T13:36:25.255Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2023-08-21T13:36:25.531Z] + du -h -d1 /home/jenkins<br/>[2023-08-21T13:36:25.531Z] 4.0K	/home/jenkins/.ssh<br/>[2023-08-21T13:36:25.531Z] 0	/home/jenkins/go<br/>[2023-08-21T13:36:25.531Z] 8.0K	/home/jenkins/.vnc<br/>[2023-08-21T13:36:25.531Z] 8.0K	/home/jenkins/.m2<br/>[2023-08-21T13:36:25.531Z] 2.2G	/home/jenkins/git-repos<br/>[2023-08-21T13:36:25.531Z] 8.0K	/home/jenkins/.config<br/>[2023-08-21T13:36:25.786Z] 154M	/home/jenkins/virtenvs<br/>[2023-08-21T13:36:25.786Z] 4.0K	/home/jenkins/.cekit<br/>[2023-08-21T13:36:25.786Z] 30M	/home/jenkins/remoting<br/>[2023-08-21T13:36:25.786Z] 0	/home/jenkins/.cache<br/>[2023-08-21T13:36:25.786Z] 14M	/home/jenkins/workspace<br/>[2023-08-21T13:36:25.786Z] 100M	/home/jenkins/tools<br/>[2023-08-21T13:36:25.786Z] 0	/home/jenkins/caches<br/>[2023-08-21T13:36:25.786Z] 2.5G	/home/jenkins<br/>[Pipeline] echo<br/>[2023-08-21T13:36:25.806Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2023-08-21T13:36:26.088Z] + du -h -d3 /home/jenkins/workspace<br/>[2023-08-21T13:36:26.088Z] 14M	/home/jenkins/workspace/KIE/drools/main<br/>[2023-08-21T13:36:26.088Z] 14M	/home/jenkins/workspace/KIE/drools<br/>[2023-08-21T13:36:26.088Z] 14M	/home/jenkins/workspace/KIE<br/>[2023-08-21T13:36:26.088Z] 14M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-08-21T13:36:26.655Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2023-08-21T13:36:26.729Z] [INFO] build-chain version recovered '^v3'<br/>[Pipeline] sh<br/>[2023-08-21T13:36:27.019Z] + npm install -g '@kie/build-chain-action@^v3' -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2023-08-21T13:36:32.251Z] <br/>[2023-08-21T13:36:32.251Z] added 95 packages, and audited 96 packages in 5s<br/>[2023-08-21T13:36:32.251Z] <br/>[2023-08-21T13:36:32.251Z] 5 packages are looking for funding<br/>[2023-08-21T13:36:32.251Z]   run `npm fund` for details<br/>[2023-08-21T13:36:32.251Z] <br/>[2023-08-21T13:36:32.251Z] found 0 vulnerabilities<br/>[Pipeline] sh<br/>[2023-08-21T13:36:32.543Z] + npm list -g<br/>[2023-08-21T13:36:32.543Z] + grep build-chain<br/>[2023-08-21T13:36:32.798Z] ├── @kie/build-chain-action@3.5.3<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-08-21T13:36:33.191Z] LD_LIBRARY_PATH = /opt/tools/graalvm/lib/server<br/>[Pipeline] echo<br/>[2023-08-21T13:36:33.218Z] BUILD_MVN_OPTS_CURRENT =  <br/>[Pipeline] configFileProvider<br/>[2023-08-21T13:36:33.230Z] provisioning config files...<br/>[2023-08-21T13:36:33.236Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kie-jpmml-integration@tmp/config2322754575822370037tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2023-08-21T13:36:33.285Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-08-21T13:36:33.327Z] BUILD_MVN_OPTS =  -s /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kie-jpmml-integration@tmp/config2322754575822370037tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true<br/>[Pipeline] sh<br/>[2023-08-21T13:36:33.349Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2023-08-21T13:36:33.349Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2023-08-21T13:36:33.350Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2023-08-21T13:36:33.635Z] + source /home/jenkins/virtenvs/swf/bin/activate<br/>[2023-08-21T13:36:33.635Z] ++ '[' /home/jenkins/virtenvs/swf/bin/activate = /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kie-jpmml-integration@tmp/durable-7997ee7a/script.sh ']'<br/>[2023-08-21T13:36:33.635Z] ++ deactivate nondestructive<br/>[2023-08-21T13:36:33.635Z] ++ unset -f pydoc<br/>[2023-08-21T13:36:33.635Z] ++ '[' -z '' ']'<br/>[2023-08-21T13:36:33.635Z] ++ '[' -z '' ']'<br/>[2023-08-21T13:36:33.635Z] ++ hash -r<br/>[2023-08-21T13:36:33.635Z] ++ '[' -z '' ']'<br/>[2023-08-21T13:36:33.635Z] ++ unset VIRTUAL_ENV<br/>[2023-08-21T13:36:33.635Z] ++ '[' '!' nondestructive = nondestructive ']'<br/>[2023-08-21T13:36:33.635Z] ++ VIRTUAL_ENV=/home/jenkins/virtenvs/swf<br/>[2023-08-21T13:36:33.635Z] ++ '[' linux-gnu = cygwin ']'<br/>[2023-08-21T13:36:33.635Z] ++ '[' linux-gnu = msys ']'<br/>[2023-08-21T13:36:33.635Z] ++ export VIRTUAL_ENV<br/>[2023-08-21T13:36:33.635Z] ++ _OLD_VIRTUAL_PATH=/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-08-21T13:36:33.635Z] ++ PATH=/home/jenkins/virtenvs/swf/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-08-21T13:36:33.635Z] ++ export PATH<br/>[2023-08-21T13:36:33.635Z] ++ '[' -z '' ']'<br/>[2023-08-21T13:36:33.635Z] ++ '[' -z '' ']'<br/>[2023-08-21T13:36:33.635Z] ++ _OLD_VIRTUAL_PS1=<br/>[2023-08-21T13:36:33.635Z] ++ '[' x '!=' x ']'<br/>[2023-08-21T13:36:33.635Z] +++ basename /home/jenkins/virtenvs/swf<br/>[2023-08-21T13:36:33.635Z] ++ PS1='(swf) '<br/>[2023-08-21T13:36:33.635Z] ++ export PS1<br/>[2023-08-21T13:36:33.635Z] ++ alias pydoc<br/>[2023-08-21T13:36:33.635Z] ++ true<br/>[2023-08-21T13:36:33.635Z] ++ hash -r<br/>[2023-08-21T13:36:33.635Z] + build-chain build cross_pr --token **** -f https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml -o bc -p kiegroup/kie-jpmml-integration -u https://github.com/kiegroup/drools/pull/5188 --skipParallelCheckout<br/>[2023-08-21T13:36:34.995Z] # Executing pre section<br/>[2023-08-21T13:36:34.995Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kie-jpmml-integration@tmp/config2322754575822370037tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-08-21T13:36:34.995Z] BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kie-jpmml-integration@tmp/config2322754575822370037tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-08-21T13:36:34.995Z] [command]/usr/bin/echo BUILD_MVN_OPTS_CURRENT=  dependency:tree<br/>[2023-08-21T13:36:34.995Z] BUILD_MVN_OPTS_CURRENT=  dependency:tree<br/>[2023-08-21T13:36:34.995Z] [command]/usr/bin/echo QUARKUS_VERSION=<br/>[2023-08-21T13:36:34.995Z] QUARKUS_VERSION=<br/>[2023-08-21T13:36:34.995Z] [command]/usr/bin/echo ENABLE_DEPLOY=<br/>[2023-08-21T13:36:34.995Z] ENABLE_DEPLOY=<br/>[2023-08-21T13:36:34.995Z]  <br/>[2023-08-21T13:36:34.995Z] # Execution Plan<br/>[2023-08-21T13:36:34.995Z] [INFO] 2 projects will be executed<br/>[2023-08-21T13:36:34.995Z] [INFO] [kiegroup/drools]<br/>[2023-08-21T13:36:34.995Z] [INFO] 	 Level type: upstream<br/>[2023-08-21T13:36:34.995Z] [INFO] 	 [before]<br/>[2023-08-21T13:36:34.995Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-08-21T13:36:34.995Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-08-21T13:36:34.995Z] [INFO] 	 [commands]<br/>[2023-08-21T13:36:34.995Z] [INFO] 		 mvn clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-08-21T13:36:34.995Z] [INFO] 	 [after]<br/>[2023-08-21T13:36:34.995Z] [INFO] 		 docker system prune -f<br/>[2023-08-21T13:36:34.995Z] [INFO] [kiegroup/kie-jpmml-integration]<br/>[2023-08-21T13:36:34.995Z] [INFO] 	 Level type: current<br/>[2023-08-21T13:36:34.995Z] [INFO] 	 [before]<br/>[2023-08-21T13:36:34.995Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_CURRENT }}<br/>[2023-08-21T13:36:34.995Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_CURRENT }}; fi"<br/>[2023-08-21T13:36:34.995Z] [INFO] 	 [commands]<br/>[2023-08-21T13:36:34.995Z] [INFO] 		 export MVN_CMD=`bash -c "if [ '${{ env.ENABLE_DEPLOY }}' = 'true' ]; then printf 'deploy ${{ env.DEPLOY_MVN_OPTS }} ${{ env.KIE_JPMML_INTEGRATION_DEPLOY_MVN_OPTS }}'; else printf 'install'; fi"`<br/>[2023-08-21T13:36:34.995Z] mvn clean ${{ env.MVN_CMD }} ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_CURRENT }} ${{ env.KIE_JPMML_INTEGRATION_BUILD_MVN_OPTS }}<br/>[2023-08-21T13:36:34.995Z] [INFO] 	 [after]<br/>[2023-08-21T13:36:34.995Z] [INFO] 		 docker system prune -f<br/>[2023-08-21T13:36:34.995Z]  <br/>[2023-08-21T13:36:34.995Z] # Checking out kiegroup/kie-jpmml-integration and its dependencies (2 projects in total). It can take some time.<br/>[2023-08-21T13:36:49.837Z] [ERROR] [kiegroup/drools] Error merging tkobayas/drools:remote-file-store<br/>[2023-08-21T13:36:49.837Z]                       into kiegroup/drools:main<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[2023-08-21T13:36:49.926Z] Deleting 1 temporary files<br/>[Pipeline] // configFileProvider<br/>[Pipeline] }<br/>[Pipeline] // script<br/>Post stage<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-08-21T13:36:50.387Z] + find . -type d -name node_modules -exec rm -rf '{}' ';'<br/>[Pipeline] junit<br/>[2023-08-21T13:36:50.413Z] Recording test results<br/>[2023-08-21T13:36:50.815Z] [Checks API] No suitable checks publisher found.<br/>[Pipeline] archiveArtifacts<br/>[2023-08-21T13:36:50.830Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-08-21T13:36:49.806Z] No test report files were found. Configuration error?<br/>[2023-08-21T13:36:51.469Z] + rm -rf console.log<br/>[Pipeline] sh<br/>
</details>

**Comment by tkobayas** [comment]
Here is the benchmark result.

https://github.com/kiegroup/drools/pull/5188
https://github.com/kiegroup/kie-benchmarks/pull/233

```
Benchmark                 (factsNr)  (joinsNr)             (mode)  (rulesNr)  Mode  Cnt    Score   Error  Units
InsertOnlyBenchmark.test         10          3             REMOTE        768    ss  100    3.077 ± 0.215  ms/op
InsertOnlyBenchmark.test         10          3  REMOTE_FILE_STORE        768    ss  100    4.750 ± 0.317  ms/op
InsertOnlyBenchmark.test        100          3             REMOTE        768    ss  100   20.731 ± 0.525  ms/op
InsertOnlyBenchmark.test        100          3  REMOTE_FILE_STORE        768    ss  100   32.107 ± 0.603  ms/op
InsertOnlyBenchmark.test       1000          3             REMOTE        768    ss  100  197.794 ± 3.519  ms/op
InsertOnlyBenchmark.test       1000          3  REMOTE_FILE_STORE        768    ss  100  329.814 ± 3.168  ms/op
```

I think it's enough to confirm the result (and how to test) and we don't need to merge this mode and benchmark, because it would somewhat complicate the code base.

**Comment by tkobayas** [comment]
Closing because this is just for evaluation.

**Pull request closed without merging**
