### PR TITLE
DROOLS-3380 - Refactor EvalHelper.normalizeVariableName()

### PR DESCRIPTION
**Pull request by barreiro**
This includes a fast-path for characters know to be valid that improves DMNEvaluateDecisionNameLengthBenchmark results in 10%

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mariofusco** [comment]
ok to test

**Comment by mariofusco** [comment]
@barreiro This PR is making FEELContextsTest.testExpression to fail. Please check it

**Comment by barreiro** [comment]
@mariofusco the problem was when there was a single 'non-regular' space char. That has to be replaced with the regular space char ```' '```. Added an expression to EvalHelperTest.

**Comment by tarilabs** [comment]
Thanks @barreiro --noticed this just now, please tag me when you submit a PR to DMN, so I can react more quickly for the Jenkins too (as I'm not gatekeeper I don't sub to repo-wide notification)

**Pull request merged**
