### PR TITLE
DROOLS-7028 - fix NPE: decision table has FIRST hit policy and result is null

### PR DESCRIPTION
**Pull request by vpiyanov**
**JIRA**: https://issues.redhat.com/browse/DROOLS-7028

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins run cdb

**Review by tarilabs — APPROVED** [review]
ready to go as soon as all CI green. thanks again @vpiyanov !

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins run cdb

**Comment by tarilabs** [comment]
Jenkins run cdb

**Comment by tarilabs** [comment]
the `Linux - Compile Downstream Build — Build finished. 16 tests run, 0 skipped, 0 failed.` in ([link](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.x/job/compile/job/drools-7.x.compile/335/))
```
[2022-06-21T09:49:12.122Z] [INFO] Business Central - Webapp .......................... FAILURE [ 50.616 s]
[2022-06-21T09:49:12.122Z] [INFO] Business Central - Distribution Wars Parent ........ SUCCESS [  2.373 s]
[2022-06-21T09:49:12.122Z] [INFO] Business Central - Monitoring Distribution Wars .... SUCCESS [ 32.461 s]
[2022-06-21T09:49:12.122Z] [INFO] Business Central - Distribution Wars ............... SKIPPED
[2022-06-21T09:49:12.122Z] [INFO] jBPM server distribution ........................... SKIPPED
[2022-06-21T09:49:12.122Z] [INFO] business central add-ons distribution .............. SUCCESS [ 30.937 s]
[2022-06-21T09:49:12.122Z] [INFO] Business Central Tests :: Parent ................... SKIPPED
[2022-06-21T09:49:12.122Z] [INFO] Business Central Tests :: REST API ................. SKIPPED
[2022-06-21T09:49:12.122Z] [INFO] KIE (Drools) Workbench Tests :: GUI ................ SKIPPED
[2022-06-21T09:49:12.122Z] [INFO] ------------------------------------------------------------------------
[2022-06-21T09:49:12.122Z] [INFO] BUILD FAILURE
[2022-06-21T09:49:12.122Z] [INFO] ------------------------------------------------------------------------
[2022-06-21T09:49:12.122Z] [INFO] Total time:  02:01 min (Wall Clock)
[2022-06-21T09:49:12.122Z] [INFO] Finished at: 2022-06-21T05:49:11-04:00
[2022-06-21T09:49:12.122Z] [INFO] ------------------------------------------------------------------------
[2022-06-21T09:49:12.122Z] [ERROR] Failed to execute goal org.wildfly.plugins:wildfly-jar-maven-plugin:6.1.2.Final:package (default) on project business-central-webapp: Packaging wildfly failed: InvocationTargetException: java.util.concurrent.ExecutionException: org.jboss.as.cli.CommandLineException: Cannot start embedded server: WFLYEMB0022: Cannot invoke 'start' on embedded process: WFLYEMB0021: Cannot start embedded process: JBTHR00005: Operation failed: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details. -> [Help 1]
[2022-06-21T09:49:12.122Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.plugins:wildfly-jar-maven-plugin:6.1.2.Final:package (default) on project business-central-webapp: Packaging wildfly failed
```

unrelated. merging.

**Comment by vpiyanov** [comment]
@tarilabs, thank you for a quick turn around!

**Comment by tarilabs** [comment]
don't mention it, thank you @vpiyanov for reporting _AND_ providing a solution! I just refactored a bit for further simplifications 👍

**Pull request merged**
