### PR TITLE
[7.x] Remove unused mvel-parser dependency

### PR DESCRIPTION
**Pull request by jomarko**
`mvn dependency:analyze` marked `mvel-parser` as unused dependency of `kie-dmn-feel` module

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* cherry-pick of #4096 

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do cdb

**Review by tarilabs — APPROVED** [review]
I did have already approved the upstream?
Thank you again

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins do cdb

**Comment by jomarko** [comment]
CDB output
```
[2022-01-12T10:09:01.299Z] [INFO] BUILD FAILURE
[2022-01-12T10:09:01.299Z] [INFO] ------------------------------------------------------------------------
[2022-01-12T10:09:01.299Z] [INFO] Total time:  36:26 min (Wall Clock)
[2022-01-12T10:09:01.299Z] [INFO] Finished at: 2022-01-12T05:08:59-05:00
[2022-01-12T10:09:01.299Z] [INFO] ------------------------------------------------------------------------
[2022-01-12T10:09:01.299Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (default) on project uberfire-security-management-client-wb: MavenReportException: Error while generating Javadoc: 
[2022-01-12T10:09:01.299Z] [ERROR] Exit code: 1 - javadoc: error - Error fetching URL: https://docs.oracle.com/javase/8/docs/api/
[2022-01-12T10:09:01.299Z] [ERROR] 
[2022-01-12T10:09:01.299Z] [ERROR] Command line was: /opt/tools/jdk11/bin/javadoc -J-Xmx512m -J-Xms128m @options @packages
[2022-01-12T10:09:01.299Z] [ERROR] 
[2022-01-12T10:09:01.299Z] [ERROR] Refer to the generated Javadoc files in '/home/jenkins/workspace/KIE/7.59.x/compile/drools-7.59.x.compile/bc/kiegroup_appformer/uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client-wb/target/apidocs' dir.
[2022-01-12T10:09:01.299Z] [ERROR] -> [Help 1]
[2022-01-12T10:09:01.299Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (default) on project uberfire-security-management-client-wb: MavenReportException: Error while generating Javadoc: 
[2022-01-12T10:09:01.300Z] Exit code: 1 - javadoc: error - Error fetching URL: https://docs.oracle.com/javase/8/docs/api/
[2022-01-12T10:09:01.300Z] 
[2022-01-12T10:09:01.300Z] Command line was: /opt/tools/jdk11/bin/javadoc -J-Xmx512m -J-Xms128m @options @packages
[2022-01-12T10:09:01.300Z] 
[2022-01-12T10:09:01.300Z] Refer to the generated Javadoc files in '/home/jenkins/workspace/KIE/7.59.x/compile/drools-7.59.x.compile/bc/kiegroup_appformer/uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client-wb/target/apidocs' dir.
```

**Comment by jomarko** [comment]
Jenkins do cdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
