### PR TITLE
Add test case for reproduce exception when remove and fire rule

### PR DESCRIPTION
**Pull request by chenem2000**
- testRemoveHasSameConElement method will throw exception when fire rule after remove rule has same condition element.
- testFireAfterRemoveWithSameCondition method will throw exception , but change the fire rule sentence order or add rule order,  no exception throw.
- testRemoveWithSameRuleNameInDiffPackage test remove rule has same name in different package.
- testSameEval test fire rule has same eval sentence.

### CODE REVIEW

**Comment by psiroky** [comment]
Thanks for the PR! 

There are two small things that would be great if you could fix:
1) Could you please rebase the commits into single one? It seems most of the commits are either merge commits or small fixes, that can be incorporated to the previous commit.

2) You seem to be using different chars for indenting (I see both spaces and tabs). Could you please update the tests to use only 4 spaces to be consistent with the rest of the codebase?

**Comment by chenem2000** [comment]
sorry , my mistake.
I am not familiar with git.
Is it now ok ?

**Comment by psiroky** [comment]
I just ran the tests and they are still failing.

@mariofusco could you please briefly look at this? It seems the tests are finding real bugs regarding removing rules from KieBase.

The tests are using the old method `removeKnowledgePackage()` but since the new method `removeKiePackage()` calls exactly that one, it should not matter.

**Comment by mariofusco** [comment]
The provided test cases evidenced 3 different bugs that I reported in these jira:
- https://issues.jboss.org/browse/DROOLS-891
- https://issues.jboss.org/browse/DROOLS-893
- https://issues.jboss.org/browse/DROOLS-894

and fixed with the commits linked in the respective tickets.

All test cases have been also merged.

Thanks a lot for having reported these issues,
Mario

**Pull request closed without merging**
