### PR TITLE
[KIE-1064] simplify session serialization by adding dormant activations to rule executor

### LINKED ISSUE #1064: Simplify session serialization by adding dormant activations to rule executor

### PR DESCRIPTION
**Pull request by mariofusco**
With this pull request I'm getting rid of the convoluted algorithm that we had to traverse nodes and their memories to retrieve the active and dormant activations that need to be collected during serialization of the KieSession. It is replaced by simply keeping a reference of the dormant activations in the rule executor as it already did for the active ones. 

During the development and debugging of this improvement I found very useful to have [a boolean](https://github.com/apache/incubator-kie-drools/pull/5821/files#diff-ed88b138c1fcb0bdb39b61f94e44a273f61c9ea117cdefef6a741bf348841c35R69) that tells me if an activation is dormant or not and making assertions on it, so I left that boolean commented out and the corresponding assertions disabled with a [feature flag](https://github.com/apache/incubator-kie-drools/pull/5821/files#diff-1e1bf3853477703f78c734cfb42a7cb2a2a0e55e5ac89265a9a9e73982d5438bR52). 

Closes https://github.com/apache/incubator-kie-issues/issues/1064

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-drools/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/5821 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5821/4/display/redirect

**Test results:**
- PASSED: 21922
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5821/4/testReport/org.drools.mvel.integrationtests/NamedConsequencesTest/testDynamicSalience[KieBase_type=CLOUD_IDENTITY]/">org.drools.mvel.integrationtests.NamedConsequencesTest.testDynamicSalience[KieBase type=CLOUD_IDENTITY]</a></summary>
java.lang.IllegalStateException<br/>	at org.drools.core.phreak.RuleExecutor.modifyLeftTuple(RuleExecutor.java:305)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doLeftTupleUpdate(PhreakRuleTerminalNode.java:242)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doLeftUpdates(PhreakRuleTerminalNode.java:182)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doNode(PhreakRuleTerminalNode.java:57)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.innerEval(RuleNetworkEvaluator.java:335)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.outerEval(RuleNetworkEvaluator.java:189)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.evaluateNetwork(RuleNetworkEvaluator.java:147)<br/>	at org.drools.core.phreak.RuleExecutor.evaluateNetwork(RuleExecutor.java:228)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.evaluateEagerList(DefaultAgenda.java:503)<br/>	at org.drools.core.phreak.RuleExecutor.ruleWithHigherSalienceActivated(RuleExecutor.java:274)<br/>	at org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:172)<br/>	at org.drools.core.phreak.RuleExecutor.evaluateNetworkAndFire(RuleExecutor.java:90)<br/>	at org.drools.core.concurrent.AbstractGroupEvaluator.evaluateAndFire(AbstractGroupEvaluator.java:48)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.fireLoop(DefaultAgenda.java:620)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.internalFireAllRules(DefaultAgenda.java:573)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.fireAllRules(DefaultAgenda.java:565)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.internalFireAllRules(StatefulKnowledgeSessionImpl.java:1093)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1084)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1068)<br/>	at org.drools.mvel.integrationtests.NamedConsequencesTest.testDynamicSalience(NamedConsequencesTest.java:767)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.junit.runners.Suite.runChild(Suite.java:128)<br/>	at org.junit.runners.Suite.runChild(Suite.java:27)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.junit.runners.Suite.runChild(Suite.java:128)<br/>	at org.junit.runners.Suite.runChild(Suite.java:27)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:105)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:77)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5821/4/testReport/org.drools.mvel.integrationtests/NamedConsequencesTest/testDynamicSalience[KieBase_type=CLOUD_IDENTITY_MODEL_PATTERN]/">org.drools.mvel.integrationtests.NamedConsequencesTest.testDynamicSalience[KieBase type=CLOUD_IDENTITY_MODEL_PATTERN]</a></summary>
java.lang.IllegalStateException<br/>	at org.drools.core.phreak.RuleExecutor.modifyLeftTuple(RuleExecutor.java:305)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doLeftTupleUpdate(PhreakRuleTerminalNode.java:242)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doLeftUpdates(PhreakRuleTerminalNode.java:182)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doNode(PhreakRuleTerminalNode.java:57)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.innerEval(RuleNetworkEvaluator.java:335)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.outerEval(RuleNetworkEvaluator.java:189)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.evaluateNetwork(RuleNetworkEvaluator.java:147)<br/>	at org.drools.core.phreak.RuleExecutor.evaluateNetwork(RuleExecutor.java:228)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.evaluateEagerList(DefaultAgenda.java:503)<br/>	at org.drools.core.phreak.RuleExecutor.ruleWithHigherSalienceActivated(RuleExecutor.java:274)<br/>	at org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:172)<br/>	at org.drools.core.phreak.RuleExecutor.evaluateNetworkAndFire(RuleExecutor.java:90)<br/>	at org.drools.core.concurrent.AbstractGroupEvaluator.evaluateAndFire(AbstractGroupEvaluator.java:48)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.fireLoop(DefaultAgenda.java:620)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.internalFireAllRules(DefaultAgenda.java:573)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.fireAllRules(DefaultAgenda.java:565)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.internalFireAllRules(StatefulKnowledgeSessionImpl.java:1093)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1084)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1068)<br/>	at org.drools.mvel.integrationtests.NamedConsequencesTest.testDynamicSalience(NamedConsequencesTest.java:767)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.junit.runners.Suite.runChild(Suite.java:128)<br/>	at org.junit.runners.Suite.runChild(Suite.java:27)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.junit.runners.Suite.runChild(Suite.java:128)<br/>	at org.junit.runners.Suite.runChild(Suite.java:27)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:105)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:77)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-drools/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/5821 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5821/5/display/redirect

**Test results:**
- PASSED: 21922
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5821/5/testReport/org.drools.mvel.integrationtests/NamedConsequencesTest/testDynamicSalience[KieBase_type=CLOUD_IDENTITY]/">org.drools.mvel.integrationtests.NamedConsequencesTest.testDynamicSalience[KieBase type=CLOUD_IDENTITY]</a></summary>
java.lang.IllegalStateException<br/>	at org.drools.core.phreak.RuleExecutor.removeDormantTuple(RuleExecutor.java:313)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doLeftDelete(PhreakRuleTerminalNode.java:272)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doLeftDeletes(PhreakRuleTerminalNode.java:256)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doNode(PhreakRuleTerminalNode.java:51)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.innerEval(RuleNetworkEvaluator.java:335)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.outerEval(RuleNetworkEvaluator.java:189)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.evaluateNetwork(RuleNetworkEvaluator.java:147)<br/>	at org.drools.core.phreak.RuleExecutor.evaluateNetwork(RuleExecutor.java:231)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.evaluateEagerList(DefaultAgenda.java:503)<br/>	at org.drools.core.phreak.RuleExecutor.ruleWithHigherSalienceActivated(RuleExecutor.java:277)<br/>	at org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:172)<br/>	at org.drools.core.phreak.RuleExecutor.evaluateNetworkAndFire(RuleExecutor.java:90)<br/>	at org.drools.core.concurrent.AbstractGroupEvaluator.evaluateAndFire(AbstractGroupEvaluator.java:48)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.fireLoop(DefaultAgenda.java:620)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.internalFireAllRules(DefaultAgenda.java:573)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.fireAllRules(DefaultAgenda.java:565)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.internalFireAllRules(StatefulKnowledgeSessionImpl.java:1093)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1084)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1068)<br/>	at org.drools.mvel.integrationtests.NamedConsequencesTest.testDynamicSalience(NamedConsequencesTest.java:767)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.junit.runners.Suite.runChild(Suite.java:128)<br/>	at org.junit.runners.Suite.runChild(Suite.java:27)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.junit.runners.Suite.runChild(Suite.java:128)<br/>	at org.junit.runners.Suite.runChild(Suite.java:27)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:105)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:77)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5821/5/testReport/org.drools.mvel.integrationtests/NamedConsequencesTest/testDynamicSalience[KieBase_type=CLOUD_IDENTITY_MODEL_PATTERN]/">org.drools.mvel.integrationtests.NamedConsequencesTest.testDynamicSalience[KieBase type=CLOUD_IDENTITY_MODEL_PATTERN]</a></summary>
java.lang.IllegalStateException<br/>	at org.drools.core.phreak.RuleExecutor.removeDormantTuple(RuleExecutor.java:313)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doLeftDelete(PhreakRuleTerminalNode.java:272)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doLeftDeletes(PhreakRuleTerminalNode.java:256)<br/>	at org.drools.core.phreak.PhreakRuleTerminalNode.doNode(PhreakRuleTerminalNode.java:51)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.innerEval(RuleNetworkEvaluator.java:335)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.outerEval(RuleNetworkEvaluator.java:189)<br/>	at org.drools.core.phreak.RuleNetworkEvaluator.evaluateNetwork(RuleNetworkEvaluator.java:147)<br/>	at org.drools.core.phreak.RuleExecutor.evaluateNetwork(RuleExecutor.java:231)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.evaluateEagerList(DefaultAgenda.java:503)<br/>	at org.drools.core.phreak.RuleExecutor.ruleWithHigherSalienceActivated(RuleExecutor.java:277)<br/>	at org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:172)<br/>	at org.drools.core.phreak.RuleExecutor.evaluateNetworkAndFire(RuleExecutor.java:90)<br/>	at org.drools.core.concurrent.AbstractGroupEvaluator.evaluateAndFire(AbstractGroupEvaluator.java:48)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.fireLoop(DefaultAgenda.java:620)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.internalFireAllRules(DefaultAgenda.java:573)<br/>	at org.drools.kiesession.agenda.DefaultAgenda.fireAllRules(DefaultAgenda.java:565)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.internalFireAllRules(StatefulKnowledgeSessionImpl.java:1093)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1084)<br/>	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1068)<br/>	at org.drools.mvel.integrationtests.NamedConsequencesTest.testDynamicSalience(NamedConsequencesTest.java:767)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.junit.runners.Suite.runChild(Suite.java:128)<br/>	at org.junit.runners.Suite.runChild(Suite.java:27)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.junit.runners.Suite.runChild(Suite.java:128)<br/>	at org.junit.runners.Suite.runChild(Suite.java:27)<br/>	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)<br/>	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:105)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:77)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)<br/>	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)<br/>
</details>

**Comment by tkobayas** [comment]
@mariofusco Does/Will this PR have a test case which expresses the originally reported problem?

**Comment by mariofusco** [comment]
> @mariofusco Does/Will this PR have a test case which expresses the originally reported problem?

The test case reproducing the original reported problem has been already merged with [this commit](https://github.com/apache/incubator-kie-drools/commit/f3179021b7e97499e77a79ddceec483f5d568449). That commit fixed the existing (convoluted) way to retrieve activations from nodes memories while with this second rework I'm totally getting rid of that algorithm and simply storing also the dormant activations in the rule executors.

**Review by lucamolteni — APPROVED** [review]

**Review by tkobayas — APPROVED** [review]
@mariofusco Thanks, it gets pretty clearer.

**Pull request merged**
