### PR TITLE
DROOLS-5131: [DMN Designer] Boxed List support

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/DROOLS-5131

This PR complete support for `List` in `kie-dmn-backend` marshallers.

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
Looks good to me thanks!

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@tarilabs I thought `drools` had automated CI builds too?!?!

This PR does not appear to be triggering anything.

Am I mistaken?

**Comment by tarilabs** [comment]
@manstis usually it does, from time to time Jenkins CI might be lagging

**Comment by jomarko** [comment]
ehm, it was fast merge

**Comment by manstis** [comment]
Oh sorry @jomarko 

I didn't realise you wanted to review this as it's core DMN and not editor.

**Comment by jomarko** [comment]
@manstis please mark me in the UI one at least

**Pull request merged**
