### PR TITLE
Consider OS and java version for concurrency group

### PR DESCRIPTION
**Pull request by danielezonca**
**Thank you for submitting this pull request**

**NOTE!:** Double check the target branch for this PR.
The default is `main` so it will target Drools 8 / Kogito / Optaplanner 8.
If this PR is not strictly related to drools and kogito project in `drools.git`, it should probably target `7.x`as a branch

**Ports** If a forward-port or a backport is needed, paste the forward port PR here

[link](https://www.example.com)

**JIRA**: _(please edit the JIRA link if it exists)_

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by danielezonca** [comment]
@Ginxo 
Can you please help me to understand why all GHA are failing?
The change of this PR is very minimal so I don't understand 🤔

**Comment by Ginxo** [comment]
sure @danielezonca 

Since we are using `${BRANCH:main}` https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/671de261d3274bde25dd3751aedcd72fc5091a06/.ci/actions/build-chain/action.yml#L10 for the definition file the tool tries additional places to get definition-file from. See
`[INFO]  https://raw.githubusercontent.com/danielezonca/droolsjbpm-build-bootstrap/main/.ci/pull-request-config.yaml exists, using it`
and your pull-request-config.yaml is out of date.

It tries to get it from `${KIEGROUP}/droolsjbpm-build-bootstrap:7.x` first which does not exist and then it tries `${KIEGROUP}/droolsjbpm-build-bootstrap:main` (default branch value)
You can obviously rebase your `danielezonca/droolsjbpm-build-bootstrap:main` branch with upstream, but I would suggest to replace https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/671de261d3274bde25dd3751aedcd72fc5091a06/.ci/actions/build-chain/action.yml#L10 by `https://raw.githubusercontent.com/${GROUP:kiegroup}/droolsjbpm-build-bootstrap/${BRANCH:main}/.ci/pull-request-config.yaml` this way it won't ever try `danielezonca/droolsjbpm-build-bootstrap/main` but `kiegroup/droolsjbpm-build-bootstrap/main` for this use case. See https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1820
wdyt? is it clear enough?


See
```
$ build-chain-action -df 'https://raw.githubusercontent.com/${GROUP:kiegroup}/droolsjbpm-build-bootstrap/${BRANCH:main}/.ci/pull-request-config.yaml' build pr -url https://github.com/kiegroup/drools/pull/4005 --skipCheckout --skipExecution

[INFO]  Executing pull request flow for https://github.com/kiegroup/drools/pull/4005 in build_chain_2021101274414
[WARN]  https://raw.githubusercontent.com/danielezonca/droolsjbpm-build-bootstrap/fix-job-concurrency-conf/.ci/pull-request-config.yaml does not exists.
[WARN]  https://raw.githubusercontent.com/kiegroup/droolsjbpm-build-bootstrap/7.x/.ci/pull-request-config.yaml does not exists.
[WARN]  https://raw.githubusercontent.com/kiegroup/droolsjbpm-build-bootstrap/fix-job-concurrency-conf/.ci/pull-request-config.yaml does not exists.
[INFO]  https://raw.githubusercontent.com/kiegroup/droolsjbpm-build-bootstrap/main/.ci/pull-request-config.yaml exists, using it
::group::[Pull Request Flow] Checking out kiegroup/drools and its dependencies
[INFO]  Tree for project kiegroup/drools. Dependencies: 
kiegroup/droolsjbpm-build-bootstrap,
kiegroup/kie-soup,
kiegroup/droolsjbpm-knowledge,
kiegroup/drools
[INFO]  [kiegroup/droolsjbpm-build-bootstrap] Checking out project
[INFO]  [kiegroup/kie-soup] Checking out project
[INFO]  [kiegroup/droolsjbpm-knowledge] Checking out project
[INFO]  [kiegroup/drools] Checking out project
[WARN]  project github.com/danielezonca/droolsjbpm-build-bootstrap:fix-job-concurrency-conf does not exist. It's not necessarily an error.
[WARN]  project github.com/danielezonca/kie-soup:fix-job-concurrency-conf does not exist. It's not necessarily an error.
[WARN]  project github.com/danielezonca/droolsjbpm-knowledge:fix-job-concurrency-conf does not exist. It's not necessarily an error.
[WARN]  project github.com/kiegroup/droolsjbpm-build-bootstrap:fix-job-concurrency-conf does not exist. It's not necessarily an error.
[WARN]  project github.com/kiegroup/kie-soup:fix-job-concurrency-conf does not exist. It's not necessarily an error.
[WARN]  project github.com/kiegroup/droolsjbpm-knowledge:fix-job-concurrency-conf does not exist. It's not necessarily an error.
[INFO]  [kiegroup/drools] Check out skipped.
[INFO]  [kiegroup/kie-soup] Check out skipped.
[INFO]  [kiegroup/droolsjbpm-build-bootstrap] Check out skipped.
[INFO]  [kiegroup/droolsjbpm-knowledge] Check out skipped.
::endgroup::
::group::[Pull Request Flow] Checkout Summary...
[INFO]  ----------------------------------------------
[INFO]  kiegroup/droolsjbpm-build-bootstrap:main.
[INFO]  kiegroup/kie-soup:main.
[INFO]  kiegroup/droolsjbpm-knowledge:7.x.
[INFO]  danielezonca/drools:fix-job-concurrency-conf. It has been merged with kiegroup/drools:7.x
[INFO]  ----------------------------------------------
[INFO]  Projects taken from branch "main":
  kiegroup/droolsjbpm-build-bootstrap,
  kiegroup/kie-soup
[INFO]  Projects taken from branch "7.x":
  kiegroup/droolsjbpm-knowledge
[INFO]  Projects taken from branch "fix-job-concurrency-conf":
  danielezonca/drools. Merged with kiegroup/drools:7.x
[INFO]  ----------------------------------------------
::endgroup::
[INFO]  Execution has been skipped.
```

**Comment by danielezonca** [comment]
@Ginxo 
Thanks for the clarification, I have approved your PR :)
Btw I think the current behaviour is misleading: I don't think `danielezonca/droolsjbpm-buid-bootstrap:main` should be considered even in case of placeholder without default value.

I understand checking `danielezonca/droolsjbpm-buid-bootstrap:sourceBranch` (in this case `fix-job-concurrency-conf`) so that I can do a multi repo PR and test CI but after that I think  `kiegroup/droolsjbpm-buid-bootstrap:main` should be the second in the list of priorities.
In general I don't see when `sourceOrg:targetBrach` might be the expected result 🤔 

Wdyt?
I can create an issue for the action if you agree

**Comment by Ginxo** [comment]
> @Ginxo Thanks for the clarification, I have approved your PR :) Btw I think the current behaviour is misleading: I don't think `danielezonca/droolsjbpm-buid-bootstrap:main` should be considered even in case of placeholder without default value.
> 
> I understand checking `danielezonca/droolsjbpm-buid-bootstrap:sourceBranch` (in this case `fix-job-concurrency-conf`) so that I can do a multi repo PR and test CI but after that I think `kiegroup/droolsjbpm-buid-bootstrap:main` should be the second in the list of priorities. In general I don't see when `sourceOrg:targetBrach` might be the expected result thinking
> 
> Wdyt? I can create an issue for the action if you agree

I didn't probably explain myself well, sorry for that. I was just talking about definition-file and the behavior in case of placeholder (either, group, project or/and branch) is

- sourceGroup/sourceProject:sourceBranch
- targetGroup/targetProject:sourceBranch (in case a PR without forking it)
- target all
This way we are able to get latest changes from definition-file. This thing is repeated but replacing default values for placeholder (in case they exist). So assigning default values either for group and branch danielezonca/droolsjbpm-build-bootstrap won't be considered at all unless you open a specific PR for that project.

It was basically a configuration error solved by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1820

**Comment by baldimir** [comment]
Hi, is this still relevant please? Do we need to keep it open?

**Comment by danielezonca** [comment]
@baldimir 
I would say that it is too old so let's close it :)

**Pull request closed without merging**
