### PR TITLE
[main] Bump Quarkus version to 2.9.2.Final

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/optaplanner/pull/2001
- https://github.com/kiegroup/optaplanner-quickstarts/pull/345
- https://github.com/kiegroup/drools/pull/4417
- https://github.com/kiegroup/kogito-runtimes/pull/2224
- https://github.com/kiegroup/kogito-examples/pull/1271

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-examples tests

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by radtriste — APPROVED** [review]

**Pull request merged**
