### PR TITLE
DROOLS-3014 Remove drools-pmml module

### PR DESCRIPTION
**Pull request by baldimir**
- The module is not part of Drools Maven build and is succeeded by kie-pmml. We should remove it. 

@lanceleverich @jiripetrlik what do you think? @mariofusco please do not merge this till @lanceleverich reviews it.

### CODE REVIEW

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Comment by baldimir** [comment]
The failures in downstream are unrelated. @lanceleverich could you please review?

**Review by lanceleverich — APPROVED** [review]
No problems or issues that I can find.

**Comment by mariofusco** [comment]
@lanceleverich ok for me, but please resolve merge conflicts

**Comment by baldimir** [comment]
@mariofusco I rebased it, let's wait for green.

**Pull request merged**
