### PR TITLE
 DROOLS-5431 DMN XStream and JDK11

### PR DESCRIPTION
**Pull request by tarilabs**
requires https://github.com/kiegroup/kie-soup/pull/145

### CODE REVIEW

**Comment by tarilabs** [comment]
Usually problems are reported on JDK11+ as:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/Users/mmortari/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The PRs in this ensemble resolved the problem when **running DMN** on JDK11+ etc the Warning is no longer reported.

For the ease of testing out these improvements I also created an external project which I tested with a failing flag: https://github.com/tarilabs/test20200713/blob/9aec6a9034beee70a3e45c5e38a05f6dc3c38c4f/pom.xml#L95-L117

Please note this ensemble of PRs do not resolve for all the places where XStream is used in `drools.git`, only for DMN.

**Comment by evacchi** [comment]
interesting I remember doing something similar https://github.com/kiegroup/kogito-runtimes/commit/35193480bd166853eb6cc8c7d9b0563db7bbede4 we should probably align...

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
most internal issues connection in FDB

Jenkins execute full downstream build

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
FDB failures are:

```
org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testSignalToProcess | 0 ms | 4
org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testStartProcess | 0 ms | 4
org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testGetProcessIds | 0 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById | 86 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById | 86 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById | 86 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId | 63 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId | 65 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId | 65 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId | 46 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId | 46 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId | 46 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries | 70 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries | 70 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries | 70 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances | 21 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances | 22 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances | 22 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus | 85 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus | 85 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus | 85 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId | 44 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId | 44 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId | 44 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses | 14 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses | 27 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses | 27 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator | 16 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator | 16 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator | 16 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId | 49 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId | 49 ms | 4
org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId | 49 ms | 4
org.kie.camel.container.integration.tests.remote.RuleClientIntegrationTest.testExecuteCommand | 90 ms | 4
org.kie.camel.container.integration.tests.remote.RuleClientIntegrationTest.testExecuteCommand | 94 ms | 4
org.kie.camel.container.integration.tests.remote.RuleClientIntegrationTest.testExecuteCommand | 94 ms | 4
org.kie.hacep.KafkaTest.basicTest | 2.4 sec | 7
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest | 2.1 sec | 7
org.kie.hacep.PodAsLeaderTest.processOneSentMessageAsLeaderTest | 1 min 1 sec | 7
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest | 35 sec | 7
```

at this point I wouldn't say is related.
@hellowdan agree?

**Comment by hellowdan** [comment]
> FDB failures are:
> 
> ```
> org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testSignalToProcess | 0 ms | 4
> org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testStartProcess | 0 ms | 4
> org.kie.camel.container.integration.tests.ProcessEngineIntegrationTest.testGetProcessIds | 0 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById | 86 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById | 86 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesById | 86 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId | 63 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId | 65 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerId | 65 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId | 46 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId | 46 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessByContainerIdProcessId | 46 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries | 70 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries | 70 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testListQueries | 70 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances | 21 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances | 22 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstances | 22 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus | 85 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus | 85 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByStatus | 85 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId | 44 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId | 44 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessesByContainerIdWrongId | 44 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses | 14 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses | 27 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcesses | 27 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator | 16 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator | 16 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstanceByInitiator | 16 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId | 49 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId | 49 ms | 4
> org.kie.camel.container.integration.tests.remote.QueryClientIntegrationTest.testFindProcessInstancesByContainerId | 49 ms | 4
> org.kie.camel.container.integration.tests.remote.RuleClientIntegrationTest.testExecuteCommand | 90 ms | 4
> org.kie.camel.container.integration.tests.remote.RuleClientIntegrationTest.testExecuteCommand | 94 ms | 4
> org.kie.camel.container.integration.tests.remote.RuleClientIntegrationTest.testExecuteCommand | 94 ms | 4
> org.kie.hacep.KafkaTest.basicTest | 2.4 sec | 7
> org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest | 2.1 sec | 7
> org.kie.hacep.PodAsLeaderTest.processOneSentMessageAsLeaderTest | 1 min 1 sec | 7
> org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest | 35 sec | 7
> ```
> 
> at this point I wouldn't say is related.
> @hellowdan agree?

Agreed

**Pull request merged**
