### PR TITLE
[DROOLS-4743] Add needed background data on 1.7 -> 1.8 migration

### PR DESCRIPTION
**Pull request by gitgabrio**
see https://issues.jboss.org/browse/DROOLS-4743

@danielezonca @dupliaka

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]

**Comment by yesamer** [comment]
Reminder: factMappingValueType on background's factMappings

**Review by yesamer — CHANGES_REQUESTED** [review]
Please add factMappingValueType Node:
            `final List<Node> factMappingNodesList = DOMParserUtil.getNestedChildrenNodesList(document, SIMULATION_DESCRIPTOR_NODE, FACT_MAPPINGS_NODE, FACT_MAPPING_NODE);
            factMappingNodesList.forEach(factMappingNode -> DOMParserUtil.createNodeAtPosition(factMappingNode, FACT_MAPPING_VALUE_TYPE_NODE, FactMappingValueType.NOT_EXPRESSION.toString(), null));`

**Comment by gitgabrio** [comment]
jenkins please retest this

**Review by yesamer — APPROVED** [review]

**Comment by danielezonca** [comment]
jenkins execute compile downstream build

**Comment by dupliaka** [comment]
**Issue 1** 
"Unable to complete your request" occurs if I run imported scesim asset of 1.6 version.
The same for DMN and for DRL.
Workaround: double click on GIVEN

Screenshot from 2019-11-12 20-17-51

**Comment by yesamer** [comment]
@dupliaka @danielezonca @gitgabrio I analysed the scesim file you sent me. Where you took it? In my opinion it's invalid. A missing element in the xml causes the issue: <dmoSession>default</dmoSession> .
But this element is mandatory since version 1.5. Therefore, it's invalid to have a 1.6 document without that tag element

**Comment by gitgabrio** [comment]
@dupliaka 
which files are you importing? Do not understand @yesamer comment about invalid format
Anyway, just done complete test with correct 1.6 files without issue

**Review by dupliaka — APPROVED** [review]
The manual check is complete. I didn't find any bug related to this PR.

**Pull request merged**
