### PR TITLE
[RHPAM-3291] fix performance regression

### PR DESCRIPTION
**Pull request by elguardian**
https://issues.redhat.com/browse/RHPAM-3291

### CODE REVIEW

**Comment by elguardian** [comment]
run fdb

**Comment by elguardian** [comment]
Jenkins run fdb

**Comment by elguardian** [comment]
Jenkins run fdb

**Comment by gmunozfe** [comment]
Failures in ExceptionHandlingIntegrationTest and UserTaskAdminServiceIntegrationTest seem related, @elguardian could you check?

**Comment by elguardian** [comment]
@gmunozfe it works in my local... not really sure what happened

**Comment by elguardian** [comment]
Jenkins run fdb

**Comment by elguardian** [comment]
Jenkins run fdb

**Comment by mariofusco** [comment]
@elguardian can you please clarify a bit the intent of this change? I believe that in general `ThreadLocal`s are a code smell since they are a potential source of problems, especially in environments using threads pools, and can be cause of memory leaks.

**Comment by elguardian** [comment]
@mariofusco 3 ms has the fault. It seems that QE issue a report that using tx data is too slow. This is meant as temporary solution for now.

**Comment by gmunozfe** [comment]
> @gmunozfe it works in my local... not really sure what happened

now tests worked fine for me locally, let's wait for the fdb green

**Comment by elguardian** [comment]
failure is not related.

**Review by MarianMacik — APPROVED** [review]

**Pull request merged**
