### PR TITLE
[7.52.x] DROOLS-5892 Guided Rule Editor: Method calls do not support template keys

### PR DESCRIPTION
**Pull request by Rikkola**
[DROOLS-5892](https://issues.redhat.com/browse/DROOLS-5892) Guided Rule Editor: Method calls do not support template keys

**referenced Pull Requests**: 

* https://github.com/kiegroup/drools/pull/3519
* https://github.com/kiegroup/drools-wb/pull/1479

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by jomarko — APPROVED** [review]
Thank you for a cherry-pick

**Comment by Rikkola** [comment]
Jenkins run fdb

**Review by danielzhe — APPROVED** [review]

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
camel tests failing 

jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
```
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testInsertGetDeleteFact
org.kie.camel.container.integration.tests.RuleEngineIntegrationTest.testFireAllRules
org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojo
org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojoMalformedData
org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignal
org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignal
org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignalsTransactional
org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessage
org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignalsAndMessagesTransactional
org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testBoundaryMessageMultipleProcesses
```


Jenkins run fdb

**Comment by mareknovotny** [comment]
merging as those tests are failing on other PRs too and people should already work on fixing.

**Pull request merged**
