### PR TITLE
Remove unused dependency org.eclipse.aether:aether-spi

### PR DESCRIPTION
**Pull request by jomarko**
This is an attempt to fix the failing [master nightly build](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/PROD/job/rhpam-master-nightly-release-pipeline/job/y-rhpam-master-drools-wb/).

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by domhanak** [comment]
@mareknovotny

**Comment by jomarko** [comment]
@domhanak @mareknovotny  downstream build failed due to failing tests, but they seems unrelated to me. I tried the produced war locally and seems working to me.

**Comment by mareknovotny** [comment]
@jomarko How have you identified just `aether-spi` to be the problem?

I ran `mvn dependency:analyze` and it shows more deps unused deps:

```
[INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ kie-ci ---
[WARNING] Used undeclared dependencies found:
[WARNING]    javax.inject:javax.inject:jar:1:compile
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[WARNING]    javax.enterprise:cdi-api:jar:1.2:compile
[WARNING] Unused declared dependencies found:
[WARNING]    org.apache.maven:maven-artifact:jar:3.3.9:compile
[WARNING]    org.apache.maven:maven-model-builder:jar:3.3.9:compile
[WARNING]    org.apache.maven:maven-plugin-api:jar:3.3.9:compile
[WARNING]    org.apache.maven:maven-settings:jar:3.3.9:compile
[WARNING]    org.apache.maven:maven-settings-builder:jar:3.3.9:compile
[WARNING]    org.apache.maven:maven-compat:jar:3.3.9:compile
[WARNING]    org.apache.maven:maven-aether-provider:jar:3.3.9:compile
[WARNING]    org.apache.maven.wagon:wagon-provider-api:jar:3.0.0:compile
[WARNING]    org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[WARNING]    org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[WARNING]    org.codehaus.plexus:plexus-utils:jar:3.0.22:compile
[WARNING]    org.eclipse.aether:aether-util:jar:1.1.0:compile
[WARNING]    org.eclipse.aether:aether-impl:jar:1.1.0:compile
[WARNING]    org.eclipse.aether:aether-connector-basic:jar:1.1.0:compile
[WARNING]    org.eclipse.aether:aether-spi:jar:1.1.0:compile
[WARNING]    org.eclipse.aether:aether-transport-wagon:jar:1.1.0:compile
[WARNING]    org.eclipse.aether:aether-transport-file:jar:1.1.0:compile
[WARNING]    org.eclipse.aether:aether-transport-http:jar:1.1.0:compile
[WARNING]    org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.2:compile
[WARNING]    org.apache.ant:ant:jar:1.8.4:compile
[WARNING]    org.apache.maven.wagon:wagon-http:jar:3.0.0:compile
[WARNING]    org.slf4j:jcl-over-slf4j:jar:1.7.26:runtime
[WARNING]    org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[WARNING]    org.sonatype.plexus:plexus-cipher:jar:1.7:compile
[WARNING]    com.google.inject:guice:jar:no_aop:4.0:compile
[WARNING]    ch.qos.logback:logback-classic:jar:1.2.3:test
[WARNING]    org.mockito:mockito-core:jar:1.10.19:test
```

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@mareknovotny I removed more dependencies, but not all provided by `mvn dependency:analyze`. Removing of the rest would cause test failures, so I think if the full downstream build will produce working war, we can merge.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
could we merge or [these failures](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/drools-downstream-pullrequests/64/consoleText) are related ? I guess they are not.

**Pull request merged**
