### PR TITLE
synchronized work item map

### PR DESCRIPTION
**Pull request by calbazasebastian**
JpaWorkItemManager is not thread safe.. I've synchronized the workItems map and done some code cleaning.

PS. I tried filling a bug for this, but it didn't let me..don't know why... also the getWorkItems method looks suspicious.. it just returns an empty set.. is that ok?

### CODE REVIEW

**Comment by mrietveld** [comment]
The getWorkItems() method should return an empty set -- this has to do with the code [here](https://github.com/calbazasebastian/drools/blob/master/drools-persistence-jpa/src/main/java/org/drools/persistence/SingleSessionCommandService.java#L459)

The way persistence work, only workitems (or process instances, for that matter) that are being handled within a transaction, should be available during a transaction. When the transaction ends, the cache (of workitems) should be emptied. 

I think the only reason the getWorkItems() method exists is maybe because it has to because of the Interface? Normally, that class would never implement that because exposing the internal cache to other code will just lead to problems.

**Comment by mrietveld** [comment]
Also, I'm not sure making the JpaWorkItemManager needs to be thread safe -- I though it was only used within the synchronized block of the SingleSessionCommandService, which means that it's never called concurrently. 

Of course, I might be mistaken in this, in which case making it thread-safe is good!

**Comment by calbazasebastian** [comment]
Yeah, if it is accessed inside the session's execute method context it's ok...but I saw code in jBPM  GenericHTWorkItemHandler that uses the manager outside the context, but probably there are some more... I think it might be good to add some logic to allow calls to the manager's methods only if we are in the session's execute method context... this will force any invalid usage to be changed/fixed.

**Comment by calbazasebastian** [comment]
I think I might be mistaken... the manager is accessed properly from jBPM..  no need to add thread safety here

**Pull request closed without merging**
