### PR TITLE
DROOLS-5314: assume possible dots in import alias

### PR DESCRIPTION
**Pull request by jomarko**
for more details see:
- https://issues.redhat.com/browse/DROOLS-5314

**Before**
Screenshot from 2021-11-02 16-16-25

**After**
Screenshot from 2021-11-02 16-14-43

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by tarilabs — COMMENTED** [review]
I've commented on the PR I've received first as notification.
Please reference comments there.

btw, you don't have to duplicate PR up-front for main/7.x ; if you prefer, you can create a PR against a 7.x or main, and then cherry-pick only after approved and merged. If you prefer.

**Comment by jomarko** [comment]
This PR will be updated (aligned) with 7.x once there I have an approval

**Comment by jomarko** [comment]
"[2021-11-05T07:05:08.137Z] [INFO] Kogito :: Drools :: Kogito Scenario Simulation Runner FAILURE [  7.421 s]" - checking

**Comment by barboras7** [comment]
jenkins do fdb

**Review by barboras7 — APPROVED** [review]
Thanks @jomarko, looks good :tada:

**Comment by jomarko** [comment]
@tarilabs I think we can merge this PR

**Comment by tarilabs** [comment]
thank you for your contributions @jomarko

**Pull request merged**
