### PR TITLE
[new-parser] Support trait type declaration

### PR DESCRIPTION
**Pull request by yurloc**
Fixes
- #5816 

### Before PR in `drools-traits`
```
[ERROR] Tests run: 363, Failures: 150, Errors: 142, Skipped: 6
```

### After PR in `drools-traits`
```
[ERROR] Tests run: 363, Failures: 94, Errors: 105, Skipped: 6
```

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

**Comment by yurloc** [comment]
@tkobayas @mariofusco @gitgabrio please review.

**Review by tkobayas — APPROVED** [review]

**Review by gitgabrio — APPROVED** [review]

**Comment by gitgabrio** [comment]
Hi @yurloc @tkobayas @mariofusco 
looking at this PR, I noticed there are a lot of `null` check; e.g. :
```java     
if (ctx.DRL_TRAIT() != null) {
            typeDeclarationDescr.setTrait(true);
}
```
I think I understand the reason, but I wonder if there could be a nicer design to avoid them. 
I don't know how easy would be to change the `DRLParser.TypeDeclarationContext` (and similar *Context), but somehow all this null checking does not look very nice: what do you think ? (note: this would be just a nice-to-have)

**Comment by yurloc** [comment]
> Hi @yurloc @tkobayas @mariofusco looking at this PR, I noticed there are a lot of `null` check; e.g. :
> 
> ```java
> if (ctx.DRL_TRAIT() != null) {
>             typeDeclarationDescr.setTrait(true);
> }
> ```
> 
> I think I understand the reason, but I wonder if there could be a nicer design to avoid them. I don't know how easy would be to change the `DRLParser.TypeDeclarationContext` (and similar *Context), but somehow all this null checking does not look very nice: what do you think ? (note: this would be just a nice-to-have)

Yeah, I totally hear you @gitgabrio but the whole `DRLParser` class is a _generated_ source code produced by `antlr4-maven-plugin` from `.g4` grammar files. I have no power over its API.

**Comment by gitgabrio** [comment]
> > Hi @yurloc @tkobayas @mariofusco looking at this PR, I noticed there are a lot of `null` check; e.g. :
> > ```java
> > if (ctx.DRL_TRAIT() != null) {
> >             typeDeclarationDescr.setTrait(true);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think I understand the reason, but I wonder if there could be a nicer design to avoid them. I don't know how easy would be to change the `DRLParser.TypeDeclarationContext` (and similar *Context), but somehow all this null checking does not look very nice: what do you think ? (note: this would be just a nice-to-have)
> 
> Yeah, I totally hear you @gitgabrio but the whole `DRLParser` class is a _generated_ source code produced by `antlr4-maven-plugin` from `.g4` grammar files. I have no power over its API.

Ok @yurloc thanks for explanation! 👍

**Review by mariofusco — APPROVED** [review]

**Comment by yurloc** [comment]
Overall fixing progress: There were 436 failed tests.

**Pull request merged**
