### PR TITLE
JBPM-8445: Stunner -  unable to set cycle timer with cron expression

### PR DESCRIPTION
**Pull request by wmedvede**
- Splits the CronExpression in drools into a GWT compatible part in kie-soup required by Stunner and the non GWT complatible methods remains in drools

### CODE REVIEW

**Comment by wmedvede** [comment]
To make the CronExpression available in Stunner (client side) it was necessary to do a small code split into one piece that is 100% GWT compatible/compilable and all the non GWT compatible methods in the other part of the split. But code is essentially the same as before, just some methods placed in kie-soup and the rest of the methods remained in drools.

@mariofusco @romartin   would you mind review this PR?

Thanks!

depends on:

https://github.com/kiegroup/kie-soup/pull/96

**Review by romartin — APPROVED** [review]
The code splitting looks good to me @wmedvede :+1: 

Hey @mariofusco , so we need some of this code available on client side and we went ahead and tried to refactor it instead of duplicating the code on other modules.. plz let us know what you think. 

Thanks!

**Comment by wmedvede** [comment]
Hi @mariofusco don't forget to take a look at this please.
Thanks.

**Review by manstis — APPROVED** [review]

**Comment by wmedvede** [comment]
Hi @baldimir would you mind prioritize this PR? We need to merge this into master and proceed with the cherry-pick into 7.4.1 asap.

Thanks!

**Comment by wmedvede** [comment]
Hi @baldimir sorry for chasing, but I'll will be asked for the status of this in today's scrum meeting. Any chance you can take a look at this?

**Review by hasys — APPROVED** [review]
Hi @wmedvede,

thank you, looks good to me!

**Comment by wmedvede** [comment]
@hasys @romartin two greens

**Pull request merged**
