### PR TITLE
KOGITO-6091 Setup Jenkins jobs

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-6091

Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/286
- https://github.com/kiegroup/kogito-runtimes/pull/1660
- https://github.com/kiegroup/drools/pull/3902
- https://github.com/kiegroup/optaplanner/pull/1615
- https://github.com/kiegroup/kogito-apps/pull/1066
- https://github.com/kiegroup/kogito-examples/pull/934

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by radtriste** [comment]
jenkins rerun drools tests

**Comment by radtriste** [comment]
jenkins rerun drools tests

**Comment by radtriste** [comment]
jenkins rerun kogito-examples tests

**Review by danielezonca — APPROVED** [review]

**Comment by radtriste** [comment]
jenkins rerun kogito-examples

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
