### PR TITLE
ERRAI-1042: Moving ErraiApp.properties to META-INF dir

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/ERRAI-1042

### CODE REVIEW

**Comment by manstis** [comment]
Hi @tiagobento could you please review and approve?

**Review by tiagobento — APPROVED** [review]
@manstis Looks good to me. Ok to merge when it's green.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@mswiderski Could you please look at the failing test?

https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/drools-downstream-pullrequests/47/testReport/org.jbpm.kie.services.test/FilteredKModuleDeploymentServiceTest/testMultipleRemotableInPojoJar/

Looks like a positive failure (it's 10 builds old).

**Comment by mswiderski** [comment]
@manstis the only thing I see in there is that it can build the kjar due to missing dependency of uberfire so most likely jenkins issue... 

so I'd say go ahead and merge

**Pull request merged**
