### PR TITLE
DROOLS-5558 kie-dmn-validation migration to exec model

### PR DESCRIPTION
**Pull request by tarilabs**

### CODE REVIEW

**Review by lucamolteni — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
SonarCloud is complaining hard about the fact the path for code generated file is supplied as a configuration, but it's the same which is done here: https://github.com/kiegroup/droolsjbpm-integration/blob/c9d43f996fe05679b4fcd56bd13bcece32b45fa3/kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java#L178-L180
🤷‍♂️ 

downstream build test failures are mostly about JMS client failed to init
```
Test Result (41 failures / +29)
org.kie.server.integrationtests.drools.ActivationGroupIntegrationTest.initializationError
org.kie.server.integrationtests.drools.AgendaGroupIntegrationTest.initializationError
org.kie.server.integrationtests.drools.AgendaIntegrationTest.initializationError
org.kie.server.integrationtests.drools.ClassesInludedInKJarIntegrationTest.initializationError
org.kie.server.integrationtests.drools.CombinedUpdateIntegrationTest.initializationError
org.kie.server.integrationtests.drools.ConcurrentRequestsIntegrationTest.initializationError
org.kie.server.integrationtests.drools.ContainerIsolationIntegrationTest.initializationError
org.kie.server.integrationtests.drools.ContainerSnapshotUpdateIntegrationTest.initializationError
org.kie.server.integrationtests.drools.ContainerUpdateDifferentKBaseIntegrationTest.initializationError
org.kie.server.integrationtests.drools.ContainerUpdateDifferentPackageIntegrationTest.initializationError
org.kie.server.integrationtests.drools.ContainerUpdateIntegrationTest.initializationError
org.kie.server.integrationtests.drools.DisposeCommandIntegrationTest.initializationError
org.kie.server.integrationtests.drools.DroolsMetricIntegrationTest.initializationError
org.kie.server.integrationtests.drools.GuidedDecisionTableIntegrationTest.testExecuteGuidedDecisionTableRule[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:41534/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.drools.GuidedDecisionTableIntegrationTest.testExecuteGuidedDecisionTableRule[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:41534/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.drools.GuidedDecisionTableIntegrationTest.testExecuteGuidedDecisionTableRule[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:41534/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.drools.GuidedDecisionTableIntegrationTest.testExecuteGuidedDecisionTableRule[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.drools.GuidedDecisionTableIntegrationTest.testExecuteGuidedDecisionTableRule[4: JSON KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.drools.GuidedDecisionTableIntegrationTest.testExecuteGuidedDecisionTableRule[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.drools.GuidedDecisionTreeIntegrationTest.initializationError
org.kie.server.integrationtests.drools.KieServerBackwardCompatDroolsIntegrationTest.initializationError
org.kie.server.integrationtests.drools.KieServerDroolsIntegrationTest.initializationError
org.kie.server.integrationtests.drools.MultiModuleProjectIntegrationTest.initializationError
org.kie.server.integrationtests.drools.ObjectHandlingIntegrationTest.initializationError
org.kie.server.integrationtests.drools.RollingUpdateContainerIntegrationTest.initializationError
org.kie.server.integrationtests.drools.RuleFlowIntegrationTest.initializationError
org.kie.server.integrationtests.drools.RuleTemplateIntegrationTest.initializationError
org.kie.server.integrationtests.drools.SpreadsheetIntegrationTest.initializationError
org.kie.server.integrationtests.drools.StatefulSessionUsageIntegrationTest.initializationError
org.kie.server.integrationtests.drools.StatelessSessionUsageIntegrationTest.initializationError
org.kie.server.integrationtests.drools.jms.DroolsJmsResponseHandlerIntegrationTest.initializationError
org.kie.server.integrationtests.drools.pmml.ApplyDecisionTreeModelIntegrationTest.initializationError
org.kie.server.integrationtests.drools.pmml.ApplyPmmlMultipleTimesIntegrationTest.initializationError
org.kie.server.integrationtests.drools.pmml.ApplyRegressionModelIntegrationTest.initializationError
org.kie.server.integrationtests.drools.pmml.ApplyScorecardModelIntegrationTest.initializationError
org.kie.server.integrationtests.drools.pmml.ApplyScorecardMultiModuleIntegrationTest.initializationError
org.kie.server.integrationtests.drools.rest.RestMalformedRequestIntegrationTest.org.kie.server.integrationtests.drools.rest.RestMalformedRequestIntegrationTest
org.kie.hacep.KafkaTest.basicTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsLeaderTest.processOneSentMessageAsLeaderTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
```

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
At ffd7e43 the FDB test failures again unrelated:
```
org.kie.server.integrationtests.common.KieServerContainerCRUDIntegrationTest.initializationError
org.kie.server.integrationtests.common.KieServerIntegrationTest.initializationError
org.kie.server.integrationtests.common.jms.ContainerJmsResponseHandlerIntegrationTest.initializationError
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:44193/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerEmptyBody[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:44193/kie-server-services/services/rest/server'}]
org.kie.hacep.KafkaTest.basicTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsLeaderTest.processOneSentMessageAsLeaderTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
```

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
@hellowdan I have no idea how to avoid SonarCloud false report, as explained here https://github.com/kiegroup/drools/pull/3028#issuecomment-668129698 , I would just classify it as a false problem.

**Review by hellowdan — APPROVED** [review]

**Comment by hellowdan** [comment]
> @hellowdan I have no idea how to avoid SonarCloud false report, as explained here [#3028 (comment)](https://github.com/kiegroup/drools/pull/3028#issuecomment-668129698) , I would just classify it as a false problem.
Looking the SonarCloud complains: I agree, it seems false problem.

**Comment by tarilabs** [comment]
Jenkins execute full downstream compile

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
@rsynek unfortunately c97f2b6 it didn't work as expected... any other ideas pls? 🤔

**Comment by rsynek** [comment]
@tarilabs I am sorry to hear that. For me this worked:
https://github.com/kiegroup/optaplanner/blob/master/optaplanner-core/src/main/java/org/optaplanner/core/impl/io/jaxb/JaxbIO.java#L95

Let's see if putting the annotation on the local variables helps.

**Comment by tarilabs** [comment]
> Let's see if putting the annotation on the local variables helps.

Yes, and if that doesn't solve it, while I'm at it I would also try with the `//NOSONAR` line comment on each of those lines, as described here: https://docs.sonarqube.org/latest/faq/
I mean, at least we will have tried every possible option! 🤣

**Comment by rsynek** [comment]
@tarilabs :) or we can waive it in the UI, still keeping the comment.

**Comment by tarilabs** [comment]
but IIRC setting it in the UI doesn't change the big red X here on this github pr page

**Comment by rsynek** [comment]
> but IIRC setting it in the UI doesn't change the big red X here on this github pr page

One has to rerun the analysis again in order to update the PR check, I think.

**Comment by tarilabs** [comment]
no dice, will give it the 3rd attempt

**Comment by mbiarnes** [comment]
Jenkins execute full downstream compile

**Comment by mbiarnes** [comment]
Jenkins execute compile downstream build

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
@rsynek it worked as intended with the `//NOSONAR` command line variant.
And the rest is false positive since the code is used in full while the Maven reactor build is performed downstream but this can't ever be detected :) 
I would have preferred for the `@SuppressWarning` variant, but I believe this is the best we can achieve so far.
wdyt?

**Comment by tarilabs** [comment]
```
Test Result (1 failure / +1)
org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT
```
FDB failures unrelated

**Comment by rsynek** [comment]
> @rsynek it worked as intended with the `//NOSONAR` command line variant.
> And the rest is false positive since the code is used in full while the Maven reactor build is performed downstream but this can't ever be detected :)
> I would have preferred for the `@SuppressWarning` variant, but I believe this is the best we can achieve so far.
> wdyt?

@tarilabs Regardless of how we suppress the issue (it's a pity the annotation does not work here), a comment explaining what the issue is and why it's a false positive could still help in the future, do you agree?

**Comment by tarilabs** [comment]
Done!
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
can a @kiegroup/gatekeepers kindly merge with squash, please?

SonarCloud code coverage report is wrong since this new code is used by Maven build, so likely undetected. Other SonarCloud considerations and others if needed, have been discussed above.

**Pull request merged**
