### PR TITLE
DROOLS-3841: [DMN Designer] Included Models - An error is raised when a DMN file with imports is saved

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3841

@tarilabs @mariofusco This PR shows the error reported in the referenced JIRA.

It comes about by the Workbench adding the second DMN file (the one _importing_ the other) is added incrementally to `KieBuilder`. This is how the workbench builds projects incrementally...  A full build is OK.

### CODE REVIEW

**Comment by manstis** [comment]
IMO it appears `DMNAssemblerService` is at fault.

When handling a single additional resource it fails to try and resolve the single resources possible import dependency. Simply commenting out the "quick path" reveals that the issue is slightly more complex as presumably `ImportDMNResolverUtil` does not consider DMN files already assembled!?

**Comment by tarilabs** [comment]
IMO `KieAssemblerService#addResources` was added to cover build order, but it seems to me by the API usage you have in the test, that the KieAssembler is not covering this use case, when there is a dependency from a previously added resources which is either: not passed to the collection of resources (again) nor I have a notification of removed assets (as they been compiled but not removed)

**Comment by manstis** [comment]
@tarilabs PR updated to include your PR on my fork.

Could you please approve?

**Review by tarilabs — APPROVED** [review]

**Review by jomarko — APPROVED** [review]
Thank you, checked with workbench where included models were not turned off and it fixed the issue.

**Pull request merged**
