### PR TITLE
[incubator-kie-issues#1395] Write developer documentation for the DMN implementation

### LINKED ISSUE #1395: Write developer documentation for the DMN implementation
Create a Developer_Guide.md file, inside `kie-dmn`, to give guidance and explanations for developers that are going to contribute to the project.
Main topics to cover

    overall architecture
    critical code paths
    general guidelines

### PR DESCRIPTION
**Pull request by gitgabrio**
Fixes https://github.com/apache/incubator-kie-issues/issues/1395

@bncriju

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Comment by tiagobento** [comment]
Hi @gitgabrio, I have some questions about the `.puml` files you added... I see they're also present for documenting other parts of the project, but I'm not familiar with them. Do you mind providing details about how to edit, visualize, re-generate the PNGs based on them? I'm asking because these diagrams can change in the future, based on changes applied to the code, so having instructions on how to manage them is essential for keeping these docs up-to-date. Thanks in advance! And sorry if this is already written somewhere I didn't find.

**Review by bncriju — COMMENTED** [review]
This documentation is readable and understandable even to a new person who might not have complete knowledge of the same. It was nice if the sections 'Interpreted vs Codegen' and 'Coercion' were little more explanatory. Thanks

**Review by bncriju — COMMENTED** [review]
Changes made look good and now the sections mentioned are easy to be understood. Also the main Readme looks good. Thanks

**Comment by gitgabrio** [comment]
> Hi @gitgabrio, I have some questions about the `.puml` files you added... I see they're also present for documenting other parts of the project, but I'm not familiar with them. Do you mind providing details about how to edit, visualize, re-generate the PNGs based on them? I'm asking because these diagrams can change in the future, based on changes applied to the code, so having instructions on how to manage them is essential for keeping these docs up-to-date. Thanks in advance! And sorry if this is already written somewhere I didn't find.

Since it involves different modules, I add it to top-level "Readme"

**Review by yesamer — APPROVED** [review]

**Pull request merged**
