### PR TITLE
[DROOLS-7234] Declare KieRuntimeServicePMMLMapInput for NativeImage recognition

### PR DESCRIPTION
**Pull request by gitgabrio**
@evacchi 

**JIRA**: 
[link](https://issues.redhat.com/browse/DROOLS-7234)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

 - for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel-lts</b>
</details>

### CODE REVIEW

**Comment by gitgabrio** [comment]
Jenkins run native

**Comment by evacchi** [comment]
jenkins run kogito-runtimes native

**Comment by kie-ci3** [comment]
**(native) - kogito-apps job** `#35` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-apps/35/display/redirect

**Test results:**
- PASSED: 1353
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-apps/35/testReport/org.kie.kogito.it.jobs/SwitchStateTimeoutsIT/Build_projects___switchStateEventConditionTimeoutsTransitionTimeoutsExceeded/">Build projects / org.kie.kogito.it.jobs.SwitchStateTimeoutsIT.switchStateEventConditionTimeoutsTransitionTimeoutsExceeded</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.it.jobs.SwitchStateTimeoutsIT No requests exactly matched. Most similar request was:  expected:<<br/>POST<br/>/<br/><br/>kogitoprocinstanceid [equalTo] 2304867c-533b-45e5-a058-75d96a43ba73<br/>type [equalTo] process_result_event<br/>data.decision [equalTo] NoDecision> but was:<<br/>POST<br/>/<br/><br/>{}<br/>{}<br/>{}> within 50 seconds.<br/>	at org.kie.kogito.it.jobs.SwitchStateTimeoutsIT.verifyNoDecisionEventWasProduced(SwitchStateTimeoutsIT.java:48)<br/>Caused by: com.github.tomakehurst.wiremock.client.VerificationException: <br/>No requests exactly matched. Most similar request was:  expected:<<br/>POST<br/>/<br/><br/>kogitoprocinstanceid [equalTo] 2304867c-533b-45e5-a058-75d96a43ba73<br/>type [equalTo] process_result_event<br/>data.decision [equalTo] NoDecision> but was:<<br/>POST<br/>/<br/><br/>{}<br/>{}<br/>{}><br/>	at org.kie.kogito.it.jobs.SwitchStateTimeoutsIT.lambda$verifyNoDecisionEventWasProduced$0(SwitchStateTimeoutsIT.java:48)<br/>
</details>

**Comment by kie-ci3** [comment]
**(tests) - kogito-examples job** `#746` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/746/display/redirect

**Test results:**
- PASSED: 532
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/746/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49227] should be listening)<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.before(OutboxIT.java:86)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49227] should be listening)<br/>
</details>

**Comment by kie-ci3** [comment]
**(native) - kogito-runtimes job** `#38` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-runtimes/38/display/redirect

**Test results:**
- PASSED: 3113
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-runtimes/38/testReport/org.kie.kogito.quarkus.workflows/EventFlowIT/testNotStartingMultipleEventRainy/">org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEventRainy</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Condition with alias 'dead' didn't complete within 5 seconds because assertion condition defined as a lambda expression in org.kie.kogito.quarkus.workflows.EventFlowIT that uses java.lang.String, java.lang.Stringjava.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/>.<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.waitForFinish(EventFlowIT.java:133)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEventRainy(EventFlowIT.java:94)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.lambda$waitForFinish$1(EventFlowIT.java:138)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-runtimes/38/testReport/org.kie.kogito.quarkus.workflows/EventFlowIT/testNotStartingMultipleEvent/">org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEvent</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Condition with alias 'dead' didn't complete within 15 seconds because assertion condition defined as a lambda expression in org.kie.kogito.quarkus.workflows.EventFlowIT that uses java.lang.String, java.lang.Stringjava.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/>.<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.waitForFinish(EventFlowIT.java:133)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.doIt(EventFlowIT.java:144)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEvent(EventFlowIT.java:69)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.lambda$waitForFinish$1(EventFlowIT.java:138)<br/>
</details>

**Comment by kie-ci3** [comment]
**(native) - kogito-runtimes job** `#37` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-runtimes/37/display/redirect

**Test results:**
- PASSED: 3113
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-runtimes/37/testReport/org.kie.kogito.quarkus.workflows/EventFlowIT/testNotStartingMultipleEventRainy/">org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEventRainy</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Condition with alias 'dead' didn't complete within 5 seconds because assertion condition defined as a lambda expression in org.kie.kogito.quarkus.workflows.EventFlowIT that uses java.lang.String, java.lang.Stringjava.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/>.<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.waitForFinish(EventFlowIT.java:133)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEventRainy(EventFlowIT.java:94)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.lambda$waitForFinish$1(EventFlowIT.java:138)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-runtimes/37/testReport/org.kie.kogito.quarkus.workflows/EventFlowIT/testNotStartingMultipleEvent/">org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEvent</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Condition with alias 'dead' didn't complete within 15 seconds because assertion condition defined as a lambda expression in org.kie.kogito.quarkus.workflows.EventFlowIT that uses java.lang.String, java.lang.Stringjava.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/>.<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.waitForFinish(EventFlowIT.java:133)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.doIt(EventFlowIT.java:144)<br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.testNotStartingMultipleEvent(EventFlowIT.java:69)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>	at org.kie.kogito.quarkus.workflows.EventFlowIT.lambda$waitForFinish$1(EventFlowIT.java:138)<br/>
</details>

**Comment by radtriste** [comment]
jenkins rerun kogito-examples tests

**Comment by radtriste** [comment]
kogito-apps native -> `org.kie.kogito.it.jobs.SwitchStateTimeoutsIT` -> known issue AFAIK

**Comment by radtriste** [comment]
kogito-runtimes native -> https://issues.redhat.com/browse/KOGITO-8213

**Comment by kie-ci3** [comment]
**(native) - kogito-examples job** `#33` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-examples/33/display/redirect

**Test results:**
- PASSED: 273
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-examples/33/testReport/org.kogito.serverless.examples/ApplicantWorkflowIT/testApplicantProcess/">org.kogito.serverless.examples.ApplicantWorkflowIT.testApplicantProcess</a></summary>
java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/drools.native.downstream.kogito-examples/33/testReport/org.acme.newsletter.subscription.flow/SubscriptionFlowIT/verifySubscription/">org.acme.newsletter.subscription.flow.SubscriptionFlowIT.verifySubscription</a></summary>
Assertion condition defined as a lambda expression in org.acme.newsletter.subscription.flow.SubscriptionFlowIT No requests exactly matched. Most similar request was:  expected:<<br/>POST<br/>/<br/><br/>new.subscription<br/>yeneffer@witch.com<br/>Yeneffer> but was:<<br/>POST<br/>/<br/><br/>{}<br/>{}<br/>{}> within 10 seconds.
</details>

**Comment by gitgabrio** [comment]
@radtriste @evacchi 
PMML seems fixed with that. All failures in this PR seems unrelated to me. Could you  verify and eventually approve/merge it ?
Thanks

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
@evacchi I let you merge it once approved :)

**Review by evacchi — APPROVED** [review]

**Pull request merged**
