### PR TITLE
DROOLS-5589 Review kie-dmn-core (misc) DMN examples version in codebase

### PR DESCRIPTION
**Pull request by tarilabs**
**Thank you for submitting this pull request**

**JIRA**: DROOLS-5589

**referenced Pull Requests**: none

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
```
Setting status of 83ac3bac68eba47209483508fdfc6b9a5d3828a8 to FAILURE with url https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/compileDownstream/job/new-CDB-drools-master.compile/191/ and message: 'Build finished. No test results found.'
Using context: Linux - Compile Downstream Build
ERROR: script returned exit code 2
Finished: FAILURE
```

🤷

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
superseeded by https://github.com/kiegroup/drools/pull/3057

**Pull request closed without merging**
