### PR TITLE
DROOLS-4250: Improve data source type resolving in OOPath

### PR DESCRIPTION
**Pull request by evacchi**
Some changes @lucamolteni and I discussed together in person. Better error reporting and ~~refactored data source type resolving for code generation.~~ fix oopath parsing. Refactoring removed and possibly moved to a different PR

### CODE REVIEW

**Comment by baldimir** [comment]
@evacchi Nitpicking: please see SonarCloud report - there is unused import there. 

I expect this is largely tested by existing tests, right?

**Comment by evacchi** [comment]
yes, just a refactoring/error reporting (it was an NPE before) if it's green then it should be good to go

**Review by baldimir — APPROVED** [review]

**Comment by evacchi** [comment]
I am fixing the sonarcloud issues

**Comment by evacchi** [comment]
jenkins please execute full downstream build

**Comment by evacchi** [comment]
jenkins please execute full downstream build

**Comment by evacchi** [comment]
@mariofusco is the failing test a flaky one? can we merge?

**Comment by evacchi** [comment]
jenkins please execute full downstream build

**Comment by evacchi** [comment]
jenkins please execute full downstream build

**Pull request merged**
