### PR TITLE
DROOLS-6605 SceSim run DMN models on BC/WB does not include expected profiles

### PR DESCRIPTION
**Pull request by tarilabs**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6605

**referenced Pull Requests**: none

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]
Thanks for the PR, very well done 👍

**Comment by tarilabs** [comment]
```
kiegroup_drools/kie-dmn/kie-dmn-feel-gwt-showcase/src/test/java/org/kie/dmn/feel/client/showcase/FEELShowcaseIT.java:54 | No connection could be made because the target machine actively refused it. (os error 10061) Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z' System info: host: 'fv-az153-751', ip: '10.1.0.86', os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_302' Driver info: driver.version: FirefoxDriver remote stacktrace:
kiegroup_drools/kie-dmn/kie-dmn-feel-gwt-showcase/src/test/java/org/kie/dmn/feel/client/showcase/FEELShowcaseIT.java:60 | java.lang.NullPointerException 	at org.kie.dmn.feel.client.showcase.FEELShowcaseIT.quitDriver(FEELShowcaseIT.java:60)
```

unrelated.

**Review by yesamer — APPROVED** [review]
Thank you @tarilabs!

**Review by hellowdan — APPROVED** [review]

**Review by pibizza — APPROVED** [review]
Looks good to me.

**Pull request merged**
