### PR TITLE
RHPAM-2307: Remove unused dependencies

### PR DESCRIPTION
**Pull request by jomarko**
During RHPAM-2307 review some unused dependencies were found.

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed test:
```
org.kie.hacep.LocalStorageStreamingKieSessionTest.fireUntilHaltTest
```

jenkins execute full downstream build

**Comment by mareknovotny** [comment]
@jomarko Is this required to be merged to resolve RHPAM-2307 completely?

**Comment by jomarko** [comment]
@mareknovotny no I think jira status can be sot to done. I reference RHPAM-2307 just to have reference to something related.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@baldimir may I ask you for a review of this PR?

**Review by baldimir — APPROVED** [review]

**Comment by jomarko** [comment]
@mareknovotny may I ask you for a merge?

**Pull request merged**
