### PR TITLE
DROOLS-3380 - Remove whitespaces with for loop instead of matcher().replaceAll()

### PR DESCRIPTION
**Pull request by barreiro**
Improves the performance of `EvalHelper.normalizeVariableName()` by not using a regex to do remove the white-space chars.

### CODE REVIEW

**Comment by barreiro** [comment]
@tarilabs you may want to look at this!

**Review by tarilabs — APPROVED** [review]
Jenkins test again

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by tarilabs** [comment]
ok to test

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
```
Test Result (1 failure / ±0)
org.drools.compiler.integrationtests.CepEspTest.testEventExpirationInSlidingWindow[KieBase type=STREAM_IDENTITY_MODEL_FLOW]
```

Jenkins test again

**Pull request merged**
