### PR TITLE
[RHDM-1895] Saving dmn model is not working when using not() function

### PR DESCRIPTION
**Pull request by danielzhe**
Fixed by a backport of https://github.com/kiegroup/drools/pull/4334

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]

**Review by mariofusco — CHANGES_REQUESTED** [review]
On drools 7.x we still use `hamcrest` instead of `assertj` so the tests have some compilation failures like
```
[ERROR] /home/runner/work/drools/drools/kiegroup_drools/kie-dmn/kie-dmn-validation/src/test/java/org/kie/dmn/validation/dtanalysis/IntervalTest.java:[100,9] no suitable method found for assertThat(java.util.List<org.kie.dmn.validation.dtanalysis.model.Interval>)
```
Please fix the test classes accordingly.

**Comment by tarilabs** [comment]
> On drools 7.x we still use `hamcrest` instead of `assertj` so the tests have some compilation failures ...

not necessarily, see https://github.com/kiegroup/drools/commit/5d65d9ffe1448bf47bc3e27bffb3b475d2b7d845#diff-8a18918b6b326c010f70aa152461a8eb27f36b22c19b693f227a063fecfdb820R117

I believe it might fix with the appropriate `import` backport fix.

**Comment by danielzhe** [comment]
@mariofusco Changes applied. I think it is ok now.

**Review by mariofusco — APPROVED** [review]

**Comment by danielzhe** [comment]
@kiegroup/gatekeepers Merge, please!

**Comment by danielezonca** [comment]
@baldimir FYI

**Pull request merged**
