### PR TITLE
DROOLS-5869 : Running tests should not affect incremental build

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**: 
[link](https://issues.redhat.com/browse/DROOLS-5869)

The ticket was reopened. The real producer and deatails here https://issues.redhat.com/browse/DROOLS-5458 
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
@yesamer I prepared something like this. I asked @lucamolteni if this is the best way to fix it and how to test it, since I failed at making a reproducing unit test.

**Comment by Rikkola** [comment]
@jstastny-cz Since this is tricky to test as unit test would it be possible to cover it with our selenium tests?

**Comment by Rikkola** [comment]
I'll race with the fdb to make a war.

Jenkins run fdb

**Comment by lucamolteni** [comment]
@Rikkola we can provide the test tomorrow - does this fix the problem? do we already have an integration test? @jstastny-cz

**Comment by Rikkola** [comment]
@lucamolteni if it is possible to test this reasonably for the PR to pass I think we are fine. I'm more worried about if the implementation is correct or not.

**Comment by mariofusco** [comment]
I tried to reproduce this issue with a unit test [here](https://gist.github.com/mariofusco/491194312fa8a65128c2c5bcfd8bff15) but it doesn't fail even without this fix, so I have no clue on how to recreate this problem with a single test.
@Rikkola please give a look at my test, and check if it makes sense for you and more important if you could find a way to modify it in order to reproduce the problem.
@lucamolteni in case we are not able to create a unit test for this issue, I don't see any harm in this PR and also I don't see any alternative other than merging it as it is.

**Review by mariofusco — APPROVED** [review]

**Review by lucamolteni — APPROVED** [review]
Fine by me then

**Review by jstastny-cz — APPROVED** [review]
LGTM, run regression suite and confirmation tests. All seems good, execution times seem unaffected (though judging on my local machine only).

**Review by yesamer — APPROVED** [review]

**Comment by Rikkola** [comment]
@mariofusco I tried similar tests with incremental builder setup for example and also failed to reproduce. I feel like we need the UI test anyway to make sure the path works correctly. So we might have to merge as it is.

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Local test run in kie-wb-distributions passed.

**Pull request merged**
