### PR TITLE
[JBPM-10187] Sorting the transformable set to avoid deadlock

### PR DESCRIPTION
**Pull request by fjtirado**
Sorting resources to avoid oracle deadlock

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins run fdb

**Comment by fjtirado** [comment]
jenkins run fdb

**Comment by fjtirado** [comment]
jenkins run fdb

**Comment by fjtirado** [comment]
jenkins run fdb

**Comment by fjtirado** [comment]
jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do cdb

**Comment by fjtirado** [comment]
jenkins run fdb

**Review by mariofusco — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do cdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
please check the failures and errors in CDB/FDB. @mariofusco @fjtirado

**Comment by fjtirado** [comment]
Closing since we need to expand on this one

**Pull request closed without merging**
