### PR TITLE
[DROOLS-1730] Cyclic information requirement generates a stackoverflow

### PR DESCRIPTION
**Pull request by kurobako**

### CODE REVIEW

**Comment by etirelli** [comment]
@kurobako , we are no longer maintaining branch 7.3.x. This fix just needs to be merged into master and 7.4.x.

**Comment by kurobako** [comment]
@etirelli changed base branch

**Comment by kurobako** [comment]
java.lang.RuntimeException: Can not connect to GitHub using the configured OAuth token

environment seems to be in trouble now, will try again later

**Comment by kurobako** [comment]
retest this please

**Comment by etirelli** [comment]
jenkins test this

**Comment by kurobako** [comment]
@etirelli seems good now

**Review by etirelli — APPROVED** [review]

**Pull request merged**
