### PR TITLE
[DROOLS-7511] Review StoredObject and StoredEvent structure

### PR DESCRIPTION
**Pull request by tkobayas**
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7511

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

 - for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Actually, I didn't change the inheritance structure much. Rather, this PR is to adapt Event use cases to `PersistenceObjectsStrategy.OBJECT_REFERENCES`

If `SerializableStoredRefEvent` extends `SerializableStoredRefObject`, Event classes cannot extends `BaseStoredEvent` so all Event classes would need to implement `timestamp` and `duration` fields. It would be messy.

In order to reduce the code duplication, I moved `updateReferencedObjects` logic to `ReliabilityUtils` in order to share  among `SerializableStoredRefObject` and `SerializableStoredRefEvent`. Also introduced `ReferenceWireable` interface to be common to these classes.

**Comment by kie-ci4** [comment]
**(tests) - kogito-apps job** `#1689` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/drools/pull/5505 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/1689/display/redirect

**Test results:**
- PASSED: 2789
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-09-01T11:41:06.142Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-09-01T11:41:06.142Z] devtmpfs        7.7G     0  7.7G   0% /dev<br/>[2023-09-01T11:41:06.142Z] tmpfs           7.7G     0  7.7G   0% /dev/shm<br/>[2023-09-01T11:41:06.142Z] tmpfs           7.7G   49M  7.7G   1% /run<br/>[2023-09-01T11:41:06.142Z] tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup<br/>[2023-09-01T11:41:06.142Z] /dev/vda3        80G   55G   26G  68% /<br/>[2023-09-01T11:41:06.142Z] /dev/vda2       100M  5.8M   95M   6% /boot/efi<br/>[2023-09-01T11:41:06.142Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2023-09-01T11:41:06.164Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2023-09-01T11:41:06.440Z] + du -h -d1 /home/jenkins<br/>[2023-09-01T11:41:06.440Z] 4.0K	/home/jenkins/.ssh<br/>[2023-09-01T11:41:06.440Z] 0	/home/jenkins/go<br/>[2023-09-01T11:41:06.440Z] 8.0K	/home/jenkins/.vnc<br/>[2023-09-01T11:41:06.998Z] 2.1G	/home/jenkins/.m2<br/>[2023-09-01T11:41:07.251Z] 2.2G	/home/jenkins/git-repos<br/>[2023-09-01T11:41:07.251Z] 32K	/home/jenkins/.config<br/>[2023-09-01T11:41:07.504Z] 154M	/home/jenkins/virtenvs<br/>[2023-09-01T11:41:07.504Z] 4.0K	/home/jenkins/.cekit<br/>[2023-09-01T11:41:07.504Z] 31M	/home/jenkins/remoting<br/>[2023-09-01T11:41:08.062Z] 703M	/home/jenkins/.cache<br/>[2023-09-01T11:41:08.315Z] du: cannot access '/home/jenkins/workspace/atomic7135793095485538433tmp': No such file or directory<br/>[2023-09-01T11:41:08.315Z] 7.3G	/home/jenkins/workspace<br/>[2023-09-01T11:41:08.569Z] 145M	/home/jenkins/tools<br/>[2023-09-01T11:41:08.569Z] 0	/home/jenkins/caches<br/>[2023-09-01T11:41:08.825Z] 181M	/home/jenkins/.npm<br/>[2023-09-01T11:41:08.825Z] 52K	/home/jenkins/.docker<br/>[2023-09-01T11:41:11.329Z] 979M	/home/jenkins/.local<br/>[2023-09-01T11:41:11.329Z] 0	/home/jenkins/.mozilla<br/>[2023-09-01T11:41:11.329Z] 310M	/home/jenkins/.sonar<br/>[2023-09-01T11:41:11.329Z] 14G	/home/jenkins<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-09-01T11:41:11.915Z] + wget --no-check-certificate -qO - 'https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/1689/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>[2023-09-01T11:41:12.248Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/1689/consoleText<br/>[2023-09-01T11:41:12.249Z] + tail -n 50<br/>
</details>

**Comment by tkobayas** [comment]
@mariofusco @nprentza @pibizza Please review, thanks!

**Review by mariofusco — APPROVED** [review]
Nice work :+1:

**Review by nprentza — APPROVED** [review]
Nice work!

**Pull request merged**
