### PR TITLE
[KOGITO-2852] descoping of mvel/asm from the core engine

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mareknovotny** [comment]
Jenkins do cdb

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mareknovotny** [comment]
there is problem on master it seems, https://github.com/kiegroup/droolsjbpm-integration/commit/012fbaa3fcbe4d0ca9c604b4c72abc1094505812 added `org.jbpm.contrib:kafka-workitem` dependency into  **kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/pom.xml**, but that dependency is built in jbpm-work-items repository which is not built before droolsjbpm-integration.
fyi @elguardian @gmunozfe https://issues.redhat.com/browse/JBPM-9396
I guess we need to change the order of repository-list.txt now to satisfy the dependencies

**Comment by mareknovotny** [comment]
I sent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1479 to fix the order of repositories in repository-list.txt

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins execute cdb

**Pull request merged**
