### PR TITLE
[7.x] KOGITO-6781: XML Prolog support for .scesim files 

### PR DESCRIPTION
**Pull request by yesamer**
Scesim unmarshaller extracts the scesim version from the XML prolog instead of ScenarioSimulationNode

JIRA: https://issues.redhat.com/browse/KOGITO-6781

Backport of https://github.com/kiegroup/drools/pull/4205

Required to support scesims files generated with lastest versions of Kogito

### CODE REVIEW

**Review by gitgabrio — APPROVED** [review]
LGTM! Thanks @yesamer

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
once war file is generated, I will do some sanity check and approve

**Review by jomarko — APPROVED** [review]
Manual check result
- running existing scesim (:+1:)
- creating a new scesim (:+1:)

@yesamer thank you for a PR.

**Comment by yesamer** [comment]
@danielezonca can you please merge it? (failues on FDB seems unrelated)

**Pull request merged**
