### PR TITLE
[DROOLS-6067] Calling fireAllRules simultaneously from multiple threa…

### PR DESCRIPTION
**Pull request by tkobayas**
…ds in plain drl sometimes causes MVEL syntax errors.

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6067

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
@mariofusco @hellowdan 

Please review. The point is that ParserContext (PropertyVerifier.pCtx) is mutable so has an concurrency issue as Masato described in DROOLS-6067.

The most conservative approach is to synchronize all MVELConditionEvaluator calls. (e.g. https://gist.github.com/tkobayas/1044be7c0760ed1c426a1b84157cc0d4).

But as far as I tested with the DROOLS-6067 test case (ConstraintConcurrencyTest), it's enough to synchronize MVELConditionEvaluator creation and the first evaluate() call (where mvel optimization takes place).

It's a turtle test so you need to run it with:

`mvn test -Dtest=ConstraintConcurrencyTest -DrunTurtleTests`

Do you have any concerns in this approach? It's only the first evaluate() call so less performance impact. Also I think  mvelOptimized.await() won't cause a deadlock...

**Review by hellowdan — APPROVED** [review]

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
