### PR TITLE
DROOLS-4873 DMN v1.3 unary test syntax of range

### PR DESCRIPTION
**Pull request by tarilabs**
/cc @etirelli @baldimir @jiripetrlik @hellowdan

### CODE REVIEW

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
no way it's 0% red coverage.

Jenkins test again

**Comment by tarilabs** [comment]
no way it's 0% red coverage.

Jenkins test again

**Review by jiripetrlik — CHANGES_REQUESTED** [review]
It seems that there are some expressions which always evaluate to "false" according to Sonar cloud report. Please check and remove these expressions if possible.

**Comment by tarilabs** [comment]
The SonarCloud report I believe is dangerous.

I believe the correct solution is NOT to remove the expression which SonarCloud is suggesting to remove, but change it from
`... lowEndPoint == null || highEndPoint == null ...`
to
`... lowEndPoint == null && highEndPoint == null ...`

**Comment by jiripetrlik** [comment]
@tarilabs 
Yes, I agree. Sonar cloud is definitely not always true. Can you try to change it as you proposed and run PR checks?

**Review by baldimir — APPROVED** [review]

**Pull request merged**
