### PR TITLE
DROOLS-4629 DMN heuristic for invocation name

### PR DESCRIPTION
**Pull request by tarilabs**
/cc @etirelli @baldimir @jiripetrlik

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
```
Test Result (4 failures / -9)
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testContentManagerPerspective
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testLibraryPerspectiveWithHeader
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testLibraryPerspectiveWithoutHeader
```

as the downstream is only about Selenium tests failure (unrelated) I vote to merge.

**Comment by sutaakar** [comment]
ok for me (do not consider it as a QE PR review, needs to  be done by someone with DMN knowledge, @jiripetrlik ?)

**Review by baldimir — APPROVED** [review]

**Pull request merged**
