### PR TITLE
BAQE-1567 - Change revapi to check against 7.44.0.Final

### PR DESCRIPTION
**Pull request by MarianMacik**
**Thank you for submitting this pull request**

**JIRA**: [BAQE-1567](https://issues.redhat.com/browse/BAQE-1567)

depends on kiegroup/droolsjbpm-build-bootstrap#1485

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins execute compile downstream build

**Comment by MarianMacik** [comment]
Jenkins run cdb

**Comment by MarianMacik** [comment]
Compile downstream fails because of an issue in the droolsjbpm-tools repository (not related with changes in this PR).
Java 11 fails because of an appformer issue (not related with changes in this PR).

**Review by gmunozfe — APPROVED** [review]
Looks good to me

**Comment by MarianMacik** [comment]
jenkins retest this

**Pull request merged**
