### PR TITLE
[JBPM-10117] Assume a null id object is not deattached

### PR DESCRIPTION
**Pull request by fjtirado**
If the object is not a deattached one, find should not be called

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-10117)

### CODE REVIEW

**Comment by fjtirado** [comment]
Jenkins run fdb

**Comment by fjtirado** [comment]
jenkins run fdb

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins run fdb

**Comment by fjtirado** [comment]
jenkins run fdb

**Review by elguardian — APPROVED** [review]

**Review by afalhambra — COMMENTED** [review]
looks good to me though it would be great if we can provide a test case for this, maybe in the integration repo?

**Comment by fjtirado** [comment]
> looks good to me though it would be great if we can provide a test case for this, maybe in the integration repo?

@afalhambra  I tried but I was not able to force the test to pick pessimistic, copy pasting the diff here
```

diff --git a/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_9077_63122c16_a b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_9077_63122c16_a
new file mode 100644
index 0000000..ba31ab0
--- /dev/null
+++ b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_9077_63122c16_a
Binary files differ
diff --git a/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a1fb_63122515_a b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a1fb_63122515_a
new file mode 100644
index 0000000..931929a
--- /dev/null
+++ b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a1fb_63122515_a
Binary files differ
diff --git a/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a3b1_63122b6f_a b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a3b1_63122b6f_a
new file mode 100644
index 0000000..902561d
--- /dev/null
+++ b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a3b1_63122b6f_a
Binary files differ
diff --git a/jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/RetrySyncWorkItemByJPATest.java b/jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/RetrySyncWorkItemByJPATest.java
index f8cd951..96d7e19 100644
--- a/jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/RetrySyncWorkItemByJPATest.java
+++ b/jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/RetrySyncWorkItemByJPATest.java
@@ -15,6 +15,8 @@
  */
 package org.jbpm.test.functional.workitem;
 
+import static org.junit.Assert.assertEquals;
+
 import java.util.Collection;
 import java.util.HashMap;
 import java.util.List;
@@ -23,6 +25,7 @@
 import org.drools.core.process.instance.WorkItemManager;
 import org.jbpm.test.JbpmTestCase;
 import org.junit.Test;
+import org.kie.api.runtime.EnvironmentName;
 import org.kie.api.runtime.KieSession;
 import org.kie.api.runtime.manager.RuntimeEngine;
 import org.kie.api.runtime.process.NodeInstance;
@@ -31,8 +34,6 @@
 import org.kie.api.task.model.TaskSummary;
 import org.kie.internal.runtime.manager.context.EmptyContext;
 
-import static org.junit.Assert.assertEquals;
-
 public class RetrySyncWorkItemByJPATest extends JbpmTestCase {
 
     private static final String RETRY_WORKITEM_JPA_PROCESS_ID = "org.jbpm.test.retryWorkitem-jpa";
@@ -43,9 +44,21 @@
 
     @Test
     public void workItemRecoveryTestByJPA() {
+        workItemRecovery(false);
+    }
+    
+    @Test
+    public void workItemRecoveryTestByJPAPessimistic() {
+        workItemRecovery(true);
+    }
+
+    private void workItemRecovery (boolean pessimistic) {
         manager = createRuntimeManager( "org/jbpm/test/functional/workitem/retry-workitem-jpa.bpmn2" );
         RuntimeEngine runtimeEngine = getRuntimeEngine( EmptyContext.get() );
+        
+        
         KieSession kieSession = runtimeEngine.getKieSession();
+        kieSession.getEnvironment().set(EnvironmentName.USE_PESSIMISTIC_LOCKING, pessimistic);
         WorkItemManager workItemManager = (org.drools.core.process.instance.WorkItemManager) kieSession.getWorkItemManager();
 
         workItemManager.registerWorkItemHandler( "ExceptionWorkitem", new ExceptionWorkItemHandler() );
@@ -67,6 +80,7 @@
         Collection<NodeInstance> nis = ((org.kie.api.runtime.process.WorkflowProcessInstance) processInstance).getNodeInstances();
         retryWorkItem( workItemManager, nis );
         assertProcessInstanceCompleted( processInstance.getId() );
+
     }
 
     private void retryWorkItem( WorkItemManager workItemManager, Collection<NodeInstance> nis ) {



```

**Comment by afalhambra** [comment]
> > looks good to me though it would be great if we can provide a test case for this, maybe in the integration repo?
> 
> @afalhambra I tried but I was not able to force the test to pick pessimistic, copy pasting the diff here
> 
> ```
> 
> diff --git a/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_9077_63122c16_a b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_9077_63122c16_a
> new file mode 100644
> index 0000000..ba31ab0
> --- /dev/null
> +++ b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_9077_63122c16_a
> Binary files differ
> diff --git a/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a1fb_63122515_a b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a1fb_63122515_a
> new file mode 100644
> index 0000000..931929a
> --- /dev/null
> +++ b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a1fb_63122515_a
> Binary files differ
> diff --git a/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a3b1_63122b6f_a b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a3b1_63122b6f_a
> new file mode 100644
> index 0000000..902561d
> --- /dev/null
> +++ b/jbpm-test-coverage/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_a3b1_63122b6f_a
> Binary files differ
> diff --git a/jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/RetrySyncWorkItemByJPATest.java b/jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/RetrySyncWorkItemByJPATest.java
> index f8cd951..96d7e19 100644
> --- a/jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/RetrySyncWorkItemByJPATest.java
> +++ b/jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/RetrySyncWorkItemByJPATest.java
> @@ -15,6 +15,8 @@
>   */
>  package org.jbpm.test.functional.workitem;
>  
> +import static org.junit.Assert.assertEquals;
> +
>  import java.util.Collection;
>  import java.util.HashMap;
>  import java.util.List;
> @@ -23,6 +25,7 @@
>  import org.drools.core.process.instance.WorkItemManager;
>  import org.jbpm.test.JbpmTestCase;
>  import org.junit.Test;
> +import org.kie.api.runtime.EnvironmentName;
>  import org.kie.api.runtime.KieSession;
>  import org.kie.api.runtime.manager.RuntimeEngine;
>  import org.kie.api.runtime.process.NodeInstance;
> @@ -31,8 +34,6 @@
>  import org.kie.api.task.model.TaskSummary;
>  import org.kie.internal.runtime.manager.context.EmptyContext;
>  
> -import static org.junit.Assert.assertEquals;
> -
>  public class RetrySyncWorkItemByJPATest extends JbpmTestCase {
>  
>      private static final String RETRY_WORKITEM_JPA_PROCESS_ID = "org.jbpm.test.retryWorkitem-jpa";
> @@ -43,9 +44,21 @@
>  
>      @Test
>      public void workItemRecoveryTestByJPA() {
> +        workItemRecovery(false);
> +    }
> +    
> +    @Test
> +    public void workItemRecoveryTestByJPAPessimistic() {
> +        workItemRecovery(true);
> +    }
> +
> +    private void workItemRecovery (boolean pessimistic) {
>          manager = createRuntimeManager( "org/jbpm/test/functional/workitem/retry-workitem-jpa.bpmn2" );
>          RuntimeEngine runtimeEngine = getRuntimeEngine( EmptyContext.get() );
> +        
> +        
>          KieSession kieSession = runtimeEngine.getKieSession();
> +        kieSession.getEnvironment().set(EnvironmentName.USE_PESSIMISTIC_LOCKING, pessimistic);
>          WorkItemManager workItemManager = (org.drools.core.process.instance.WorkItemManager) kieSession.getWorkItemManager();
>  
>          workItemManager.registerWorkItemHandler( "ExceptionWorkitem", new ExceptionWorkItemHandler() );
> @@ -67,6 +80,7 @@
>          Collection<NodeInstance> nis = ((org.kie.api.runtime.process.WorkflowProcessInstance) processInstance).getNodeInstances();
>          retryWorkItem( workItemManager, nis );
>          assertProcessInstanceCompleted( processInstance.getId() );
> +
>      }
>  
>      private void retryWorkItem( WorkItemManager workItemManager, Collection<NodeInstance> nis ) {
> ```

ok, never mind, I will try to create a test case later on. Thanks

**Review by afalhambra — APPROVED** [review]
nice work @fjtirado

**Pull request merged**
