### PR TITLE
[DROOLS-4343] change FactHandle ID from a Integer into a Long

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mariofusco** [comment]
@etirelli @baldimir please review what I've done regarding serialization. In order to avoid breaking backward compatibility of serialized session I added a second int32 to the protobuf message named extendedID and I store there the first 32 bits of the long FactHandle ID. Then I programmatically split the long id into 2 ints during protobuf serialization and recombine them during deserialization.

**Comment by baldimir** [comment]
jenkins retest this

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Comment by baldimir** [comment]
Another version here [1] https://github.com/kiegroup/drools/pull/2468. We don't need the split to base and extended ID as the int32 and int64 types are compatible in protobuf [1].

[1] https://developers.google.com/protocol-buffers/docs/proto3#updating

**Comment by mariofusco** [comment]
Replaced by https://github.com/kiegroup/drools/pull/2468

**Pull request closed without merging**
