### PR TITLE
[DROOLS-6852] ForceEagerActivationFilter doesn't work correctly for e…

### PR DESCRIPTION
**Pull request by tkobayas**
…xec-model (#4238)

**Ports** 
This is a forward-port PR of https://github.com/kiegroup/drools/pull/4238 for main

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6852

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - drools job** `#342` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/342/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-04T10:03:04.405Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-03-04T10:03:04.406Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646388179281/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/react-icons/dist/js/icons/utensils-icon.d.ts’: No such file or directory<br/>[2022-03-04T10:03:04.406Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646388179281/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/react-icons/dist/js/icons/vaadin-icon.d.ts’: No such file or directory<br/>[2022-03-04T10:03:04.406Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646388179281/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/react-icons/dist/js/icons/vector-square-icon.d.ts’: No such file or directory<br/>[2022-03-04T10:03:04.406Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646388179281/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/react-icons/dist/js/icons/venus-double-icon.d.ts’: No such file or directory<br/>[2022-03-04T10:03:04.406Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646388179281/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/react-icons/dist/js/icons/venus-icon.d.ts’: No such file or directory<br/>[2022-03-04T10:03:04.406Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646388179281/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/react-icons/dist/js/icons/venus-mars-icon.d.ts’: No such file or directory<br/>[2022-03-04T10:03:04.406Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646388179281/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/react-icons/dist/js/icons/viacoin-icon.d.ts’: No such file or directory<br/>[2022-03-04T10:03:04.406Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.13.x/pullrequest/kogito-runtimes.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646388179281/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/react-icons/dist/js/icons/viadeo-icon.d.ts’: No such file or directory<br/>[2022-03-04T10:03:04.406Z] 647M	/home/jenkins/workspace/KIE/kogito/1.13.x<br/>[2022-03-04T10:03:04.406Z] 2.1M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-03-04T10:03:04.406Z] 649M	/home/jenkins/workspace/KIE/kogito<br/>[2022-03-04T10:03:04.406Z] 649M	/home/jenkins/workspace/KIE<br/>[2022-03-04T10:03:04.406Z] 649M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-03-04T10:03:05.212Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/342/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by kie-ci1** [comment]
**(tests) - optaweb-vehicle-routing job** `#339` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.optaweb-vehicle-routing/339/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-04T10:19:55.976Z] 3.7G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-03-04T10:19:55.995Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-03-04T10:19:56.274Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-03-04T10:19:56.274Z] 0	/home/jenkins/workspace/KIE/kogito/1.13.x<br/>[2022-03-04T10:19:56.274Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646389186084/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/patternfly/assets/fonts/overpass-webfont/example.html’: No such file or directory<br/>[2022-03-04T10:19:56.274Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646389186084/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/patternfly/assets/fonts/overpass-webfont/overpass-bold-italic.ttf’: No such file or directory<br/>[2022-03-04T10:19:56.275Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646389186084/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/patternfly/assets/fonts/overpass-webfont/overpass-bold.ttf’: No such file or directory<br/>[2022-03-04T10:19:56.275Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-employee-rostering_ws-cleanup_1646389186084/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@patternfly/patternfly/assets/fonts/overpass-webfont/overpass-extrabold-italic.ttf’: No such file or directory<br/>[2022-03-04T10:19:56.275Z] 846M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-03-04T10:19:56.275Z] 846M	/home/jenkins/workspace/KIE/kogito<br/>[2022-03-04T10:19:56.275Z] 846M	/home/jenkins/workspace/KIE<br/>[2022-03-04T10:19:56.275Z] 846M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-03-04T10:19:57.192Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.optaweb-vehicle-routing/339/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by kie-ci1** [comment]
**(tests) - kogito-runtimes job** `#344` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2525
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-runtimes/344/testReport/org.kie.kogito.codegen/RuleUnitCompilerIT/testRuleUnitDelete(SessionType)[1]/">org.kie.kogito.codegen.RuleUnitCompilerIT.testRuleUnitDelete(SessionType)[1]</a></summary>
org.kie.kogito.codegen.rules.RuleCodegenError: <br/>Errors were generated during the code-generation process:<br/>java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.<br/><br/>	at org.kie.kogito.codegen.RuleUnitCompilerIT.createApplication(RuleUnitCompilerIT.java:386)<br/>	at org.kie.kogito.codegen.RuleUnitCompilerIT.createApplication(RuleUnitCompilerIT.java:380)<br/>	at org.kie.kogito.codegen.RuleUnitCompilerIT.testRuleUnitDelete(RuleUnitCompilerIT.java:124)<br/>Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.<br/>	at org.kie.kogito.codegen.RuleUnitCompilerIT.createApplication(RuleUnitCompilerIT.java:386)<br/>	at org.kie.kogito.codegen.RuleUnitCompilerIT.createApplication(RuleUnitCompilerIT.java:380)<br/>	at org.kie.kogito.codegen.RuleUnitCompilerIT.testRuleUnitDelete(RuleUnitCompilerIT.java:124)<br/>Caused by: java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-runtimes/344/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#342` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 453
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/342/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/testSendProcessEvents/">org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.quarkus.outbox.OutboxIT 1 expectation failed.<br/>Expected status code <200> but was <404>.<br/> within 1 minutes.<br/>	at org.kie.kogito.quarkus.outbox.OutboxIT.testSendProcessEvents(OutboxIT.java:129)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.outbox.OutboxIT.lambda$testSendProcessEvents$1(OutboxIT.java:136)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/342/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - kogito-apps job** `#340` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2694
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/340/testReport/org.kie.kogito.index/ProcessDataIndexInfinispanIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexInfinispanIT.testProcessInstanceEvents</a></summary>
org.junit.ComparisonFailure: expected:<[NewTaskComm]ent> but was:<[newCommentCont]ent><br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/340/display/redirect

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
@mariofusco  Please merge this forward-port PR. Thanks!

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
