### PR TITLE
[DROOLS-5637] Hide definedKeySet of InputSet/OutputSet from Swagger/O…

### PR DESCRIPTION
**Pull request by tkobayas**
…penApi

**JIRA**: https://issues.redhat.com/browse/DROOLS-5637

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by tkobayas** [comment]
I manually confirmed that this fix hides "definedKeySet" from swagger-ui example payload in dmn-quakus-example with kogito.decisions.stronglytyped=true

You may find another issue with "Date" (value is empty in the example payload) but i will be addressed by DROOLS-5554

**Review by tarilabs — COMMENTED** [review]
Thank you @tkobayas this is good, but could you kindly rebase on top of https://github.com/kiegroup/drools/pull/3097 , please?

I also believe this will give you the chance to make it hidden also when using Swagger OASv3 annotations, which I believe are the correct one we should _also_ use from now on to deal with SpringBoot

**Comment by tarilabs** [comment]
I should add, maybe is best to await  #3097 is completely merged, since there will be some minor changes due to the code review

**Comment by tkobayas** [comment]
Sure, I will wait. No problem :)

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
Thank you for your patience @tkobayas ; the  #3097 is now merged, can you kindly rebase on master, add the equivalent annotation for SpringBoot-based setup as shown, and I believe will be good to merge then 👍

**Review by tarilabs — APPROVED** [review]
Thank you! 👍

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
