### PR TITLE
[7.48.x] DROOLS-5960 : GDST V&V should support Dates

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**: 

[DROOLS-5960](https://issues.redhat.com/browse/DROOLS-5960)

**referenced Pull Requests**: 

* https://github.com/kiegroup/drools/pull/3423
* https://github.com/kiegroup/kie-wb-common/pull/3589
* https://github.com/kiegroup/drools-wb/pull/1469

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
@vpellegrino @jomarko PRs updated to match master. No conflicts.

**Comment by Rikkola** [comment]
Jenkins run fdb

**Review by jomarko — APPROVED** [review]
2/3, approving, thank you @Rikkola

**Review by vpellegrino — APPROVED** [review]
Thanks @Rikkola

**Comment by Rikkola** [comment]
```
org.kie.server.integrationtests.jbpm.BARuntimeDataServiceIntegrationTest.initializationError
org.kie.server.integrationtests.jbpm.ByPassUserTaskServiceIntegrationTest.initializationError
org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.initializationError
org.kie.server.integrationtests.jbpm.ContainerUpdateIntegrationTest.initializationError
org.kie.server.integrationtests.jbpm.CustomDataProcessServiceIntegrationTest.initializationError
org.kie.server.integrationtests.jbpm.DocumentServiceIntegrationTest.initializationError
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.initializationError
org.kie.server.integrationtests.jbpm.JobServiceIntegrationTest.initializationError
org.kie.server.integrationtests.jbpm.KieServerContainerListFilteringIntegrationTest.initializationError
org.kie.server.integrationtests.jbpm.ProcessDefinitionIntegrationTest.initializationError
```

Jenkins run fdb

**Comment by Rikkola** [comment]
```
20:59:10  Body did not finish within grace period; terminating with extreme prejudice
Error when executing always post condition:
org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution.cancel(TimeoutStepExecution.java:160)
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution.access$100(TimeoutStepExecution.java:38)
```

Jenkins run fdb

**Pull request merged**
