### PR TITLE
DROOLS-2254 - Automate .proto files rebuild in pom.xml

### PR DESCRIPTION
**Pull request by dmvolod**
Please note that auto-generated java files will be changed if .proto files or protobuf version are updated
The current changes are related to update protobuf version from 2.6.0 to 2.6.1
I will update https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/README.md document (Regenerating Protobuf Files section) when this PR will be accepted.

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mswiderski** [comment]
@dmvolod  @mariofusco  just a side note that jbpm has proto file too so not sure if this is drools only change or shall it be introduced in jbpm-flow module as well.

**Comment by mariofusco** [comment]
@mswiderski Yes I agree that the same thing should be done also on jbpm.
@dmvolod I guess the 2 things are independent, can you please do the same on jbpm when this PR will be merged?

**Comment by mariofusco** [comment]
@dmvolod Unfortunately I cannot merge this PR, build on jenkins is failing as it follows:

08:11:22 [ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.1:compile (default) on project drools-core: Missing:
08:11:22 [ERROR] ----------
08:11:22 [ERROR] 1) com.google.protobuf:protoc:exe:linux-x86_64:2.6.0
08:11:22 [ERROR] 
08:11:22 [ERROR]   Try downloading the file manually from the project website.
08:11:22 [ERROR] 
08:11:22 [ERROR]   Then, install it using the command: 
08:11:22 [ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=2.6.0 -Dclassifier=linux-x86_64 -Dpackaging=exe -Dfile=/path/to/file
08:11:22 [ERROR] 
08:11:22 [ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
08:11:22 [ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=2.6.0 -Dclassifier=linux-x86_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
08:11:22 [ERROR] 
08:11:22 [ERROR]   Path to dependency: 
08:11:22 [ERROR]   	1) org.drools:drools-core:bundle:7.7.0-SNAPSHOT
08:11:22 [ERROR]   	2) com.google.protobuf:protoc:exe:linux-x86_64:2.6.0
08:11:22 [ERROR] 
08:11:22 [ERROR] ----------
08:11:22 [ERROR] 1 required artifact is missing.
08:11:22 [ERROR] 
08:11:22 [ERROR] for artifact: 
08:11:22 [ERROR]   org.drools:drools-core:bundle:7.7.0-SNAPSHOT
08:11:22 [ERROR] 
08:11:22 [ERROR] from the specified remote repositories:
08:11:22 [ERROR]   jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/, releases=true, snapshots=true),
08:11:22 [ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
08:11:22 [ERROR] -> [Help 1]
08:11:22 org.apache.maven.lifecycle.Life

Please review and fix this.

**Comment by dmvolod** [comment]
@mariofusco , I know why this error is occurring, the version of protobuf was not updated to 2.6.1, but I don't understand why, as my PR was merged on master (looks like some pom versions issue with embedded components) https://github.com/jboss-integration/jboss-integration-platform-bom/pull/417
Good point, @mswiderski , I will do the same on the jbpm.

**Comment by dmvolod** [comment]
I've defined, that current drools points to the jboss-integration-platform-bom version 8.0.0.CR3, however change from https://github.com/jboss-integration/jboss-integration-platform-bom/pull/417 places to the 8.0.0-SNAPSHOT.
@mbiarnes , could you please to help and say when this change will place to the next development snapshot. Thanks in advance.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mariofusco** [comment]
We're working on a new marshalling strategy and upgraded to protobuf 3 to support it.

**Pull request closed without merging**
