### PR TITLE
DROOLS-6265 : Guided Rule Editor: Formula with contains does not reopen correctly

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**: 

[DROOLS-6265](https://issues.redhat.com/browse/DROOLS-6265)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
Jenkins run fdb

**Review by jomarko — APPROVED** [review]
Thank you for this PR @Rikkola . Could we please increase the coverage before the merge?
https://github.com/Rikkola/drools/pull/11

**Review by yesamer — APPROVED** [review]

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
enkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
File path issue.

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
` org.kie.hacep.LocalStorageStreamingKieSessionTest.getCommandsTest`

jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
`org.jbpm.executor.impl.jms.JmsAvaiableJobExecutorTest.testAsyncAuditErrorProducer`
jenkins run fdb

**Comment by Rikkola** [comment]
`11:24:26  [ERROR]  You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.`
I only start two each day, but here goes.
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

Build stuck

**Comment by Rikkola** [comment]
41 failures, here are few of them:
```
org.kie.karaf.itest.DecisionTablesIntegrationTest.org.kie.karaf.itest.DecisionTablesIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.DecisionTablesIntegrationTest
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest
org.kie.karaf.itest.KieDMNKarafIntegrationTest.org.kie.karaf.itest.KieDMNKarafIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.KieDMNKarafIntegrationTest
org.kie.karaf.itest.KieSpringDependencyKarafIntegrationTest.testKieBase
org.kie.karaf.itest.KieSpringMetaInfAppContextKarafIntegrationTest.testKieBase
org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest.org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest
```
jenkins run fdb

**Comment by jomarko** [comment]
are :
```
org.kie.karaf.itest.DecisionTablesIntegrationTest.org.kie.karaf.itest.DecisionTablesIntegrationTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.kie.karaf.itest.DecisionTablesIntegrationTest
```

unrelated?

**Comment by Rikkola** [comment]
Yes. Due to, I guess, every test in that module failing I think it might be just that module. Also I can't run the tests in the module locally, but I think that is just me.

jenkins run fdb

**Comment by Rikkola** [comment]
Looks like FDB is stuck.

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
I doubt the change here is actually covered by anything that would fail, but since there is still some time I'll refire this.

jenkins run fdb

**Comment by Rikkola** [comment]
@mareknovotny We merged the 7.52.x version of this in. So I suspect we can merge this one too.

**Comment by mareknovotny** [comment]
> @mareknovotny We merged the 7.52.x version of this in. So I suspect we can merge this one too.

that is true, but the CI was green here it was not the case and I can see also some old runs still running, so i cancelled them on Jenkins

Could you maybe rebase this from master branch?

**Comment by jstastny-cz** [comment]
jenkins retest this and run cdb

**Comment by Rikkola** [comment]
jenkins retest this and run cdb

**Comment by Rikkola** [comment]
jenkins retest this

**Comment by jomarko** [comment]
The build passed, I think this should be merged, it is opened since April.

**Comment by Rikkola** [comment]
@mareknovotny Can we merge this?

**Pull request merged**
