### PR TITLE
[DROOLS-7180] Add Reactive Messaging with DataSource and  RuleUnit ex…

### PR DESCRIPTION
**Pull request by tkobayas**
…ample

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7180

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

 - for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel-lts</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Hi @evacchi  @mariofusco 

This is a draft example. Feel free to share your thoughts on this.

- Is `drools-drl-quarkus-extension/drools-drl-quarkus-examples/drools-drl-quarkus-examples-reactive` a good place to have this example?
- This example depends on quarkus. Is an example without quarkus better?
- We plan to introduce "Specialized DataSources" (e.g. connect to Kafka topics), when we introduce them, I can modify this example accordingly (probably we will be able to simplify what `Adaptor` class does in this example).

**Review by evacchi — APPROVED** [review]
I really like this!!! I think with @mariofusco's most recent change you can even make it shorter! https://github.com/kiegroup/drools/pull/4803

**Comment by tkobayas** [comment]
@evacchi Thank you!

> I think with @mariofusco's most recent change you can even make it shorter! https://github.com/kiegroup/drools/pull/4803

Yes, this can be shorter with DSL, but we may keep this example as standard DRL style, right? (so that users can focus on this example's main feature = reactive messaging)

**Review by mariofusco — APPROVED** [review]

**Comment by mariofusco** [comment]
Very nice example, great work @tkobayas !!!

I agree that it would be even nicer when we will introduce `DataSource`s that we will be able to natively talk to a kafka topic and this also seem a very good starting point to explore in that direction.

Regarding @evacchi 's note it is true that, with the last change that he linked, it would be also possible to write the same example also using the rule unit DSL, but I'm not strongly opinionated on one of the 2 formats and this implementation detail is in my opinion not related to what you wanted to demonstrate here.

I'll merge this PR as it is as soon as CI will be green. @tkobayas I also strongly suggest to write a blog post explaining how this works and maybe outlining the next improvements that we're planning to develop in this area.

**Comment by tkobayas** [comment]
>  @tkobayas I also strongly suggest to write a blog post explaining how this works and maybe outlining the next improvements that we're planning to develop in this area.

Sure, thanks!

**Pull request merged**
