### PR TITLE
AF-648 :  Change Project from a folder in a repo to a repository

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by mbarkley** [comment]
@ederign @paulovmr @Rikkola Force pushed to rebase off master.

**Comment by ederign** [comment]
@ederign @paulovmr @Rikkola Force pushed to rebase off master.

**Review by porcelli — APPROVED** [review]
great job @Rikkola @mbarkley @paulovmr @ederign!

**Comment by porcelli** [comment]
thank you also @tomasdavidorg @jhrcek for QE support

**Pull request merged**
