### PR TITLE
[KOGITO-5122] fix java compiler classpath on Windows

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Review by gitgabrio — APPROVED** [review]
HI @mariofusco. Thanks for this PR. LGTM!

**Comment by ge0ffrey** [comment]
Related https://github.com/kiegroup/kogito-runtimes/pull/1297

**Review by hellowdan — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by triceo** [comment]
Any chance for a test here, @mariofusco ?
This broke our getting started experience three repos downstream from this one.

**Pull request merged**
