### PR TITLE
DROOLS-5696 : Guided Rule Editor: Call method on XYZ with formula containing quotes does not re-open correctly

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**: 

[link](https://issues.redhat.com/browse/DROOLS-5696)
 

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
@jstastny-cz And this one is green and ready for reviews.

**Comment by Rikkola** [comment]
Just firing this since it in the list.
Jenkins run fdb

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Review by jstastny-cz — APPROVED** [review]

**Comment by Rikkola** [comment]
@karreiro Hi, could you help with the review please.

**Review by karreiro — APPROVED** [review]
Thank you, @Rikkola. LGTM :-)

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Can I get a merge please.

**Pull request merged**
