### PR TITLE
[DROOLS-1700] Avoid forking a useless thread issueing a FireUntilHalt…

### PR DESCRIPTION
**Pull request by mariofusco**
…Command when the engine is already firing

### CODE REVIEW

**Comment by mswiderski** [comment]
out of curiosity, is there a way to sop fire until halt using commands? Thinking about KIE Server use case... what would be the halt there? kie container dispose?

**Comment by mariofusco** [comment]
@mswiderski There's an HaltCommand for that: https://github.com/kiegroup/drools/blob/master/drools-core/src/main/java/org/drools/core/command/runtime/rule/HaltCommand.java

**Comment by mswiderski** [comment]
all clear, thanks @mariofusco

**Review by tarilabs — APPROVED** [review]

**Comment by mariofusco** [comment]
Jenkins execute full downstream build

**Pull request merged**
