### PR TITLE
[DROOLS-3389] Created scenario simulation runtime modules

### PR DESCRIPTION
**Pull request by danielezonca**
@kkufova @gitgabrio @Rikkola 

Created two runtime modules (backend and api) in `drools` repo. This PR does not contains real new code, it is just a move from the existing modules in `drools-wb`.
The only changes are:
- removed `@Portable` annotation from API classes and replaced with `errai.marshalling.serializableTypes` property
- created a constant `FILE_EXTENSION` to avoid the usages of `ScenarioSimulationResourceTypeDefinition`

https://issues.jboss.org/browse/DROOLS-3389

NOTE: to be merged after https://github.com/kiegroup/drools-wb/pull/1126

PRs list:
- https://github.com/kiegroup/drools-wb/pull/1132
- https://github.com/kiegroup/drools/pull/2325
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/951

### CODE REVIEW

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by kkufova — APPROVED** [review]
Looks good to me.

:+1:

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by gitgabrio — APPROVED** [review]
@danielezonca 
Fine for me

**Pull request merged**
