### PR TITLE
DROOLS-3343 Refactor Message/MessageImpl to avoid rely on impl

### PR DESCRIPTION
**Pull request by tarilabs**

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
Depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/345

**Review by baldimir — APPROVED** [review]

**Pull request merged**
