### PR TITLE
[DROOLS-1353] define ExecutableRunner interface - fix for osgi

### PR DESCRIPTION
**Pull request by mswiderski**
depends on https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/196

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
anyone willing to review?

**Comment by psiroky** [comment]
I would very much like to, but I have unfortunately no idea how this code is supposse to work and if this is the correct classloader to use....

**Comment by mswiderski** [comment]
it needs to use same class loader that has the implementation class mentioned in RequestContext interface https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/196/files#diff-555c711c48d850e1ac1855682aecf68cR38

**Comment by psiroky** [comment]
You mean the same classloader as `org.drools.core.command.RequestContextImpl` uses?

**Comment by mswiderski** [comment]
yes, pretty much

**Comment by psiroky** [comment]
So `org.drools.core.command.RequestContextImpl.class.getClassLoader()` would work as well? If we really need the same CL, then this make it more obvious I think.

**Comment by mswiderski** [comment]
osgi wise it needs to come from the same bundle so I just used class loader from drools as they are bundled and thus same bundle class loader is used.

**Comment by psiroky** [comment]
OK, that makes sense. Although looking just at the diff  I would not be able to easily figure that out.

**Pull request merged**
