### PR TITLE
[DROOLS-1667] FEEL expression fails: 1 + if true then 1 else 2

### PR DESCRIPTION
**Pull request by kurobako**
https://issues.jboss.org/browse/DROOLS-1667

### CODE REVIEW

**Comment by etirelli** [comment]
@kurobako can you please add a few tests for the quantified expressions and for expressions as well? E.g.:
quantified: if every x in [ 1, 2, 3 ] satisfies x < 5 then "foo" else "bar"
for: count( for x in [1, 2, 3] returns x+1 )

**Review by etirelli — APPROVED** [review]

**Comment by etirelli** [comment]
@kurobako sorry, one more thing, in the FEEL grammar, you added the parser rules into primary, but I don't see it removing from the previous place they were at the top of the file... don't we need to remove them from there?

**Review by etirelli — APPROVED** [review]

**Comment by psiroky** [comment]
Could we make sure these PRs are properly tested by Jenkins before merging?

(Looks like we should add @kurobako to our org. unit so that we don't need to approve every single PR from him, correct?)

**Comment by etirelli** [comment]
@psiroky Sorry, when I merged all "icons" were green. What did I miss?

I will add @kurobako to the org.

**Pull request merged**
