### PR TITLE
[incubator-kie-issues#854] DMN - Add implicit type conversion of date to date and time when necessary

### PR DESCRIPTION
**Pull request by gitgabrio**
> Add an implicit date to date and time conversion in DMN FEEL evaluation, based on this rule:
> "When the type of the expression is date and the target type is date and time, the expression is converted to a date time value in which the time of day is UTC midnight (00:00:00)."
> 
> Acceptance criteria:
> 
>     Implicit conversion is implemented in FEEL expressions, where date is used as the input type of the expression and the result needs to be date and time.
>     New code is 100% covered with tests.

Notes:
1. it is not possible to modify the FEELFunction itself because it does not receive the required type; so, conversion is executed inside `DMNContextEvaluator`
2. currently only `LocalDate` are transformed, and generated object is a `ZonedDateTime`
3. small refactoring of `DMNContextEvaluator` has been done to improve test coverage

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

 - for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-drools/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/5657 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5657/1/display/redirect

**Test results:**
- PASSED: 21874
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5657/1/testReport/org.kie.dmn.core/DMNStronglyTypedSupportTest/testDateAndTime[KIE_API_TYPECHECK]/">org.kie.dmn.core.DMNStronglyTypedSupportTest.testDateAndTime[KIE_API_TYPECHECK]</a></summary>
expected:<...me.LocalDate), "from[]YearMonthDay"=1999-1...> but was:<...me.LocalDate), "from[StringToDateTime"=2015-12-24T00:00Z (java.time.ZonedDateTime), "from]YearMonthDay"=1999-1...>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5657/1/testReport/org.kie.dmn.core/DMNStronglyTypedSupportTest/testDateAndTime[BUILDER_DEFAULT_NOCL_TYPECHECK]/">org.kie.dmn.core.DMNStronglyTypedSupportTest.testDateAndTime[BUILDER_DEFAULT_NOCL_TYPECHECK]</a></summary>
expected:<...me.LocalDate), "from[]YearMonthDay"=1999-1...> but was:<...me.LocalDate), "from[StringToDateTime"=2015-12-24T00:00Z (java.time.ZonedDateTime), "from]YearMonthDay"=1999-1...>
</details>

**Review by tarilabs — COMMENTED** [review]
The linked issue is private, so without context is difficult for me to provide a review.

I'm not sure either why the modification seems to be affecting only boxed context at the DMN level? What is strange to me is that this modification (if required) was not done at the FEEL level, only wiring where necessary at DMN level; based on the title alone I would have expected a modification at the FEEL level, with type check wirings at DMN level.

You may want to discuss this first with @baldimir to fully check the semantic aspects and implication with the DMN spec.

**Comment by gitgabrio** [comment]
@tarilabs 
I add the ticket content in the description of this PR.

>  based on the title alone I would have expected a modification at the FEEL level,

yes, but I failed to find how to do that, and that's why I would ask you suggestion again 😄 
Tibor currently is not available, but we have to keep going on in the meantime.
Debugging the code I found the FEELFunctions for date, but those does not receive other parameters to allow a different object return; and, IINW, the function to call is choosed automatically based on the expression itself, so maybe I'm missing some critical point

**Comment by tarilabs** [comment]
I really wish I could dedicate unlimited time, but I'm currently on sick leave.
The things I noticed, are:

A.
This seems a behavioural change introduced with DMNv1.5, I'd suggest first to bump the DMN engine to this level of spec conformance by parsing the metamodel, or (much less ideal) guard it under feature flag. That would also save you troubles of "old behaviour" version can be fix-pointed to the previous Drools releases. Myself and @baldimir discussed what bumping to DMNv1.5 entails during hand-over. 

B.
Provided my understanding this is for DMNv1.5 is confirmed, this coercion seems to me applicable in 2 places:
- function invocation,
- and type-conformance in the DMN level.

if that is indeed the semantic discussed,

B.1.
For function invocation, you could consider to do similarly to:
https://github.com/apache/incubator-kie-drools/blob/9a3128e47f13d7c0e85fe8ff00e573ec769d2f9d/kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/BaseFEELFunction.java#L239-L261

this coerces the actual parameter in the case of singleton lists.
You could consider similar, analogous strategy for the date->date and time coercion.
You will need to implement the coercion in the actual parameter being set in the CandidateMethod (eg actual parameters value as is, except for the coerced date -> date and time)

B.2.
For type-conformance in the DMN level, you could consider to do similarly to:
https://github.com/apache/incubator-kie-drools/blob/9a3128e47f13d7c0e85fe8ff00e573ec769d2f9d/kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeImpl.java#L675-L687
and
https://github.com/apache/incubator-kie-drools/blob/9a3128e47f13d7c0e85fe8ff00e573ec769d2f9d/kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeImpl.java#L442

by introducing the additional coercion rule during type-conformance.

Hope this explain better why a modification in the DMN boxed Context does not seem the appropriate solution, but that's just me.
This is not a small task, so I would also suggest splitting it into subtasks.

I really hope this will help you.

**Comment by gitgabrio** [comment]
@tarilabs 
> [...]
> I really hope this will help you.

Gosh, it really help a lot. 
Sorry, I did not know you also were in sick leave, thanks again for all that help.
I'll start from what you wrote and see where I'll get to. 
Thanks again and take care!

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-drools/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/5657 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5657/2/display/redirect

**Test results:**
- PASSED: 21874
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5657/2/testReport/org.kie.dmn.core/DMNRuntimeTest/testDateAndTime[false]/">org.kie.dmn.core.DMNRuntimeTest.testDateAndTime[false]</a></summary>
expected:<...me"=2015-12-24T00:00[Z (java.time.Zoned]DateTime), "fromYear...> but was:<...me"=2015-12-24T00:00[ (java.time.Local]DateTime), "fromYear...>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5657/2/testReport/org.kie.dmn.core/DMNStronglyTypedSupportTest/testDateAndTime[KIE_API_TYPECHECK]/">org.kie.dmn.core.DMNStronglyTypedSupportTest.testDateAndTime[KIE_API_TYPECHECK]</a></summary>
expected:<...me.LocalDate), "from[]YearMonthDay"=1999-1...> but was:<...me.LocalDate), "from[StringToDateTime"=2015-12-24T00:00 (java.time.LocalDateTime), "from]YearMonthDay"=1999-1...>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5657/2/testReport/org.kie.dmn.core/DMNStronglyTypedSupportTest/testDateAndTime[BUILDER_DEFAULT_NOCL_TYPECHECK]/">org.kie.dmn.core.DMNStronglyTypedSupportTest.testDateAndTime[BUILDER_DEFAULT_NOCL_TYPECHECK]</a></summary>
expected:<...me.LocalDate), "from[]YearMonthDay"=1999-1...> but was:<...me.LocalDate), "from[StringToDateTime"=2015-12-24T00:00 (java.time.LocalDateTime), "from]YearMonthDay"=1999-1...>
</details>

**Pull request closed without merging**
