### PR TITLE
Drools 5603 - Refactor super invocation setting

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @mariofusco @jiripetrlik

see https://issues.redhat.com/browse/DROOLS-5603

This pr
1) create some utility method to edit a ExplicitConstructorInvocationStmt parameter by name
2) replace all the direct invocation of ExplicitConstructorInvocationStmt with the above methods

// TO be merged/viewed *after* DROOLS-5143 has been merged

### CODE REVIEW

**Comment by gitgabrio** [comment]
jenkins execute fdb

**Review by jiripetrlik — COMMENTED** [review]
Looks good to me. However there are few suggestions from Sonar cloud.
1. If I look at code coverage report. It seems that we don't have covered False predicate in "KiePMMLPredicateFactory".
2. There are three tests without assertions. See code smells report.

Is it possible to do something about these Sonar cloud suggestions?

**Comment by gitgabrio** [comment]
> Looks good to me. However there are few suggestions from Sonar cloud.
> 
> 1. If I look at code coverage report. It seems that we don't have covered False predicate in "KiePMMLPredicateFactory".
> 2. There are three tests without assertions. See code smells report.
> 
> Is it possible to do something about these Sonar cloud suggestions?

@jiripetrlik 
Hi, just pushed test refactoring.

**Review by jiripetrlik — APPROVED** [review]
@gitgabrio Thank you for your changes!

**Review by danielezonca — APPROVED** [review]

**Comment by gitgabrio** [comment]
jenkins execute fdb

**Comment by gitgabrio** [comment]
@danielezonca Hi! Could you please merge this, squashing commits? Thanks!

**Pull request merged**
