### PR TITLE
[7.48.x] DROOLS-5888 : Comments starting with ruletable without a space should work

### PR DESCRIPTION
**Pull request by Rikkola**
**Thank you for submitting this pull request**

**JIRA**:  

[DROOLS-5888](https://issues.redhat.com/browse/DROOLS-5888)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
```
org.drools.decisiontable.LinkedWorkbookTest.testBrokenExternalLinkButValueIsCached
org.drools.decisiontable.SpreadsheetCompilerUnitTest.testOOXMLParseCellValue
org.drools.decisiontable.SpreadsheetCompilerUnitTest.testNoLhsParam
org.drools.decisiontable.SpreadsheetCompilerUnitTest.testChecksOnLhs
org.drools.decisiontable.SpreadsheetCompilerUnitTest.testLoadCustomListener
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsxWithOOPathTest[KieBase type=CLOUD_IDENTITY]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.csvWithOOPathTest[KieBase type=CLOUD_IDENTITY]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsWithOOPathTest[KieBase type=CLOUD_IDENTITY]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsxWithOOPathTest[KieBase type=CLOUD_IDENTITY_MODEL_FLOW]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.csvWithOOPathTest[KieBase type=CLOUD_IDENTITY_MODEL_FLOW]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsWithOOPathTest[KieBase type=CLOUD_IDENTITY_MODEL_FLOW]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsxWithOOPathTest[KieBase type=CLOUD_IDENTITY_MODEL_PATTERN]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.csvWithOOPathTest[KieBase type=CLOUD_IDENTITY_MODEL_PATTERN]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsWithOOPathTest[KieBase type=CLOUD_IDENTITY_MODEL_PATTERN]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsxWithOOPathTest[KieBase type=STREAM_IDENTITY]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.csvWithOOPathTest[KieBase type=STREAM_IDENTITY]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsWithOOPathTest[KieBase type=STREAM_IDENTITY]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsxWithOOPathTest[KieBase type=STREAM_IDENTITY_MODEL_FLOW]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.csvWithOOPathTest[KieBase type=STREAM_IDENTITY_MODEL_FLOW]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsWithOOPathTest[KieBase type=STREAM_IDENTITY_MODEL_FLOW]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsxWithOOPathTest[KieBase type=STREAM_IDENTITY_MODEL_PATTERN]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.csvWithOOPathTest[KieBase type=STREAM_IDENTITY_MODEL_PATTERN]
org.drools.testcoverage.functional.oopath.OOPathDtablesTest.xlsWithOOPathTest[KieBase type=STREAM_IDENTITY_MODEL_PATTERN]
```

This might actually be my fault.

**Comment by mareknovotny** [comment]
this is the same as master PR, @jstastny-cz @karreiro  your approvals please if you agree you checked it

**Review by karreiro — APPROVED** [review]
Thank you, @Rikkola LGTM!

**Comment by jstastny-cz** [comment]
Testing.

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Pull request merged**
