### PR TITLE
DROOLS-1614 Revise coverage of DMN decision tables runtime tests

### PR DESCRIPTION
**Pull request by baldimir**
- Adds missing hit policies tests
- Revises decision tables output and input tests

### CODE REVIEW

**Comment by baldimir** [comment]
Contains reproducers for: 
- https://issues.jboss.org/browse/DROOLS-1612
- https://issues.jboss.org/browse/DROOLS-1613

So checks will fail with these tests.

**Comment by baldimir** [comment]
2 tests failed as expected. See previous comment.

**Review by etirelli — APPROVED** [review]

**Comment by etirelli** [comment]
@baldimir can you please fix this PR? I will merge it asap.

**Comment by etirelli** [comment]
Closing this PR as it is replaced by https://github.com/kiegroup/drools/pull/1328

**Pull request closed without merging**
