### PR TITLE
[6.4.x] BZ1301051: Column values are deleted after changing the operator in a Guided Decision Table

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1301051

This is the corollary of https://github.com/droolsjbpm/drools/pull/656 for 6.4.x 

(cherry picked from commit bd2b052e425688e214574048763bce1b9e3cf6dc)

### CODE REVIEW

**Comment by manstis** [comment]
* DO NOT MERGE YET - NEEDS A RELATED PR FOR DROOLS-WB *

**Comment by manstis** [comment]
See https://github.com/droolsjbpm/drools-wb/pull/128 too.

**Comment by Rikkola** [comment]
+1

**Comment by mswiderski** [comment]
merged into 6.4.x

**Pull request closed without merging**
