### PR TITLE
[BAPL-1096] optionally allow to keep cells untrimmed in decision tables

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mariofusco** [comment]
ok to test

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
ok to test

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by baldimir** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
jenkins retest this

**Pull request merged**
