### PR TITLE
[incubator-kie-drools-6163] Clean up leftover of change-set support

### PR DESCRIPTION
**Pull request by tkobayas**
**Issue**: 

* https://github.com/apache/incubator-kie-drools/issues/6163

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Review by yesamer — COMMENTED** [review]
@tkobayas Thank you for this cleanup task.
Can you please update the rat-excludes file accordingly with the removed files?
In addition, I searched for `changeSet` key in the repo, and I found 240+ usages. Are those usage still required?

Screenshot 2024-12-10 at 07 44 23

**Comment by tkobayas** [comment]
Hi @yesamer ,

> Can you please update the rat-excludes file accordingly with the removed files?

Thank you! I completely forgot the point. Fixed.

> In addition, I searched for changeSet key in the repo, and I found 240+ usages. Are those usage still required?

Yes. Some classes use the name `ChangeSet` for different capability, which handles differences between current version and next version of kieModule. They are still required.

This PR removed the feature related to "change-set.xml" file, which is no longer functional nor tested.

**Review by baldimir — APPROVED** [review]

**Review by yesamer — APPROVED** [review]
Thank you @tkobayas

**Comment by tkobayas** [comment]
re-running GHA

**Comment by tkobayas** [comment]
Test failures on CallbackStateTimeoutsIT, MultipleTimerInstancesIT etc. are being solved by https://github.com/apache/incubator-kie-kogito-runtimes/pull/3814

**Pull request merged**
