### PR TITLE
[7.44.x]DROOLS-5766 : Issue while using LocalDateTime field reference in GRE

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 0c859d2d61f436d284073bf3932dd4b9b38b986a)

**JIRA**: 

[link](https://issues.redhat.com/browse/DROOLS-5766)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
@karreiro Hi, this could use a review. Same as the one for master.

**Comment by Rikkola** [comment]
Jenkins retest this

**Review by karreiro — APPROVED** [review]
Thank you, @Rikkola. LGTM!

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
jenkins do fdb

**Comment by Rikkola** [comment]
Jenkins run cdb

**Review by dupliaka — APPROVED** [review]
LGTM

- [x] Edition
- [x] Reopening
- [x] Creation from the scratch
- [x] Reimporting

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers I would like a merge please.

**Comment by manstis** [comment]
@mareknovotny Hi, the FDB failed but from the logs it appears a CI configuration error?

**Pull request merged**
