### PR TITLE
DROOLS-3159 : Supporting multiple lines in a cell in a DESCRIPTION column of Decision Tables

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-3159

@jomarko here you are. About tests, open to ideas about better test coverage.

### CODE REVIEW

**Comment by jomarko** [comment]
Looks fine, I would like to increase coverage in following #2131 and manually check, will approve soon.

**Comment by Rikkola** [comment]
@jomarko if there are no code changes needed, I say we merge your PR with all the changes.

**Comment by jomarko** [comment]
@Rikkola I have no preference, leaving decision up to you, I tried manually and can confirm it works fine.

**Review by jomarko — APPROVED** [review]

**Comment by Rikkola** [comment]
@jomarko less work and safer to use yours I think. I'll close this one.

**Comment by Rikkola** [comment]
@etirelli hi, could you merge please.

**Pull request merged**
