### PR TITLE
Filter out Java source files from compilation in KieBuilder

### PR DESCRIPTION
**Pull request by mbarkley**
This PR is required for LiveSpark, where we require the ability to prevent client-side classes with GWT dependencies from being compiled.

### CODE REVIEW

**Comment by mbarkley** [comment]
Related PRs:
https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/145
https://github.com/droolsjbpm/kie-wb-common/pull/359

**Comment by mswiderski** [comment]
+1 

@mariofusco could you please check this too?

**Comment by mariofusco** [comment]
@mswiderski see my comment here https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/145/files#r63663654

**Comment by mbarkley** [comment]
This PR has been updated based on discussion [here](https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/145).

**Comment by mbarkley** [comment]
jenkins, retest this

**Comment by mbarkley** [comment]
The build passes on my machine. The single failing test (CepEspTest#testEventWithShortExpiration) doesn't appear to be related to the changes in this PR, and it looks like the test depends on something happening during short call to `Thread.sleep`, so I suspect this might have to do with some environment-dependent behaviour.

@mariofusco @mswiderski Any ideas?

**Comment by psiroky** [comment]
@mbarkley yeah, that is a flaky test. Failing "randomly". For sure not related with changes in this PR.

(we should somehow fix/remove that test...)

**Comment by mariofusco** [comment]
@mbarkley +1 I'm about to merge this.
The only improvement I could think about is using that new Predicate to filter any other kind of resources and not only java sources, but this is something I can implement on my own.

**Pull request merged**
