### PR TITLE
[DROOLS-5503] avoid creating a KnowledgeBuilder where there is no ass…

### PR DESCRIPTION
**Pull request by mariofusco**
…et to be built

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Review by lucamolteni — APPROVED** [review]

**Comment by mariofusco** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Review by hellowdan — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Pull request merged**
