### PR TITLE
GUVNOR-2585: In test scenario, expert contraint of type enum can be set but are always false

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/GUVNOR-2585

Auto-import enums from the class in order to avoid this:
enum-bug

### CODE REVIEW

**Comment by manstis** [comment]
@Rikkola could you please review this...

**Comment by karreiro** [comment]
Jenkins, please retest this.

**Comment by Rikkola** [comment]
+1

**Comment by manstis** [comment]
IIRC "getDeclaredFields()" does just that - excluding inherited and delegated. You might want to look at including fields on super classes and methods with return types (that are enums).

**Comment by karreiro** [comment]
Jenkins, please retest this.

**Comment by karreiro** [comment]
Thanks @Rikkola and @manstis :-)

**Comment by manstis** [comment]
@karreiro Looks good to me - @mariofusco did you want tor review (and merge?)

**Comment by mariofusco** [comment]
I agreed with @karreiro that this PR cannot be accepted as it is. The enum discovery introduced in the TypeResolver will introduce a compile time delay that will be useless in 99.9...% of cases.

**Pull request closed without merging**
