### PR TITLE
DROOLS-2390 Migrate tests from drools-compiler module

### PR DESCRIPTION
**Pull request by baldimir**
JIRA related to these tests: https://issues.jboss.org/browse/DROOLS-2625

@mariofusco could you please review?

### CODE REVIEW

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Comment by mariofusco** [comment]
@baldimir There are a couple of tests that are failing regardless if they're running against the executable model or not, Please fix them.

**Comment by baldimir** [comment]
Sorry I missed this. Fixing it right now.

**Comment by baldimir** [comment]
jeknins retest this

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Comment by baldimir** [comment]
Failed test not related to the changes. It is an already reported issue: https://issues.jboss.org/browse/DROOLS-2592

Let's wait for downstream build now.

**Pull request merged**
