### PR TITLE
[DROOLS-1266] fix oopath returning a primitive type

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by tarilabs** [comment]
+1 to merge

[.CepEspTest.testEventWithShortExpiration]

Jenkins, test again :8ball:

**Comment by tarilabs** [comment]
[CepEspTest.testEventWithShortExpiration]

Jenkins, test again :8ball: :8ball:

**Comment by baldimir** [comment]
+1

[CepEspTest.testEventWithShortExpiration]

Jenkins, test again :8ball: :8ball: :8ball:

**Comment by tarilabs** [comment]
[JpaOptLockPersistentStatefulSessionTest.testOptimisticLockInterceptor]

Jenkins, test again :8ball: :8ball: :8ball: :8ball:

**Pull request merged**
