### PR TITLE
[KIE-DROOLS-6190] fix removal of detached tuples during incremental compilation

### LINKED ISSUE #6190: Some tests failing in incremental compilation
Some tests are failing - apparently because of a memory issue.

The failures were not discovered before  because they were tests executed only on demand - so called TurtleTests.

AddRemoveGenerated2RulesEvalTest.java
AddRemoveGenerated2RulesIntegerTest.java
AddRemoveGenerated2RulesMapContainsTest.java
AddRemoveGenerated2RulesNotNotTest.java
AddRemoveGenerated2RulesNotTest.java
AddRemoveGenerated2RulesStringIntegerTest.java
AddRemoveGenerated2RulesStringTest.java

The test 

IncrementalCompilationTest.testDecisionTable

fails only after the migration to Junit5.

### PR DESCRIPTION
**Pull request by mariofusco**
Fixes https://github.com/apache/incubator-kie-drools/issues/6190

There are a few other incremental compilation tests that are failing for a totally unrelated reason and anyway without causing any endless loop. I left them disabled and I will keep investigating and fix them with a subsequent pull request.

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6192 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6192/1/display/redirect

**Test results:**
- PASSED: 41085
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6192/1/testReport/org.drools.mvel.integrationtests/Misc2Test/testDynamicAddRule(KieBaseTestConfiguration)[1]/">org.drools.mvel.integrationtests.Misc2Test.testDynamicAddRule(KieBaseTestConfiguration)[1]</a></summary>
<br/>Expecting value to be true but was false
</details>

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6192 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6192/2/display/redirect

**Test results:**
- PASSED: 41085
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6192/2/testReport/org.drools.mvel.integrationtests/Misc2Test/testDynamicAddRule(KieBaseTestConfiguration)[1]/">org.drools.mvel.integrationtests.Misc2Test.testDynamicAddRule(KieBaseTestConfiguration)[1]</a></summary>
<br/>Expecting value to be true but was false
</details>

**Review by tkobayas — APPROVED** [review]

**Comment by tkobayas** [comment]
Test failure on `Misc2Test.testDynamicAddRule` needs to be addressed.

Other test failures in kogito-* are mostly "pull access denied for vectorized/redpanda", which is being investigated by https://github.com/apache/incubator-kie-issues/issues/1682

**Comment by mariofusco** [comment]
> Test failure on `Misc2Test.testDynamicAddRule` needs to be addressed.

It's good that we had that test, it gave me a better insight of what @mdproctor was attempting to do there and where the problem actually was. This should be fixed now.

**Review by pibizza — APPROVED** [review]
Looks good to me, thank you.

**Review by tkobayas — APPROVED** [review]

**Comment by mariofusco** [comment]
@pibizza With the additional fix that I pushed yesterday evening all incremental tests pass, so I re-enabled them all.

**Pull request merged**
