### PR TITLE
[Drools-3838] Improve error reporting in scenario result 

### PR DESCRIPTION
**Pull request by yesamer**
This PR contains the server side and api changes required for https://issues.jboss.org/browse/DROOLS-3838. 
Related PR on drools-wb which cointans frontend change is here https://github.com/kiegroup/drools-wb/pull/1125

@jomarko @danielezonca @gitgabrio can you please review and test it?

PRs list:
    kiegroup/drools-wb#1125

Thanks

### CODE REVIEW

**Review by jomarko — COMMENTED** [review]
@yesamer this part of ensemble looks good to me, however I think we should use use just one assertion framework in the test to not cause confusion when reading tests, I prepared changes you can merge to your fork and they will appear in this PR. 

https://github.com/yesamer/drools/pull/1

**Comment by yesamer** [comment]
@jomarko Merged!

**Review by jomarko — APPROVED** [review]
@yesamer thank you!

**Review by danielezonca — APPROVED** [review]
Fine for me

**Pull request merged**
