### PR TITLE
DROOLS-6477: Collections Data Objects can be filled with expressions only.

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6477

**referenced Pull Requests**: 
* https://github.com/kiegroup/drools-wb/pull/1503
 
The issue occurs when the user imports a Collection or a Map from the "Data Object" tab.
Screencast from 07-08-2021 10_35_28 AM

In the  Test Tools area, the Collection (eg. ArrayList) will wrongly show `empty` as a field. Selecting it or the `ArrayList`fact, will not enable the Guided Collection Editor as expected. 

With the change introduced with this PR, now `value` field will be shown. As a results, adding the value parameter in the grid, will  show the Guided Collection Editor.

Screencast from 07-08-2021 10_34_29 AM

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by jomarko** [comment]
war file generated, downloading

**Review by jomarko — APPROVED** [review]
Approving 1/2, due to infrastructure issues, I am not able to finish war downloading, please be patient with my review with the second part of this ensemble.

**Comment by yesamer** [comment]
@jomarko In case that difficulty persists, I can give you the war generated in my local

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Pull request merged**
