### PR TITLE
[DROOLS-1186] iterate all child left tuples during a left update

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
All optaplanner's non-turtleTests succeeded. (turtle tests take too long to find out)

**Comment by ge0ffrey** [comment]
Assigned to @yurloc to test against the original reproducer.

**Comment by triceo** [comment]
@ge0ffrey Taking into account this week's CZ public holidays and PTOs, this is likely to fall over to next week.

**Comment by ge0ffrey** [comment]
@triceo Thanks for the info, good to know. Have a good holiday :)

**Comment by yurloc** [comment]
+1 from me. The original reproducer is fixed.

@ge0ffrey shall we wait for the result of turtle tests?

Jenkins, please retest.

**Comment by ge0ffrey** [comment]
No, the turtle tests can't run without it being merged - as running them locally takes too long to be practical. +1 to merge

**Pull request merged**
