### PR TITLE
[Drools-5453] Add/Fix pmml(s) to kie-pmml-regression tests

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @mariofusco @jiripetrlik

See https://issues.redhat.com/browse/DROOLS-5453

This PR implement OutputField management inside RegressionModel

### CODE REVIEW

**Review by jiripetrlik — APPROVED** [review]
Looks good to me. I have two questions:
1. Do you plan to implement output field management also for other models?
2. There are some new integration tests. However, shouldn't we also test this functionality in some our older integration tests?

**Comment by gitgabrio** [comment]
> Looks good to me. I have two questions:
> 
> 1. Do you plan to implement output field management also for other models?
> 2. There are some new integration tests. However, shouldn't we also test this functionality in some our older integration tests?

Hi,
this ticket was about having the attached models working inside PMML. 
Part of that was due to completely missing Outputfield management (that is present in other models).
Full OutputField management goes too far of this ticket

**Comment by gitgabrio** [comment]
Jenkins run cdb

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
Jenkins run cdb

**Pull request merged**
