### PR TITLE
CCE storing session with activations in agenda

### PR DESCRIPTION
**Pull request by marianbuenosayres**
When trying to persist (serialize) a session that has an activated agenda, a ClassCastException occurs like this when calling fireAllRules(). This solution avoids this issue by not returning something different from an Activation inside ActivationIterator

### CODE REVIEW

**Comment by marianbuenosayres2** [comment]
@mrietveld Here's the commit for master. Sorry for the previous error on the pull request

**Comment by mrietveld** [comment]
No problem! Thanks for fixing it so quickly. :) Unfortunately, I know very little about this code, so I'll have to leave the merging to one of the drools experts. :/

**Comment by salaboy** [comment]
Mariano, can you provide an isolated test case demonstrating the failing scenario that generates the exception?
Cheers

**Comment by mdproctor** [comment]
Any news on a test case for this? So we can apply?

**Comment by marianbuenosayres** [comment]
This issue was solved differently from proposed correction as stated on jira issue JBRULES-3674
I'll discard this pull request.

**Pull request closed without merging**
