### PR TITLE
[DROOLS-5404] Preserve the order of the DMN definitions elements in the DMNModel (i…

### PR DESCRIPTION
**Pull request by SimonRinguette**
…nput data, decision, bkms, item definitions, decision services)

### CODE REVIEW

**Comment by SimonRinguette** [comment]
@tarilabs This is the code that i've spoken to you about last week for guaranteeing that iterating through the inputs of a model will return the file order.

**Review by tarilabs — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
The SonarCloud comments are not impacting the _new code_. Will ask the merge.

**Comment by tarilabs** [comment]
can someone please rename by prefixing with "DROOLS-5404 " please?

**Review by hellowdan — APPROVED** [review]

**Pull request merged**
