### PR TITLE
[DROOLS-7231] @Clock, @EventProcessing in RuleUnit

### PR DESCRIPTION
**Pull request by tkobayas**
- Moved test domain classes to a domain package

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7231

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

 - for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel-lts</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
GHA Kogito Apps : Not related to this PR.
```
2022-12-08T05:56:33.6345976Z [ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 89.721 s <<< FAILURE! - in org.kie.kogito.it.jobs.ProcessTimerIT
```

GHA Windows Java 11 : Not related to this PR. (Somewhat flaky tests)
```
2022-12-08T05:09:41.9030244Z [ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.087 s <<< FAILURE! - in org.drools.compiler.integrationtests.TimerAndCalendarFireUntilHaltTest
2022-12-08T05:09:41.9919719Z [ERROR] testTimerRuleDoesRestartsIfNoLongerHolds[KieBase type=STREAM_IDENTITY_MODEL_PATTERN](org.drools.compiler.integrationtests.TimerAndCalendarFireUntilHaltTest)  Time elapsed: 4.456 s  <<< ERROR!
2022-12-08T05:09:42.0853301Z org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.drools.compiler.integrationtests.TimerAndCalendarFireUntilHaltTest was not fulfilled within 2 seconds.
...
2022-12-08T05:06:34.6108351Z [ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.651 s <<< FAILURE! - in org.drools.mvel.integrationtests.KieContainerTest
2022-12-08T05:06:34.6265869Z [ERROR] testIncrementalCompilationSynchronization[KieBase type=CLOUD_IDENTITY](org.drools.mvel.integrationtests.KieContainerTest)  Time elapsed: 20.448 s  <<< ERROR!
2022-12-08T05:06:34.6443894Z org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
```

**Comment by tkobayas** [comment]
1. I haven't worked on `@SessionsPool`. `@SessionsPool` can be technically conveyed to `KieBase` but `KieSessionsPool` is not actually used because `RuleUnit` creates `RuleUnitInstance` backed by `RuleUnitExecutorImpl`, not `KieSession`. We may introduce another pool mechanism for `RuleUnitInstance`, but `RuleUnitExecutorImpl` is lightweight than `KieSession` so it may not be highly demanded. If you think it's worth implementing such a pool before requested by users, I would file a JIRA. WDYT, @mariofusco  ?

2. SonarCloud informed 3 bugs `Use an "instanceof" comparison instead.` for the class name comparisons:
https://sonarcloud.io/project/issues?id=org.kie%3Adrools-parent&pullRequest=4857&resolved=false&types=BUG
I know that `drools-model-codegen` doesn't depend on `drools-ruleunits-api` so we cannot use `instanceof` or `isAssignableFrom` here. However, even if we add `drools-ruleunits-api` dependency to `drools-model-codegen`, it wouldn't cause a circular dependency, so we can do it? If you think it's better to add the dependency, I would file a JIRA. WDYT, @mariofusco  ? (In that case, I wonder if we need to consider a classloader issue which `AssignableChecker` deals with)

**Review by mariofusco — APPROVED** [review]

**Comment by mariofusco** [comment]
> 1. I haven't worked on `@SessionsPool`. `@SessionsPool` can be technically conveyed to `KieBase` but `KieSessionsPool` is not actually used because `RuleUnit` creates `RuleUnitInstance` backed by `RuleUnitExecutorImpl`, not `KieSession`. We may introduce another pool mechanism for `RuleUnitInstance`, but `RuleUnitExecutorImpl` is lightweight than `KieSession` so it may not be highly demanded. If you think it's worth implementing such a pool before requested by users, I would file a JIRA. WDYT, @mariofusco  ?

I believe that pooling could be useful also for rule units actually. This is lower priority, but please open a jira also for it.

> 
>     2. SonarCloud informed 3 bugs `Use an "instanceof" comparison instead.` for the class name comparisons:
>        https://sonarcloud.io/project/issues?id=org.kie%3Adrools-parent&pullRequest=4857&resolved=false&types=BUG
>        I know that `drools-model-codegen` doesn't depend on `drools-ruleunits-api` so we cannot use `instanceof` or `isAssignableFrom` here. However, even if we add `drools-ruleunits-api` dependency to `drools-model-codegen`, it wouldn't cause a circular dependency, so we can do it? If you think it's better to add the dependency, I would file a JIRA. WDYT, @mariofusco  ? (In that case, I wonder if we need to consider a classloader issue which `AssignableChecker` deals with)

I don't think this is a big issue and for now I'd prefer to keep the executable model independent from rule units if possible.

**Review by hellowdan — APPROVED** [review]

**Comment by tkobayas** [comment]
@mariofusco 

> I believe that pooling could be useful also for rule units actually. This is lower priority, but please open a jira also for it.

Thanks. I filed https://issues.redhat.com/browse/DROOLS-7258

> I don't think this is a big issue and for now I'd prefer to keep the executable model independent from rule units if possible.

Agreed.

**Pull request merged**
