### PR TITLE
DROOLS-3282: Should not move to next AgendaGroup even if current is empty

### PR DESCRIPTION
**Pull request by evacchi**
This is used for Units' scheduler-based impl. Figured we better track this feature/bug-fix in its own Jira. 

@mariofusco Not sure how to test

### CODE REVIEW

**Comment by mariofusco** [comment]
@evacchi I'm afraid this change is breaking the sequential agenda, see failures in https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/drools-pullrequests/255/

**Comment by evacchi** [comment]
good to know, will look into that

**Comment by evacchi** [comment]
Jenkins please retest this

**Comment by evacchi** [comment]
@mariofusco I kept a note to self here "check if it's the same agenda group" but I don't remember what I was supposed to actually write in code

**Comment by mariofusco** [comment]
@evacchi This PR is intended to provide a way to suspend the execution of a rule by switching to a different empty agenda-group. However I'm afraid that calling getNextFocus() at each iteration will be performance expensive and moreover I'd prefer to have a cleaner primitive to suspend the execution. Let's discuss this in person.

**Comment by evacchi** [comment]
discussed with @mariofusco. The AgendaGroup stack should *not* suspend execution, it's a stack that must progress execution till the end. We may add a boolean `suspend` == true when execution must halt (reset to false from the body of this method when execution gets suspended)

**Pull request closed without merging**
