### PR TITLE
DROOLS-4187 kie-dmn-validation: Incorrect import detection

### PR DESCRIPTION
**Pull request by tarilabs**
@etirelli @baldimir @jiripetrlik

FYI @jomarko @manstis

### CODE REVIEW

**Comment by tarilabs** [comment]
```
10:32:30 Fetching upstream changes from https://github.com/kiegroup/drools.git
10:32:30  > git fetch --tags --progress https://github.com/kiegroup/drools.git +refs/pull/*:refs/remotes/origin/pr/*
10:32:30 ERROR: Error fetching remote repo 'origin'
10:32:30 hudson.plugins.git.GitException: Failed to fetch from https://github.com/kiegroup/drools.git
10:32:30 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:888)
10:32:30 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1155)
10:32:30 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
10:32:30 	at hudson.scm.SCM.checkout(SCM.java:495)
10:32:30 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
10:32:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
10:32:30 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
10:32:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
10:32:30 	at hudson.model.Run.execute(Run.java:1724)
10:32:30 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
10:32:30 	at hudson.model.ResourceController.execute(ResourceController.java:97)
10:32:30 	at hudson.model.Executor.run(Executor.java:429)
10:32:30 Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/kiegroup/drools.git +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
10:32:30 stdout: 
10:32:30 stderr: fatal: git fetch_pack: expected ACK/NAK, got 'ERR upload-pack: not our ref 7998fb3a2269dbaeb6404fbcdcae507b5199008d'
10:32:30 fatal: The remote end hung up unexpectedly
```

Jenkins test again

**Comment by jomarko** [comment]
@tarilabs thank you for PR. The code looks well, no comments there. My manual check pending.

**Comment by jomarko** [comment]
@tarilabs hi, I tried your PR manually. I can confirm import of another DMN model now works without validation issues. However If I import [PMML](https://github.com/kiegroup/drools/blob/master/kie-pmml/src/test/resources/org/kie/pmml/pmml_4_2/test_tree_with_surrogate.pmml) I still got validation errors.

Server error log:
```
09:26:59,063 ERROR [org.kie.dmn.validation.DMNValidatorImpl] (default task-7) Validation of the DMN Model cannot be performed because of some runtime exception 'null'.
```

Workbench alerts:
- `[uuid] DMN: Validation of the DMN Model cannot be performed because of some runtime exception 'null'. (DMN Validation stopped on failed validation for some DMN Model)`
- `[_340EA0AC-C4CC-4C3E-A5DE-329B015CF2FA] DMN: Required import not found: P for node 'P' (DMN id: _340EA0AC-C4CC-4C3E-A5DE-329B015CF2FA, The referenced import was not found)`

**Comment by tarilabs** [comment]
thanks for reporting @jomarko , will take care this import validation to focus just on DMN type of Import(s)

**Comment by jomarko** [comment]
@tarilabs sorry, I am not sure if I understand, will we merge this PR as it is and address the PMML imports in different ticket or are you going to update this PR?

**Comment by tarilabs** [comment]
See 923ca93

**Comment by jomarko** [comment]
@tarilabs thank you, it is improved, however still one error is present.

`[uuid] DMN: Validation of the DMN Model cannot be performed because of some runtime exception 'null'. (DMN Validation stopped on failed validation for some DMN Model)`

Screenshot from 2019-08-08 16-02-49

**Comment by tarilabs** [comment]
In summary.

This addressed the original JIRA which mentioned about wrong detection of (DMN) Import(s).
The attached test cases demonstrates the problem, and proper fix by means rule correction.

What reported in https://github.com/kiegroup/drools/pull/2494#issuecomment-519533332 seems to be related to WB and additional code beyond the scope of this original JIRA. Once this manual check will be synthesized as a reproducer and if require my attention, don't hesitate to involve me and let me know. I'm all glad if I can support any other additional problems which may raise, but I don't believe is good of scope creep within this original JIRA. 

Can I kindly have a QE ack and merge this PR, please?  @baldimir @jiripetrlik @jomarko

**Review by jomarko — COMMENTED** [review]
Approving this PR, mentioned problems with PMML will be addressed via another jira https://issues.jboss.org/browse/DROOLS-4395.

Thank you @tarilabs

**Review by jomarko — APPROVED** [review]

**Review by baldimir — APPROVED** [review]

**Pull request merged**
