### PR TITLE
Support generic range type in DMN engine

### LINKED ISSUE #1536: DMN engine doesn't support generic range type
When there is a FEEL expression like 

```
range(string("[1..3]")) instance of range<number>
```

The DMN engine fails with an exception: 
```
Error compiling FEEL expression 'range(string("[1..3]")) instance of range<number>'
```

This error was highlighted by running the DMN TCK test suite.

### PR DESCRIPTION
**Pull request by baldimir**
Fixes https://github.com/apache/incubator-kie-issues/issues/1536

### CODE REVIEW

**Review by yesamer — APPROVED** [review]
LGTM

**Comment by yesamer** [comment]
@baldimir 
Most likely there's a regression, can you please double-check?
I run your changes against the TCK tests and I discovered those failing tests:


Screenshot 2024-10-14 at 10 09 18
Screenshot 2024-10-14 at 10 09 08


IIRC these tests were ok last time I checked.

**Review by yesamer — APPROVED** [review]

**Comment by baldimir** [comment]
Those failures are also failing on current main. I will focus on those next.

**Review by gitgabrio — APPROVED** [review]
Thx @baldimir LGTM!

**Comment by baldimir** [comment]
kogito-runtimes and serverless-workflow-examples downstream jobs failed because of Python environment problems, not related to this PR.

**Pull request merged**
