### PR TITLE
GUVNOR-2444: Guided Decision Table: Can't add columns/rows

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2444

This was a regression introduced by https://bugzilla.redhat.com/show_bug.cgi?id=1301055

### CODE REVIEW

**Comment by Rikkola** [comment]
+1

**Comment by manstis** [comment]
Test failure on Jenkins is unrelated to this PR.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by etirelli** [comment]
Merged.

**Pull request closed without merging**
