### PR TITLE
DROOLS-4344 DMN DT Analysis normalize Contractions for complete 2NFcheck

### PR DESCRIPTION
**Pull request by tarilabs**
@etirelli @baldimir @jiripetrlik

### CODE REVIEW

**Comment by tarilabs** [comment]
```
11:38:47 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-blacklisted-dependencies) on project kie-wb-common-compiler-distribution: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
```

unrelated.

Jenkins test again

**Comment by tarilabs** [comment]
```
14:02:17 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-blacklisted-dependencies) on project kie-wb-common-compiler-distribution: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
```

still unrelated, I propose to go ahead with the merge anyway.

**Comment by baldimir** [comment]
jenkins execute compile downstream build

**Review by baldimir — APPROVED** [review]

**Comment by tarilabs** [comment]
```
08:56:22 [INFO] Reactor Summary:
08:56:22 [INFO] 
08:56:22 [INFO] openshift-kie-parent ............................... SUCCESS [  3.327 s]
08:56:22 [INFO] kie-remote ......................................... FAILURE [  6.633 s]
...
08:56:23 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (default) on project kie-remote: MavenReportException: Error while generating Javadoc: 
08:56:23 [ERROR] Exit code: 1 - javadoc: warning - No source files for package org.kie.remote
```

I would vote to merge anyway, as unrelated.

**Comment by tarilabs** [comment]
Jenkins test again

**Pull request merged**
