### PR TITLE
[r7.54.0.Final] [DROOLS-6344] Update drools-impact-analysis pom.xml

### PR DESCRIPTION
**Pull request by tkobayas**
Make sure to be deployed to nexus.

**JIRA**: 

https://issues.redhat.com/browse/DROOLS-6344

Backport https://github.com/kiegroup/drools/pull/3606 to r7.54.0.Final branch

<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
@tkobayas a PR and fdb doesn't work on these branches: r7.54.0.Final. They are only configured to work for master, 7.52.x etc. branches! We have to look for the results at https://github.com/kiegroup/drools/pull/3609. Once @mariofusco approves it I will merge this one.

**Comment by tkobayas** [comment]
Closing as this is not required for release.

**Pull request closed without merging**
