### PR TITLE
[DROOLS-5584] fix lazy kbuilder creation from an empty one

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mariofusco** [comment]
@danielezonca I added one more test to check packages and globals, I hope this is enough for test coverage.

**Comment by mariofusco** [comment]
jenkins execute cdb

**Review by danielezonca — COMMENTED** [review]
Can you please add a test to verify that if you have an Empty, add a broken resource, build and verify that there are errors? And then if you remove it again (or replace with a valid one) build will succeed?

**Comment by mariofusco** [comment]
@danielezonca done

**Review by danielezonca — APPROVED** [review]
LGTM approving 👍

**Pull request merged**
