### PR TITLE
DROOLS-5711 link requirements to MID

### PR DESCRIPTION
**Pull request by TommyNeubert**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://issues.redhat.com/browse/DROOLS-5711)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
@TommyNeubert could you kindly attach a picture of the diagram to this PR or JIRA, please?
I believe the code change is fine, but I would like to be sure I really understood completely the case which was missing from the original implementation. Thanks! 👍

**Review by tarilabs — APPROVED** [review]

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
```
11:13:23  Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.google.http-client:google-http-client:jar:1.23.0 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar.part (No such file or directory)
11:13:23      at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
11:13:23      at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:369)
11:13:23      at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
11:13:23      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
11:13:23      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
11:13:23      at java.lang.Thread.run (Thread.java:748)
11:13:23  Caused by: java.io.FileNotFoundException: /home/jenkins/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar.part (No such file or directory)
```

Jenkins run cdb

**Comment by tarilabs** [comment]
same error again in CDB, I conclude is unrelated.

```
16:24:59  [INFO] BUILD FAILURE
16:24:59  [INFO] ------------------------------------------------------------------------
16:24:59  [INFO] Total time:  02:20 min (Wall Clock)
16:24:59  [INFO] Finished at: 2020-10-12T10:23:50-04:00
16:24:59  [INFO] ------------------------------------------------------------------------
16:24:59  [ERROR] Failed to execute goal on project google-tasks-workitem: Could not resolve dependencies for project org.jbpm.contrib:google-tasks-workitem:jar:7.45.0-SNAPSHOT: Could not transfer artifact com.google.http-client:google-http-client:jar:1.23.0 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar.part (No such file or directory) -> [Help 1]
16:24:59  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project google-tasks-workitem: Could not resolve dependencies for project org.jbpm.contrib:google-tasks-workitem:jar:7.45.0-SNAPSHOT: Could not transfer artifact com.google.http-client:google-http-client:jar:1.23.0 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kie-all/): /home/jenkins/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar.part (No such file or directory)
```

**Pull request merged**
