### PR TITLE
[DROOLS-6920] Fails to parse a constraint connected with OR with a bi…

### PR DESCRIPTION
**Pull request by tkobayas**
…nd variable on right side in executable-model

**Ports** 
This PR is for 7.x
for main -> https://github.com/kiegroup/drools/pull/4361

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6920

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
@mariofusco Please review this PR. I confirmed that tests passed for `drools-model` and `test-compiler-integration` locally.

**Comment by tkobayas** [comment]
CDB: Not likely related to this PR.
```
[2022-04-27T10:35:02.177Z] [ERROR] /home/jenkins/workspace/KIE/7.x/compile/drools-7.x.compile/bc/kiegroup_kie_wb_common/kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/relations/multipleSubform/MultipleSubFormFieldRenderer.java:[34,1] Internal error in org.kie.workbench.common.forms.adf.processors.FieldRendererProcessorjava.lang.ExceptionInInitializerError
[2022-04-27T10:35:02.177Z]      at freemarker.ext.beans.ClassIntrospectorBuilder.<init>(ClassIntrospectorBuilder.java:73)
[2022-04-27T10:35:02.177Z]      at freemarker.ext.beans.BeansWrapperConfiguration.<init>(BeansWrapperConfiguration.java:94)
[2022-04-27T10:35:02.177Z]      at freemarker.template.DefaultObjectWrapperConfiguration.<init>(DefaultObjectWrapperConfiguration.java:40)
[2022-04-27T10:35:02.177Z]      at freemarker.template.DefaultObjectWrapper$1.<init>(DefaultObjectWrapper.java:118)
[2022-04-27T10:35:02.177Z]      at freemarker.template.DefaultObjectWrapper.<init>(DefaultObjectWrapper.java:118)
[2022-04-27T10:35:02.177Z]      at freemarker.template.DefaultObjectWrapper.<init>(DefaultObjectWrapper.java:87)
[2022-04-27T10:35:02.177Z]      at freemarker.template.DefaultObjectWrapper.<clinit>(DefaultObjectWrapper.java:67)
[2022-04-27T10:35:02.177Z]      at freemarker.template._TemplateAPI.<clinit>(_TemplateAPI.java:82)
[2022-04-27T10:35:02.177Z]      at freemarker.core.Configurable.<init>(Configurable.java:420)
[2022-04-27T10:35:02.177Z]      at freemarker.template.Configuration.<init>(Configuration.java:940)
[2022-04-27T10:35:02.177Z]      at org.kie.workbench.common.forms.adf.processors.TemplateWriter.writeTemplate(TemplateWriter.java:49)
[2022-04-27T10:35:02.177Z]      at org.kie.workbench.common.forms.adf.processors.FieldRendererProcessor.processWithExceptions(FieldRendererProcessor.java:105)
[2022-04-27T10:35:02.177Z]      at org.uberfire.annotations.processors.AbstractErrorAbsorbingProcessor.process(AbstractErrorAbsorbingProcessor.java:78)
[2022-04-27T10:35:02.177Z]      at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:985)
[2022-04-27T10:35:02.177Z]      at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:901)
[2022-04-27T10:35:02.177Z]      at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1227)
[2022-04-27T10:35:02.177Z]      at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1340)
[2022-04-27T10:35:02.177Z]      at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
[2022-04-27T10:35:02.177Z]      at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
[2022-04-27T10:35:02.177Z]      at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
[2022-04-27T10:35:02.177Z]      at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
[2022-04-27T10:35:02.177Z]      at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
[2022-04-27T10:35:02.177Z]      at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
[2022-04-27T10:35:02.177Z]      at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
[2022-04-27T10:35:02.177Z]      at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
[2022-04-27T10:35:02.177Z]      at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
[2022-04-27T10:35:02.177Z]      at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
[2022-04-27T10:35:02.177Z]      at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[2022-04-27T10:35:02.177Z]      at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[2022-04-27T10:35:02.177Z]      at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[2022-04-27T10:35:02.177Z]      at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[2022-04-27T10:35:02.177Z]      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[2022-04-27T10:35:02.177Z]      at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:205)
[2022-04-27T10:35:02.177Z]      at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:77)
[2022-04-27T10:35:02.177Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2022-04-27T10:35:02.177Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-04-27T10:35:02.177Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-04-27T10:35:02.177Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-04-27T10:35:02.177Z]      at java.base/java.lang.Thread.run(Thread.java:829)
[2022-04-27T10:35:02.177Z]   Caused by: java.lang.IllegalStateException: Couldn't init freemarker.ext.beans.DefaultMemberAccessPolicy instance
[2022-04-27T10:35:02.177Z]      at freemarker.ext.beans.DefaultMemberAccessPolicy.<init>(DefaultMemberAccessPolicy.java:156)
[2022-04-27T10:35:02.177Z]      at freemarker.ext.beans.DefaultMemberAccessPolicy.<clinit>(DefaultMemberAccessPolicy.java:47)
[2022-04-27T10:35:02.177Z]      ... 39 more
[2022-04-27T10:35:02.177Z]   Caused by: java.io.IOException: Stream closed
[2022-04-27T10:35:02.177Z]      at java.base/java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:68)
[2022-04-27T10:35:02.177Z]      at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:143)
[2022-04-27T10:35:02.177Z]      at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
[2022-04-27T10:35:02.177Z]      at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
[2022-04-27T10:35:02.177Z]      at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
[2022-04-27T10:35:02.177Z]      at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[2022-04-27T10:35:02.177Z]      at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
[2022-04-27T10:35:02.177Z]      at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
[2022-04-27T10:35:02.177Z]      at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
[2022-04-27T10:35:02.177Z]      at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
[2022-04-27T10:35:02.177Z]      at freemarker.ext.beans.DefaultMemberAccessPolicy.loadMemberSelectorFileLines(DefaultMemberAccessPolicy.java:167)
[2022-04-27T10:35:02.177Z]      at freemarker.ext.beans.DefaultMemberAccessPolicy.<init>(DefaultMemberAccessPolicy.java:73)
[2022-04-27T10:35:02.177Z]      ... 40 more
```

**Comment by tkobayas** [comment]
Jenkins run cdb

**Comment by tkobayas** [comment]
Jenkins retest this

**Review by mariofusco — APPROVED** [review]

**Comment by tkobayas** [comment]
Linux - Compile Downstream Build : Tests were successful. Seemed to just fail to update the github status.
```
Finished: SUCCESS
```

**Review by hellowdan — APPROVED** [review]

**Pull request merged**
