### PR TITLE
DROOLS-5683: Collection editor not opening for DRL based scenarios

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**: https://issues.redhat.com/browse/DROOLS-5683

**referenced Pull Requests**: 

* https://github.com/kiegroup/drools-wb/pull/1435

Test Scenario backend now supports evaluation of following Java Class:
- `BigDecimal`
- `BigInteger`
- `LocalDateTime`
- `LocalTime`

`BigDecimal` & `BigInteger` support number grouping (eg. user can write `1,000,000.34` and it will be parsed as `1000000.34`)
`LocalDateTime` uses [ISO_LOCAL_DATE_TIME](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_LOCAL_DATE_TIME) which is `2011-12-03T10:15:30` format. It supports nanoseconds as well, so I added supports for this format as well `2011-12-03T10:15:30.9999`. Seconds and nano are optionals, so `2011-12-03T10:15` is a valid pattern user can wrote.
`LocalTime` uses [ISO_LOCAL_TIME](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_LOCAL_TIME) which is `10:15:30` format. It supports nanoseconds as well, so I added supports for this format as well `10:15:30.9999`. Seconds and nano are optionals, so `10:15` is a valid pattern user can wrote.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]
LGTM approving :+1:

**Comment by yesamer** [comment]
jenkins do fdb

**Comment by yesamer** [comment]
jenkins execute compile downstream build

**Review by jstastny-cz — APPROVED** [review]

**Comment by yesamer** [comment]
@kiegroup/gatekeepers Can you please merge this ensemble?

**Pull request merged**
