### PR TITLE
[6.4.x] DROOLS-1279: [GSS] Compilation of spreadsheet fails with specific condition

### PR DESCRIPTION
**Pull request by karreiro**
## Cherry picked from https://github.com/droolsjbpm/drools/pull/940

See https://issues.jboss.org/browse/DROOLS-1279

LhsBuilder is re-used when a spreadsheet contain merged columns. It contains state for a specific constraint's FieldType which was being overwritten by second and subsequent merged columns. We need to store the FieldType per column to avoid it being overwritten.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Review by manstis — APPROVED** [review]
+1 to merge (when green).

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Pull request merged**
