### PR TITLE
DROOLS-4720-4721: Replace equals with Objects.equals

### PR DESCRIPTION
**Pull request by jomarko**
Small refactoring to minimize risk of NPE during equals method call

For more details see
- https://issues.redhat.com/browse/DROOLS-4720
- https://issues.redhat.com/browse/DROOLS-4721

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
Thanks for your PR :)

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
