### PR TITLE
DROOLS-4297 : Guided Rule Template removes quotation marks in concatenated String

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-4297

https://github.com/kiegroup/drools/pull/2448
https://github.com/kiegroup/kie-wb-common/pull/2757

### CODE REVIEW

**Review by manstis — COMMENTED** [review]
@Rikkola Should we not have a test in [this](https://github.com/kiegroup/drools/blob/master/drools-workbench-models/drools-workbench-models-guided-template/src/test/java/org/drools/workbench/models/guided/template/backend/RuleTemplateModelDRLPersistenceTest.java) (or similar) for https://issues.jboss.org/browse/DROOLS-4297

I know you state "..The existing unit tests should reflect the change.." however is that _really_ sufficient to prove the JIRA has been fixed!?

**Comment by Rikkola** [comment]
I can add a test into the persistence tests we have. Might be a good idea since I just just changed the type from "this" to "ActualType" here, but the tests do not really describe why.

**Comment by Rikkola** [comment]
@Bonuseto Here is another PR where I could use a review thank you.

**Comment by Rikkola** [comment]
jenkins execute full downstream build

**Review by manstis — APPROVED** [review]

**Comment by Bonuseto** [comment]
jenkins execute full downstream build

**Comment by Rikkola** [comment]
@kkufova Here is one of the PRs I mentioned. This bundle could use some eyes, thank you.

**Review by kkufova — APPROVED** [review]
The fix works well. Approving.

:+1:

**Pull request merged**
