### PR TITLE
DROOLS-2643: Extraneous parentheses generated by Guided Rule editor

### PR DESCRIPTION
**Pull request by manstis**
@jomarko This is an alternative (non-hacked) fix for https://issues.jboss.org/browse/DROOLS-2643

This uses the "depth" of patterns to determine whether they are "sub patterns".

### CODE REVIEW

**Review by jomarko — CHANGES_REQUESTED** [review]
Please add reproducer tests that will show correct source is generated for different "from accumulate" expressions.

**Comment by manstis** [comment]
@jomarko Tests for the different types of "accumulate" added.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Review by jomarko — APPROVED** [review]
Thanks!

**Pull request merged**
