### PR TITLE
5.5.x

### PR DESCRIPTION
**Pull request by shivshnkr**

### CODE REVIEW

**Comment by sotty** [comment]
Was this pull request opened by mistake, or is it the result of a wrong rebase?

**Comment by shivshnkr** [comment]
by mistake, and i tried to undo the pull request, but could not find a way.
sorry

**Comment by sotty** [comment]
No problem, I'll close it. Cheers

**Comment by shivshnkr** [comment]
True

**Comment by shivshnkr** [comment]
Hi droolsjbpm/drools,

I&#39;d like to add you to my professional network on LinkedIn.
- Shiv Shankar

Accept: https://www.linkedin.com/blink?simpleRedirect=0Me3gUc34Tej0RdP0Ne3oUd3ARfkh9rCZFt65QqnpKqipitSoVlBhPljRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9DoPbj8QtDBLqzdFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8557408634_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=tzcJczhSumZGcSAJtSVDoStHfmhFpipzkkhNjj5KtBhQnQdLk6RUhj5NhDwMgmF2c7p6mDFAp6ZOiltnhkFzcQtFuCUUd79Vlz8JomoTrRpbekBImll2h3pfd4V2cS5atAVfgkdctldotCllmjx8jk8PjjsJiRYSpz1qiDx9lCpLpPtQs754d7FpgDBQjQFEoT9LlkxFokxjd3BmtQlPpBcSk6V6czdLlk51gk5QdztktQ9gimdJi551fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DoPbj8QtDBLqzdFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I8557408634_500&amp;markAsRead=This email was intended for droolsjbpm/drools droolsjbpm/drools. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DoPbj8QtDBLqzdFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8557408634_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by shivshnkr** [comment]
Shiv Shankar Verma would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Me3gUc34Tej0RdP0Ne3oUd3ARfkh9rCZFt65QqnpKqipitSoVlBhPljRVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9DEObnkNpjpOs3dFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8557408634_500&markAsRead=

View Shiv Shankar Verma&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9DEObnkNpjpOs3dFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8557408634_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kUdPATc38QbmpCc3BAd3txoCkRemlBpzgNoClxe3dAoS9xd6oRpzBBe3ATc3dyej0Je38RdP8Ue34Jqk8O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0Ud3wMcjsVc3kTc34UdzwQejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9DEObnkNpjpOs3dFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8557408634_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1WcyRRcmkSsD0PqiRTrCtzpSIZp6BB9DdCnT9etDh3uBhMqSROdmZcrCNqdAt7sTEQbn13mmJcrkldiC4Ms31eoDxCdSZcdmt2l6pDsSByuClLr6dyl6BdcAJom75iulpUek4RpRl5j4dPj7p6s7tpkl5hoRZzc498s6JPsRx6gjBpkmlbrQETr3xUhz96cP4UuDpcbl1gi55zpDpviA9emzhLgQRPjD1lgk51pRtEpQZ2h4pigCl7kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DEObnkNpjpOs3dFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I8557408634_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DEObnkNpjpOs3dFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8557408634_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by shivshnkr** [comment]
Shiv Shankar Verma would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Me3gUc34Tej0RdP0Ne3oUd3ARfkh9rCZFt65QqnpKqipitSoVlBhPljRVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9z0Obj1CtDtLuzdFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8557408634_500&markAsRead=

View Shiv Shankar Verma&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9z0Obj1CtDtLuzdFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8557408634_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kUdPATc38QbmpCc3BAd3txoCkRemlBpzgNoClxe3dAoS9xd6oRpzBBe3ATc3dyej0Je38RdP8Ue34Jqk8O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0Ud3wMcjsVc3kTc34UdzwQejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9z0Obj1CtDtLuzdFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8557408634_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=0McyQMpDpTrTEPqiRTrCtzpSIZp6BB9DdSdBxNuB1DoPpGqztdoAt4tRpojzgTqkAJkkFQmkxpuC5CtktcpjpFsmBjjRFgrTFmclByhAURqAlNe6tHdkdjsm9lrQ9li78Nr6xomBdSqTB5i30MkDpkpDxgjCNptDlDcSFcs4gVc4J7jAJlkTgVpzlCtPxiu39Cc6ZEl3lDhzcMkz9ShmVIt3pDdAZDu71lgk51kmZ5jP9Dm4RanSB6kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9z0Obj1CtDtLuzdFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I8557408634_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9z0Obj1CtDtLuzdFbntKpSdDqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8557408634_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by psiroky** [comment]
I have unsubscribed the e-mail address of this PR from Linkedin updates, so hopefully no more spam in the comments.

**Comment by shivshnkr** [comment]
Apologies, as this was my fault. Sometime I invited all the contacts, and
it was a mistake. Sorry for this trouble.

**Pull request closed without merging**
