### PR TITLE
GUVNOR-3576: Creating a guided rule causes java.lang.RuntimeException

### PR DESCRIPTION
**Pull request by mbarkley**
Fixes an error introduced by [this](https://github.com/kiegroup/drools/pull/1444) PR.

//cc @kkufova

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko Hi, IDK if you want to give this a try too?

**Comment by jomarko** [comment]
@manstis thanks,  building&trying locally right now if it solves problem I spotted.

**Review by jomarko — CHANGES_REQUESTED** [review]
@mbarkley Hi, please see my comment in the corresponding jira GUVNOR-3576. I think there is need to add one more item in these `errai.marshalling.serializableTypes`. Could you please have a look?

**Comment by kkufova** [comment]
@mbarkley, the scenario I was using for testing the bug is working now, but I can confirm that the file @jomarko uploaded in [GUVNOR-3576](https://issues.jboss.org/browse/GUVNOR-3576) causes a similar error:

> Unable to complete your request. The following exception occurred: java.lang.RuntimeException: java.lang.RuntimeException: no marshalling definition available for type:org.drools.workbench.models.datamodel.imports.Import.

Log: https://pastebin.com/h6Jgfbyj.

**Comment by mbarkley** [comment]
@jomarko @kkufova I have amended the commit to fix the Import issue as well. I believe this PR now covers all of the new types that should be serializable.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by mbarkley** [comment]
Looks like a webapp is missing a source jar for the workbench models. I will take a look in a bit.

**Comment by jomarko** [comment]
@mbarkley thank you, I will have a look on Monday.

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Review by jomarko — APPROVED** [review]
Thanks @mbarkley . Looks my problem is gone.

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by mbarkley** [comment]
The downstream build is failing because of the `ConcurrentHumanTaskTest` in jbpm. But running the build locally I see this test also failing on master.

**Review by kkufova — APPROVED** [review]

**Pull request merged**
