### PR TITLE
DROOLS-1419 Make generic interface AccumulateFunction<S extends Seria…

### PR DESCRIPTION
**Pull request by ge0ffrey**
…lizable>

 To avoid downcasting verbosity in implementations

Requires this PR: https://github.com/droolsjbpm/droolsjbpm-knowledge
Related to this PR: https://github.com/droolsjbpm/kie-docs/pull/204

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Jenkins error.
Jenkins retest this.

**Comment by ge0ffrey** [comment]
while (jenkins log contains git error) {
  jenkins retest this
}

**Comment by mariofusco** [comment]
ok to test

**Comment by ge0ffrey** [comment]
jenkins retest this

**Comment by ge0ffrey** [comment]
jenkins retest this. revapi fixed

**Pull request merged**
