### PR TITLE
DROOLS-2732 FEEL invoking a function on a literal context

### PR DESCRIPTION
**Pull request by tarilabs**
/cc @etirelli @baldimir @winklerm

### CODE REVIEW

**Review by etirelli — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
image

image

**Comment by tarilabs** [comment]
Jenkins test again

**Review by baldimir — APPROVED** [review]

**Comment by manstis** [comment]
@tarilabs IIRC CI builds are now ran/checked once per hour to avoid our DoS attack on GitHub's API.

**Comment by tarilabs** [comment]
> to avoid our DoS attack on GitHub's API

@manstis I thought it was 30m, but anyway the point remains, if the reverse proxy would allow for the githook mechanism, I still don't understand what is preventing for such solution to be deployed.

**Comment by tarilabs** [comment]
image

**Pull request merged**
