### PR TITLE
RHBPMS-4435 Fixes behaviour when interval scanning is stopped when kieScanner.scanNow() is called

### PR DESCRIPTION
**Pull request by baldimir**
When scanNow() was called after interval scanning was started with kieScanner.start(),
the interval scanning was stopped, because "status" of kieScanner was set to STOPPED.
Adds reproducer for mentioned issue and proposed fix.

### CODE REVIEW

**Comment by psiroky** [comment]
Looks good, thanks @baldimir.

Two questions regarding the test: (1) is there any chance to remove the Thread.sleep()?, (2) should we stop/shutdown the scanner after the test? It seems the background thread will be running until the JVM shutdown, which is not ideal.

**Comment by baldimir** [comment]
After discussion with @psiroky I will add new commit with changes.

**Comment by baldimir** [comment]
@psiroky, requested changes added.

**Comment by psiroky** [comment]
Thanks @baldimir! This is what I had originally in mind https://github.com/droolsjbpm/drools/pull/1065/commits/ba546362b139d2e2cfce6736d48b49b2577d2efd. Please let me know what you think.

**Comment by baldimir** [comment]
@psiroky thanks, that will do, I added the commit also to https://github.com/droolsjbpm/drools/pull/1066

**Review by psiroky — APPROVED** [review]

**Pull request merged**
