### PR TITLE
[8.21.x] Bump Quarkus version to 2.9.0.Final (#4347)

### PR DESCRIPTION
**Pull request by radtriste**
cherry-pick: https://github.com/kiegroup/drools/pull/4347

Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/437
- https://github.com/kiegroup/drools/pull/4357
- https://github.com/kiegroup/kogito-runtimes/pull/2188
- https://github.com/kiegroup/optaplanner/pull/1967
- https://github.com/kiegroup/optaplanner-quickstarts/pull/330
- https://github.com/kiegroup/kogito-apps/pull/1331
- https://github.com/kiegroup/kogito-examples/pull/1245

### CODE REVIEW

**Comment by radtriste** [comment]
jenkins retest this

**Review by evacchi — APPROVED** [review]

**Comment by kie-ci1** [comment]
**(tests) - optaplanner-quickstarts job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 140
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.21.x/job/pullrequest/job/drools.tests.downstream.optaplanner-quickstarts/3/testReport/org.acme.employeescheduling.rest/EmployeeScheduleResourceTest/solveDemoDataUntilFeasible/">org.acme.employeescheduling.rest.EmployeeScheduleResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus<br/>Caused by: java.lang.RuntimeException: Failed to start quarkus<br/>Caused by: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method<br/>Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.<br/>Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement<br/>Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement<br/>Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: <br/>Table "SHIFT" not found; SQL statement:<br/>insert into Shift (employee_name, end, location, requiredSkill, start, id) values (?, ?, ?, ?, ?, ?) [42102-210]<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.21.x/job/pullrequest/job/drools.tests.downstream.optaplanner-quickstarts/3/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - optaplanner-quickstarts job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 140
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.21.x/job/pullrequest/job/drools.tests.downstream.optaplanner-quickstarts/5/testReport/org.acme.employeescheduling.rest/EmployeeScheduleResourceTest/solveDemoDataUntilFeasible/">org.acme.employeescheduling.rest.EmployeeScheduleResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus<br/>Caused by: java.lang.RuntimeException: Failed to start quarkus<br/>Caused by: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method<br/>Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.<br/>Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement<br/>Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement<br/>Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: <br/>Table "SHIFT" not found; SQL statement:<br/>insert into Shift (employee_name, end, location, requiredSkill, start, id) values (?, ?, ?, ?, ?, ?) [42102-210]<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.21.x/job/pullrequest/job/drools.tests.downstream.optaplanner-quickstarts/5/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - optaplanner-quickstarts job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 140
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.21.x/job/pullrequest/job/drools.tests.downstream.optaplanner-quickstarts/4/testReport/org.acme.employeescheduling.rest/EmployeeScheduleResourceTest/solveDemoDataUntilFeasible/">org.acme.employeescheduling.rest.EmployeeScheduleResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus<br/>Caused by: java.lang.RuntimeException: Failed to start quarkus<br/>Caused by: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method<br/>Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.<br/>Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement<br/>Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement<br/>Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: <br/>Table "SHIFT" not found; SQL statement:<br/>insert into Shift (employee_name, end, location, requiredSkill, start, id) values (?, ?, ?, ?, ?, ?) [42102-210]<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.21.x/job/pullrequest/job/drools.tests.downstream.optaplanner-quickstarts/4/display/redirect

**Comment by kie-ci1** [comment]
**(tests) - optaplanner-quickstarts job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 140
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.21.x/job/pullrequest/job/drools.tests.downstream.optaplanner-quickstarts/2/testReport/org.acme.employeescheduling.rest/EmployeeScheduleResourceTest/solveDemoDataUntilFeasible/">org.acme.employeescheduling.rest.EmployeeScheduleResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus<br/>Caused by: java.lang.RuntimeException: Failed to start quarkus<br/>Caused by: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method<br/>Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.<br/>Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement<br/>Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement<br/>Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: <br/>Table "SHIFT" not found; SQL statement:<br/>insert into Shift (employee_name, end, location, requiredSkill, start, id) values (?, ?, ?, ?, ?, ?) [42102-210]<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.21.x/job/pullrequest/job/drools.tests.downstream.optaplanner-quickstarts/2/display/redirect

**Comment by radtriste** [comment]
jenkins rerun optaplanner-quickstarts tests

**Comment by radtriste** [comment]
drools test failure is flaky and already known. can be ignored ...

**Pull request merged**
