### PR TITLE
DROOLS-1695 When unmarshalling attributePrefix as null on IBM JDK

### PR DESCRIPTION
**Pull request by tarilabs**
forwardport to master from 72x of #1407

### CODE REVIEW

**Comment by tarilabs** [comment]
@baldimir thanks again for your reports; I checked and indeed when on IBM JDK the default/silent prefix is returned as `null` from the xml infra, instead of respecting the JDK contract in the Javadoc for `XMLConstants.DEFAULT_NS_PREFIX`.

For example, an element with two attribute as:
```
<myelement a="avalue" drools:kind="kindvalue">
```
on JDK would unmarshal the attributes prefix as:
` XMLConstants.DEFAULT_NS_PREFIX` for the first `a` attribute
`drools` for the second `kind` attribute

while on IBM JDK is returning:
`null` for the first, and `drools` for the second.

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by baldimir** [comment]
+1, looks good. Thanks.

**Review by baldimir — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
`9305 tests run, 442 skipped, 0 failed.`
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
Downstream is an unrelated failure:
```
Test Result (1 failure / +1)
org.jbpm.kie.services.test.FilteredKModuleDeploymentServiceTest.testMultipleRemotableInPojoJar
```

**Pull request merged**
