### PR TITLE
[7.x] [DROOLS-6655] IllegalArgumentException: DTDDVFactoryImpl does not ext…

### PR DESCRIPTION
**Pull request by tkobayas**
…end from DTDDVFactory

**Ports** If a forward-port or a backport is needed, paste the forward port PR here

https://github.com/kiegroup/drools/pull/3957 for main

**JIRA**: 

https://issues.redhat.com/browse/DROOLS-6655

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
the CDB/FDB issue on drools 7.x issue is being discussed on gchat "BA Central CI".

**Comment by tkobayas** [comment]
Hi @mariofusco , currently FDB is not functioning and then (after FDB) I will need to ask @sutaakar to test it with IBM JDK. But I confirmed this solves the issue with IBM JDK on my local end. Do you have any concern in this fix?

Another approach is to remove xerces.jar from kie-server (https://github.com/kiegroup/droolsjbpm-integration/pull/2634) but I'm a bit reluctant considering any ramifications (all supported app-servers could be affected).

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
FDB: Those tests are also failed in daily builds so not likely related to this PR.
```
    org.uberfire.ext.metadata.backend.infinispan.provider.InfinispanPingServiceTest.testPingSuccess

    org.jbpm.springboot.samples.BusinessProcessTest.testProcessStartAndWorkOnUserTasks
    org.jbpm.springboot.samples.BusinessProcessTest.testProcessStartAndWorkOnUserTasks
    org.jbpm.springboot.samples.BusinessProcessTest.testProcessStartAndAbort
    org.jbpm.springboot.samples.BusinessProcessTest.testProcessStartAndAbort
    org.jbpm.springboot.samples.CaseTest.testProcessStartAndAbort
    org.jbpm.springboot.samples.CaseTest.testProcessStartAndAbort
    org.jbpm.springboot.samples.ConfigurationTest.testProcessEventListenerRegistration
    org.jbpm.springboot.samples.ConfigurationTest.testProcessEventListenerRegistration
    org.jbpm.springboot.samples.ConfigurationTest.testWorkItemHandlerRegistration
    org.jbpm.springboot.samples.ConfigurationTest.testWorkItemHandlerRegistration
    org.jbpm.springboot.samples.DeadlinesNotificationTest.testSaveContentAfterDeadlines
    org.jbpm.springboot.samples.DeadlinesNotificationTest.testSaveContentAfterDeadlines
    org.jbpm.springboot.samples.DeadlinesNotificationTest.testRepeatedNotificationsAfterDeadlinesWhenNotCompleted
    org.jbpm.springboot.samples.DeadlinesNotificationTest.testRepeatedNotificationsAfterDeadlinesWhenNotCompleted
    org.jbpm.springboot.samples.DeadlinesNotificationTest.testRepeatedNotificationsAfterDeadlinesWhenNotStarted
    org.jbpm.springboot.samples.DeadlinesNotificationTest.testRepeatedNotificationsAfterDeadlinesWhenNotStarted
    org.jbpm.springboot.samples.EventEmitterTest.testProcessEventListenerRegistration
    org.jbpm.springboot.samples.EventEmitterTest.testProcessEventListenerRegistration
    org.jbpm.springboot.samples.EventEmitterTest.testEmitterBusinessAdminOperations
    org.jbpm.springboot.samples.EventEmitterTest.testEmitterBusinessAdminOperations
    org.jbpm.springboot.samples.ExtendedEMFBusinessProcessTest.processorsInitialization
    org.jbpm.springboot.samples.ExtendedEMFBusinessProcessTest.processorsInitialization
    org.jbpm.springboot.samples.ExtendedEMFBusinessProcessTest.testProcessStartAndAbort
    org.jbpm.springboot.samples.ExtendedEMFBusinessProcessTest.testProcessStartAndAbort
    org.jbpm.springboot.samples.JMXQuartzSchedulerTest.whenSchedulerStartedThenTimerIsFired
    org.jbpm.springboot.samples.JMXQuartzSchedulerTest.whenSchedulerStartedThenTimerIsFired
    org.jbpm.springboot.samples.JMXQuartzSchedulerTest.whenSchedulerRestartedThenTimerIsFired
    org.jbpm.springboot.samples.JMXQuartzSchedulerTest.whenSchedulerRestartedThenTimerIsFired
    org.jbpm.springboot.samples.JMXQuartzSchedulerTest.testTimerName
    org.jbpm.springboot.samples.JMXQuartzSchedulerTest.testTimerName
    org.jbpm.springboot.samples.JMXQuartzSchedulerTest.whenSchedulerPausedThenTimerNotFired
    org.jbpm.springboot.samples.JMXQuartzSchedulerTest.whenSchedulerPausedThenTimerNotFired
    org.jbpm.springboot.samples.MigrationProcessTest.testProcessStartAndAbort
    org.jbpm.springboot.samples.MigrationProcessTest.testProcessStartAndAbort
    org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskCompletedBoundaryTimerProcessInstance
    org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskCompletedBoundaryTimerProcessInstance
    org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskNotCompletedBoundaryTimerProcessInstance
    org.jbpm.springboot.samples.TimerInProcessMigrationTest.testMigrateUserTaskNotCompletedBoundaryTimerProcessInstance
    org.jbpm.springboot.samples.TimerProcessTest.testProcessStartWithTimer
    org.jbpm.springboot.samples.TimerProcessTest.testProcessStartWithTimer

    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testBoundarySignal
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojoBothParamsNull
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojoMismatchedInput
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessageInDifferentContainers
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojoClassNotFound
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignalInDifferentContainers
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojoFirstParamNull
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testSubprocessSignal
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojoWrongType
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testBoundarySignalMultipleProcesses
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testBoundaryMessage
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testIntermediateCatchEventMessage
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessageComplexPojo
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testIntermediateCatchEventSignal
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojo
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojoMalformedData
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testSubprocessMessage
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignal
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignalsTransactional
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessagePojoSecondParamNull
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartMessage
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testStartSignalsAndMessagesTransactional
    org.kie.server.springboot.samples.KafkaConsumerHappyPathTest.testBoundaryMessageMultipleProcesses

    org.kie.spring.jbpm.PerProcessInstanceWithExternalTXSpringTest.testCompleteTasksWithSeparateThread[0: jbpm/jta-emf/per-process-instance.xml]
    org.kie.spring.jbpm.PessimisticLockingSpringTest.testPessimisticLock[1: jbpm/pessimistic-lock/pessimistic-locking-local-emf-factory-beans.xml]
    org.kie.spring.jbpm.ProcessFlowSpringTest.testEventBasedGatewayWithUserTransaction[0: jbpm/jta-emf/singleton.xml]
    org.kie.spring.jbpm.ProcessFlowSpringTest.testEventBasedGatewayWithUserTransaction[1: jbpm/jta-em/singleton.xml]
    org.kie.spring.jbpm.RuntimeManagerInitNoInitialContextSpringTest.testSimpleTaskInvocation[0: jbpm/no-initial-context/local-emf-singleton.xml]
    org.kie.spring.jbpm.RuntimeManagerInitNoInitialContextSpringTest.testSimpleTaskInvocation[1: jbpm/no-initial-context/local-emf-per-process.xml]
    org.kie.spring.jbpm.RuntimeManagerInitNoInitialContextSpringTest.testSimpleTaskInvocation[2: jbpm/no-initial-context/local-emf-per-request.xml]
    org.kie.spring.jbpm.SwimlaneSpringTest.testCompleteTaskInSwimlane[0: jbpm/usergroup-callback/local-emf-singleton.xml]
    org.kie.spring.jbpm.UserManagedSharedTaskServiceSpringTest.testSpringWithJTAAndSharedEMFAndUserManagedTx[0: jbpm/shared-taskservice/jta-em-singleton.xml]
    org.kie.spring.jbpm.UserManagedSharedTaskServiceSpringTest.testSpringWithJTAAndSharedEMFAndUserManagedTx[1: jbpm/shared-taskservice/jta-emf-singleton.xml]
    org.kie.spring.jbpm.UserManagedTransactionAuditLogSpringTest.testUserTransaction[0: jbpm/jta-emf/singleton.xml]
    org.kie.spring.jbpm.UserManagedTransactionAuditLogSpringTest.testUserTransaction[1: jbpm/jta-em/singleton.xml]
```

**Comment by tkobayas** [comment]
@sutaakar Could you test this with IBM JDK? I confirmed this solves the issue with IBM JDK on my local end.

@mariofusco Please review and let me know if you have any concerns in this fix.

**Comment by tkobayas** [comment]
IBM JDK has jre/lib/xml.jar which is based on XML4J 4.5 (based on Xerces-J 2.9).

The Exception tells that DTDDVFactoryImpl cannot be cast to DTDDVFactory. Which means their classloaders are different (one is system classLoader, the other is ModuleClassLoader)

https://github.com/apache/xerces2-j/blob/Xerces-J_2_9_0/src/org/apache/xerces/impl/dv/DTDDVFactory.java#L63

DTDDVFactory.getInstance() depends on ObjectFactory.findClassLoader() which uses Context ClassLoader.

https://github.com/apache/xerces2-j/blob/Xerces-J_2_9_0/src/org/apache/xerces/impl/dv/ObjectFactory.java#L272-L326

In case of WildFly, it's ModuleClassLoader. It loads classes from xercesImpl.jar in kie-server.war and also "org.apache.xerces" module in WildFly .

By setting system classloader to TCCL, those classes are aligned with system classloader.

Another approach is to remove xerces.jar from kie-server (https://github.com/kiegroup/droolsjbpm-integration/pull/2634) but I'm a bit reluctant considering any ramifications (all supported app-servers could be affected).

**Review by sutaakar — APPROVED** [review]

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
