### PR TITLE
[incubator-kie-drools-5798] [new-parser] Ensure Descr properties

### PR DESCRIPTION
**Pull request by tkobayas**
- Use DescrHelper

**Issue**: 

* https://github.com/apache/incubator-kie-drools/issues/5798

No change in `drools-model-codegen` test result.

Just refactoring and adding unit tests.

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Hi @yurloc  @gitgabrio  @mariofusco 

I think of some approaches for this refactoring and not very sure which one is the best. I'd like to hear your thoughts.

The point is to make sure `Descr`'s common properties (e.g. `startCharacter`) are set. The current implementation explicitly calls `DRLVisitorImpl.populateStartEnd()` to populate them. So we'd like to do it implicitly.

A) Introduce a constructor `BaseDescr(BasicDescrContext ctx)` where `BasicDescrContext` is a new interface to hold basic information like `startCharacter`. We can specify a super class of generated Context classes by an option `contextSuperClass=DRLParserRuleContext` (https://github.com/antlr/antlr4/blob/master/doc/options.md#contextsuperclass). So we can pass the context class to the constructor without making `drools-drl-ast` depending on antlr4. The PR is https://github.com/apache/incubator-kie-drools/pull/5826

B) Introduce a helper method like `DescrHelper.init(new PackageDescr(), ctx)`. This doesn't hide a Descr constructor, so is not much different from the current code (= calling `populateStartEnd()`). However, new contributors will understand how to initialize the Descr object and make sure common properties are set. It is this PR. https://github.com/apache/incubator-kie-drools/pull/5827

C) Introduce a factory method like `DescrHelper.createPackageDescr(ctx)` replacing the option B's `DescrHelper.init(new PackageDescr(), ctx)`. It can hide the Descr constructor. Instead, `DescrHelper` would have a bunch of similar factory methods. e.g.
```
pablic static PackageDescr createPackageDescr(DRLParser.CompilationUnitContext ctx) {
    return populateCommonProperties(new PackageDescr(), ctx);
}

pablic static RuleDescr createRuleDescr(DRLParser.RuledefContext ctx) {
    return populateCommonProperties(new RuleDescr(), ctx);
}
...
```
I haven't wrote this version yet, but it's easy to write it on top of option B.

---

Option A looks smarter. But actually, I had to modify many codes and also I still need `DescrHelper` for some special cases (root AndDescr, PatternBind). 

Option B and C may not be smart, but I think it's easier to understand/maintain. I'm leaning towards option C.

WDYT?

**Comment by gitgabrio** [comment]
Thanks @tkobayas , good stuff!

I've made a slight modification on top of you B) proposal that somehow mix B) and C)
1. a "Factory" class (with builder pattern) 
2. remove instantiation concern from `DescrHelper`

Reason for that:
1. use common and well-known design pattern
2. clearly define and separate concerns - the factory is responsible of instantiation, the Helper is responsible of manipulation - the two should be somehow independent
3. extensibility: if/ever, there will be need to add a "needed" parameter at instantiation time, the builder pattern allows easy extension (the init method would requires overrides or parameters explosion)


My proposal is [here](https://github.com/gitgabrio/drools/tree/incubator-kie-drools-5798-descr-props-DescrHelper)

@tkobayas @mariofusco @yurloc wdyt ?

**Comment by tkobayas** [comment]
Thank you, @gitgabrio ! I merged your suggestion and it's much better.

Please review this PR, thanks! @yurloc @mariofusco @gitgabrio

**Review by gitgabrio — APPROVED** [review]
Thanks @tkobayas LGTM!

**Comment by mariofusco** [comment]
@tkobayas I must admit that when I read the options you listed my first reaction was "Option A) looks smarter and way better, let's go for it". However now I also see that it would introduce some additional complexity and more importantly will require much more time that in this moment we could better use moving forward the parser development faster. This pull request, also thanks to @gitgabrio's improvements, is more pragmatic so it is ok for me.

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
