### PR TITLE
DROOLS-7267 DMN extend rule to catch non-normalized named elements

### PR DESCRIPTION
**Pull request by tarilabs**
**JIRA**:  https://issues.redhat.com/browse/DROOLS-7267

**referenced Pull Requests**: none

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

 - for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Review by tkobayas — APPROVED** [review]

**Comment by kie-ci3** [comment]
**(tests) - drools job** `#881` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/881/display/redirect

**Test results:**
- PASSED: 20939
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/881/testReport/org.kie.dmn.legacy.tests.validation.v1_1/ValidatorTest/testVARIABLE_LEADING_TRAILING_SPACES/">org.kie.dmn.legacy.tests.validation.v1_1.ValidatorTest.testVARIABLE_LEADING_TRAILING_SPACES</a></summary>
[Message [id=0, level=WARNING, path=null, line=37, column=-1<br/>   text=DMN: Name ' Greet Person' is not trimmed for element TDecision with id '_1f54fd51-6805-4280-b576-607450f85edd' (DMN id: _1f54fd51-6805-4280-b576-607450f85edd, The listed name is not a valid FEEL identifier) ]<br/>Message [id=0, level=WARNING, path=null, line=38, column=-1<br/>   text=DMN: Name ' Greet Person' is not trimmed for element TInformationItem with id '_dd662d27-7896-42cb-9d14-bd74203bdbec' (DMN id: _dd662d27-7896-42cb-9d14-bd74203bdbec, The listed name is not a valid FEEL identifier) ]] <br/>Expected size: 1 but was: 2 in:<br/>[Message [id=0, level=WARNING, path=null, line=37, column=-1<br/>   text=DMN: Name ' Greet Person' is not trimmed for element TDecision with id '_1f54fd51-6805-4280-b576-607450f85edd' (DMN id: _1f54fd51-6805-4280-b576-607450f85edd, The listed name is not a valid FEEL identifier) ],<br/>    Message [id=0, level=WARNING, path=null, line=38, column=-1<br/>   text=DMN: Name ' Greet Person' is not trimmed for element TInformationItem with id '_dd662d27-7896-42cb-9d14-bd74203bdbec' (DMN id: _dd662d27-7896-42cb-9d14-bd74203bdbec, The listed name is not a valid FEEL identifier) ]]
</details>

**Comment by tarilabs** [comment]
right https://github.com/kiegroup/drools/pull/4890#issuecomment-1362689702 it is the re-do of test in previous DMN serialization. amending.

**Comment by tarilabs** [comment]
Oplaplanner related failure seems wrt to OP doc, so unrelated

<details>

```

2022-12-22T11:20:32.1507329Z [INFO] OptaPlanner documentation .......................... FAILURE [01:54 min]
2022-12-22T11:20:32.1507630Z [INFO] OptaPlanner Javadoc ................................ SUCCESS [01:16 min]
2022-12-22T11:20:32.1507924Z [INFO] OptaPlanner distribution internal .................. SUCCESS [  8.036 s]
2022-12-22T11:20:32.1508321Z [INFO] ------------------------------------------------------------------------
2022-12-22T11:20:32.1508591Z [INFO] BUILD FAILURE
2022-12-22T11:20:32.1508946Z [INFO] ------------------------------------------------------------------------
2022-12-22T11:20:32.1509224Z [INFO] Total time:  06:38 min
2022-12-22T11:20:32.1509533Z [INFO] Finished at: 2022-12-22T11:20:32Z
2022-12-22T11:20:32.1509899Z [INFO] ------------------------------------------------------------------------
2022-12-22T11:20:32.1581809Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.4.2:single (package-generated-docs) on project optaplanner-docs: Failed to create assembly: Error creating assembly archive zip-with-generated-docs: Problem creating zip: Execution exception: Java heap space -> [Help 1]
2022-12-22T11:20:32.1583237Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.4.2:single (package-generated-docs) on project optaplanner-docs: Failed to create assembly: Error creating assembly archive zip-with-generated-docs: Problem creating zip: Execution exception
2022-12-22T11:20:32.1584069Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
2022-12-22T11:20:32.1584592Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
2022-12-22T11:20:32.1585096Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2022-12-22T11:20:32.1585589Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
2022-12-22T11:20:32.1586067Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
2022-12-22T11:20:32.1586629Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2022-12-22T11:20:32.1587260Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2022-12-22T11:20:32.1588092Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2022-12-22T11:20:32.1588729Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2022-12-22T11:20:32.1589265Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
2022-12-22T11:20:32.1589654Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2022-12-22T11:20:32.1590036Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2022-12-22T11:20:32.1590418Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
2022-12-22T11:20:32.1590781Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
2022-12-22T11:20:32.1591143Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
2022-12-22T11:20:32.1591545Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2022-12-22T11:20:32.1592034Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2022-12-22T11:20:32.1592571Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2022-12-22T11:20:32.1593019Z     at java.lang.reflect.Method.invoke (Method.java:566)
2022-12-22T11:20:32.1593457Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2022-12-22T11:20:32.1593958Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2022-12-22T11:20:32.1594462Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2022-12-22T11:20:32.1594955Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2022-12-22T11:20:32.1595715Z Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error creating assembly archive zip-with-generated-docs: Problem creating zip: Execution exception
2022-12-22T11:20:32.1596357Z     at org.apache.maven.plugins.assembly.mojos.AbstractAssemblyMojo.execute (AbstractAssemblyMojo.java:578)
2022-12-22T11:20:32.1596943Z     at org.apache.maven.plugins.assembly.mojos.SingleAssemblyMojo.execute (SingleAssemblyMojo.java:60)
2022-12-22T11:20:32.1597525Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
2022-12-22T11:20:32.1598074Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
2022-12-22T11:20:32.1598575Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
2022-12-22T11:20:32.1599063Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2022-12-22T11:20:32.1599536Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
2022-12-22T11:20:32.1599996Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
2022-12-22T11:20:32.1600551Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2022-12-22T11:20:32.1601181Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2022-12-22T11:20:32.1601862Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2022-12-22T11:20:32.1602489Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2022-12-22T11:20:32.1602934Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
2022-12-22T11:20:32.1603321Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2022-12-22T11:20:32.1603701Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2022-12-22T11:20:32.1604068Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
2022-12-22T11:20:32.1604421Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
2022-12-22T11:20:32.1604767Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
2022-12-22T11:20:32.1605246Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2022-12-22T11:20:32.1605729Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2022-12-22T11:20:32.1606305Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2022-12-22T11:20:32.1606743Z     at java.lang.reflect.Method.invoke (Method.java:566)
2022-12-22T11:20:32.1607186Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2022-12-22T11:20:32.1607685Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2022-12-22T11:20:32.1608188Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2022-12-22T11:20:32.1608677Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2022-12-22T11:20:32.1609430Z Caused by: org.apache.maven.plugins.assembly.archive.ArchiveCreationException: Error creating assembly archive zip-with-generated-docs: Problem creating zip: Execution exception
2022-12-22T11:20:32.1610159Z     at org.apache.maven.plugins.assembly.archive.DefaultAssemblyArchiver.createArchive (DefaultAssemblyArchiver.java:181)
2022-12-22T11:20:32.1610800Z     at org.apache.maven.plugins.assembly.mojos.AbstractAssemblyMojo.execute (AbstractAssemblyMojo.java:522)
2022-12-22T11:20:32.1611386Z     at org.apache.maven.plugins.assembly.mojos.SingleAssemblyMojo.execute (SingleAssemblyMojo.java:60)
2022-12-22T11:20:32.1612085Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
2022-12-22T11:20:32.1615573Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
2022-12-22T11:20:32.1617020Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
2022-12-22T11:20:32.1617521Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2022-12-22T11:20:32.1666026Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
2022-12-22T11:20:32.1666534Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
2022-12-22T11:20:32.1667112Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2022-12-22T11:20:32.1667751Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2022-12-22T11:20:32.1668443Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2022-12-22T11:20:32.1669083Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2022-12-22T11:20:32.1669541Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
2022-12-22T11:20:32.1669970Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2022-12-22T11:20:32.1670360Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2022-12-22T11:20:32.1670730Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
2022-12-22T11:20:32.1671092Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
2022-12-22T11:20:32.1671442Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
2022-12-22T11:20:32.1671843Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2022-12-22T11:20:32.1672317Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2022-12-22T11:20:32.1672856Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2022-12-22T11:20:32.1673290Z     at java.lang.reflect.Method.invoke (Method.java:566)
2022-12-22T11:20:32.1673726Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2022-12-22T11:20:32.1674238Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2022-12-22T11:20:32.1674903Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2022-12-22T11:20:32.1680616Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2022-12-22T11:20:32.1681238Z Caused by: org.codehaus.plexus.archiver.ArchiverException: Problem creating zip: Execution exception
2022-12-22T11:20:32.1681809Z     at org.codehaus.plexus.archiver.AbstractArchiver.createArchive (AbstractArchiver.java:1045)
2022-12-22T11:20:32.1682464Z     at org.apache.maven.plugins.assembly.archive.archiver.AssemblyProxyArchiver.createArchive (AssemblyProxyArchiver.java:441)
2022-12-22T11:20:32.1683189Z     at org.apache.maven.plugins.assembly.archive.DefaultAssemblyArchiver.createArchive (DefaultAssemblyArchiver.java:176)
2022-12-22T11:20:32.1683836Z     at org.apache.maven.plugins.assembly.mojos.AbstractAssemblyMojo.execute (AbstractAssemblyMojo.java:522)
2022-12-22T11:20:32.1684421Z     at org.apache.maven.plugins.assembly.mojos.SingleAssemblyMojo.execute (SingleAssemblyMojo.java:60)
2022-12-22T11:20:32.1685014Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
2022-12-22T11:20:32.1685560Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
2022-12-22T11:20:32.1686052Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
2022-12-22T11:20:32.1686534Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2022-12-22T11:20:32.1687009Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
2022-12-22T11:20:32.1687474Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
2022-12-22T11:20:32.1688032Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2022-12-22T11:20:32.1688654Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2022-12-22T11:20:32.1689337Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2022-12-22T11:20:32.1689968Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2022-12-22T11:20:32.1690414Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
2022-12-22T11:20:32.1690800Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2022-12-22T11:20:32.1691180Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2022-12-22T11:20:32.1691547Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
2022-12-22T11:20:32.1692063Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
2022-12-22T11:20:32.1692424Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
2022-12-22T11:20:32.1692817Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2022-12-22T11:20:32.1693305Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2022-12-22T11:20:32.1693850Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2022-12-22T11:20:32.1694295Z     at java.lang.reflect.Method.invoke (Method.java:566)
2022-12-22T11:20:32.1694731Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2022-12-22T11:20:32.1695230Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2022-12-22T11:20:32.1695722Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2022-12-22T11:20:32.1696216Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2022-12-22T11:20:32.1696599Z Caused by: java.io.IOException: Execution exception
2022-12-22T11:20:32.1697030Z     at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.close (AbstractZipArchiver.java:798)
2022-12-22T11:20:32.1697561Z     at org.codehaus.plexus.archiver.AbstractArchiver.createArchive (AbstractArchiver.java:1032)
2022-12-22T11:20:32.1698272Z     at org.apache.maven.plugins.assembly.archive.archiver.AssemblyProxyArchiver.createArchive (AssemblyProxyArchiver.java:441)
2022-12-22T11:20:32.1699039Z     at org.apache.maven.plugins.assembly.archive.DefaultAssemblyArchiver.createArchive (DefaultAssemblyArchiver.java:176)
2022-12-22T11:20:32.1699683Z     at org.apache.maven.plugins.assembly.mojos.AbstractAssemblyMojo.execute (AbstractAssemblyMojo.java:522)
2022-12-22T11:20:32.1700269Z     at org.apache.maven.plugins.assembly.mojos.SingleAssemblyMojo.execute (SingleAssemblyMojo.java:60)
2022-12-22T11:20:32.1700844Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
2022-12-22T11:20:32.1701383Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
2022-12-22T11:20:32.1701887Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
2022-12-22T11:20:32.1702384Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2022-12-22T11:20:32.1702869Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
2022-12-22T11:20:32.1703330Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
2022-12-22T11:20:32.1703893Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2022-12-22T11:20:32.1704521Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2022-12-22T11:20:32.1705197Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2022-12-22T11:20:32.1705825Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2022-12-22T11:20:32.1706279Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
2022-12-22T11:20:32.1706676Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2022-12-22T11:20:32.1707047Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2022-12-22T11:20:32.1707420Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
2022-12-22T11:20:32.1707775Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
2022-12-22T11:20:32.1708129Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
2022-12-22T11:20:32.1708532Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2022-12-22T11:20:32.1709015Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2022-12-22T11:20:32.1709548Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2022-12-22T11:20:32.1709985Z     at java.lang.reflect.Method.invoke (Method.java:566)
2022-12-22T11:20:32.1710411Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2022-12-22T11:20:32.1710918Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2022-12-22T11:20:32.1711422Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2022-12-22T11:20:32.1711920Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2022-12-22T11:20:32.1712307Z Caused by: java.lang.OutOfMemoryError: Java heap space
2022-12-22T11:20:32.1712776Z     at org.codehaus.plexus.archiver.zip.ByteArrayOutputStream.needNewBuffer (ByteArrayOutputStream.java:153)
2022-12-22T11:20:32.1713357Z     at org.codehaus.plexus.archiver.zip.ByteArrayOutputStream.write (ByteArrayOutputStream.java:192)
2022-12-22T11:20:32.1713907Z     at org.apache.commons.io.output.ThresholdingOutputStream.write (ThresholdingOutputStream.java:232)
2022-12-22T11:20:32.1714514Z     at org.codehaus.plexus.archiver.zip.DeferredScatterOutputStream.writeOut (DeferredScatterOutputStream.java:44)
2022-12-22T11:20:32.1715234Z     at org.apache.commons.compress.archivers.zip.StreamCompressor$ScatterGatherBackingStoreCompressor.writeOut (StreamCompressor.java:291)
2022-12-22T11:20:32.1715889Z     at org.apache.commons.compress.archivers.zip.StreamCompressor.writeCounted (StreamCompressor.java:273)
2022-12-22T11:20:32.1716512Z     at org.apache.commons.compress.archivers.zip.StreamCompressor.deflate (StreamCompressor.java:264)
2022-12-22T11:20:32.1717136Z     at org.apache.commons.compress.archivers.zip.StreamCompressor.deflateUntilInputIsNeeded (StreamCompressor.java:257)
2022-12-22T11:20:32.1717815Z     at org.apache.commons.compress.archivers.zip.StreamCompressor.writeDeflated (StreamCompressor.java:238)
2022-12-22T11:20:32.1718392Z     at org.apache.commons.compress.archivers.zip.StreamCompressor.write (StreamCompressor.java:205)
2022-12-22T11:20:32.1718946Z     at org.apache.commons.compress.archivers.zip.StreamCompressor.deflate (StreamCompressor.java:184)
2022-12-22T11:20:32.1719578Z     at org.apache.commons.compress.archivers.zip.ScatterZipOutputStream.addArchiveEntry (ScatterZipOutputStream.java:100)
2022-12-22T11:20:32.1720308Z     at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator.lambda$createCallable$2 (ParallelScatterZipCreator.java:253)
2022-12-22T11:20:32.1720979Z     at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator$$Lambda$5740/0x0000000100ccf040.call (Unknown Source)
2022-12-22T11:20:32.1721452Z     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
2022-12-22T11:20:32.1721868Z     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
2022-12-22T11:20:32.1722334Z     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
2022-12-22T11:20:32.1722690Z     at java.lang.Thread.run (Thread.java:829)
```

</details>

@triceo is your team aware? ^ /cc @radtriste

**Comment by triceo** [comment]
We recently fixed this on OP side; it happened only occasionally. (Maven needs more heap than it is getting by default.) I didn't realize downstream builds run our documenation too.

Two options I see here:

1. Speed up downstream build by skipping these extra bits. (AFAIK there is no way how Drools could break our documentation, yet the docs could take minutes.)
2. Fix `MAVEN_OPTS` for all KIE projects to always increase `Xmx`.

WDYT @tarilabs @radtriste ?

**Comment by tarilabs** [comment]
Thanks @triceo for https://github.com/kiegroup/drools/pull/4890#issuecomment-1362742773 in general I'd go that downstream build of OP skip the doc module, but I believe @mariofusco to make official call for it.
/cc @danielezonca

**Comment by mariofusco** [comment]
:+1: for OP to skip the doc module, the shorter we could make our CI execution (without losing features or confidence) the better it is.

**Comment by tarilabs** [comment]
@radtriste I believe this [comment](https://github.com/kiegroup/drools/pull/4890#issuecomment-1362984281) didn't tag you but in fact there is an action point for you, please? Can you kindly implement this for the GHAs when suitable? I really don't believe is urgent, and could be scheduled when feasible.

**Review by danielezonca — APPROVED** [review]

**Comment by tarilabs** [comment]
proceeding to merge ref https://github.com/kiegroup/drools/pull/4890#issuecomment-1362731460

**Comment by radtriste** [comment]
@triceo @tarilabs you were talking about this job right ? https://github.com/kiegroup/drools/actions/runs/3757145690/jobs/6384229998

**Comment by radtriste** [comment]
for now the `-Dfull` is hardcoded into the pull request config: https://github.com/kiegroup/optaplanner/blob/main/.ci/pull-request-config-rhbop.yaml#L29

**Comment by radtriste** [comment]
we should maybe extract and configure each which want to add it to the `BUILD_MVN_OPTS_CURRENT` env variable

**Comment by radtriste** [comment]
do you really need the `-Dfull` for productized GHA checks ?
would that not interfere with `-Dproductized` ?

**Pull request merged**
