### PR TITLE
[DROOLS-1326] add indexed key in tuple hashtable's buckets

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Being tested by turtle tests here: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/optaplanner-turtleTests-drools1326/2/ (thanks to Jiri Locker)

**Comment by yurloc** [comment]
Please **do not merge** at this moment. This change causes frequent score corruption in OptaPlanner examples. This is currently under investigation.

**Comment by yurloc** [comment]
We came to the conclusion that the second commit breaks some stuff and needs additional work. Reproducer attached to https://issues.jboss.org/browse/DROOLS-1326 as `Drools1326Test.java`

@mariofusco please update the PR by reverting the second commit so that I can re-run turtle tests.

**Comment by mariofusco** [comment]
Merged by https://github.com/droolsjbpm/drools/commit/d4324bc97

**Pull request closed without merging**
