### PR TITLE
BXMSPROD-685: Weld 3.1.5.SP1 upgrade and adding exclusions due duplic…

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.redhat.com/browse/BXMSPROD-685

Parent PR kiegroup/droolsjbpm-build-bootstrap#1320

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins do cdb

**Comment by mareknovotny** [comment]
Jenkins do cdb

**Comment by mareknovotny** [comment]
Jenkins do cdb

**Comment by mareknovotny** [comment]
Jenkins do cdb

**Review by yesamer — APPROVED** [review]

**Pull request merged**
