### PR TITLE
GUVNOR-2933: Guvnor ALA integration

### PR DESCRIPTION
**Pull request by wmedvede**
- adds helper classes for consumming the maven build logs

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @porcelli , this PR is for the maven build integration we have been chatting about.
Would you mind review.

Thanks.

depends on:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/420

**Comment by porcelli** [comment]
@mariofusco @etirelli guys. are you ok with this PR? we need this for maven based build

**Comment by etirelli** [comment]
@porcelli I am not familiar with the code that will use this, but it looks fine to me...

**Review by porcelli — APPROVED** [review]

**Comment by mariofusco** [comment]
+1

**Comment by porcelli** [comment]
@wmedvede this is not needed anymore, with the work done by @desmax74

**Pull request closed without merging**
