### PR TITLE
[DO-NOT-MERGE] [DROOLS-6534] DowncastTest failure with github action build chain wit…

### PR DESCRIPTION
**Pull request by tkobayas**
…h JDK 11

- DO-NOT-MERGE : just debug log

**Thank you for submitting this pull request**

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6534

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
In Build Chain ubuntu-latest, 11, confirmed the error with debug logs:
```
2021-08-02T07:36:24.6424207Z 07:36:24.641 [main] WARN  o.drools.modelcompiler.DowncastTest.testDowncast:23 - java.vendor : Azul Systems, Inc.^M
2021-08-02T07:36:24.6432358Z 07:36:24.642 [main] WARN  o.drools.modelcompiler.DowncastTest.testDowncast:24 - java.version : 11.0.12^M
2021-08-02T07:36:24.6439521Z 07:36:24.643 [main] WARN  o.drools.modelcompiler.DowncastTest.testDowncast:25 - java.vm.version : 11.0.12+7-LTS^M
2021-08-02T07:36:24.6446619Z 07:36:24.644 [main] WARN  o.drools.modelcompiler.DowncastTest.testDowncast:26 - os.version : 5.8.0-1039-azure^M
2021-08-02T07:36:24.6453410Z 07:36:24.644 [main] WARN  o.drools.modelcompiler.DowncastTest.testDowncast:27 - java.class.version : 55.0^M
2021-08-02T07:36:24.6460435Z 07:36:24.645 [main] WARN  o.drools.modelcompiler.DowncastTest.testDowncast:28 - java.runtime.version : 11.0.12+7-LTS^M
2021-08-02T07:36:24.6675840Z 07:36:24.666 [main] WARN  o.d.m.b.g.e.ExpressionTyper.parseMethodCallExpr:824 - parseMethodCallExpr : m = public java.math.BigDecimal java.math.BigDecimal.subtract(java.math.BigDecimal)^M
2021-08-02T07:36:24.6689786Z 07:36:24.667 [main] WARN  o.d.m.b.g.e.ExpressionTyper.promoteBigDecimalParameters:868 - argumentType : class java.math.BigDecimal, actualArgumentType = class java.math.BigDecimal, argumentExpression((CashProduct) $cp.getProduct()).getCashValue()^M
2021-08-02T07:36:24.6702610Z 07:36:24.669 [main] WARN  o.d.m.b.g.e.ExpressionTyper.parseMethodCallExpr:824 - parseMethodCallExpr : m = public java.math.BigDecimal java.math.BigDecimal.divide(java.math.BigDecimal)^M
2021-08-02T07:36:24.6714593Z 07:36:24.670 [main] WARN  o.d.m.b.g.e.ExpressionTyper.promoteBigDecimalParameters:868 - argumentType : class java.math.BigDecimal, actualArgumentType = class java.math.BigDecimal, argumentExpression((CashProduct) $cp.getProduct()).getCashValue()^M
2021-08-02T07:36:24.6724359Z 07:36:24.671 [main] WARN  o.d.m.b.g.e.ExpressionTyper.parseMethodCallExpr:824 - parseMethodCallExpr : m = public static long java.lang.Math.abs(long)^M
2021-08-02T07:36:24.6738653Z 07:36:24.672 [main] WARN  o.d.m.b.g.e.ExpressionTyper.promoteBigDecimalParameters:868 - argumentType : class java.math.BigDecimal, actualArgumentType = long, argumentExpression((LoanProduct) _this.getProduct()).getLoanValue().subtract(((CashProduct) $cp.getProduct()).getCashValue()).divide(((CashProduct) $cp.getProduct()).getCashValue())^M
2021-08-02T07:36:24.6747090Z 07:36:24.674 [main] WARN  o.d.m.u.BigDecimalArgumentCoercion.coercedArgument:44 - coercedArgument : no match^M
2021-08-02T07:36:24.7281738Z [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.112 s <<< FAILURE! - in org.drools.modelcompiler.DowncastTest^M
2021-08-02T07:36:24.7319640Z [ERROR] testDowncast[PATTERN_DSL](org.drools.modelcompiler.DowncastTest)  Time elapsed: 0.079 s  <<< FAILURE!^M
2021-08-02T07:36:24.7328155Z java.lang.AssertionError: ^M
2021-08-02T07:36:24.7405868Z [Message [id=1, level=ERROR, path=src/main/java/defaultpkg/P06/LambdaPredicate0688A1DD5281632D522D3E1A74A74155.java, line=24, column=1141^M
2021-08-02T07:36:24.7408469Z    text=The method abs(int) in the type Math is not applicable for the arguments (BigDecimal)], Message [id=2, level=ERROR, path=src/main/java/defaultpkg/P06/LambdaPredicate0688A1DD5281632D522D3E1A74A74155.java, line=0, column=0^M
2021-08-02T07:36:24.7410775Z    text=Java source of src/main/java/defaultpkg/P06/LambdaPredicate0688A1DD5281632D522D3E1A74A74155.java in error:^M
```
It means `MethodUtils.findMethod()` picks up `java.lang.Math.abs(long)` as the best candidate and it was missed in `BigDecimalArgumentCoercion.coercedArgument()`. The order of elements in a returned array by `clazz.getMethods()` is up to jvm implementation.

**Comment by baldimir** [comment]
Hi, this PR is now more than a year old. Is it still relevant please?

**Comment by kie-ci3** [comment]
**(tests) - drools job** `#443` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/443/display/redirect

**Test results:**
- PASSED: 20570
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/443/testReport/org.drools.model.codegen.execmodel/ComplexRulesTest/testConstraintWithTernaryOperator[PATTERN_DSL]/">org.drools.model.codegen.execmodel.ComplexRulesTest.testConstraintWithTernaryOperator[PATTERN_DSL]</a></summary>
class com.github.javaparser.printer.DefaultPrettyPrinterVisitor cannot be cast to class org.drools.mvel.parser.ast.visitor.DrlVoidVisitor (com.github.javaparser.printer.DefaultPrettyPrinterVisitor and org.drools.mvel.parser.ast.visitor.DrlVoidVisitor are in unnamed module of loader 'app')
</details>

**Comment by tkobayas** [comment]
This PR can close. Thanks!

**Pull request closed without merging**
