### PR TITLE
[DROOLS-5809] remove Janino declaration

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]

**Comment by mariofusco** [comment]
Jenkins retest this

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
Jenkins retest this

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
jenkins retest this

**Pull request merged**
