### PR TITLE
Backport MSF changes to fix IndexOutOfBoundsException on "" for trim path

### PR DESCRIPTION
**Pull request by ge0ffrey**
I needed to backport all 3 commits.

@mariofusco This includes the first commit which you originally didn't desire to have on 6.4.x too...

### CODE REVIEW

**Comment by psiroky** [comment]
Build failed, because I've used Java 7/8 API in the commit: `java.nio.charset.StandardCharsets.UTF_8` as I thought we won't need to backport this to 6.4.x. We will need to use IoUtils.UTF_8 (or what is it called).

**Comment by ge0ffrey** [comment]
jenkins please retest this

It failed with:
[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.13:check (check-java-1.6-compatibility) on project drools-compiler: Signature errors found. Verify them and ignore them with the proper annotation if needed. -> [Help 1]

**Comment by ge0ffrey** [comment]
Ok, I 'll fix that and update the PR. I had build it locally with JDK 8, instead of 7.

**Comment by psiroky** [comment]
The error comes from animal-sniffer, so it should fail even on JDK 8. Could you please double check that? (make sure to run with -Dfull). If it does not fail, we need to fix it.

**Comment by ge0ffrey** [comment]
@psiroky Just tried it again: it definitely does fail without -Dfull. And I don't do -Dfull when committing as it takes too long...

**Comment by psiroky** [comment]
You mean it does _not_ fail without -Dfull (seems to be the case when looking at -kie-parent-metadata)? In any any case, that's why we have these PR jobs...

**Comment by ge0ffrey** [comment]
yes indeed, success without -Dfull. This PR jobs are great indeed!

2016-02-15 19:01 GMT+01:00 Petr Široký notifications@github.com:

> You mean it does _not_ fail without -Dfull (seems to be the case when
> looking at -kie-parent-metadata)? In any any case, that's why we have these
> PR jobs...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/droolsjbpm/drools/pull/648#issuecomment-184327271.

## 

With kind regards / Met vriendelijke groeten,
Geoffrey De Smet

**Pull request merged**
