### PR TITLE
[DROOLS-6781] keystore file opened ~4 times per request/process

### PR DESCRIPTION
**Pull request by gillyobeast**
**Thank you for submitting this pull request**
targetting 7.x for now as that's what jBPM uses from what I can tell - LMK if I need to target main.

**JIRA**:
[DROOLS-6781](https://issues.redhat.com/browse/DROOLS-6781)

**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-integration/pull/2664

This patch attempts to solve an issue we've seen with jBPM 7.44.0.Final where a keystore file is kept open many times by a single request/process, taking up FDs on our jBPM servers.

I've raised this Draft PR to start a discussion on the best way to manage this - my approach here is pretty naïve, just making KeyStoreHelper static in PersisterHelper and KieModuleCacheHelper. I also applied a similar change in KeyStoreHelperUtil in https://github.com/kiegroup/droolsjbpm-integration, see https://github.com/kiegroup/droolsjbpm-integration/pull/2664.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by triceo** [comment]
ok to test

**Comment by gillyobeast** [comment]
the class that opens the .jceks file is KeyStoreHelper , which does so in its constructor. the issue is that several classes (the targets of my PRs) instantiate this KeyStoreHelper every time they need it, so the file is opened every time it’s needed.

so my approach here is just to make KeyStoreHelper a static member of classes that use it, and to use lazy instantiation. i’ve given it a cursory check and i think it should be thread-safe to do it this way, as KeyStoreHelper’s public methods are free from side effects, but i don’t really have the experience there to say for sure.

there may be a better solution that i haven’t seen but this got us going :slightly_smiling_face:

let me know what you think!

**Review by mariofusco — CHANGES_REQUESTED** [review]
I see what you did there, and caching and reusing the `KeyStoreHelper` makes sense. What I don't understand is why do you need an instance for each class that needs it instead of making the `KeyStoreHelper` itself a singleton and using the same singleton everywhere. Do you think you could change this pull request accordingly? Am I missing something?

**Comment by gillyobeast** [comment]
thanks @mariofusco, that's a fair comment. I simply hadn't noticed that this case was suitable for a singleton, I'll see if I can get the PRs updated shortly. :)

**Comment by mariofusco** [comment]
@gillyobeast I just attempted to make this change against our main branch here https://github.com/kiegroup/drools/pull/4137

**Comment by gillyobeast** [comment]
that'll do for me, as long as it makes it back to 7.x too :) it'll require a change in droolsjbpm-integration/kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/KeyStoreHelperUtil.java too, per my [other PR](https://github.com/kiegroup/droolsjbpm-integration/pull/2664)

**Comment by mariofusco** [comment]
@gillyobeast great thanks. I'll close your PRs then, merge mine when approved and also backport it to 7.x. Thanks again for having noticed and reported this.

**Pull request closed without merging**
