### PR TITLE
DROOLS-5580 Drools repo-wide .gitignore update

### PR DESCRIPTION
**Pull request by tarilabs**
In my local clone which I've been using for the past year I get this when double-checking the change is okay:
```
$ find . \( -name ".*" ! -name ".gitignore" ! -name ".project" ! -name ".classpath" ! -name ".settings" ! -name ".DS_Store" \)
.
./.github
./kie-ci/.factorypath
./kie-dmn/kie-dmn-tck/.vscode
./kie-dmn/.vscode
./.git
./drools-examples-api/kiecontainer-from-kierepo/.factorypath
```

while on a fresh clone is even cleaner:
```
$ find . \( -name ".*" ! -name ".gitignore" ! -name ".project" ! -name ".classpath" ! -name ".settings" ! -name ".DS_Store" \)
.
./.github
./.git
```

So this _also_ puts the `.github` directory under source control.

Checked there is no "local" directory names coming from java packages or the likes.
```
$ find . \( -name "local" ! -name ".gitignore" ! -name ".project" ! -name ".classpath" ! -name ".settings" ! -name ".DS_Store" \)

```

So I would conclude this change seems to respect the current setup of the Drools repo, and it also improves it by putting the `/.github` directory under source control, which is something that was discovered as part of this exercise.

### CODE REVIEW

**Comment by mariofusco** [comment]
@tarilabs could we remove all the .gitignore files at modules level with this change?

**Comment by tarilabs** [comment]
At least all which were similar. I can do it as part of this PR, if we agree THIS version is the gold standard

**Comment by tarilabs** [comment]
> @tarilabs could we remove all the .gitignore files at modules level with this change?

@mariofusco it is done for all except `kie-pmml/.gitignore` which has custom settings and I left it unchanged.

**Review by mareknovotny — APPROVED** [review]

**Comment by lucamolteni** [comment]
thanks @tarilabs

**Pull request merged**
