### PR TITLE
Remove drools-workbench-models-datamodel-api unused dependencies

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
@mariofusco may I ask you for review?

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed tests:
`
org.jbpm.test.container.test.TransactionsTest.testTimer
org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsWithNamedQueryTest 
org.kie.server.integrationtests.dmn.DMNPMMLIntegrationTest.org.kie.server.integrationtests.dmn.DMNPMMLIntegrationTest
`

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed test:
-  org.kie.server.integrationtests.controller.KieControllerCrashIntegrationTest.testCrashAfterRegistered[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:37158/kie-server-services/services/rest/server'}]
- org.kie.server.integrationtests.controller.KieControllerCrashIntegrationTest.testCrashAfterRegistered[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:37158/kie-server-services/services/rest/server'}]
- org.jbpm.executor.impl.wih.AsyncContinuationSupportTest.testAsyncModeWithParallelGateway

**Comment by jomarko** [comment]
@kiegroup/gatekeepers the fails seems to be random, could we please merge?

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
