### PR TITLE
[DROOLS-4561] DMN introspect PMML for output types

### PR DESCRIPTION
**Pull request by tkobayas**
First draft. Will discuss with Matteo.

### CODE REVIEW

**Comment by tarilabs** [comment]
@tkobayas can you kindly rebase on top of `master` head, please?
I believe github shows code changes beyond your suggested changes.. thx!

**Comment by tkobayas** [comment]
Sure, rebased :)

Feel free to let me know if there is a suspicious diff like "changes beyond your suggested changes".

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Review by tarilabs — APPROVED** [review]
The FDB will demonstrate test execution for `kie-dmn-jpmml` as well, but already checked locally is good to merge, thanks!

**Review by tarilabs — APPROVED** [review]

**Pull request merged**
