### PR TITLE
[RHBRMS-3027] avoid ProjectClassLoader creation when creating a new K…

### PR DESCRIPTION
**Pull request by mariofusco**
…ieSession

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Review by baldimir — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Pull request merged**
