### PR TITLE
[DROOLS-6063] drools-decisiontables takes "100%" as String even in Pe…

### PR DESCRIPTION
**Pull request by tkobayas**
…rcent format cell

- Introduced option 'IgnoreNumericFormat'

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6063

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Hi @mariofusco  please review.

As written in https://issues.redhat.com/browse/DROOLS-6063

Currently, when you use `Percent` format, the value `1` becomes `100%` which is not good when a user wants to interpolate the value to `BigDecimal` (or other numeric types). It also has an inconsistent behavior that the value `0.5` becomes `0.5` (while it displays `50%` in Excel). `Currency` format (and any Numeric+special formatting) also has the similar problem.

This PR introduces a new option `IgnoreNumericFormat` (true|false). Default is 'false' because there may be users who rely on the current behavior.

When `IgnoreNumericFormat` = true, we no longer use cell's formatter and pass the numeric value as is. But there is one exception. If the cell format is `GENERAL`, the formatter would trim its fractional portion (`42.0` becomes `42`) where you use integer values (I think this is always useful).

**Comment by tkobayas** [comment]
CDB error is not related to this PR:
```
[2021-04-10T15:33:11.892Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project kie-server-services-jbpm: Compilation failure
[2021-04-10T15:33:11.892Z] [ERROR] /home/jenkins/workspace/KIE/master/compile/drools-master.compile/bc/kiegroup_droolsjbpm_integration/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/QueryDataServiceBaseTest.java:[59,53] no suitable constructor found for UserTaskInstanceWithPotOwnerDesc(java.lang.String,java.lang.String,java.util.Date,java.util.Date,java.lang.Long,java.lang.String,int,java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
[2021-04-10T15:33:11.892Z] [ERROR]     constructor org.jbpm.kie.services.impl.model.UserTaskInstanceWithPotOwnerDesc.UserTaskInstanceWithPotOwnerDesc(java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.Date,java.lang.String,java.util.Date,java.util.Date,java.lang.String,java.lang.Integer,java.lang.String,java.lang.Long,java.lang.String,java.lang.String,java.lang.String) is not applicable
[2021-04-10T15:33:11.892Z] [ERROR]       (actual and formal argument lists differ in length)
[2021-04-10T15:33:11.893Z] [ERROR]     constructor org.jbpm.kie.services.impl.model.UserTaskInstanceWithPotOwnerDesc.UserTaskInstanceWithPotOwnerDesc(java.lang.String,java.lang.String,java.util.Date,java.util.Date,java.lang.Long,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) is not applicable
[2021-04-10T15:33:11.893Z] [ERROR]       (actual and formal argument lists differ in length)
```

**Review by mariofusco — APPROVED** [review]

**Review by hellowdan — APPROVED** [review]

**Pull request merged**
