### PR TITLE
DROOLS-4164 DMN invoke PMML noname NN (and DROOLS-4157 )

### PR DESCRIPTION
**Pull request by tarilabs**
@etirelli @baldimir @jiripetrlik

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
This PR breaks `kie-wb-common-dmn-backend` branch `DROOLS-4042` but we can handle it afterwards.

Out of interest what does `targetFieldNames` represent!?! Do they need exposing in the UI!?!

**Comment by jomarko** [comment]
@tarilabs hi, just one question, in the logic we touched now stores the `pmmlModel` and `pmmlDocument` however tests do not assert any similar variable (from my point of view, maybe missing something) is it correct?

**Comment by tarilabs** [comment]
@jomarko in the logic both `pmmlDocument` and `pmmlModel` are only local variables to the method.
https://github.com/kiegroup/drools/pull/2384/files#diff-a3d2eba0ee36c9e5308a593336e75bf4R463
1. I can't directly assert on them
2. nor I do need to really assert on them, given those are just there as representing the content of the DMN model, and the actual point of this method is to locate the PMML model to invoke

I am not understanding your question.

**Comment by tarilabs** [comment]
I still don't see the need of the full downstream given all changes are of `kie-dmn-core`, moreover the full downstream is failing on tests which are nowhere near my area of expertise
```
Test Result (7 failures / +3)
org.jbpm.executor.impl.wih.AsyncContinuationSupportTest.testAsyncModeWithParallelGateway
org.kie.workbench.common.screens.server.management.backend.EmbeddedControllerIT.org.kie.workbench.common.screens.server.management.backend.EmbeddedControllerIT
org.kie.workbench.common.screens.server.management.backend.StandaloneControllerIT.org.kie.workbench.common.screens.server.management.backend.StandaloneControllerIT
org.kie.workbench.common.screens.server.management.backend.StandaloneControllerMultinodeIT.org.kie.workbench.common.screens.server.management.backend.StandaloneControllerMultinodeIT
org.kie.wb.selenium.ui.LoginIntegrationTest.loginAndLogout
org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromCustomRepository
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective
```
from my pov, unrelated.

@baldimir kindly awaiting for your review, and if nothing left then I will propose to proceed to merge. Thanks.

**Review by baldimir — APPROVED** [review]

**Pull request merged**
