### PR TITLE
[PLANNER-488] remove deleted RightTuples from the RightTupleMemory before processing the updates

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
+1 I've locally proven that this PR also fixes the nurse rostering variant of PLANNER-488

**Comment by ge0ffrey** [comment]
-1 This PR fails CoachShuttleGatheringPerformanceTest and VehicleRoutingPerfTest

**Comment by ge0ffrey** [comment]
This introduces regression, but Mario's new PR fixes the issue without introducing regressions:
 https://github.com/droolsjbpm/drools/pull/767

**Comment by mariofusco** [comment]
DO NOT MERGE. This makes a few optaplanner tests to fail and requires more investigation. Temporarily replaced by https://github.com/droolsjbpm/drools/pull/767

**Comment by mariofusco** [comment]
Merged by https://github.com/droolsjbpm/drools/commit/11c04ff34

**Pull request closed without merging**
