### PR TITLE
Fixing selenium integration tests in `dmn-feel-gwt-showcase`

### PR DESCRIPTION
**Pull request by yesamer**
**Thank you for submitting this pull request**

**NOTE!:** Double check the target branch for this PR.
The default is `main` so it will target Drools 8 / Kogito / Optaplanner 8.
If this PR is not strictly related to drools and kogito project in `drools.git`, it should probably target `7.x`as a branch

**Ports** If a forward-port or a backport is needed, paste the forward port PR here

[link](https://www.example.com)

**JIRA**: _(please edit the JIRA link if it exists)_

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] mandrel</b>
</details>

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#532` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/532/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] echo<br/>[2022-05-06T08:45:23.578Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-05-06T08:45:23.861Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-05-06T08:45:23.862Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.21.x/nightly/kogito-quarkus-2.8_ws-cleanup_1651826707615/kogito-apps/data-index/data-index-service/data-index-service-postgresql/target/jib/org/dmg/pmml/mining/VariableWeight.class’: No such file or directory<br/>[2022-05-06T08:45:23.862Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.21.x/nightly/kogito-quarkus-2.8_ws-cleanup_1651826707615/kogito-apps/data-index/data-index-service/data-index-service-postgresql/target/jib/org/dmg/pmml/mining/Segmentation$MissingPredictionTreatment.class’: No such file or directory<br/>[2022-05-06T08:45:23.862Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.21.x/nightly/kogito-quarkus-2.8_ws-cleanup_1651826707615/kogito-apps/data-index/data-index-service/data-index-service-postgresql/target/jib/org/dmg/pmml/mining/MiningModel.class’: No such file or directory<br/>[2022-05-06T08:45:23.862Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.21.x/nightly/kogito-quarkus-2.8_ws-cleanup_1651826707615/kogito-apps/data-index/data-index-service/data-index-service-postgresql/target/jib/org/dmg/pmml/mining/Segment.class’: No such file or directory<br/>[2022-05-06T08:45:23.862Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/1.21.x/nightly/kogito-quarkus-2.8_ws-cleanup_1651826707615/kogito-apps/data-index/data-index-service/data-index-service-postgresql/target/jib/org/dmg/pmml/mining/PMMLAttributes.class’: No such file or directory<br/>[2022-05-06T08:45:24.788Z] 13G	/home/jenkins/workspace/KIE/kogito/1.21.x<br/>[2022-05-06T08:45:24.788Z] 2.3M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-05-06T08:45:24.788Z] 13G	/home/jenkins/workspace/KIE/kogito<br/>[2022-05-06T08:45:24.788Z] 13G	/home/jenkins/workspace/KIE<br/>[2022-05-06T08:45:24.788Z] 13G	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-05-06T08:45:25.718Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/532/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by danielezonca** [comment]
@yesamer 
Still failing with
`kiegroup_drools/drools/kie-dmn/kie-dmn-feel-gwt-showcase/src/test/java/org/kie/dmn/feel/client/showcase/FEELShowcaseIT.java:49 | io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.31.0`

**Comment by yesamer** [comment]
> @yesamer Still failing with `kiegroup_drools/drools/kie-dmn/kie-dmn-feel-gwt-showcase/src/test/java/org/kie/dmn/feel/client/showcase/FEELShowcaseIT.java:49 | io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.31.0`

Yep, I noticed that. Locally this issue is not present (even with the current version in `main`). 
Investigation in progress....

**Comment by yesamer** [comment]
@danielezonca @mariofusco It seems solved now, although I don't have a clear idea of the root cause. I think it's not able to retrieve the gecko driver from the official repo (https://api.github.com/repos/mozilla/geckodriver/releases) while using the mirror works well (https://registry.npmmirror.com/-/binary/geckodriver/).

**Review by danielezonca — APPROVED** [review]

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
