### PR TITLE
DO NOT MERGE: DROOLS-2379: DROOLS-2380: DROOLS:2381: adding test case and partial fix

### PR DESCRIPTION
**Pull request by etirelli**
Opening a PR with a test case for the listed tickets.

### CODE REVIEW

**Comment by tarilabs** [comment]
Please ref https://github.com/etirelli/drools/pull/6

**Comment by etirelli** [comment]
jenkins test again

**Comment by tarilabs** [comment]
@etirelli to resolve conflicts I rebased the original commits here: https://github.com/kiegroup/drools/pull/1839

**Comment by etirelli** [comment]
Closing as it is replaced by #1839

**Pull request closed without merging**
