### PR TITLE
[DROOLS-7330] Remove kie-dmn-feel-gwt module (and related)

### PR DESCRIPTION
**Pull request by danielezonca**
~~This module is not maintained and probably not neither used (@yesamer please confirm).~~
~~It is producing multiple problems in the alignment of the dependencies (antlr especially) so I'm proposing to remove it.~~
~~As alternative approach we can move it to another repo but we first need to find who can maintain it.~~

The module is still used by DMN Editor and it has been moved to `kie-tools` repo
- https://github.com/kiegroup/kie-tools/pull/1442

The remaining left over (`GWTIncompatible` usages mainly) will remain for now.

**Thank you for submitting this pull request**

**NOTE!:** Double check the target branch for this PR.
The default is `main` so it will target Drools 8 / Kogito.
If this PR is not strictly related to drools and kogito project in `drools.git`, it should probably target `7.x`as a branch

**Ports** If a forward-port or a backport is needed, paste the forward port PR here

[link](https://www.example.com)

**JIRA**: _(please edit the JIRA link if it exists)_

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

 - for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by danielezonca** [comment]
@yesamer @tarilabs @mariofusco @baldimir 
Wdyt?

I preserved all `*.gwt.xml` files because I don't know if these modules are still used in the editor anywhere (i.e. ['DMNModel.gwt.xml'](https://github.com/kiegroup/drools/blob/main/kie-dmn/kie-dmn-model/src/main/resources/org/kie/dmn/model/DMNModel.gwt.xml)). 
@yesamer Can you please verify which modules of Drools DMN are still compiled on client side?

FYI @Rikkola given that essentially it is code that you wrote :)

**Review by yesamer — CHANGES_REQUESTED** [review]
Please do not merge until we completed all the checks related https://github.com/kiegroup/kie-tools/pull/1442

**Comment by danielezonca** [comment]
Thanks @yesamer for the update.
FYI I removed the `@GWTIncompatible` annotation from DMN core modules, let me know if they need to stay to make the code that you are moving, continue to work.

**Comment by yesamer** [comment]
@danielezonca I think we still need those `@GWTIncompatible`  annotations and the `*.gwt.xml` files

**Comment by Rikkola** [comment]
The FEEL autocomplete needs these. I see Yeser moved them to kie-tools, so based on that they were needed. The modules could for example depend on a set version of DMN to reduce upstream failures. They are not used to run FEEL or DMN so it likely does not need the latest updates all the time.

**Comment by danielezonca** [comment]
@rsynek @triceo 
I'm getting a failure of OptaPlanner Job but this PR is touching only some DMN code so I think it is unrelated. The error seems related with a missing property in the pom (dependencyManagement).
https://github.com/kiegroup/drools/actions/runs/4116298407/jobs/7106166282

Can you please have a look and confirm that it is unrelated?

**Comment by danielezonca** [comment]
@yesamer 
Restored all GWTIncompatible, can you try your PR with this?

**Comment by rsynek** [comment]
@danielezonca `-Dversion.org.drools= ` is empty in the build command in logs. I think this is where the build command is defined:
https://github.com/kiegroup/optaplanner/blob/main/.ci/pull-request-config-rhbop.yaml#L29

This log message looks suspicious:
`2023-02-07T16:58:18.2450893Z echo "DROOLS_VERSION=${{ env.DROOLS_VERSION }}"`
Like if the replacement in the BCT didn't work properly.

@lampajr any idea what could cause that? There was an upgrade of the BCT recently, could it be related?

**Comment by lampajr** [comment]
Hey @rsynek ,

> @lampajr any idea what could cause that? There was an upgrade of the BCT recently, could it be related?

It could be related because the definition file did not change AFAIK. I can see that the export has been performed but it looks like it has been executed after all build commands and not after the drools one, as expected:

```
[COMMANDS] [kiegroup/drools] mvn clean install -Dquickly  -nsu -ntp -fae -e -DskipTests=true -Dproductized=true -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3   -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B
[COMMANDS] [kiegroup/optaplanner] mvn clean install -Dfull  -nsu -ntp -fae -e -DskipTests=true -Dproductized=true -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3  dependency:tree  -Dversion.org.drools= -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B

Executing after
[AFTER] [kiegroup/drools] export DROOLS_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout` -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B
[AFTER] [kiegroup/drools] echo "DROOLS_VERSION=8.35.0-SNAPSHOT"
```

Need to further investigate

@Ginxo ^

**Comment by Ginxo** [comment]
ok, checking....
@shubhbapna FYI

**Comment by Ginxo** [comment]
@lampajr @shubhbapna https://github.com/kiegroup/github-action-build-chain/issues/376

**Review by yesamer — APPROVED** [review]
Hi @danielezonca, after [we moved the involved modules to the client side](https://github.com/kiegroup/kie-tools/pull/1442), we can proceed to remove them on the backend side safely.
About the JDK 11 API compatibility issue I reported to you (introduced in a previous PR), I found a solution to manage that on the client-side, so no need to apply any further change.
Thank you.

**Comment by Ginxo** [comment]
@rsynek @lampajr @danielezonca optaplanner flow is already working as expected after fixing https://github.com/kiegroup/github-action-build-chain/issues/376
Thanks for the effort @shubhbapna

**Comment by danielezonca** [comment]
@baldimir 
Can you please review/approve? I would like to merge it now that @yesamer already moved the code to `kie-tools`
- https://github.com/kiegroup/kie-tools/pull/1442

**Review by baldimir — APPROVED** [review]

**Comment by baldimir** [comment]
Done.

**Pull request merged**
