### PR TITLE
Testing Pull Request for Jenkins Github PR builder

### PR DESCRIPTION
**Pull request by psiroky**
Testing PR to verify/test the integration with Jenkins Github PR builder. I will close this PR once I am done with the testing.

### CODE REVIEW

**Comment by psiroky** [comment]
retest this please

**Comment by psiroky** [comment]
retest this please

**Comment by etirelli** [comment]
retest this please

**Comment by psiroky** [comment]
Closing as the testing with this PR is now done. I will merge the changes manually as they are still useful.

**Pull request closed without merging**
