### PR TITLE
DROOLS-4650: Fix missing equals implementations

### PR DESCRIPTION
**Pull request by jomarko**
In original DROOLS-4650 PR we missed some equals implementations what caused to fail tests in drools-wb repository. This PR fixes it.

Ensemble together wit:
https://github.com/kiegroup/drools-wb/pull/1252

### CODE REVIEW

**Review by Rikkola — APPROVED** [review]

**Comment by Rikkola** [comment]
@jomarko Thanks I was just looking into this.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by Rikkola** [comment]
The original cause was reverted.

**Comment by jomarko** [comment]
Conflicts resolved I think.
jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed tests
```
org.drools.compiler.integrationtests.ParallelEvaluationTest.testFireUntilHalt2
org.drools.compiler.integrationtests.ParallelEvaluationTest.testFireUntilHaltWithExpiration2
```

jenkins please retest this

**Comment by mareknovotny** [comment]
still one of previous failing `org.drools.compiler.integrationtests.ParallelEvaluationTest.testFireUntilHaltWithExpiration2`

**Comment by mareknovotny** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@manstis may I ask you for review and merge? together with kiegroup/drools-wb#1252 ?

**Review by manstis — COMMENTED** [review]
@jomarko Sonar has detected missing `hashCode()` methods. 

Do you think these should be addressed?

**Comment by jomarko** [comment]
@manstis no I do not think they should be implemented. I personally think due to missing fields in class implementing `hashCode` is not necessary.

I implemented `equals` in these 4 classes to fix `assertEquals(DescriptionCol52 instance, RowNumberCor52 instance)`.

However as you didn't approved and merged , it is signal to me you do not see it in that way, I added new commit and starting build wit comment below.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Thank-you for the explanation @jomarko I didn't realise the 4 classes had no fields to include in the hash code calculation; I was simply reporting what Sonar had detected (it is also encouraged by Oracle [too](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object))).. What you have done in your new commit will at least make people like me not wonder why you've implemented `equals(..)` but not `hashCode()` in the future :-)

**Review by manstis — APPROVED** [review]

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
