### PR TITLE
DROOLS-1693 ProcessBuilderFactory refactoring dealing tech debt

### PR DESCRIPTION
**Pull request by tarilabs**

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
@mswiderski @mariofusco can you review, please?
@mswiderski , we identified the code could be made more simple following DROOLS-1649 ServiceRegistry refactoring. What do you think?

**Comment by mariofusco** [comment]
+1 for me. I'll wait for @mswiderski feedback and then I'll merge this.

**Comment by tarilabs** [comment]
Here's something weird.

Most recent full downstream build is n27
https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/drools-downstream-pullrequests/27/
which failed with

```
Test Result (1 failure / +1)
org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromCustomRepository
```

although I wonder what triggered it^.
Maybe when I changed the title on this PR?

Because originally full downstream build was n26
https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/drools-downstream-pullrequests/26/
which had no test failure whatsoever.

**Comment by mariofusco** [comment]
@tarilabs I believe that one is a false negative and anyway totally unrelated with you change.

**Comment by tarilabs** [comment]
Agreed. But see? It started building again :8ball:

**Comment by psiroky** [comment]
@tarilabs I am afraid your previous comment triggered new build. Jenkins is not that smart to figure out that you weren't trying to get a new build, simply matching a regex `.*jenkins.*test.*` will suffice. We can of course make the regex more strict, but then people may likely find themselves wondering why the build wasn't triggered. I am open to ideas though!

**Comment by tarilabs** [comment]
Thanks @psiroky for the feedback. I would suggest having match 1 whitespace just after "jenkins"
```
.*jenkins\s.*test.*
         ^^
```
or if the incoming string from github is Unicode I guess it may need be adapted as:
```
.*jenkins\p{Z}.*test.*
         ^^^^^
```

This is because I would expect comments to be something like

- "Jenkins run the test"
- or "hey Jenkins test ..."

but never "heyJenkinstestagain".
Or if it was "hey Jenkinstest again formeplease" I believe the original commentator could accept it is not a valid bot instruction.

What do you think?

**Comment by psiroky** [comment]
@tarilabs thanks. I've changed the regex to `.*[j|J]enkins,?\s.*test.*` (the one I mentioned before was simplification).

**Comment by mswiderski** [comment]
looks good to me, Though let's wait for the tests to finish as I believe this code was needed for some OSGi related stuff that we should have test for in droolsjbpm-integration.

**Review by mswiderski — APPROVED** [review]
once the full build is green (especially droolsjbpm-integration repo)

**Comment by tarilabs** [comment]
In addition to the downstream build 26 and 27 commented above,
downstream build 28:
```
Test Result (3 failures / +2)
org.jbpm.designer.server.indexing.BPMN2FileIndexerIndexingTest.testBpmnIndexing
org.jbpm.kie.services.test.FilteredKModuleDeploymentServiceTest.testMultipleRemotableInPojoJar
org.kie.wb.test.rest.security.OrganizationalUnitAccessIntegrationTest.testUpdateOrganizationalUnit[user: NO_REST]
```

I am awaiting for downstream build 29, but they are not adding much to downstream build 26 which completed without any failure.

**Pull request merged**
