### PR TITLE
fix incorrect variable reference in isConvertible method

### PR DESCRIPTION
**Pull request by wu-yun**
**Thank you for submitting this pull request**

**JIRA**: NA

within the `isConvertible` method block, the 2nd if logic should be based on `Byte.TYPE.equals( srcPrimitive )` instead of `Byte.TYPE.equals( tgtPrimitive )`. I believe it is a typo.

### CODE REVIEW

**Comment by wu-yun** [comment]
@mariofusco @danielezonca @mbiarnes Could any of you review it ? It's a tiny PR but a bugfix.

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins test

**Review by mariofusco — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]
Thanks for your PR, approving :+1:

**Pull request merged**
