### PR TITLE
[DROOLS-6834] remove drl prefix from drools quarkus extension + create drools-drl parent module

### PR DESCRIPTION
**Pull request by mariofusco**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6834

Related PRs:
https://github.com/apache/incubator-kie-drools/pull/5564
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3261

### CODE REVIEW

**Review by lucamolteni — APPROVED** [review]
What was `-drl` for btw?

**Comment by mariofusco** [comment]
> What was `-drl` for btw?

In the Quarkus extension? Something that we added to (mistakenly) underline that the extension was only for drl and the biggest part of the capabilities were in kogito.

**Review by baldimir — APPROVED** [review]

**Comment by jstastny-cz** [comment]
Looking at the jenkins PR checks results - this failure is expected?
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project kogito-quarkus-common-deployment: Could not resolve dependencies for project org.kie.kogito:kogito-quarkus-common-deployment:jar:2.0.0-SNAPSHOT: Could not find artifact org.drools:drools-drl-quarkus-util-deployment:jar:8.45.0-SNAPSHOT in apache-public-repository-group
```

**Comment by mariofusco** [comment]
@jstastny-cz Do you mean the failure on jenkins? I was actually only looking at the github actions. That failure is caused by the fact that jenkins run without the 2nd PR the one on kogito-runtimes https://github.com/apache/incubator-kie-kogito-runtimes/pull/3261 which fixes the problem.

**Comment by jstastny-cz** [comment]
Ah, ok, a retrigger of the failed jenkins check once the 2nd PR was available would resolve, the new run would pick the change up. Thanks for explanation @mariofusco

**Pull request merged**
