### PR TITLE
Fixed EmptyStackException occurring after assorted syntax errors

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by etirelli** [comment]
Wolfgang, I tried to apply your patch above and it does not apply:

etirelli@yoda core [master $=] $ curl https://github.com/droolsjbpm/drools/pull/13.patch | git am
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16964  100 16964    0     0  12599      0  0:00:01  0:00:01 --:--:-- 15407
Applying: Avoid EmptyStackException due to simple typo: declare foo ; int end
error: patch failed: drools-compiler/src/main/java/org/drools/lang/DRLParser.java:492
error: drools-compiler/src/main/java/org/drools/lang/DRLParser.java: patch does not apply
Patch failed at 0001 Avoid EmptyStackException due to simple typo: declare foo ; int end
When you have resolved this problem run "git am --resolved".
If you would prefer to skip this patch, instead run "git am --skip".
To restore the original branch and stop patching run "git am --abort".

Can you please redo it? My guess is the problem happens because of your 3-way merge above.

**Comment by ghost** [comment]
If I look at the diff in 13.patch, I see that only the second one reflects
the change; the first one is the old one you told me you did on Monday.

So, if there's a pull request out, open, and you pull - who is supposed to
close it?

Perhaps I should have, but then I don't really know (without research) that
you have indeed taken it.

How can I redo this?

-W

**Comment by etirelli** [comment]
Wolfgang, I closed the pull request from last Monday (#12), as you can
see here:

https://github.com/droolsjbpm/drools/pull/12

https://github.com/droolsjbpm/drools/pull/12   The pull request for today
is #13, so I imagine there was a problem when you created it. I suggest you
delete the pull request and create a new one.

   Edson

2011/5/12 laune <
reply@reply.github.com>

> If I look at the diff in 13.patch, I see that only the second one reflects
> the change; the first one is the old one you told me you did on Monday.
> 
> So, if there's a pull request out, open, and you pull - who is supposed to
> close it?
> 
> Perhaps I should have, but then I don't really know (without research) that
> you have indeed taken it.
> 
> How can I redo this?
> 
> -W
> 
> On 12 May 2011 16:00, etirelli <
> reply@reply.github.com>wrote:
> 
> > Wolfgang, I tried to apply your patch above and it does not apply:
> > 
> > etirelli@yoda core [master $=] $ curl
> > https://github.com/droolsjbpm/drools/pull/13.patch | git am
> >  % Total    % Received % Xferd  Average Speed   Time    Time     Time
> >  Current
> >                                 Dload  Upload   Total   Spent    Left
> >  Speed
> > 100 16964  100 16964    0     0  12599      0  0:00:01  0:00:01 --:--:--
> > 15407
> > Applying: Avoid EmptyStackException due to simple typo: declare foo ; int
> > end
> > error: patch failed:
> > drools-compiler/src/main/java/org/drools/lang/DRLParser.java:492
> > error: drools-compiler/src/main/java/org/drools/lang/DRLParser.java:
> > patch
> > does not apply
> > Patch failed at 0001 Avoid EmptyStackException due to simple typo:
> > declare
> > foo ; int end
> > When you have resolved this problem run "git am --resolved".
> > If you would prefer to skip this patch, instead run "git am --skip".
> > To restore the original branch and stop patching run "git am --abort".
> > 
> > Can you please redo it? My guess is the problem happens because of your
> > 3-way merge above.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/droolsjbpm/drools/pull/13#issuecomment-1146596
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/droolsjbpm/drools/pull/13#issuecomment-1146665

## 

  Edson Tirelli
  JBoss Drools Core Development
  JBoss by Red Hat @ www.jboss.com

**Comment by ghost** [comment]
I've re-created it, but please note that only the last commit should be
applied.

I can't get rid of the other two commits when I create the pull request?!

-W

**Comment by etirelli** [comment]
You have to rebase your code to point to master's HEAD. While you don't
do that, your pull request will be wrong...

```
Edson
```

2011/5/12 laune <
reply@reply.github.com>

> I've re-created it, but please note that only the last commit should be
> applied.
> 
> I can't get rid of the other two commits when I create the pull request?!
> 
> -W
> 
> On 12 May 2011 16:17, etirelli <
> reply@reply.github.com>wrote:
> 
> > Wolfgang, I closed the pull request from last Monday (#12), as you can
> > see here:
> > 
> > https://github.com/droolsjbpm/drools/pull/12
> > 
> > https://github.com/droolsjbpm/drools/pull/12   The pull request for
> > today
> > is #13, so I imagine there was a problem when you created it. I suggest
> > you
> > delete the pull request and create a new one.
> > 
> >   Edson
> > 
> > 2011/5/12 laune <
> > reply@reply.github.com>
> > 
> > > If I look at the diff in 13.patch, I see that only the second one
> > > reflects
> > > the change; the first one is the old one you told me you did on Monday.
> > > 
> > > So, if there's a pull request out, open, and you pull - who is supposed
> > > to
> > > close it?
> > > 
> > > Perhaps I should have, but then I don't really know (without research)
> > > that
> > > you have indeed taken it.
> > > 
> > > How can I redo this?
> > > 
> > > -W
> > > 
> > > On 12 May 2011 16:00, etirelli <
> > > reply@reply.github.com>wrote:
> > > 
> > > > Wolfgang, I tried to apply your patch above and it does not apply:
> > > > 
> > > > etirelli@yoda core [master $=] $ curl
> > > > https://github.com/droolsjbpm/drools/pull/13.patch | git am
> > > >  % Total    % Received % Xferd  Average Speed   Time    Time     Time
> > > >  Current
> > > >                                 Dload  Upload   Total   Spent    Left
> > > >  Speed
> > > > 100 16964  100 16964    0     0  12599      0  0:00:01  0:00:01
> > > > --:--:--
> > > > 15407
> > > > Applying: Avoid EmptyStackException due to simple typo: declare foo ;
> > > > int
> > > > end
> > > > error: patch failed:
> > > > drools-compiler/src/main/java/org/drools/lang/DRLParser.java:492
> > > > error: drools-compiler/src/main/java/org/drools/lang/DRLParser.java:
> > > > patch
> > > > does not apply
> > > > Patch failed at 0001 Avoid EmptyStackException due to simple typo:
> > > > declare
> > > > foo ; int end
> > > > When you have resolved this problem run "git am --resolved".
> > > > If you would prefer to skip this patch, instead run "git am --skip".
> > > > To restore the original branch and stop patching run "git am
> > > > --abort".
> > > > 
> > > > Can you please redo it? My guess is the problem happens because of
> > > > your
> > > > 3-way merge above.
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/droolsjbpm/drools/pull/13#issuecomment-1146596
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/droolsjbpm/drools/pull/13#issuecomment-1146665
> > 
> > ## 
> > 
> >  Edson Tirelli
> >  JBoss Drools Core Development
> >  JBoss by Red Hat @ www.jboss.com
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/droolsjbpm/drools/pull/13#issuecomment-1146702
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/droolsjbpm/drools/pull/13#issuecomment-1146789

## 

  Edson Tirelli
  JBoss Drools Core Development
  JBoss by Red Hat @ www.jboss.com

**Pull request closed without merging**
