### PR TITLE
[DROOLS-4018] Add support for LocalDate in Rule based test scenarios

### PR DESCRIPTION
**Pull request by danielezonca**
This PR introduce a basic support for `LocalDate` class to Rule based scenario.
`LocalDate` parsing supports only `yyyy-MM-dd` format at the moment

https://issues.jboss.org/browse/DROOLS-4018

@jomarko @gitgabrio @Rikkola 

PRs list:
- https://github.com/kiegroup/drools-wb/pull/1148
- https://github.com/kiegroup/drools/pull/2359

### CODE REVIEW

**Review by Rikkola — APPROVED** [review]
There is a property for setting the date time format for the editors that can be used later on.

**Review by jomarko — APPROVED** [review]
No comments here, will provide final review in second part of the ensemble.

**Comment by jomarko** [comment]
Please update the jira description, in code we use `yyyy-MM-dd`

**Comment by danielezonca** [comment]
> Please update the jira description, in code we use `yyyy-MM-dd`

Done

**Pull request merged**
