### PR TITLE
[7.52.x] DROOLS-6265 : Guided Rule Editor: Formula with contains does not reopen correctly

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**: 

[DROOLS-6265](https://issues.redhat.com/browse/DROOLS-6265)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
@yesamer @jomarko I think you both reviewed this earlier even for this branch, but here we go again :)

**Review by yesamer — APPROVED** [review]

**Review by jomarko — CHANGES_REQUESTED** [review]
I would like to ask you to include both tests we have as part of https://github.com/kiegroup/drools/pull/3517/files

**Comment by Rikkola** [comment]
@jomarko Well spotted. Added your changes in.

**Review by jomarko — APPROVED** [review]

**Comment by jomarko** [comment]
Thank you @Rikkola approved

**Pull request merged**
