### PR TITLE
[DROOLS-5862]  Deprecating legacy implementation

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @mariofusco @jiripetrlik

This PR actually deprecates the legacy implementation

Bundle with
https://github.com/kiegroup/droolsjbpm-knowledge#505
https://github.com/kiegroup/droolsjbpm-integration/pull/2409

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]

**Comment by gitgabrio** [comment]
Jenkins run cdb

**Comment by gitgabrio** [comment]
Jenkins run cdb

**Comment by gitgabrio** [comment]
Jenkins run cdb

**Comment by gitgabrio** [comment]
Jenkins run cdb

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by gitgabrio** [comment]
Jenkins retest this

**Review by jiripetrlik — APPROVED** [review]

**Pull request merged**
