### PR TITLE
BXMSDOC-6058-master: Update built-in FEEL adoc file to align with docs.

### PR DESCRIPTION
**Pull request by sterobin**
@tarilabs , ready for your review. Applied changes from docs PR https://github.com/kiegroup/kie-docs/pull/2790.

Links:
* [Jira](https://issues.redhat.com/browse/BXMSDOC-6058)
* [Docs PR](https://github.com/kiegroup/kie-docs/pull/2790)

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]

**Review by hellowdan — APPROVED** [review]

**Comment by sterobin** [comment]
@kiegroup/gatekeepers , ready for merge.

**Comment by tarilabs** [comment]
@sterobin let's wait for Linux... tasks to complete

**Comment by tarilabs** [comment]
Some of the changes in the adoc is making fail `org.kie.dmn.feel.documentation.ADocFEELExamplesTest.org.kie.dmn.feel.documentation.ADocFEELExamplesTest` I need to jump on this, investigating...

**Comment by sterobin** [comment]
@kiegroup/gatekeepers @tarilabs Looks like all green enough now, correct?

**Comment by tarilabs** [comment]
I concur @sterobin ; @kiegroup/gatekeepers please merge with squash

**Pull request merged**
