### PR TITLE
KOGITO-212 Ensure Jandex for Kie API and DMN API

### PR DESCRIPTION
**Pull request by tarilabs**
Requires https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1043

@mariofusco @baldimir kindly review, please?

### CODE REVIEW

**Comment by tarilabs** [comment]
OSGi =>

Jenkins execute full downstream build

**Comment by tarilabs** [comment]
```
org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.testDeployedBrokenProjectFixAndRedeploy[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34804/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.testDeployedBrokenProjectFixAndRedeploy[2: XSTREAM KieServicesConfiguration{transport=REST, serverUrl='http://localhost:34804/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.testDeployedBrokenProjectFixAndRedeploy[3: JAXB KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.testDeployedBrokenProjectFixAndRedeploy[5: XSTREAM KieServicesConfiguration{transport=JMS, serverUrl='null'}]
org.kie.processmigration.it.ProcessMigrationIntegrationTest.testMigration
org.kie.processmigration.it.ProcessMigrationIntegrationTest.testHealthCheck
org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromCustomRepository
org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest
org.kie.wb.test.rest.functional.HealthServiceIntegrationTest.testGetReady
org.kie.wb.test.rest.functional.HealthServiceIntegrationTest.testGetHealthy
org.kie.wb.test.rest.functional.HealthServiceIntegrationTest.org.kie.wb.test.rest.functional.HealthServiceIntegrationTest
org.kie.wb.test.rest.functional.JobIntegrationTest.org.kie.wb.test.rest.functional.JobIntegrationTest
org.kie.wb.test.rest.functional.JobIntegrationTest.org.kie.wb.test.rest.functional.JobIntegrationTest
org.kie.wb.test.rest.functional.ProjectIntegrationTest.org.kie.wb.test.rest.functional.ProjectIntegrationTest
org.kie.wb.test.rest.functional.ProjectIntegrationTest.org.kie.wb.test.rest.functional.ProjectIntegrationTest
org.kie.wb.test.rest.functional.RepositoryIntegrationTest.org.kie.wb.test.rest.functional.RepositoryIntegrationTest
org.kie.wb.test.rest.functional.RepositoryIntegrationTest.org.kie.wb.test.rest.functional.RepositoryIntegrationTest
org.kie.wb.test.rest.functional.SpaceIntegrationTest.testDeleteExisting
org.kie.wb.test.rest.functional.SpaceIntegrationTest.testAddProjectToNotExistingSpace
org.kie.wb.test.rest.functional.SpaceIntegrationTest.testGetExisting
org.kie.wb.test.rest.functional.SpaceIntegrationTest.testCreateWithGroupId
org.kie.wb.test.rest.functional.SpaceIntegrationTest.testCreateEmptyOwner
org.kie.wb.test.rest.functional.SpaceIntegrationTest.testDeleteNotExisting
org.kie.wb.test.rest.functional.SpaceIntegrationTest.testCreateMinimal
org.kie.wb.test.rest.functional.SpaceIntegrationTest.testCreateEmptyName
org.kie.wb.test.rest.functional.SpaceIntegrationTest.testGetAll
org.kie.wb.test.rest.functional.SpaceIntegrationTest.org.kie.wb.test.rest.functional.SpaceIntegrationTest
org.kie.wb.test.rest.functional.SpacesScreenServiceIntegrationTest.org.kie.wb.test.rest.functional.SpacesScreenServiceIntegrationTest
org.kie.wb.test.rest.functional.SpacesScreenServiceIntegrationTest.org.kie.wb.test.rest.functional.SpacesScreenServiceIntegrationTest
org.kie.wb.test.rest.security.HealthCheckServiceIntegrationTest.testGetReady
org.kie.wb.test.rest.security.HealthCheckServiceIntegrationTest.testGetHealthy
org.kie.wb.test.rest.security.HealthCheckServiceIntegrationTest.org.kie.wb.test.rest.security.HealthCheckServiceIntegrationTest
org.kie.wb.test.rest.security.JobAccessIntegrationTest.testDeleteJob[user: NO_REST]
org.kie.wb.test.rest.security.JobAccessIntegrationTest.testGetJob[user: NO_REST]
org.kie.wb.test.rest.security.JobAccessIntegrationTest.testDeleteJob[user: REST_PROJECT]
org.kie.wb.test.rest.security.JobAccessIntegrationTest.testGetJob[user: REST_PROJECT]
org.kie.wb.test.rest.security.JobAccessIntegrationTest.org.kie.wb.test.rest.security.JobAccessIntegrationTest
org.kie.wb.test.rest.security.ProjectAccessIntegrationTest.org.kie.wb.test.rest.security.ProjectAccessIntegrationTest
org.kie.wb.test.rest.security.ProjectAccessIntegrationTest.org.kie.wb.test.rest.security.ProjectAccessIntegrationTest
org.kie.wb.test.rest.security.RepositoryAccessIntegrationTest.org.kie.wb.test.rest.security.RepositoryAccessIntegrationTest
org.kie.wb.test.rest.security.RepositoryAccessIntegrationTest.org.kie.wb.test.rest.security.RepositoryAccessIntegrationTest
org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.testDeleteSpace[user: NO_REST]
org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.testGetSpace[user: NO_REST]
org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.testCreateSpace[user: NO_REST]
org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.testGetSpaces[user: NO_REST]
org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.testDeleteSpace[user: REST_PROJECT]
org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.testGetSpace[user: REST_PROJECT]
org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.testCreateSpace[user: REST_PROJECT]
org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.testGetSpaces[user: REST_PROJECT]
org.kie.wb.test.rest.security.SpaceAccessIntegrationTest.org.kie.wb.test.rest.security.SpaceAccessIntegrationTest
```

none related to OSGi.

🎱 

Jenkins execute full downstream build

**Review by jiripetrlik — CHANGES_REQUESTED** [review]
@tarilabs Hello this change will probably break OSGI support. I will try test this change in Karaf.

**Review by jiripetrlik — APPROVED** [review]
Looks good to me. I've manually checked that OSGI bundle manifest headers are generated.

**Comment by tarilabs** [comment]
```
09:31:32 ERROR: kie-psi-rhel7-xlarge-xmem-0 is offline; cannot locate kie-jdk1.8
09:31:32 ERROR: Step ‘Delete workspace when build is done’ failed: no workspace for KIE/master/pullrequest/drools-downstream-pullrequests #915
09:31:32 Finished: FAILURE
```

**Comment by tarilabs** [comment]
Superseeded by quarkusio/quarkus#3771

**Pull request closed without merging**
