### PR TITLE
BZ-1305798: add reproducer

### PR DESCRIPTION
**Pull request by winklerm**
Added reproducer for BZ 1305798 in a new module `drools-test-coverage` (discussed with @psiroky).

The test `org.drools.testcoverage.kieci.withoutdomain.KJarLoadingTest` fails when creating the KieContainer. 

Please note that similar test `org.drools.testcoverage.kieci.withoutdomain.KJarLoadingTest` passes, I have created it in order to catch possible regressions.

### CODE REVIEW

**Comment by winklerm** [comment]
Changed `drools-test-coverage` project structure according to our discussion with @psiroky.

There is `standalone` module which is supposed to contain modules for tests that need specific dependencies or other specific Maven configuration. Currently, it contains modules for KIE-CI tests with/without dependency on a domain model.

Please let me know if I should make additional changes, thanks!

**Comment by mrietveld** [comment]
@winklerm Are there (concrete) plans for other modules in `drools-test-coverage` besides `common` and `standalone`?

**Comment by psiroky** [comment]
Thanks @winklerm, I will take a look later today.

**Comment by winklerm** [comment]
@mrietveld Yes, we are planning to move some of QE tests (related to Drools engine) into a module located under `drools-test-coverage`. It should be similar to `jbpm/jbpm-test-coverage`, just for Drools-related tests.

**Comment by winklerm** [comment]
Updated according to feedback from @psiroky:
- renamed groupId and artifactId,
- removed module `common`,
- ignored failing test to allow merging.

Please let me know if there are any other issues, thanks!

**Comment by psiroky** [comment]
The remaining test failure is not related to this PR (looks like intermittent fail).

**Comment by psiroky** [comment]
@winklerm sorry for the delay, I haven't forgotten about this, but had to switch to other priority tasks. I'll make sure to merge this by end of the week.

**Comment by psiroky** [comment]
+1. Squashed and merge as https://github.com/droolsjbpm/drools/commit/0589ee26d8ed9c241c1e253f6fb8954644cc31cc.

I basically kept the structure as is for now. If we find a better a way (I did not yet :)), we can change it later.

Shame on me for taking so long to merge this :(

**Pull request closed without merging**
