### PR TITLE
BZ-1321281: add test

### PR DESCRIPTION
**Pull request by winklerm**
Added test covering the fix for BZ 1321281. Please note that the test does not rely on non-case-preserving OS, it simulates the original issue by attempting to load a class which generates ExceptionInInitializerError (subclass of LinkageError).

Please do not merge yet, I would like to gather feedback first.

### CODE REVIEW

**Comment by winklerm** [comment]
@mariofusco, @psiroky When you have time, I would be happy to hear your comments.

Meanwhile, I am waiting for feedback from GSS.

**Comment by winklerm** [comment]
Confirmed the test case with GSS.

I should probably squash the commits into one, I'll do it after review so there would be no further changes.

**Comment by baldimir** [comment]
+1 for me. Looks good.

**Comment by psiroky** [comment]
+1

**Pull request merged**
