### PR TITLE
BAQE-1114 - Change revapi to check against 7.26.0.Final

### PR DESCRIPTION
**Pull request by MarianMacik**
depends on kiegroup/droolsjbpm-build-bootstrap#1070

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by baldimir** [comment]
Shouldn't this be checking against 7.27.0.Final? There is 7.28.0-SNAPSHOT on master.

**Comment by MarianMacik** [comment]
Nope. We always check the last version which has a productized artifact, i.e. the highest available branch other than master.

**Review by baldimir — APPROVED** [review]

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins execute compile downstream build

Will try the compile downstream once more, but if it doesn't work, we can merge this anyway... Cross-repository dependencies work and all repositories with revapi work, so there is no really point to have compile downstream green.

**Comment by MarianMacik** [comment]
jenkins execute compile downstream build

**Pull request merged**
