### PR TITLE
[DROOLS-2468] put stateful session under control of kbase coordinatio…

### PR DESCRIPTION
**Pull request by mariofusco**
…n for incremental update even when wrapped by a stateless session

### CODE REVIEW

**Comment by mariofusco** [comment]
This PR doesn't ensure atomicity of stateless session execute with regard to kbase update.

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Review by baldimir — APPROVED** [review]
Benchmarks results: https://gist.github.com/baldimir/efbe8dc0e29223feffbb8e3ca5e6653f

**Pull request merged**
