### PR TITLE
DROOLS-5957: clean up drools-workbench-models dependencies

### PR DESCRIPTION
**Pull request by jomarko**
For more details see https://issues.redhat.com/browse/DROOLS-5957

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by Rikkola — APPROVED** [review]

**Comment by jomarko** [comment]
`drools-mvel` removal reverted due to fails is `org.drools.workbench.models.guided.dtable.backend.GuidedDTableParsingIntegrationTest.`

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
