### PR TITLE
[RHDM-1895] Saving dmn model is not working when using not() function

### PR DESCRIPTION
**Pull request by danielzhe**
Fixed by a backport of https://github.com/kiegroup/drools/pull/4334

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]

**Review by mariofusco — CHANGES_REQUESTED** [review]
On drools 7.x we still use `hamcrest` instead of `assertj` so the tests have some compilation failures like

```
[ERROR] /home/runner/work/drools/drools/kiegroup_drools/kie-dmn/kie-dmn-validation/src/test/java/org/kie/dmn/validation/dtanalysis/IntervalTest.java:[100,9] no suitable method found for assertThat(java.util.List<org.kie.dmn.validation.dtanalysis.model.Interval>)
```

Please fix the test classes accordingly.

**Comment by tarilabs** [comment]
> On drools 7.x we still use `hamcrest` instead of `assertj` so the tests have some compilation failures ...

not necessarily, see https://github.com/kiegroup/drools/commit/5d65d9ffe1448bf47bc3e27bffb3b475d2b7d845#diff-8a18918b6b326c010f70aa152461a8eb27f36b22c19b693f227a063fecfdb820R117

I believe it might fix with the appropriate `import` backport fix.

**Comment by danielzhe** [comment]
@mariofusco Changes applied. I think it is ok now.

**Review by mariofusco — APPROVED** [review]

**Comment by danielzhe** [comment]
@kiegroup/gatekeepers Merge, please

The build error doesn't seem to be related, since the same code is merged and the blue branch and analyzing the logs it doesn't seem to be related, so I think it is ok to merge it since today is the cut-off:

19:10:16      at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute (ServiceControllerImpl.java:1731)
19:10:16      at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run (ServiceControllerImpl.java:1559)
19:10:16      at org.jboss.threads.ContextClassLoaderSavingRunnable.run (ContextClassLoaderSavingRunnable.java:35)
19:10:16      at org.jboss.threads.EnhancedQueueExecutor.safeRun (EnhancedQueueExecutor.java:1985)
19:10:16      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask (EnhancedQueueExecutor.java:1487)
19:10:16      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1378)
19:10:16      at java.lang.Thread.run (Thread.java:829)
19:10:16  Caused by: java.lang.IllegalStateException: WFLYCTL0388: Could not create empty configuration file /home/jenkins/workspace/KIE/7.67.x/compile/drools-7.67.x.compile/bc/kiegroup_kie_wb_distributions/business-central-parent/business-central-webapp/target/bootable-jar-build-artifacts/wildfly/standalone/configuration/standalone.xml
19:10:16      at org.jboss.as.controller.persistence.ConfigurationFile.createBootFile (ConfigurationFile.java:490)
19:10:16      at org.jboss.as.controller.persistence.ConfigurationFile.getBootFile (ConfigurationFile.java:291)
19:10:16      at org.jboss.as.controller.persistence.BackupXmlConfigurationPersister.<init> (BackupXmlConfigurationPersister.java:71)
19:10:16      at org.jboss.as.server.Bootstrap$Configuration$1.createConfigurationPersister (Bootstrap.java:218)
19:10:16      at org.jboss.as.server.ServerService.start (ServerService.java:282)
19:10:16      at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService (ServiceControllerImpl.java:1739)
19:10:16      at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute (ServiceControllerImpl.java:1701)
19:10:16      at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run (ServiceControllerImpl.java:1559)
19:10:16      at org.jboss.threads.ContextClassLoaderSavingRunnable.run (ContextClassLoaderSavingRunnable.java:35)
19:10:16      at org.jboss.threads.EnhancedQueueExecutor.safeRun (EnhancedQueueExecutor.java:1985)
19:10:16      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask (EnhancedQueueExecutor.java:1487)
19:10:16      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1378)
19:10:16      at java.lang.Thread.run (Thread.java:829)
19:10:16  Caused by: java.io.IOException: No such file or directory
19:10:16      at java.io.UnixFileSystem.createFileExclusively (Native Method)
19:10:16      at java.io.File.createNewFile (File.java:1035)
19:10:16      at org.jboss.as.controller.persistence.ConfigurationFile.createBootFile (ConfigurationFile.java:484)
19:10:16      at org.jboss.as.controller.persistence.ConfigurationFile.getBootFile (ConfigurationFile.java:291)
19:10:16      at org.jboss.as.controller.persistence.BackupXmlConfigurationPersister.<init> (BackupXmlConfigurationPersister.java:71)
19:10:16      at org.jboss.as.server.Bootstrap$Configuration$1.createConfigurationPersister (Bootstrap.java:218)
19:10:16      at org.jboss.as.server.ServerService.start (ServerService.java:282)
19:10:16      at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService (ServiceControllerImpl.java:1739)
19:10:16      at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute (ServiceControllerImpl.java:1701)
19:10:16      at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run (ServiceControllerImpl.java:1559)
19:10:16      at org.jboss.threads.ContextClassLoaderSavingRunnable.run (ContextClassLoaderSavingRunnable.java:35)
19:10:16      at org.jboss.threads.EnhancedQueueExecutor.safeRun (EnhancedQueueExecutor.java:1985)
19:10:16      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask (EnhancedQueueExecutor.java:1487)
19:10:16      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1378)
19:10:16      at java.lang.Thread.run (Thread.java:829)
19:10:16  [ERROR] 
19:10:16  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
19:10:16  [ERROR] 
19:10:16  [ERROR] For more information about the errors and possible solutions, please read the following articles:
19:10:16  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
19:10:16  [ERROR] 
19:10:16  [ERROR] After correcting the problems, you can resume the build with the command
19:10:16  [ERROR]   mvn <args> -rf :business-central-webapp
19:10:16  ::error title= [kiegroup/kie-wb-distributions] [Execution ERROR]::mvn -e -nsu -fae --builder smart -T1C clean install -Dfull -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true  dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -s /home/jenkins/workspace/KIE/7.67.x/compile/drools-7.67.x.compile@tmp/config10889175235608997085tmp -Dmaven.wagon.http.ssl.insecure=true
19:10:16  [INFO]  Archive artifact won't be executed
19:10:16  ::group::[Full Downstream Flow] Execution Summary...
19:10:16  [INFO]  ----------------------------------------------
19:10:16  [INFO]  [kiegroup/droolsjbpm-build-bootstrap]. Execution Result: ok. Time: 12.5s (12500 ms)
19:10:16  [INFO]  [kiegroup/kie-soup]. Execution Result: ok. Time: 11.6s (11653 ms)
19:10:16  [INFO]  [kiegroup/droolsjbpm-knowledge]. Execution Result: ok. Time: 21.5s (21519 ms)
19:10:16  [INFO]  [kiegroup/drools]. Execution Result: ok. Time: 8m 38.7s (518793 ms)
19:10:16  [INFO]  [kiegroup/optaplanner]. Execution Result: ok. Time: 5m 16.8s (316882 ms)
19:10:16  [INFO]  [kiegroup/lienzo-core]. Execution Result: ok. Time: 8.1s (8162 ms)
19:10:16  [INFO]  [kiegroup/lienzo-tests]. Execution Result: ok. Time: 6.5s (6505 ms)
19:10:16  [INFO]  [kiegroup/appformer]. Execution Result: ok. Time: 9m 48.7s (588737 ms)
19:10:16  [INFO]  [kiegroup/kie-uberfire-extensions]. Execution Result: ok. Time: 11.8s (11815 ms)
19:10:16  [INFO]  [kiegroup/jbpm]. Execution Result: ok. Time: 5m 58.1s (358103 ms)
19:10:16  [INFO]  [kiegroup/droolsjbpm-integration]. Execution Result: ok. Time: 9m 18.6s (558608 ms)
19:10:16  [INFO]  [kiegroup/kie-wb-playground]. Execution Result: ok. Time: 25.6s (25612 ms)
19:10:16  [INFO]  [kiegroup/kie-wb-common]. Execution Result: ok. Time: 11m 7.3s (667347 ms)
19:10:16  [INFO]  [kiegroup/drools-wb]. Execution Result: ok. Time: 4m 37.6s (277601 ms)
19:10:16  [INFO]  [kiegroup/jbpm-work-items]. Execution Result: ok. Time: 2m 30s (150002 ms)
19:10:16  [INFO]  [kiegroup/jbpm-wb]. Execution Result: ok. Time: 2m 33.4s (153468 ms)
19:10:16  [INFO]  [kiegroup/optaplanner-wb]. Execution Result: ok. Time: 1m 9.3s (69350 ms)
19:10:16  [INFO]  [kiegroup/kie-wb-distributions]. Execution Result: error. Time: 1m 9.8s (69818 ms)
19:10:16  [INFO]  ----------------------------------------------

**Pull request merged**
