### PR TITLE
Tests for PlanActivityTree

### PR DESCRIPTION
**Pull request by sjamboro**
Improve test coverage for PMML decision tree

### CODE REVIEW

**Comment by gitgabrio** [comment]
HI @sjamboro 
Thanks for the PR. Could you please explain me what is the specific case that this test is covering that is not covered by others ?

**Review by jiripetrlik — APPROVED** [review]

**Comment by danielezonca** [comment]
@sjamboro 
Sorry for late reply, I just notice this PR.
I'm not sure if it is intended to cover a new codepath or what because it looks to me that the tested scenario is already covered on master, can you please clarify?
Is this PR just a test or is there a different reason for it?

/cc @gitgabrio @jiripetrlik

**Comment by sjamboro** [comment]
Hi @gitgabrio @danielezonca,
it was my first test in PMML and my first PR. So I did not think about test coverage too much at that time. Looking backward, I cannot find any PMML tree model, which use boolean value as input, in the current test suite. All tree models are about double and string. IMO benefits of this tree model is to introduce input DF called "friendsAvailable" as boolean and using string to guide beginner through my tree model. Feel free to merge or not.

**Comment by sjamboro** [comment]
@gitgabrio @danielezonca, long time ago these checks were green. I am not sure if problem is on my side (missed some refactor) or jenkins, etc.

**Comment by gitgabrio** [comment]
@sjamboro 
Many thanks to have find out this missed coverage! Please feel free to add more if/when you find them

**Comment by gitgabrio** [comment]
@sjamboro 
Could you please rebase to master ? 
Beside that, I successfully run the tree-model integration tests locally

`[INFO] Running org.kie.pmml.models.drools.tree.tests.PlanActivityTreeTest
[main] WARN org.kie.pmml.evaluator.assembler.service.PMMLAssemblerService - invoked legacy addResource (no control on the order of the assembler compilation): /home/gcardosi/Developing/MyWorks/drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-drools/kie-pmml-models-drools-tree/kie-pmml-models-drools-tree-tests/target/classes/planactivitytreemodel/PlanActivityTree.pmml
[main] INFO org.kie.pmml.evaluator.assembler.service.PMMLLoaderService - planactivitytree.PlanActivityTreeFactory class not found in rootClassLoader, going to compile model
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.93 s - in org.kie.pmml.models.drools.tree.tests.PlanActivityTreeTest
`

**Comment by sjamboro** [comment]
@gitgabrio I hope that branch is rebased now

**Comment by gitgabrio** [comment]
@sjamboro 
thanks!

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
