### PR TITLE
[6.5.x] RHBRMS-2596: Guided Decision Table: Unable to specify field type with Condition BRL fragment

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/RHBRMS-2596

(cherry picked from commit 463112ecfdb1bc7984496604ddc4f944f074778d)

This is the corollary of https://github.com/droolsjbpm/drools/pull/922 for 6.5.x.

ACKs for 6.5.x have been received.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@Rikkola could you please review (cherry-pick of PR you reviewed on master)

**Review by Rikkola — APPROVED** [review]
+1

**Pull request merged**
