### PR TITLE
DROOLS-4467 PMML with capitalized field names does not work

### PR DESCRIPTION
**Pull request by lanceleverich**
* Updated the `findDataDictionaryEntry` method of `PMML4UnitImpl`. It now looks through the raw `DataDictionary` values to find the entry, if the entry isn't found using the field name as a key to the
`dataDictionaryMap`.
* Changed the `AbstractModel.getMiningFields` method (used by all models except the MiningModel) to use findDataDictionaryEntry instead of trying to use the field name as key into the `dataDictionaryMap`.
* Added a set of unit tests to make sure that the `findDataDictionaryEntry` method works as intended. This includes also adding a PMML file that contains fields, with names that start with both upper and lower cases.

### CODE REVIEW

**Comment by tarilabs** [comment]
@jiripetrlik something you can kindly review, please?

**Review by jiripetrlik — APPROVED** [review]
Looks good to me.

**Comment by mariofusco** [comment]
jenkins test

**Comment by baldimir** [comment]
jenkins retest this

**Pull request merged**
