### PR TITLE
DROOLS-3019: Add tests for range of strings

### PR DESCRIPTION
**Pull request by jomarko**
@baldimir Hi could you please have a look?

During work on DROOLS-3019 we discussed reusing of `FEELParser` and other more lightweight solution. We decided to reuse `FEELParser` so just adding a scenario where it was better than other discussed solution.

### CODE REVIEW

**Review by baldimir — APPROVED** [review]

**Comment by baldimir** [comment]
Looks good, approving if checks are green.

**Comment by baldimir** [comment]
jenkins retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@baldimir please merge.

**Pull request merged**
