### PR TITLE
BXMSPROD-685: hibernate upgrade requires exclusion for ban-duplicated…

### PR DESCRIPTION
**Pull request by mareknovotny**
…-classes rule
Parent PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1347

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream build

**Review by mbiarnes — APPROVED** [review]
+1 LGTM

**Pull request merged**
