### PR TITLE
[DROOLS-7085] Rule doesn't match with more than 3 rules of BigDecimal…

### PR DESCRIPTION
**Pull request by tkobayas**
… coercion in non executable model

**Ports** 
This PR if for 7.x
for main -> https://github.com/kiegroup/drools/pull/4613

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7085

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Firstly, this is a hash AlphaIndex issue that is enabled when we have more than 3 same type constraint rules. The original issue in the JIRA (https://issues.redhat.com/browse/DROOLS-7085) is that `10` of the constraint `salary == 10` is created as `BigDecimal(10.0)` so it fails to match with the hash of inserted `BigDecimal("10")` in the unit test. 

Fixing `MathUtils.getBigDecimal` solves this particular issue but it doesn't solve the root issue that hashCode of BigDecimal with different scales (e.g. `10` and `10.0`) are different. The issue is also pointed in another JIRA https://issues.redhat.com/browse/DROOLS-6260

Hence, we should disable hash AlphaIndex for BigDecimal. WDYT? @mariofusco

**Comment by tkobayas** [comment]
Ah, same for hash BetaIndex.

**Comment by tkobayas** [comment]
If we will disable hash AlphaIndex/BetaIndex for BigDecimal, we may introduce an option to enable it for performance as long as users are certain that they use completely the same BigDecimal scale.

**Comment by mariofusco** [comment]
> Fixing `MathUtils.getBigDecimal` solves this particular issue but it doesn't solve the root issue that hashCode of BigDecimal with different scales (e.g. `10` and `10.0`) are different. The issue is also pointed in another JIRA https://issues.redhat.com/browse/DROOLS-6260

In which cases the fix you added to `MathUtils` isn't enough? Can you reproduce also this problem and if so can you please add this reproducer as another test case to this PR?

Also is it true that the executable model doesn't suffer of this problem as reported in https://issues.redhat.com/browse/DROOLS-7085 ? If so why? At the moment I don't understand the differences.

**Comment by tkobayas** [comment]
@mariofusco  Sorry that I haven't added test cases while saying there is a root issue.

> In which cases the fix you added to MathUtils isn't enough? Can you reproduce also this problem and if so can you please add this reproducer as another test case to this PR?

Sure, added `testAlphaIndexWithBigDecimalDifferentScale` and `testBetaIndexWithBigDecimalDifferentScale`. Please see that the BigDecimal scale are different so it fails to match.

Note : in `testAlphaIndexWithBigDecimalDifferentScale`, I still use coercion because `salary == 10B` doesn't create an alpha index in non-exec-model (it may be another issue).

> Also is it true that the executable model doesn't suffer of this problem as reported in https://issues.redhat.com/browse/DROOLS-7085 ? If so why? At the moment I don't understand the differences.

exec-model doesn't suffer of creating `BigDecimal(10.0)` from `salary == 10` because it creates the value with `EvaluationUtil.toBigDecimal(10)` instead of `MathUtils.getBigDecimal`.

However, regarding the additional 2 tests (`testAlphaIndexWithBigDecimalDifferentScale` and `testBetaIndexWithBigDecimalDifferentScale`), these tests fail with both exec-model and non-exec-model.

**Comment by mariofusco** [comment]
The problem here is in the special semantic that we're giving to the `BigDecimal`. In general when in the drl we write `a == b`, we mean `a.equals(b)`. But with `BigDecimal`s we have a different requirement because we want `new BigDecimal("10") == new BigDecimal("10.00")` to return `true` even if in java `new BigDecimal("10").equals(new BigDecimal("10.00"))` returns `false`. Given this very specific situation I agree that the only reasonable solution to fulfill this requirement is disabling alpha indexing for BigDecimals. Please implement it with this PR.

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
