### PR TITLE
DROOLS-2274 : adding support for extended unary tests

### PR DESCRIPTION
**Pull request by etirelli**
This PR fixes and replaces PR #1747

### CODE REVIEW

**Comment by etirelli** [comment]
@kurobako @tarilabs can you please review.

@baldimir I think we will need an extra effort testing this one as there are a ton of edge cases.

**Review by tarilabs — APPROVED** [review]

**Comment by tarilabs** [comment]
(minor comment but IIRC there was an article by JMH author which debunked supplying to toArray a properly sized array had any influence)

**Comment by baldimir** [comment]
Correct @tarilabs, the overall fastest option was .toArray(new SomeType[]{}) as far as I remember.

**Comment by baldimir** [comment]
Here is the article: https://shipilev.net/blog/2016/arrays-wisdom-ancients/

**Comment by etirelli** [comment]
@tarilabs @baldimir ok, good to know, thanks!

**Pull request merged**
