### PR TITLE
DROOLS-982: Optimized syntactic predicate while parsing parenthesis e…

### PR DESCRIPTION
**Pull request by soumitrak**
Optimized syntactic predicate while parsing parenthesis expression, and added a test.

### CODE REVIEW

**Comment by soumitrak** [comment]
I have not committed the Antlr generated files,  I hope they are generated as part of the build.

**Comment by mariofusco** [comment]
Good catch, I merged the fix you suggested with this commit https://github.com/droolsjbpm/drools/commit/562ec9833

Please, next time you will send a pull request always send it against our master.

Thanks.

**Comment by soumitrak** [comment]
Thanks Mario.

-------- Original message --------

**Comment by soumitrak** [comment]
Mario, Do you know which release will have this fix?

-------- Original message --------

**Comment by mariofusco** [comment]
This fix will be in Drools 6.4

**Comment by soumitrak** [comment]
Thanks for getting the fix in, looking forward to it.

-------- Original message --------

**Pull request closed without merging**
