### PR TITLE
[6.5.x] DROOLS-1903 : GRE DSL: Multiline code blocks break the editor

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit b253722ba30d700cc067bda284c4033da5c52673)

@manstis @jomarko Same as the one for master.

### CODE REVIEW

**Review by manstis — APPROVED** [review]

**Comment by jomarko** [comment]
Building locally getting fail:
```
Could not resolve dependencies for project org.kie:kie-drools-wb-webapp:war:6.5.1-SNAPSHOT: Could not find artifact org.dashbuilder:dashbuilder-hibernate-validator:jar:sources:0.5.1-20170911.191331-45 in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/)
```

jenkins execute full downstream build

**Comment by Rikkola** [comment]
Could be 6.5.x is broken then.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
build failed, but artifacts present, trying

**Review by jomarko — APPROVED** [review]
Tried built artifacts, the fix works.

**Comment by manstis** [comment]
Full build failed due to OOM. However since the build was successful up to (and including) ```kie-wb-distributions``` this PR is safe to merge :-)

**Pull request merged**
