### PR TITLE
DROOLS-4331 : Error when copying Guided Rule with Bigdecimal

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-4331

### CODE REVIEW

**Comment by Rikkola** [comment]
@manstis Hello. Was this what you were after with the fix proposition?

**Review by manstis — APPROVED** [review]
@Rikkola It is similar to what I was thinking and works the same.

I was thinking to call [this](https://github.com/kiegroup/drools/blob/e1ad62847ee8cdd402d324b99afb296a91150c4b/drools-workbench-models/drools-workbench-models-commons/src/main/java/org/drools/workbench/models/commons/backend/rule/RuleModelDRLPersistenceImpl.java#L4152) earlier and then use the `type` to know whether to `trim(..)` the value - if it ended with `B` or `I`... I guess now I've typed that you're doing it already.

That aside (as your implementation works too) I'd also be tempted to add a check that the `SingleFieldConstraint.getFieldType()` was correct too (I know we probably have tests for that too, but I didn't think it'd hurt to also include it in your new tests).

Approving however as my comments are only opinion.

Thanks for the fix Toni.

**Comment by Rikkola** [comment]
Ok. I was not sure if I could trust the type. I'll improve the tests.

**Comment by Rikkola** [comment]
@Bonuseto would you have time to review this one?

**Comment by Bonuseto** [comment]
jenkins execute full downstream build

**Comment by Rikkola** [comment]
jenkins execute full downstream build

**Review by Bonuseto — APPROVED** [review]
Tested, working perfect without issues, approved

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers could you please merge this.

full downstream fails, but the same setup already passed in compile downstream.
Failure in full downstream is:
 org.kie.server.integrationtests.drools.pmml.ApplyScorecardMultiModuleIntegrationTest.org.kie.server.integrationtests.drools.pmml.ApplyScorecardMultiModuleIntegrationTest

**Pull request merged**
