### PR TITLE
Rename root POM from drools-multiproject to just drools

### PR DESCRIPTION
**Pull request by psiroky**
This should be quite safe change as only artifacts from this repo should depend on the root POM. 

@mbiarnes @ge0ffrey @etirelli could you please confirm that we want this change in? (I was following the comment in the pom, but it is a bit old, so things might have changed).

### CODE REVIEW

**Comment by ge0ffrey** [comment]
+1 This is safe now

**Comment by psiroky** [comment]
retest this please

**Comment by mbiarnes** [comment]
+1

**Comment by mbiarnes** [comment]
I am testing it right now

**Comment by mbiarnes** [comment]
drools doesn't build - because of: https://gist.github.com/mbiarnes/f1a9e601af233d45ade2
this is another reason. Send a mail on last Friday.
we should wait until this is fixed

**Comment by psiroky** [comment]
@mbiarnes  the build error you linked is for `droolsjbpm-tools` repo. This is PR is for Drools which is built earlier in the chain, so I think this is quite safe change and would not influence the build of `droolsjbm-tools`. WDYT?

**Comment by etirelli** [comment]
+1

**Pull request merged**
