### PR TITLE
DROOLS-2943 DMN DecisionServiceCompiler not correctly wired for DMNv1.2 format

### PR DESCRIPTION
**Pull request by tarilabs**
/cc @etirelli @baldimir @jiripetrlik

### CODE REVIEW

**Comment by tarilabs** [comment]
```
Test Result (1 failure / +1)
org.drools.scorecards.ExternalObjectModelTest.testWithReasonCodes
```

Jenkins test again

**Comment by tarilabs** [comment]
```
09:06:29 [ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.5/maven-resources-plugin-2.5.pom , ReasonPhrase:Forbidden. -> [Help 1]
09:06:29 org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5
```

Jenkins test again

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
```
Test Result (1 failure / ±0)
org.drools.scorecards.ScorecardReasonCodeTest.testReasonCodesCombinations
```
unrelated_

Jenkins test again

**Comment by tarilabs** [comment]
```
Test Result (1 failure / ±0)
org.drools.persistence.session.JpaOptLockPersistentStatefulSessionTest.testOptimisticLockInterceptor
```
unrelated_

Jenkins test again

**Comment by tarilabs** [comment]
```
Test Result (25 failures / -1)
org.drools.scorecards.ScorecardProviderPMMLTest.testKnowledgeBaseWithExecution
org.drools.scorecards.ScorecardProviderTest.testKnowledgeBaseWithExection
org.drools.scorecards.ScorecardProviderTest.testDrlWithSheetName
org.drools.scorecards.ScorecardProviderTest.testDrlWithoutSheetName
org.drools.scorecards.ScorecardReasonCodeTest.testPointsAbove
org.drools.scorecards.ScorecardReasonCodeTest.testPointsBelow
org.drools.scorecards.ScorecardReasonCodeTest.testReasonCodesCombinations
org.drools.scorecards.ScorecardsKModuleTest.testScorecardFromKBase2
org.drools.scorecards.ScorecardsKModuleTest.testScorecardFromKModule2
org.drools.scorecards.ScoringStrategiesTest.testWeightedMaximum
org.drools.scorecards.ScoringStrategiesTest.testWeightedMinimum
org.drools.scorecards.ScoringStrategiesTest.testWeightedAggregate
org.drools.scorecards.ScoringStrategiesTest.testAverage
org.drools.scorecards.ScoringStrategiesTest.testWeightedAverageInitialScore
org.drools.scorecards.ScoringStrategiesTest.testMinimumInitialScore
org.drools.scorecards.ScoringStrategiesTest.testMaximumInitialScore
org.drools.scorecards.ScoringStrategiesTest.testMaximum
org.drools.scorecards.ScoringStrategiesTest.testMinimum
org.drools.scorecards.ScoringStrategiesTest.testWeightedAggregateInitialScore
org.drools.scorecards.ScoringStrategiesTest.testAggregate
org.drools.scorecards.ScoringStrategiesTest.testWeightedAverage
org.drools.scorecards.ScoringStrategiesTest.testAggregateInitialScore
org.drools.scorecards.ScoringStrategiesTest.testAverageInitialScore
org.drools.scorecards.ScoringStrategiesTest.testWeightedMinimumInitialScore
org.drools.scorecards.ScoringStrategiesTest.testWeightedMaximumInitialScore
```

unrelated.

**Review by etirelli — APPROVED** [review]

**Pull request merged**
