### PR TITLE
[DROOLS-1379] Additional tests for OOPath syntax

### PR DESCRIPTION
**Pull request by winklerm**
Adds a couple of unit tests for OOPath syntax parser (XpathAnalysis class).

### CODE REVIEW

**Comment by winklerm** [comment]
@mariofusco @tarilabs There are 4 failing tests; however, I think that majority of them fails because the expression which they test is not valid - my plan was to create this PR anyway so we could discuss it.

**Comment by winklerm** [comment]
Fixed failing tests and handling non-oopath expressions (avoid StringIndexOutOfBoundsException and add missing 'return').

**Comment by winklerm** [comment]
Please let me know if I should squash the commits.

**Comment by mariofusco** [comment]
ok to test

**Comment by baldimir** [comment]
I think it would be worth a try to also use some path in condition. E.g. "/address/street{something/somethingAttribute == \"Elm\"}"

**Pull request merged**
