### PR TITLE
[7.52.x] DROOLS-6283: Add missing xstream permission

### PR DESCRIPTION
**Pull request by jomarko**
For more details see:
- https://issues.redhat.com/browse/DROOLS-6283

**Thank you for submitting this pull request**

**JIRA**: 

[DROOLS-6283](https://issues.redhat.com/browse/DROOLS-6283)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do cdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
updates pending, please do not merge

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by jstastny-cz — APPROVED** [review]
LGTM.

We've run a fair portion of regression tests for BC with these changes.

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
