### PR TITLE
DROOLS-1722: adding support for invoking FEEL functions using boxed invocations

### PR DESCRIPTION
**Pull request by etirelli**
/cc @tarilabs @baldimir

### CODE REVIEW

**Review by baldimir — APPROVED** [review]
Looks like the tests in the PR check failed on some tests with functions. @etirelli could you please check if it is not related?

**Review by baldimir — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by etirelli** [comment]
Fixed.

**Review by baldimir — APPROVED** [review]

**Comment by baldimir** [comment]
+1, Looks good.

**Pull request merged**
