### PR TITLE
[DROOLS-6043] avoid parsing date at runtime using the executable model

### PR DESCRIPTION
**Pull request by mariofusco**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6043

### CODE REVIEW

**Review by lucamolteni — CHANGES_REQUESTED** [review]
`Modifier.Keyword.PUBLIC`

**Review by lucamolteni — CHANGES_REQUESTED** [review]
Minor issues

**Comment by mariofusco** [comment]
> `Modifier.Keyword.PUBLIC`

> Minor issues

Sorry @lucamolteni but I haven't understood to what you're referring to.

**Review by tkobayas — APPROVED** [review]
Great improvement, thanks!

**Review by hellowdan — APPROVED** [review]

**Pull request merged**
