### PR TITLE
[DROOLS-7038] Fix invoker properties

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @pibizza 

**JIRA**: _(please edit the JIRA link if it exists)_

[link](https://issues.redhat.com/browse/DROOLS-7038)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>
</details>

### CODE REVIEW

**Comment by kie-ci3** [comment]
**(tests) - kogito-apps job** `#164` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/164/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-27T10:40:54.182Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaweb-vehicle-routing.tests.optaweb-vehicle-routing_ws-cleanup_1656326450210/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/rxjs/_esm5/internal/operators/filter.js’: No such file or directory<br/>[2022-06-27T10:40:54.182Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaweb-vehicle-routing.tests.optaweb-vehicle-routing_ws-cleanup_1656326450210/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/rxjs/_esm5/internal/operators/finalize.js’: No such file or directory<br/>[2022-06-27T10:40:54.182Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaweb-vehicle-routing.tests.optaweb-vehicle-routing_ws-cleanup_1656326450210/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/rxjs/_esm5/internal/operators/find.js’: No such file or directory<br/>[2022-06-27T10:40:54.182Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaweb-vehicle-routing.tests.optaweb-vehicle-routing_ws-cleanup_1656326450210/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/rxjs/_esm5/internal/operators/findIndex.js’: No such file or directory<br/>[2022-06-27T10:40:54.182Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/optaweb-vehicle-routing.tests.optaweb-vehicle-routing_ws-cleanup_1656326450210/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/rxjs/_esm5/internal/operators/first.js’: No such file or directory<br/>[2022-06-27T10:40:54.182Z] 486M	/home/jenkins/workspace<br/>[2022-06-27T10:40:54.182Z] 0	/home/jenkins/.pki<br/>[2022-06-27T10:40:54.182Z] 137M	/home/jenkins/tools<br/>[2022-06-27T10:40:54.182Z] 0	/home/jenkins/caches<br/>[2022-06-27T10:40:54.182Z] 136M	/home/jenkins/.npm<br/>[2022-06-27T10:40:54.182Z] 0	/home/jenkins/.mozilla<br/>[2022-06-27T10:40:54.182Z] 8.0K	/home/jenkins/.java<br/>[2022-06-27T10:40:54.182Z] 410M	/home/jenkins/.sonar<br/>[2022-06-27T10:40:54.182Z] 3.4G	/home/jenkins<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-06-27T10:40:55.011Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/164/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by gitgabrio** [comment]
@danielezonca @mariofusco could you please merge this ? Modifications does not have any impact outside kie-maven-plugin "test" phase

**Review by mariofusco — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]

**Review by mariofusco — CHANGES_REQUESTED** [review]
This change seems to cause many failures in the maven plugin tests, please investigate:

```
2022-06-27T14:08:30.8334778Z [INFO] 
2022-06-27T14:08:30.8335521Z [INFO] --- maven-failsafe-plugin:2.22.1:integration-test (default) @ kie-maven-plugin ---
2022-06-27T14:08:30.8368283Z [INFO] 
2022-06-27T14:08:30.8371470Z [INFO] --- maven-invoker-plugin:2.0.0:run (integration-test) @ kie-maven-plugin ---
2022-06-27T14:08:30.9979403Z [INFO] Building: kie-maven-plugin-test-kjar-setup/pom.xml
2022-06-27T14:08:39.0186150Z [INFO] ..SUCCESS (8.0 s)
2022-06-27T14:08:39.0222855Z [INFO] Building: kie-maven-plugin-test-kjar-8-exec-model/pom.xml
2022-06-27T14:08:48.4280675Z [INFO] ..FAILED (9.4 s)
2022-06-27T14:08:48.4282236Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-exec-model/build.log for details.
2022-06-27T14:08:48.4301272Z [INFO] Building: kie-maven-plugin-test-kjar-7-exec-model/pom.xml
2022-06-27T14:08:51.7807443Z [INFO] ..FAILED (3.4 s)
2022-06-27T14:08:51.7809188Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-exec-model/build.log for details.
2022-06-27T14:08:51.7821558Z [INFO] Building: kie-maven-plugin-test-kjar-12/pom.xml
2022-06-27T14:08:56.1317372Z [INFO] ..FAILED (4.3 s)
2022-06-27T14:08:56.1331402Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-12/build.log for details.
2022-06-27T14:08:56.1337518Z [INFO] Building: kie-maven-plugin-test-kjar-11-yes-generate/pom.xml
2022-06-27T14:08:59.9743872Z [INFO] ..FAILED (3.8 s)
2022-06-27T14:08:59.9762177Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-yes-generate/build.log for details.
2022-06-27T14:08:59.9763310Z [INFO] Building: kie-maven-plugin-test-kjar-9-exec-model/pom.xml
2022-06-27T14:09:03.6963579Z [INFO] ..FAILED (3.7 s)
2022-06-27T14:09:03.6965089Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-exec-model/build.log for details.
2022-06-27T14:09:03.6974669Z [INFO] Building: kie-maven-plugin-test-kjar-10-yes-generate/pom.xml
2022-06-27T14:09:07.4119538Z [INFO] ..FAILED (3.7 s)
2022-06-27T14:09:07.4121472Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-yes-generate/build.log for details.
2022-06-27T14:09:07.4123063Z [INFO] Building: kie-maven-plugin-test-kjar-3/pom.xml
2022-06-27T14:09:14.6728149Z [INFO] ..SUCCESS (7.3 s)
2022-06-27T14:09:14.6730760Z [INFO] Building: kie-maven-plugin-test-kjar-7-no-exec-model/pom.xml
2022-06-27T14:09:18.3623895Z [INFO] ..FAILED (3.7 s)
2022-06-27T14:09:18.3625491Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-no-exec-model/build.log for details.
2022-06-27T14:09:18.3627299Z [INFO] Building: kie-maven-plugin-test-kjar-11-default/pom.xml
2022-06-27T14:09:22.0134533Z [INFO] ..FAILED (3.6 s)
2022-06-27T14:09:22.0135986Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-default/build.log for details.
2022-06-27T14:09:22.0137162Z [INFO] Building: kie-maven-plugin-test-kjar-9-no-exec-model/pom.xml
2022-06-27T14:09:25.5834873Z [INFO] ..FAILED (3.6 s)
2022-06-27T14:09:25.5836325Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-no-exec-model/build.log for details.
2022-06-27T14:09:25.5837339Z [INFO] Building: kie-maven-plugin-test-kjar-8-no-exec-model/pom.xml
2022-06-27T14:09:33.3403117Z [INFO] ..FAILED (7.8 s)
2022-06-27T14:09:33.3404778Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-no-exec-model/build.log for details.
2022-06-27T14:09:33.3413421Z [INFO] Building: kie-maven-plugin-test-kjar-13/pom.xml
2022-06-27T14:09:36.7629267Z [INFO] ..FAILED (3.4 s)
2022-06-27T14:09:36.7634945Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-13/build.log for details.
2022-06-27T14:09:36.7635546Z [INFO] Building: kie-maven-plugin-test-kjar-10-default/pom.xml
2022-06-27T14:09:40.4372362Z [INFO] ..FAILED (3.7 s)
2022-06-27T14:09:40.4373930Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-default/build.log for details.
2022-06-27T14:09:40.4375776Z [INFO] Building: kie-maven-plugin-test-kjar-14-ruleunits/pom.xml
2022-06-27T14:09:43.7919580Z [INFO] ..FAILED (3.4 s)
2022-06-27T14:09:43.7922463Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-14-ruleunits/build.log for details.
2022-06-27T14:09:43.7924509Z [INFO] Building: kie-maven-plugin-test-kjar-2/pom.xml
2022-06-27T14:09:52.9405201Z [INFO] ..SUCCESS (9.1 s)
2022-06-27T14:09:52.9413181Z [INFO] -------------------------------------------------
2022-06-27T14:09:52.9413808Z [INFO] Build Summary:
2022-06-27T14:09:52.9441805Z [INFO]   Passed: 3, Failed: 13, Errors: 0, Skipped: 0
2022-06-27T14:09:52.9442552Z [INFO] -------------------------------------------------
2022-06-27T14:09:52.9442871Z [ERROR] The following builds failed:
2022-06-27T14:09:52.9443325Z [ERROR] *  kie-maven-plugin-test-kjar-8-exec-model/pom.xml
2022-06-27T14:09:52.9443783Z [ERROR] *  kie-maven-plugin-test-kjar-7-exec-model/pom.xml
2022-06-27T14:09:52.9444525Z [ERROR] *  kie-maven-plugin-test-kjar-12/pom.xml
2022-06-27T14:09:52.9444964Z [ERROR] *  kie-maven-plugin-test-kjar-11-yes-generate/pom.xml
2022-06-27T14:09:52.9445423Z [ERROR] *  kie-maven-plugin-test-kjar-9-exec-model/pom.xml
2022-06-27T14:09:52.9446057Z [ERROR] *  kie-maven-plugin-test-kjar-10-yes-generate/pom.xml
2022-06-27T14:09:52.9446709Z [ERROR] *  kie-maven-plugin-test-kjar-7-no-exec-model/pom.xml
2022-06-27T14:09:52.9447182Z [ERROR] *  kie-maven-plugin-test-kjar-11-default/pom.xml
2022-06-27T14:09:52.9448653Z [ERROR] *  kie-maven-plugin-test-kjar-9-no-exec-model/pom.xml
2022-06-27T14:09:52.9449374Z [ERROR] *  kie-maven-plugin-test-kjar-8-no-exec-model/pom.xml
2022-06-27T14:09:52.9449966Z [ERROR] *  kie-maven-plugin-test-kjar-13/pom.xml
2022-06-27T14:09:52.9450389Z [ERROR] *  kie-maven-plugin-test-kjar-10-default/pom.xml
2022-06-27T14:09:52.9450986Z [ERROR] *  kie-maven-plugin-test-kjar-14-ruleunits/pom.xml
```

**Comment by gitgabrio** [comment]
> This change seems to cause many failures in the maven plugin tests, please investigate:
> 
> ```
> 2022-06-27T14:08:30.8334778Z [INFO] 
> 2022-06-27T14:08:30.8335521Z [INFO] --- maven-failsafe-plugin:2.22.1:integration-test (default) @ kie-maven-plugin ---
> 2022-06-27T14:08:30.8368283Z [INFO] 
> 2022-06-27T14:08:30.8371470Z [INFO] --- maven-invoker-plugin:2.0.0:run (integration-test) @ kie-maven-plugin ---
> 2022-06-27T14:08:30.9979403Z [INFO] Building: kie-maven-plugin-test-kjar-setup/pom.xml
> 2022-06-27T14:08:39.0186150Z [INFO] ..SUCCESS (8.0 s)
> 2022-06-27T14:08:39.0222855Z [INFO] Building: kie-maven-plugin-test-kjar-8-exec-model/pom.xml
> 2022-06-27T14:08:48.4280675Z [INFO] ..FAILED (9.4 s)
> 2022-06-27T14:08:48.4282236Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-exec-model/build.log for details.
> 2022-06-27T14:08:48.4301272Z [INFO] Building: kie-maven-plugin-test-kjar-7-exec-model/pom.xml
> 2022-06-27T14:08:51.7807443Z [INFO] ..FAILED (3.4 s)
> 2022-06-27T14:08:51.7809188Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-exec-model/build.log for details.
> 2022-06-27T14:08:51.7821558Z [INFO] Building: kie-maven-plugin-test-kjar-12/pom.xml
> 2022-06-27T14:08:56.1317372Z [INFO] ..FAILED (4.3 s)
> 2022-06-27T14:08:56.1331402Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-12/build.log for details.
> 2022-06-27T14:08:56.1337518Z [INFO] Building: kie-maven-plugin-test-kjar-11-yes-generate/pom.xml
> 2022-06-27T14:08:59.9743872Z [INFO] ..FAILED (3.8 s)
> 2022-06-27T14:08:59.9762177Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-yes-generate/build.log for details.
> 2022-06-27T14:08:59.9763310Z [INFO] Building: kie-maven-plugin-test-kjar-9-exec-model/pom.xml
> 2022-06-27T14:09:03.6963579Z [INFO] ..FAILED (3.7 s)
> 2022-06-27T14:09:03.6965089Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-exec-model/build.log for details.
> 2022-06-27T14:09:03.6974669Z [INFO] Building: kie-maven-plugin-test-kjar-10-yes-generate/pom.xml
> 2022-06-27T14:09:07.4119538Z [INFO] ..FAILED (3.7 s)
> 2022-06-27T14:09:07.4121472Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-yes-generate/build.log for details.
> 2022-06-27T14:09:07.4123063Z [INFO] Building: kie-maven-plugin-test-kjar-3/pom.xml
> 2022-06-27T14:09:14.6728149Z [INFO] ..SUCCESS (7.3 s)
> 2022-06-27T14:09:14.6730760Z [INFO] Building: kie-maven-plugin-test-kjar-7-no-exec-model/pom.xml
> 2022-06-27T14:09:18.3623895Z [INFO] ..FAILED (3.7 s)
> 2022-06-27T14:09:18.3625491Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-7-no-exec-model/build.log for details.
> 2022-06-27T14:09:18.3627299Z [INFO] Building: kie-maven-plugin-test-kjar-11-default/pom.xml
> 2022-06-27T14:09:22.0134533Z [INFO] ..FAILED (3.6 s)
> 2022-06-27T14:09:22.0135986Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-11-default/build.log for details.
> 2022-06-27T14:09:22.0137162Z [INFO] Building: kie-maven-plugin-test-kjar-9-no-exec-model/pom.xml
> 2022-06-27T14:09:25.5834873Z [INFO] ..FAILED (3.6 s)
> 2022-06-27T14:09:25.5836325Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-9-no-exec-model/build.log for details.
> 2022-06-27T14:09:25.5837339Z [INFO] Building: kie-maven-plugin-test-kjar-8-no-exec-model/pom.xml
> 2022-06-27T14:09:33.3403117Z [INFO] ..FAILED (7.8 s)
> 2022-06-27T14:09:33.3404778Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-8-no-exec-model/build.log for details.
> 2022-06-27T14:09:33.3413421Z [INFO] Building: kie-maven-plugin-test-kjar-13/pom.xml
> 2022-06-27T14:09:36.7629267Z [INFO] ..FAILED (3.4 s)
> 2022-06-27T14:09:36.7634945Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-13/build.log for details.
> 2022-06-27T14:09:36.7635546Z [INFO] Building: kie-maven-plugin-test-kjar-10-default/pom.xml
> 2022-06-27T14:09:40.4372362Z [INFO] ..FAILED (3.7 s)
> 2022-06-27T14:09:40.4373930Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-10-default/build.log for details.
> 2022-06-27T14:09:40.4375776Z [INFO] Building: kie-maven-plugin-test-kjar-14-ruleunits/pom.xml
> 2022-06-27T14:09:43.7919580Z [INFO] ..FAILED (3.4 s)
> 2022-06-27T14:09:43.7922463Z [INFO]   The build exited with code 1. See /home/runner/work/drools/drools/kiegroup_drools/drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-14-ruleunits/build.log for details.
> 2022-06-27T14:09:43.7924509Z [INFO] Building: kie-maven-plugin-test-kjar-2/pom.xml
> 2022-06-27T14:09:52.9405201Z [INFO] ..SUCCESS (9.1 s)
> 2022-06-27T14:09:52.9413181Z [INFO] -------------------------------------------------
> 2022-06-27T14:09:52.9413808Z [INFO] Build Summary:
> 2022-06-27T14:09:52.9441805Z [INFO]   Passed: 3, Failed: 13, Errors: 0, Skipped: 0
> 2022-06-27T14:09:52.9442552Z [INFO] -------------------------------------------------
> 2022-06-27T14:09:52.9442871Z [ERROR] The following builds failed:
> 2022-06-27T14:09:52.9443325Z [ERROR] *  kie-maven-plugin-test-kjar-8-exec-model/pom.xml
> 2022-06-27T14:09:52.9443783Z [ERROR] *  kie-maven-plugin-test-kjar-7-exec-model/pom.xml
> 2022-06-27T14:09:52.9444525Z [ERROR] *  kie-maven-plugin-test-kjar-12/pom.xml
> 2022-06-27T14:09:52.9444964Z [ERROR] *  kie-maven-plugin-test-kjar-11-yes-generate/pom.xml
> 2022-06-27T14:09:52.9445423Z [ERROR] *  kie-maven-plugin-test-kjar-9-exec-model/pom.xml
> 2022-06-27T14:09:52.9446057Z [ERROR] *  kie-maven-plugin-test-kjar-10-yes-generate/pom.xml
> 2022-06-27T14:09:52.9446709Z [ERROR] *  kie-maven-plugin-test-kjar-7-no-exec-model/pom.xml
> 2022-06-27T14:09:52.9447182Z [ERROR] *  kie-maven-plugin-test-kjar-11-default/pom.xml
> 2022-06-27T14:09:52.9448653Z [ERROR] *  kie-maven-plugin-test-kjar-9-no-exec-model/pom.xml
> 2022-06-27T14:09:52.9449374Z [ERROR] *  kie-maven-plugin-test-kjar-8-no-exec-model/pom.xml
> 2022-06-27T14:09:52.9449966Z [ERROR] *  kie-maven-plugin-test-kjar-13/pom.xml
> 2022-06-27T14:09:52.9450389Z [ERROR] *  kie-maven-plugin-test-kjar-10-default/pom.xml
> 2022-06-27T14:09:52.9450986Z [ERROR] *  kie-maven-plugin-test-kjar-14-ruleunits/pom.xml
> ```

@mariofusco Where did you find this stack ? The "drools" build is green (and I verified also in my local machine....)

**Comment by mariofusco** [comment]
@gitgabrio see https://github.com/kiegroup/drools/runs/7073667444?check_suite_focus=true and the raw log of that run https://pipelines.actions.githubusercontent.com/serviceHosts/5329f228-3e6f-4cdb-9fdf-1dc9f059b6f9/_apis/pipelines/1/runs/8055/signedlogcontent/2?urlExpires=2022-06-28T07%3A40%3A45.0879869Z&urlSigningMethod=HMACV1&urlSignature=CY3j9JPwfv4OSXVuwbw%2BS4div0g6ZGZeWL2NaMZJZ3Q%3D

**Comment by gitgabrio** [comment]
> @gitgabrio see https://github.com/kiegroup/drools/runs/7073667444?check_suite_focus=true and the raw log of that run https://pipelines.actions.githubusercontent.com/serviceHosts/5329f228-3e6f-4cdb-9fdf-1dc9f059b6f9/_apis/pipelines/1/runs/8055/signedlogcontent/2?urlExpires=2022-06-28T07%3A40%3A45.0879869Z&urlSigningMethod=HMACV1&urlSignature=CY3j9JPwfv4OSXVuwbw%2BS4div0g6ZGZeWL2NaMZJZ3Q%3D

:+1:

**Comment by gitgabrio** [comment]
Jenkins (re)run drools tests

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
