### PR TITLE
[7.52.x] DROOLS-5844: Errors when executing models using imported inputs and/or decisions nodes - BC

### PR DESCRIPTION
**Pull request by yesamer**
… (#3460)

(cherry picked from commit b2b3042f01ed854063629518e76f3e6ca4625e36)

**JIRA**: https://issues.redhat.com/browse/DROOLS-5844

**referenced Pull Requests**: 

* https://github.com/kiegroup/drools/pull/3515
* https://github.com/kiegroup/drools-wb/pull/1478

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer.

**Review by jomarko — APPROVED** [review]
Thank you for cherry-pick

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
@kiegroup/gatekeepers can you please merge this PRs ensemble?

**Pull request merged**
