### PR TITLE
Backport MSF changes to fix IndexOutOfBoundsException on "" for trim path

### PR DESCRIPTION
**Pull request by ge0ffrey**
I needed to backport all 3 commits.

@mariofusco This includes the first commit which you originally didn't desire to have on 6.4.x too...

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Clearly something went wrong here. Figuring out what...

**Comment by psiroky** [comment]
@ge0ffrey wrong target branch?

**Comment by ge0ffrey** [comment]
yes :)

**Comment by ge0ffrey** [comment]
Here's the good PR: https://github.com/droolsjbpm/drools/pull/648

**Pull request closed without merging**
