### PR TITLE
DROOLS-1232 calling getQueryResults() from RHS would hang indefinitely.

### PR DESCRIPTION
**Pull request by tarilabs**
Proposed fix by:
- isolating layer by external public API and KnowledgeHelper ctx API
- modeling in the internal layer the information about being called by a
  rule's RHS.

### CODE REVIEW

**Comment by tarilabs** [comment]
Hi @psiroky , question for you, please?

github integration here says "Build finished. 5081 tests run, 84 skipped, 0 failed." but I get a big red cross for "all checks have failed" with "1 failing check". ref screenshot:
image

I've also checked internal Jenkins job: no failures, no merge conflicts, etc.

Hence I'm a bit puzzled: can you kindly help me to understand what's wrong, please?

**Comment by mrietveld** [comment]
@tarilabs Please check the console output from the build. It shows the following: 

```
18:21:36 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project drools-reteoo: Compilation failure
18:21:36   return type requires unchecked conversion from SessionClock to T
18:21:36   where T is a type-variable:
18:21:36     T extends SessionClock declared in method <T>getSessionClock()
18:21:36 /home/jenkins/workspace/drools-pullrequests/drools-reteoo/src/main/java/org/drools/reteoo/common/ReteWorkingMemory.java:[205,4] error: method does not override or implement a method from a supertype
18:21:36 
18:21:36    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
18:21:36    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
18:21:36    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
18:21:36    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
18:21:36    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
18:21:36    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
18:21:36    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:21:36    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
18:21:36    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:21:36    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
18:21:36    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
18:21:36    at java.lang.Thread.run(Thread.java:745)
18:21:36 Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
18:21:36   return type requires unchecked conversion from SessionClock to T
18:21:36   where T is a type-variable:
18:21:36     T extends SessionClock declared in method <T>getSessionClock()
18:21:36 /home/jenkins/workspace/drools-pullrequests/drools-reteoo/src/main/java/org/drools/reteoo/common/ReteWorkingMemory.java:[205,4] error: method does not override or implement a method from a supertype
18:21:36 
18:21:36    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:972)
18:21:36    at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
18:21:36    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
18:21:36    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
18:21:36    ... 11 more
```

**Comment by psiroky** [comment]
I agree that the one-liner with the results is confusing in case the builds ends with error (like in this case with compilation error). Last time I checked (few months back), this was the limitation of the Jenkins plugin we use. Ideally it should just say "Build error!". I will check if this got fixed.

As Marco pointed out (thanks!), you will always find the actual build error in the jenkins build log.

**Comment by tarilabs** [comment]
Many thanks @mrietveld , @psiroky for your feedback

**Comment by tarilabs** [comment]
Notes:
- I've modified `WorkingMemory.getQueryResults` to return `QueryResults` instead of `QueryResultsImpl` as I got compiler issues and I think is also cleaner this way.
- There is not an issue with RHS calling Insert and then getQueryResults, as the `StatefulKnowledgeSessionImpl` method for getQueryResult even in earlier version had an explicit call to flush propagations.

**Pull request merged**
