### PR TITLE
[DROOLS-6017] Move test cases from drools-mvel to drools-test-coverag…

### PR DESCRIPTION
**Pull request by tkobayas**
…e : 3rd round

Move almost all tests from drools-mvel to drools-test-coverage/test-compiler-integration except:

- Tests in org.drools.mvel.compiler.phreak and org.drools.mvel.compiler.beliefsystem.defeasible because @lucamolteni  is working on them in https://github.com/kiegroup/drools/pull/3383 now
- Explicit unit tests for classes of drools-mvel. e.g. MVELCalendarCoercionTest
- Classes which other projects depend on. e.g. SimpleBatchExecutionTest, MoreBatchExecutionTest, SerializationHelper, IteratorToList ... I will move them (or change the dependency) in another JIRA
- Also we may clean up some unused classes in the test package. I will revisit in another JIRA.

Again, they are not yet modified to test with exec-model.

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6017

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
@lucamolteni  As I wrote in the first comment, I try to move most of test cases. Is there any conflict with your current work (https://github.com/kiegroup/drools/pull/3383) ? Or if you have any thoughts about the move (e.g. want to move XXXTest to a different place), feel free to let me know. Thanks!

**Comment by lucamolteni** [comment]
> @lucamolteni As I wrote in the first comment, I try to move most of test cases. Is there any conflict with your current work (#3383) ? Or if you have any thoughts about the move (e.g. want to move XXXTest to a different place), feel free to let me know. Thanks!

So far it's perfect thank you

**Comment by tkobayas** [comment]
Jenkins run cdb

**Comment by tkobayas** [comment]
Jenkins run cdb

**Comment by tkobayas** [comment]
[TEST BUILD CHAIN] Linux - Compile Downstream Build:
```
[2021-02-18T03:45:28.628Z] [INFO] Copying files to /home/jenkins/workspace/custom/mbiarnes/compile/drools-master.compile/build_chain_20211172286/kiegroup_jbpm/jbpm-distribution/target/jbpm-7.51.0-SNAPSHOT-bin-src-docs-examples
[2021-02-18T03:45:30.002Z] [WARNING] Assembly file: /home/jenkins/workspace/custom/mbiarnes/compile/drools-master.compile/build_chain_20211172286/kiegroup_jbpm/jbpm-distribution/target/jbpm-7.51.0-SNAPSHOT-bin-src-docs-examples is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.
[2021-02-18T03:45:30.260Z] [WARNING] Cannot include project artifact: org.jbpm:jbpm-distribution:pom:7.51.0-SNAPSHOT; it doesn't have an associated file or directory.
[2021-02-18T03:45:32.158Z] [WARNING] Cannot include project artifact: org.jbpm:jbpm-distribution:pom:7.51.0-SNAPSHOT; it doesn't have an associated file or directory.
[2021-02-18T03:45:32.158Z] [WARNING] Cannot include project artifact: org.jbpm:jbpm-distribution:pom:7.51.0-SNAPSHOT; it doesn't have an associated file or directory.
[2021-02-18T03:45:33.533Z] [INFO] Building zip: /home/jenkins/workspace/custom/mbiarnes/compile/drools-master.compile/build_chain_20211172286/kiegroup_jbpm/jbpm-distribution/target/jbpm-7.51.0-SNAPSHOT-bin-src-docs-examples.zip
[2021-02-18T03:45:34.941Z] [INFO] FAILURE build of project org.jbpm:jbpm-distribution
[2021-02-18T03:45:34.941Z] [INFO] Builder state: blocked=0 finished=73 ready-or-running=0
...
[2021-02-18T03:45:34.941Z] [INFO] jBPM :: Distribution ............................... FAILURE [02:37 min]
```
I'm not sure about the cause of the failure but it doesn't seem to be related to this PR.

**Comment by tkobayas** [comment]
Hi @lucamolteni @mariofusco @hellowdan  Please review this PR. Nowadays CDB doesn't run smoothly but I think this change doesn't affect other projects (`jbpm/jbpm-flow-builder` depends on `drools-mvel` test-jar but I tested it locally)

**Review by hellowdan — APPROVED** [review]

**Comment by tkobayas** [comment]
Jenkins run cdb

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
