### PR TITLE
Add test cases for extending POJO classes

### PR DESCRIPTION
**Pull request by acwest-cc**
This adds test cases for extending POJO classes in DRL. testDeclarationWithPojoExtensionDifferentPackage currently fails, but I don't see that it should.

testDeclarationWithPojoExtensionMultiplePackages is a working version of a case that fails for me when I load rules incrementally, I am working on a test case that fails now. I can currently only cause it to fail using thr Drools 5 API

### CODE REVIEW

**Comment by mdproctor** [comment]
"I can currently only cause it to fail using thr Drools 5 API"? 
The test passes with Drools 6?

**Comment by acwest-cc** [comment]
testDeclarationWithPojoExtensionDifferentPackage is broken in Drools 6, but a similar test in Drools 5.5 would have worked, with a minor change in the content of the DRL.
The comment about the Drools 5 API was in reference to estDeclarationWithPojoExtensionMultiplePackages, which I am working on converting the Drools 5 code to the Drools 6 api. The drools 5 version of the test would be something like:

``` java
    @Test
    public void testDeclarationWithPojoExtensionMultiplePackages() throws Exception {
        String drlDeclare = "package org.drools.compiler.integrationtests\n" +
                     "declare Drools_applications extends org.drools.compiler.integrationtests.TypeDeclarationTest.BaseClass\n" +
                     "    drools_app_name: String\n" +
                     "end";
        String drlRule = "package org.drools.compiler.test\n" +
                     "rule R1 when\n" +
                     "   $fact : org.drools.compiler.integrationtests.Drools_applications( drools_app_name == \"appName\" )\n" +
                     "then\n" +
                     "end";

        org.drools.builder.KnowledgeBuilder kbuilder = org.drools.builder.KnowledgeBuilderFactory.newKnowledgeBuilder();
        kbuilder.add(org.drools.io.ResourceFactory.newReaderResource(new StringReader(drlDeclare)), org.drools.builder.ResourceType.DRL);
        org.drools.KnowledgeBase kbase = org.drools.KnowledgeBaseFactory.newKnowledgeBase();
        kbase.addKnowledgePackages(kbuilder.getKnowledgePackages());

        org.drools.builder.KnowledgeBuilder kbuilder2 = org.drools.builder.KnowledgeBuilderFactory.newKnowledgeBuilder(kbase);
        kbuilder2.add(org.drools.io.ResourceFactory.newReaderResource(new StringReader(drlRule)), org.drools.builder.ResourceType.DRL);
        // This line may not be necessary
        // kbase.addKnowledgePackages(kbuilder2.getKnowledgePackages());

        org.drools.runtime.StatefulKnowledgeSession ksession = kbase.newStatefulKnowledgeSession();

        org.drools.definition.type.FactType factType = kbase.getFactType( "org.drools.compiler.integrationtests", "Drools_applications" );
        Object fact = factType.newInstance();
        factType.set( fact, "drools_app_name", "appName" );
        ksession.insert( fact );

        int rules = ksession.fireAllRules();
        assertEquals( 1, rules );
    }
```

This code works in Drools 5, or is at least close to what is working, I haven't run this fragment specifically

**Comment by acwest-cc** [comment]
Here is my current version converted to Drools6, but I get an NPE because getFactType returns null

``` java
    @Test
    public void testUpdateWithPojoExtensionDifferentPackages() throws Exception {
        String drlDeclare = "package org.drools.compiler.integrationtests\n" +
                     "declare Drools_applications extends org.drools.compiler.integrationtests.TypeDeclarationTest.BaseClass\n" +
                     "    drools_app_name: String\n" +
                     "end";
        String drlRule = "package org.drools.compiler.test\n" +
                     "rule R1 when\n" +
                     "   $fact : org.drools.compiler.integrationtests.Drools_applications( drools_app_name == \"appName\" )\n" +
                     "then\n" +
                     "end";

        KieServices ks = KieServices.Factory.get();
        KieFileSystem kfs = ks.newKieFileSystem();
        //ReleaseId releaseId1 = ks.newReleaseId( "org.kie", "test-upgrade", "1.0-SNAPSHOT" );
        ReleaseId releaseId1 = ks.newReleaseId( "org.kie", "test-upgrade", "1.0.0" );

        KieBuilder kieBuilder = ks.newKieBuilder( kfs );

        kfs.generateAndWritePomXML( releaseId1 );
        kfs.write( ks.getResources()
                           .newReaderResource( new StringReader( drlDeclare ) )
                           .setResourceType( ResourceType.DRL )
                           .setSourcePath( "drlDeclare.drl" ) );

        kieBuilder.buildAll();

        KieContainer kc = ks.newKieContainer( releaseId1 );

        kfs.write( ks.getResources()
                           .newReaderResource( new StringReader( drlRule ) )
                           .setResourceType( ResourceType.DRL )
                           .setSourcePath( "drlRule.drl" ) );

        IncrementalResults results = ( (InternalKieBuilder) kieBuilder ).incrementalBuild();
        System.out.println( results.getAddedMessages() );
        assertEquals( 0, results.getAddedMessages().size() );

        ReleaseId releaseId2 = ks.newReleaseId( "org.kie", "test-upgrade", "1.1.0" );
        Results updateResults = kc.updateToVersion( releaseId2 );
        assertEquals( 0, updateResults.getMessages().size() );

        // Create a session and fire rules
        KieSession ksession = kc.newKieSession();
        FactType factType = kc.getKieBase().getFactType( "org.drools.compiler.integrationtests", "Drools_applications" );
        Object fact = factType.newInstance();
        factType.set( fact, "drools_app_name", "appName" );
        ksession.insert( fact );
        assertEquals( 1, ksession.fireAllRules() );
    }
```

**Comment by acwest-cc** [comment]
Should I re-do the pull request without the merge?

**Comment by acwest-cc** [comment]
Interestingly, once I fixed the Drools6 API version of this test, it works, so the problem is KnowledgeBuilder specific.
There are now 3 tests that fail:
testDeclarationWithPojoExtensionMultiplePackages, which is the failure I started with;
testDeclarationWithPojoExtensionDifferentPackage, which is an error extending a POJO in a different package;
testDeclarationWithPojoExtension, where setting a property from the POJO through the FactType doesn't work, although it IS a bean. I don't know if that should work or not, though. Even if it shouldn't work, I would expect it to fail with an error instead of failing silently

**Comment by mariofusco** [comment]
Test case incorporated and bug fixed with this pull request https://github.com/kiegroup/drools/pull/1156

**Pull request closed without merging**
