### PR TITLE
GUVNOR-2854: Fire rules of GDST that uses Resolved Hit Policy

### PR DESCRIPTION
**Pull request by jomarko**
Is blocked by https://issues.jboss.org/browse/GUVNOR-2940

### CODE REVIEW

**Comment by Rikkola** [comment]
Good test. I'll fix GUVNOR-2940.

**Comment by jomarko** [comment]
@Rikkola thanks. Actually, I used the time before fix to prepare more scenarios for this hit policy. I hope finish them soon. I will let you know when this is finished and ready for merge.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@Rikkola I am happy with my tests now. Please feel free to take a look when you have a moment.

**Review by Rikkola — APPROVED** [review]
Thanks. Good to have these tests in.

**Comment by jomarko** [comment]
Conflicts resolved.

**Pull request merged**
