### PR TITLE
AF-593: Decouple kie-wb-common-datamodel from Drools

### PR DESCRIPTION
**Pull request by mbarkley**

### CODE REVIEW

**Comment by mbarkley** [comment]
Related:
https://github.com/AppFormer/uberfire/pull/822
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/541
https://github.com/kiegroup/droolsjbpm-knowledge/pull/263
https://github.com/kiegroup/jbpm/pull/973
https://github.com/kiegroup/droolsjbpm-integration/pull/1163
https://github.com/kiegroup/kie-wb-common/pull/1133
https://github.com/kiegroup/drools-wb/pull/596
https://github.com/kiegroup/jbpm-designer/pull/654
https://github.com/kiegroup/jbpm-wb/pull/864
https://github.com/kiegroup/optaplanner-wb/pull/218

**Review by manstis — APPROVED** [review]

**Comment by manstis** [comment]
@mariofusco From what I understand this looks fine to me. 

I'd just appreciate your approval to the MVEL related changes and movement of ```TypeResolver``` and related implementation to the AppFormer repository.

**Comment by mbarkley** [comment]
@mariofusco Hate to be a nag, but are you able to look at this soon? Your approval regarding the `TypeResolver` and MVEL code moving to AppFormer is one of the last blockers to merge.

**Review by mariofusco — CHANGES_REQUESTED** [review]
Please keep the TypeResolver and all other core classes inside drools.

**Comment by mbarkley** [comment]
@mariofusco I've updated this PR (and sent a few new ones), and as we had discussed the project-datamodel has moved to the new kie-soup repo (PR [here](https://github.com/kiegroup/kie-soup/pull/3)).

Would you mind reviewing this again, and possibly the kie-soup PR as well?

**Review by mariofusco — APPROVED** [review]

**Comment by mariofusco** [comment]
The proposed change is ok for me. I just cannot be 100% sure that this doesn't break osgi (I'm afraid so), so please make sure that all osgi tests in droolsjbpm-integration are green before merging it.

**Comment by mbarkley** [comment]
No problem. The droolsjbpm-integration PR is green right now, so I think everything is working.

**Comment by manstis** [comment]
@kkufova Hi.. this, I believe, is the PR that probably broke marshalling.

It moves to discrete ```DSLConditionSentence``` and ```DSLActionSentence``` classes. It might simply be that @mbarkley needs to include these in the marshalling [configuration](https://github.com/mbarkley/drools/blob/c968253ba8270e48538a84b6e7cac5ca683d407c/drools-workbench-models/drools-workbench-models-datamodel-api/src/main/resources/META-INF/ErraiApp.properties); however I would worry that _old_ Guided Rule Templates and Guided Decision Tables that used DSLs may no longer open. We'd need to create both asset types in ```7.2``` (or something before these changes) and try to re-open with ```master```.

**Comment by kkufova** [comment]
@manstis, thank you! Here's the filed Jira: https://issues.jboss.org/browse/GUVNOR-3576.

**Pull request merged**
