### PR TITLE
[DROOLS-1078] fix class introspection in case of an overridden getter with a covariant return

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mariofusco** [comment]
ok to test

**Comment by mariofusco** [comment]
@etirelli Jenkins reported an intermittent problem with Misc2Test.testFunctionInvokingFunction. At the moment I'm not able to reproduce that failure (even running with 100 threads instead of 10) and I'm still trying to figure out if we could have a race condition somewhere in that area. Anyway this failure is totally unrelated with the fix in this PR.

**Comment by etirelli** [comment]
Fix looks good Mario. +1

**Comment by mariofusco** [comment]
Merged by https://github.com/droolsjbpm/drools/commit/bac3ffe30

**Pull request closed without merging**
