### PR TITLE
GUVNOR-3451 : GRE DSL: Multiline code blocks break the editor

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/GUVNOR-3451

### CODE REVIEW

**Review by jomarko — COMMENTED** [review]
@Rikkola Hi, code changes looks good to me, I am just wondering if the test `testDSLExpansionLHS` shouldn't be updated in the same way? WDYT?

**Comment by Rikkola** [comment]
```
String drl = "rule \"rule1\"\n"
                + "when\n"
                + "The credit rating is AA\n"
                + "then\n"
+ "end\n";
```

The code there does not have brackets, just DSL. In this case I would be in favor of keeping the test simple. 
Thought even if I just would make a new test for this situation, but ended up editing an old one with a comment. That is not necessary the best approach.

**Comment by manstis** [comment]
Personally I think a new test is preferential over modifying an existing test.

**Comment by Rikkola** [comment]
I was battling myself if I should make a new test. So now that others feel like there should be one, I'll make one. 
Probably better to isolate the problems into as simple tests as possible covering a the simple situation. Should give better protection for the future.

**Comment by Rikkola** [comment]
Ok. New test added that targets the bug.

**Review by jomarko — APPROVED** [review]
I filed issue to create more testcases https://issues.jboss.org/browse/GUVNOR-3458, approving this PR.

**Review by manstis — APPROVED** [review]

**Pull request merged**
