### PR TITLE
DROOLS-6023 DMN inline memoization of FEEL temporal literal constants

### PR DESCRIPTION
**Pull request by tarilabs**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6023

**referenced Pull Requests**: https://github.com/kiegroup/kie-benchmarks/pull/108

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins retest this

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins run cdb

**Comment by tarilabs** [comment]
CDB timeout with
```
12:05:38  [INFO] ------------------------------------------------------------------------
12:05:38  [INFO] Skipping KIE (Drools) Workbench Tests :: GUI
12:05:38  [INFO] This project has been banned from the build due to previous failures.
12:05:38  [INFO] ------------------------------------------------------------------------
12:05:38  [INFO] SKIPPED build of project org.kie:business-central-tests-gui
12:05:38  [INFO] Builder state: blocked=0 finished=18 ready-or-running=0 
12:05:38  [INFO] ------------------------------------------------------------------------
12:05:38  [INFO] Reactor Summary for Business Central - Distributions 7.51.0-SNAPSHOT:
12:05:38  [INFO] 
12:05:38  [INFO] Business Central - Distributions ................... SUCCESS [  4.973tee: write error
20:59:49  Cancelling nested steps due to timeout
20:59:49  Sending interrupt signal to process
21:00:09  After 20s process did not stop
```

Jenkins run cdb

**Comment by tarilabs** [comment]
CDB timeout with
```
03:51:26  [INFO] Drools Workbench - Enum Editor ..................... SUCCESS [  0.325 s]
03:51:26  [INFO] Drools Workbench - Enum Editor - API ............... SUCCESS [ 22.418 s]
03:51:26  [INFO] Drools Workbench - Enum Editor - Client ............ SUCCESS [ 34.068 s]
03:51:26  [INFO] Drools Workbench - Enum Editor - Backend ........tee: write error
```

Jenkins run cdb

**Comment by tarilabs** [comment]
CDB timeout due to `17:37:54  Caused by: java.io.IOException: No space left on device`

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
