### PR TITLE
Multithread

### PR DESCRIPTION
**Pull request by fbertola**
Enabled multithreaded KieProject compilation.

### CODE REVIEW

**Comment by mrietveld** [comment]
Note for future pull requests: changing all of the spacing in a class makes it _much_ harder to see exactly what's changed.

**Comment by psiroky** [comment]
+1. Also, please do not use tabs for indenting. Drools/jbpm code style requires 4 spaces.

**Comment by fbertola** [comment]
I'm sorry, compulsively formatting the code is second nature to me :)

Federico.

Il 30/06/2014 19:19, Petr Široký ha scritto:

**Comment by mariofusco** [comment]
Federico,

can you please squash your 6 commits and shortly explain what you did? Actually it would be great if you could reedit/redo the whole PR: at the moment it's nearly impossible to figure out what you changed.

Thanks,
Mario

**Pull request closed without merging**
