### PR TITLE
DROOLS-2317 FEEL Syntax error on function(bkm) containing `for` keyword

### PR DESCRIPTION
**Pull request by kurobako**
https://issues.jboss.org/browse/DROOLS-2317

### CODE REVIEW

**Comment by etirelli** [comment]
@kurobako this change looks good to me. We are having jenkins problems, did you try your change locally? if all tests pass, we can go ahead with the merge.

**Review by etirelli — APPROVED** [review]

**Comment by kurobako** [comment]
@etirelli in fact I was unable to verify these changes locally before sending a PR because latest master at the moment was failing tests locally. Do we have some tests running as part of the build process that depend on external infrastructure by chance? 
Well, anyway, today master tests worked fine for me but this branch did not. Surprisingly enough, FlightRebookingTest fails branch because somehow relaxing conditions for verifying name parts prevents flight numbers in the example to be evaluated properly. I guess it might have something to do with us selectively swallowing validation exceptions. I am investigating that and will update this PR soon.

**Comment by kurobako** [comment]
@etirelli @tarilabs @baldimir this will be complicated.
I investigated the reason why FlightRebookingTest fails: dmn files contain 'and' as part of literal expression, like this:
Flights[ From = Original Flight.From and To = Original Flight.To and Departure > Original Flight.Departure and Status = "scheduled" and has capacity( item, Rebooked ) ][1]

checkVariableNamePart, the function which behaviour I changed is used by ParserHelper.followUp method returning boolean; FlightRebookingTest works correctly only if "and" as name part is considered invalid and thus followUp returns false. We need followUp to return false in this situation otherwise FlightNumbers won't be evaluated.

Natually, in other cases like the one I was working on followUp returning false causes no viable alt error in antlr because we need antlr to follow up after encountering "for" and possibly other keywords as part of the variable name, like in:

Federal Tax for Item
Otherwise, antrl will think we have a malformed for expression here.
I might come up with the way to sew this together but I suggest we talk about a proper way to resolve this. Should followUp really be wired to checkVariableNamePart in the first place, maybe we can start thinking from there?

**Comment by tarilabs** [comment]
> FlightRebookingTest works correctly only if "and" as name part is considered invalid and thus followUp returns false

Unfortunately we cannot do that, as "and" is totally valid as part of a name.

At the moment the only general direction I could think of, would be to try having the follow-up to check if the current followup is a valid name AND the _current **total**_ followup is the beginning of any symbol name in the current scope. If you want, you can give it a try in this direction, but don't overspend efforts please in this direction as I believe is important for @etirelli to confirm is a valid one.

**Comment by kurobako** [comment]
@etirelli updated this PR. Very questionable workaround, but that's the best I was able to come up with without refactoring whole parser helper followup machinery.

**Review by etirelli — CHANGES_REQUESTED** [review]
@kurobako sorry, but I am not sure this change is correct now. This latest solution seems to be fixing the symptom, not the root cause. You shouldn't need a second list of keywords to bypass the check.

**Comment by kurobako** [comment]
jenkins retest this

**Comment by kurobako** [comment]
@etirelli fair enough. I updated this PR.

**Comment by kurobako** [comment]
@etirelli this PR was updated, please take another look

**Review by etirelli — APPROVED** [review]

**Comment by etirelli** [comment]
@kurobako looks better now! thanks!

@tarilabs can you please double check and merge if everything is ok?

**Pull request merged**
