### PR TITLE
[7.59.x] [DROOLS-6611] parse an and constraint with a variable bound on the ri…

### PR DESCRIPTION
**Pull request by tkobayas**
…ght (#3846)

* [DROOLS-6611] parse an and constraint with a variable bound on the right

* also fix for 3 bound constraints

**JIRA**: 
* https://issues.redhat.com/browse/RHDM-1820
    * Backport DROOLS-6611 to 7.59.x

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins run cdb

**Comment by tkobayas** [comment]
GHA Build Chain / Maven Build (windows-latest, 8) Not related to this PR.
```
2022-01-13T10:27:58.1094902Z [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 134.681 s <<< FAILURE! - in org.kie.dmn.feel.client.showcase.FEELShowcaseIT
2022-01-13T10:27:58.1096873Z [ERROR] testEvaluation(org.kie.dmn.feel.client.showcase.FEELShowcaseIT)  Time elapsed: 132.609 s  <<< ERROR!
2022-01-13T10:27:58.1098429Z org.openqa.selenium.TimeoutException:
2022-01-13T10:27:58.1099954Z No connection could be made because the target machine actively refused it. (os error 10061)
```

Build Chain / Maven Build (windows-latest, 11) Not related to this PR.
```
2022-01-13T10:49:16.7757622Z [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 133.386 s <<< FAILURE! - in org.kie.dmn.feel.client.showcase.FEELShowcaseIT
2022-01-13T10:49:16.7763061Z [ERROR] testEvaluation(org.kie.dmn.feel.client.showcase.FEELShowcaseIT)  Time elapsed: 131.615 s  <<< ERROR!
2022-01-13T10:49:16.7765162Z org.openqa.selenium.TimeoutException:
2022-01-13T10:49:16.7767421Z No connection could be made because the target machine actively refused it. (os error 10061)
...
2022-01-13T11:13:02.5306237Z [ERROR] Tests run: 82, Failures: 2, Errors: 0, Skipped: 4, Time elapsed: 30.625 s <<< FAILURE! - in org.drools.compiler.integrationtests.TimerAndCalendarTest
2022-01-13T11:13:02.5308821Z [ERROR] testDurationWithNoLoop[KieBase type=STREAM_IDENTITY_MODEL_PATTERN](org.drools.compiler.integrationtests.TimerAndCalendarTest)  Time elapsed: 1.966 s  <<< FAILURE!
...
2022-01-13T11:13:02.5955849Z [ERROR] testIntervalRuleInsertion[KieBase type=STREAM_IDENTITY_MODEL_PATTERN](org.drools.compiler.integrationtests.TimerAndCalendarTest)  Time elapsed: 0.844 s  <<< FAILURE!
```

CDB failure. Not related to this PR.
```
[2022-01-17T16:21:30.645Z] [INFO] Business Central - Webapp .......................... FAILURE [02:16 min]
...
[2022-01-17T16:21:30.903Z] [ERROR] Failed to execute goal org.wildfly.plugins:wildfly-jar-maven-plugin:4.1.0.Final:package (default) on project business-central-webapp: Packaging wildfly failed: InvocationTargetException: java.util.concurrent.ExecutionException: org.jboss.as.cli.CommandLineException: Cannot start embedded server: WFLYEMB0022: Cannot invoke 'start' on embedded process: WFLYEMB0021: Cannot start embedded process: JBTHR00005: Operation failed: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details. -> [Help 1]
[2022-01-17T16:21:30.903Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.plugins:wildfly-jar-maven-plugin:4.1.0.Final:package (default) on project business-central-webapp: Packaging wildfly failed
[2022-01-17T16:21:30.903Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2022-01-17T16:21:30.903Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2022-01-17T16:21:30.903Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2022-01-17T16:21:30.903Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2022-01-17T16:21:30.903Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2022-01-17T16:21:30.903Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2022-01-17T16:21:30.903Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
[2022-01-17T16:21:30.903Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
[2022-01-17T16:21:30.903Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
[2022-01-17T16:21:30.903Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
[2022-01-17T16:21:30.903Z]     at java.lang.Thread.run (Thread.java:829)
...
[2022-01-17T16:21:30.905Z] Caused by: java.lang.Exception: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
[2022-01-17T16:21:30.905Z]     at org.jboss.as.server.BootstrapListener.bootFailure (BootstrapListener.java:87)
[2022-01-17T16:21:30.905Z]     at org.jboss.as.server.ServerService.boot (ServerService.java:434)
[2022-01-17T16:21:30.905Z]     at org.jboss.as.controller.AbstractControllerService$1.run (AbstractControllerService.java:416)
[2022-01-17T16:21:30.905Z]     at java.lang.Thread.run (Thread.java:829)
```

**Comment by tkobayas** [comment]
@mariofusco  Please merge this backport PR. Thanks!

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
