### PR TITLE
DROOLS-1797 : Incorrect V&V results when operator is filled in the row

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-1797

Part of a bundle:
https://github.com/kiegroup/drools/pull/2289
https://github.com/kiegroup/drools-wb/pull/1104

### CODE REVIEW

**Comment by Rikkola** [comment]
And no laughing at my broken copy&paste!

**Comment by Rikkola** [comment]
Windows is the desktop of 2019.

**Comment by jomarko** [comment]
Looks fine however I think we should cleanup the tests, I prepared PR that you can just merge into your fork and this PR will be updated automatically. https://github.com/Rikkola/drools/pull/1

**Review by manstis — APPROVED** [review]

**Review by jomarko — APPROVED** [review]
Thank you!

**Pull request merged**
