### PR TITLE
[KIE-781] Improve performance of InfixOpNode

### PR DESCRIPTION
**Pull request by mariofusco**
This is a fix for the performance issue reported with [this comment](https://github.com/apache/incubator-kie-drools/pull/5621#issuecomment-1860946943). 

Running the same benchmark against this commit I got the following results
```
Benchmark                  (argsType)   Mode  Cnt     Score    Error   Units
FEELInfixOpBenchmark.eval      String  thrpt   10  4398.719 ± 12.653  ops/ms
FEELInfixOpBenchmark.eval         int  thrpt   10  4303.348 ± 17.151  ops/ms
```
that are much better of the current situation but also around 20% faster than what we had on 8.44.0.Final that was
```
Benchmark                  (argsType)   Mode  Cnt     Score    Error   Units
FEELInfixOpBenchmark.eval      String  thrpt   10  3866.743 ± 30.992  ops/ms
FEELInfixOpBenchmark.eval         int  thrpt   10  3367.492 ± 11.529  ops/ms
```
I believe that there is still room for improvement, but this seems a step in the right direction that however will need to be validated with more extensive benchmarks before being merged.

### CODE REVIEW

**Comment by gitgabrio** [comment]
Thanks @mariofusco 
FYI I just pushed specific benchmarks [here](https://github.com/apache/incubator-kie-benchmarks/pull/281) (under org.drools.benchmarks.dmn.feel.infixexecutors) 
Maybe you can give them a try

**Comment by mariofusco** [comment]
The failures seems to be totally unrelated with this pull request. In particular I see that the failure of the build of `KIE :: Drools DMN engine Maven Archetype` is caused by this:
```
2023-12-19T17:13:49.5295647Z [INFO] Project created from Archetype in dir: /home/runner/work/incubator-kie-drools/incubator-kie-drools/apache_incubator-kie-drools/kie-archetypes/kie-drools-dmn-archetype/target/test-classes/projects/integrationtestDefaults/project/basic
2023-12-19T17:13:49.5300304Z [INFO] Comparing generated project with reference content: /home/runner/work/incubator-kie-drools/incubator-kie-drools/apache_incubator-kie-drools/kie-archetypes/kie-drools-dmn-archetype/target/test-classes/projects/integrationtestDefaults/reference
2023-12-19T17:13:49.5326002Z [WARNING] Contents of file pom.xml are not equal
```
but I'm totally unable to reproduce this problem locally, it successful for me and indeed the generated pom is identical to the expected one. Any clue on how we can further investigate this issue?

**Comment by gitgabrio** [comment]
> The failures seems to be totally unrelated with this pull request. In particular I see that the failure of the build of `KIE :: Drools DMN engine Maven Archetype` is caused by this:
> 
> ```
> 2023-12-19T17:13:49.5295647Z [INFO] Project created from Archetype in dir: /home/runner/work/incubator-kie-drools/incubator-kie-drools/apache_incubator-kie-drools/kie-archetypes/kie-drools-dmn-archetype/target/test-classes/projects/integrationtestDefaults/project/basic
> 2023-12-19T17:13:49.5300304Z [INFO] Comparing generated project with reference content: /home/runner/work/incubator-kie-drools/incubator-kie-drools/apache_incubator-kie-drools/kie-archetypes/kie-drools-dmn-archetype/target/test-classes/projects/integrationtestDefaults/reference
> 2023-12-19T17:13:49.5326002Z [WARNING] Contents of file pom.xml are not equal
> ```
> 
> but I'm totally unable to reproduce this problem locally, it successful for me and indeed the generated pom is identical to the expected one. Any clue on how we can further investigate this issue?

Could it be related to depenbdabot changes ?

`<version.logback>1.2.9</version.logback> -> <version.logback>1.2.13</version.logback>
`

immagine

https://github.com/apache/incubator-kie-drools/pull/5613
https://github.com/apache/incubator-kie-drools/pull/5614
https://github.com/apache/incubator-kie-drools/pull/5615
https://github.com/apache/incubator-kie-drools/pull/5616

**Review by baldimir — APPROVED** [review]

**Review by gitgabrio — APPROVED** [review]
Thanks @mariofusco nice improvements!

**Pull request merged**
