### PR TITLE
StaticImports are copied into new package instance

### PR DESCRIPTION
**Pull request by KarelCemus**
During the knowledge base process, constructed KnowledgePackages are cloned and then also manually copied into new instances. During that merge some information losts, e.g. record of static imports of function.

This pull request fixes the merge function by copying also the static imports. The functionality is required for developers (as me) programatically dealing with knowledge packages inside of knowledge base.

If the pull request will be approved I will publish another to merge it into upcoming version of 6.2.x

### CODE REVIEW

**Comment by etirelli** [comment]
@KarelCemus thank you! Can you provide a test case with your PR to avoid regressions in the future please?

@mariofusco can you please review and merge this?

**Comment by KarelCemus** [comment]
@etirelli I added the test case as you asked for. I hope it's fine.

**Comment by KarelCemus** [comment]
@etirelli What's the progress? Anything required to do to have this pull request merged? Thanks

**Comment by mariofusco** [comment]
I merged your PR and cherry-picked your fix to 6.2.x branch.
Thanks a lot and sorry for my delay.

**Comment by KarelCemus** [comment]
Thanks a lot

**Pull request merged**
