### PR TITLE
DROOLS-5888 : Comments starting with ruletable without a space should work

### PR DESCRIPTION
**Pull request by Rikkola**
**Thank you for submitting this pull request**

**JIRA**:  

[DROOLS-5888](https://issues.redhat.com/browse/DROOLS-5888)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Hi @jstastny-cz opening this for reviews, but no need to review it this week.

**Comment by jstastny-cz** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Looks like the dependencies were out of sync

**Comment by Rikkola** [comment]
" No artifacts found that match the file pattern "**/target/jbpm-server*dist*.zip". Configuration error?"

Jenkins retest this

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Comment by Rikkola** [comment]
Jenkins retest this

**Review by jstastny-cz — APPROVED** [review]
LGTM, thanks.

(There's possibly one other issue, will be tracked separately.)

**Comment by Rikkola** [comment]
@karreiro I changed the XLS file to have the issue. The actual fix is then 2 lines. If you could review the fix please.

**Review by karreiro — APPROVED** [review]
Thank you, @Rikkola LGTM!

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Among other things:
`[2021-03-03T17:23:31.207Z] No artifacts found that match the file pattern "**/target/jbpm-server*dist*.zip". Configuration error?`
Jenkins retest this

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Can I get a merge please.

**Pull request merged**
