### PR TITLE
DROOLS-4871 : Complex value list doesn't work in guided rule editor

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.redhat.com/browse/DROOLS-4871

Part one of the fix. This fixes from file to editor change.

https://github.com/kiegroup/drools/pull/2689
https://github.com/kiegroup/drools-wb/pull/1273

### CODE REVIEW

**Comment by Rikkola** [comment]
@jomarko @manstis Here the fix has two parts. One from file to editor model and another for situations when the same data is moved from model to file. If you could give me some feedback and review I would appreciate it.

**Review by manstis — COMMENTED** [review]
@jomarko (as author of the original test), @Rikkola I was expecting the constraint value to be `"a", "b, something", "c()"` i.e. preserving the quotes around `"a"` and `"c()"` however I see the test expects these quotes to be removed. Is this correct?

**Review by manstis — APPROVED** [review]
OK, I see there's some other black magic going on with the conversion back to DRL.

Works well :-)

**Review by jomarko — APPROVED** [review]
Approving 1/2

**Pull request merged**
