### PR TITLE
RHPAM-2377 It is not possible to initialize DMNRuntime in OSGI

### PR DESCRIPTION
**Pull request by tarilabs**
/cc @etirelli @jiripetrlik @baldimir

### CODE REVIEW

**Comment by tarilabs** [comment]
jenkins execute full downstream build

**Review by jiripetrlik — APPROVED** [review]
Looks good to me. I think we can merge if PR check is green.

**Comment by tarilabs** [comment]
```
org.kie.maven.plugin.AdditionalPropertiesIntegrationTest.testAdditionalPropertiesCorrectlySet[3.3.9]
org.kie.maven.plugin.AdditionalPropertiesIntegrationTest.testAdditionalPropertiesCorrectlySet[3.5.0]
org.kie.maven.plugin.BuildMojoIntegrationTest.testCleanInstallWithAllSupportedResourceTypes[3.3.9]
org.kie.maven.plugin.BuildMojoIntegrationTest.testCleanInstallWithAllSupportedResourceTypes[3.5.0]
org.kie.maven.plugin.InjectReactiveIntegrationTest.testBasicBytecodeInjection[3.3.9]
org.kie.maven.plugin.InjectReactiveIntegrationTest.testBasicBytecodeInjectionSelected[3.3.9]
org.kie.maven.plugin.InjectReactiveIntegrationTest.testBasicBytecodeInjection[3.5.0]
org.kie.maven.plugin.InjectReactiveIntegrationTest.testBasicBytecodeInjectionSelected[3.5.0]
org.kie.maven.plugin.KJarWithDMNIntegrationTest.testComplexDMNModelWithExecutableModel[3.3.9]
org.kie.maven.plugin.KJarWithDMNIntegrationTest.testCleanInstall[3.3.9]
org.kie.maven.plugin.KJarWithDMNIntegrationTest.testComplexDMNModel[3.3.9]
org.kie.maven.plugin.KJarWithDMNIntegrationTest.testComplexDMNModelWithExecutableModel[3.5.0]
org.kie.maven.plugin.KJarWithDMNIntegrationTest.testCleanInstall[3.5.0]
org.kie.maven.plugin.KJarWithDMNIntegrationTest.testComplexDMNModel[3.5.0]
org.kie.maven.plugin.BuildPMMLTest.testUseBuildKjarWithPMML[3.3.9]
org.kie.maven.plugin.BuildPMMLTest.testContentKjarWithPMML[3.3.9]
org.kie.maven.plugin.BuildPMMLTest.testCleanInstallWithPMML[3.3.9]
org.kie.maven.plugin.BuildPMMLTest.testUseBuildKjarWithPMML[3.5.0]
org.kie.maven.plugin.BuildPMMLTest.testContentKjarWithPMML[3.5.0]
org.kie.maven.plugin.BuildPMMLTest.testCleanInstallWithPMML[3.5.0]
org.kie.maven.plugin.DeclaredTypesTest.testDeclaredTypeWithJavaField[3.3.9]
org.kie.maven.plugin.DeclaredTypesTest.testDeclaredTypeWithJavaFieldExecutableModel[3.3.9]
org.kie.maven.plugin.DeclaredTypesTest.testDeclaredTypeWithJavaField[3.5.0]
org.kie.maven.plugin.DeclaredTypesTest.testDeclaredTypeWithJavaFieldExecutableModel[3.5.0]
org.kie.maven.plugin.MultiModuleTest.testMultiModule[3.3.9]
org.kie.maven.plugin.MultiModuleTest.testMultiModuleWithExecutableModel[3.3.9]
org.kie.maven.plugin.MultiModuleTest.testMultiModule[3.5.0]
org.kie.maven.plugin.MultiModuleTest.testMultiModuleWithExecutableModel[3.5.0]
org.kie.maven.takari.plugin.AdditionalPropertiesIntegrationTakariTest.testAdditionalPropertiesCorrectlySet[3.3.9]
org.kie.maven.takari.plugin.AdditionalPropertiesIntegrationTakariTest.testAdditionalPropertiesCorrectlySet[3.5.0]
org.kie.maven.takari.plugin.BuildMojoIntegrationTakariTest.testCleanInstallWithAllSupportedResourceTypes[3.3.9]
org.kie.maven.takari.plugin.BuildMojoIntegrationTakariTest.testCleanInstallWithAllSupportedResourceTypes[3.5.0]
org.kie.maven.takari.plugin.InjectReactiveIntegrationTakariTest.testBasicBytecodeInjection[3.3.9]
org.kie.maven.takari.plugin.InjectReactiveIntegrationTakariTest.testBasicBytecodeInjectionSelected[3.3.9]
org.kie.maven.takari.plugin.InjectReactiveIntegrationTakariTest.testBasicBytecodeInjection[3.5.0]
org.kie.maven.takari.plugin.InjectReactiveIntegrationTakariTest.testBasicBytecodeInjectionSelected[3.5.0]
org.kie.server.integrationtests.jbpm.ContainerUpdateUiIntegrationTest.org.kie.server.integrationtests.jbpm.ContainerUpdateUiIntegrationTest
org.kie.server.integrationtests.jbpm.DecisionTasksIntegrationTest.org.kie.server.integrationtests.jbpm.DecisionTasksIntegrationTest
org.kie.server.integrationtests.jbpm.DeploymentDescriptorIntegrationTest.org.kie.server.integrationtests.jbpm.DeploymentDescriptorIntegrationTest
org.kie.server.integrationtests.jbpm.FailureOnContainerDisposeIntegrationTest.org.kie.server.integrationtests.jbpm.FailureOnContainerDisposeIntegrationTest
org.kie.server.integrationtests.jbpm.FormServiceIntegrationTest.org.kie.server.integrationtests.jbpm.FormServiceIntegrationTest
org.kie.server.integrationtests.jbpm.ImageServiceIncludedKieBaseIntegrationTest.org.kie.server.integrationtests.jbpm.ImageServiceIncludedKieBaseIntegrationTest
org.kie.server.integrationtests.jbpm.ImageServiceIntegrationTest.org.kie.server.integrationtests.jbpm.ImageServiceIntegrationTest
org.kie.server.integrationtests.jbpm.PerProcessInstanceIntegrationTest.org.kie.server.integrationtests.jbpm.PerProcessInstanceIntegrationTest
org.kie.server.integrationtests.jbpm.RenderFormServiceIntegrationTest.org.kie.server.integrationtests.jbpm.RenderFormServiceIntegrationTest
org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest.org.kie.server.integrationtests.jbpm.RuleRelatedProcessIntegrationTest
org.kie.server.integrationtests.jbpm.cases.CarInsuranceClaimCaseIntegrationTest.org.kie.server.integrationtests.jbpm.cases.CarInsuranceClaimCaseIntegrationTest
org.kie.server.integrationtests.jbpm.cases.CaseAdminServiceIntegrationTest.org.kie.server.integrationtests.jbpm.cases.CaseAdminServiceIntegrationTest
org.kie.server.integrationtests.jbpm.cases.CaseInstanceMigrationIntegrationTest.org.kie.server.integrationtests.jbpm.cases.CaseInstanceMigrationIntegrationTest
org.kie.server.integrationtests.jbpm.cases.CaseSLAComplianceIntegrationTest.org.kie.server.integrationtests.jbpm.cases.CaseSLAComplianceIntegrationTest
org.kie.server.integrationtests.jbpm.cases.CaseServiceIntegrationTest.org.kie.server.integrationtests.jbpm.cases.CaseServiceIntegrationTest
org.kie.server.integrationtests.jbpm.rest.FormServiceRestOnlyIntegrationTest.org.kie.server.integrationtests.jbpm.rest.FormServiceRestOnlyIntegrationTest
org.kie.server.integrationtests.jbpm.rest.FormServiceRestSubFormsIntegrationTest.org.kie.server.integrationtests.jbpm.rest.FormServiceRestSubFormsIntegrationTest
org.kie.server.integrationtests.jbpm.rest.ImageServiceRestOnlyIntegrationTest.org.kie.server.integrationtests.jbpm.rest.ImageServiceRestOnlyIntegrationTest
org.kie.server.integrationtests.jbpm.rest.PerProcessInstanceWorkItemRestOnlyIntegrationTest.org.kie.server.integrationtests.jbpm.rest.PerProcessInstanceWorkItemRestOnlyIntegrationTest
org.kie.server.integrationtests.jbpm.rest.RenderFormServiceRestOnlyIntegrationTest.org.kie.server.integrationtests.jbpm.rest.RenderFormServiceRestOnlyIntegrationTest
org.kie.server.integrationtests.jbpm.rest.StackTraceIncludedIntegrationTest.org.kie.server.integrationtests.jbpm.rest.StackTraceIncludedIntegrationTest
org.kie.server.integrationtests.jbpm.rest.cases.CaseServiceRestOnlyIntegrationTest.org.kie.server.integrationtests.jbpm.rest.cases.CaseServiceRestOnlyIntegrationTest
org.kie.server.integrationtests.prometheus.PrometheusIntegrationTest.org.kie.server.integrationtests.prometheus.PrometheusIntegrationTest
org.kie.server.integrationtests.policy.CustomCaseIdIntegrationTest.org.kie.server.integrationtests.policy.CustomCaseIdIntegrationTest
org.kie.server.integrationtests.controller.ContainerConfigPropagationIntegrationTest.org.kie.server.integrationtests.controller.ContainerConfigPropagationIntegrationTest
org.kie.server.integrationtests.controller.KieControllerStartupIntegrationTest.org.kie.server.integrationtests.controller.KieControllerStartupIntegrationTest
org.kie.server.integrationtests.controller.RestKieControllerRuntimeManagementIntegrationTest.org.kie.server.integrationtests.controller.RestKieControllerRuntimeManagementIntegrationTest
org.kie.server.integrationtests.controller.WebSocketKieControllerNotificationIntegrationTest.org.kie.server.integrationtests.controller.WebSocketKieControllerNotificationIntegrationTest
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testUpgradeNotExistingContainer[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:45275/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testStartScannerNotExistingContainer[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:45275/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testStopScannerNotExistingContainer[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:45275/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testStopNotRunningScanner[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:45275/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testStartAndStopScanner[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:45275/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testScanNow[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:45275/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuleCapabilitiesIntegrationTest.testScanNowNotExistingContainer[0: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:45275/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.controller.WebSocketKieControllerRuntimeManagementIntegrationTest.org.kie.server.integrationtests.controller.WebSocketKieControllerRuntimeManagementIntegrationTest
org.kie.server.integrationtests.controller.WebSocketKieControllerStartupIntegrationTest.org.kie.server.integrationtests.controller.WebSocketKieControllerStartupIntegrationTest
org.kie.server.integrationtests.extension.custom.CustomExtensionIntegrationTest.org.kie.server.integrationtests.extension.custom.CustomExtensionIntegrationTest
org.kie.server.integrationtests.extension.custom.PrometheusCustomExtensionIntegrationTest.org.kie.server.integrationtests.extension.custom.PrometheusCustomExtensionIntegrationTest
org.kie.server.integrationtests.dmn.DMNBkmJavaIntegrationTest.org.kie.server.integrationtests.dmn.DMNBkmJavaIntegrationTest
org.kie.server.integrationtests.dmn.DMNDecisionServiceIntegrationTest.org.kie.server.integrationtests.dmn.DMNDecisionServiceIntegrationTest
org.kie.server.integrationtests.dmn.DMNGetModels2IntegrationTest.org.kie.server.integrationtests.dmn.DMNGetModels2IntegrationTest
org.kie.server.integrationtests.dmn.DMNGetModelsIntegrationTest.org.kie.server.integrationtests.dmn.DMNGetModelsIntegrationTest
org.kie.server.integrationtests.dmn.DMNImportItemDefinitionIntegrationTest.org.kie.server.integrationtests.dmn.DMNImportItemDefinitionIntegrationTest
org.kie.server.integrationtests.dmn.DMNInputDataStringIntegrationTest.org.kie.server.integrationtests.dmn.DMNInputDataStringIntegrationTest
org.kie.server.integrationtests.dmn.DMNIntegrationTest.org.kie.server.integrationtests.dmn.DMNIntegrationTest
org.kie.server.integrationtests.dmn.DMNMetricIntegrationTest.org.kie.server.integrationtests.dmn.DMNMetricIntegrationTest
org.kie.server.integrationtests.dmn.DMNTwoDMNModelsIntegrationTest.org.kie.server.integrationtests.dmn.DMNTwoDMNModelsIntegrationTest
org.kie.server.integrationtests.dmn.pmml.DMNPMMLMiningIntegrationTest.org.kie.server.integrationtests.dmn.pmml.DMNPMMLMiningIntegrationTest
org.kie.server.integrationtests.dmn.pmml.DMNPMMLRegressionIntegrationTest.org.kie.server.integrationtests.dmn.pmml.DMNPMMLRegressionIntegrationTest
org.kie.server.integrationtests.dmn.pmml.DMNPMMLScorecardIntegrationTest.org.kie.server.integrationtests.dmn.pmml.DMNPMMLScorecardIntegrationTest
org.kie.server.integrationtests.dmn.pmml.DMNPMMLTreeIntegrationTest.org.kie.server.integrationtests.dmn.pmml.DMNPMMLTreeIntegrationTest
org.kie.server.integrationtests.policy.KieServerPolicyDroolsIntegrationTest.org.kie.server.integrationtests.policy.KieServerPolicyDroolsIntegrationTest
org.kie.server.integrationtests.policy.KieServerPolicyJbpmIntegrationTest.org.kie.server.integrationtests.policy.KieServerPolicyJbpmIntegrationTest
org.kie.server.integrationtests.router.KieServerRouterDroolsIntegrationTest.org.kie.server.integrationtests.router.KieServerRouterDroolsIntegrationTest
org.kie.server.integrationtests.router.KieServerRouterJbpmIntegrationTest.org.kie.server.integrationtests.router.KieServerRouterJbpmIntegrationTest
```

none OSGi related

Jenkins execute full downstream build

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Comment by baldimir** [comment]
jenkins retest this

**Comment by tarilabs** [comment]
```
12:04:41 [INFO] -------------------------------------------------------
12:04:41 [INFO]  T E S T S
12:04:41 [INFO] -------------------------------------------------------
12:04:41 [INFO] Running org.kie.hacep.RemoteKieSessionImplTest
12:04:50 [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.184 s - in org.kie.hacep.RemoteKieSessionImplTest
12:04:50 [INFO] Running org.kie.hacep.PodAsReplicaTest
12:05:10 [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.064 s - in org.kie.hacep.PodAsReplicaTest
12:05:10 [INFO] Running org.kie.hacep.RemoteStreamingKieSessionImplTest
12:05:31 [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.161 s - in org.kie.hacep.RemoteStreamingKieSessionImplTest
12:05:31 [INFO] Running org.kie.hacep.LocalStorageStreamingKieSessionTest
12:05:34 [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.053 s - in org.kie.hacep.LocalStorageStreamingKieSessionTest
12:05:34 [INFO] Running org.kie.hacep.PodAsLeaderTest
17:50:07 Unexpected error while executing the Downstream repositories builder for PR builds! Error while executing Maven process!
17:50:07 java.lang.RuntimeException: Error while executing Maven process!
17:50:07 	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:65)
17:50:07 	at org.kie.jenkinsci.plugins.kieprbuildshelper.AbstractPRBuilder.perform(AbstractPRBuilder.java:130)
17:50:07 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
17:50:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
17:50:07 	at hudson.model.Build$BuildExecution.build(Build.java:206)
17:50:07 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
17:50:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
17:50:07 	at hudson.model.Run.execute(Run.java:1724)
17:50:07 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
17:50:07 	at hudson.model.ResourceController.execute(ResourceController.java:97)
17:50:07 	at hudson.model.Executor.run(Executor.java:429)
17:50:07 Caused by: java.lang.InterruptedException
17:50:07 	at java.lang.Object.wait(Native Method)
17:50:07 	at hudson.remoting.Request.call(Request.java:167)
17:50:07 	at hudson.remoting.Channel.call(Channel.java:907)
17:50:07 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:281)
17:50:07 	at com.sun.proxy.$Proxy103.join(Unknown Source)
17:50:07 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1124)
17:50:07 	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:63)
17:50:07 	... 10 more
17:50:07 Build step 'Build dependent downstream repositories (for PR builds)' marked build as failure
17:50:07 Terminating xvnc.
```

Unrelated, again.

I propose to merge.

**Pull request merged**
