### PR TITLE
DROOLS-1682 DMN Marshaller prefix preservation and minor improvements

### PR DESCRIPTION
**Pull request by tarilabs**
forward port kiegroup/drools#1389

### CODE REVIEW

**Comment by tarilabs** [comment]
cc/ @baldimir @etirelli can you review please?

**Review by baldimir — APPROVED** [review]
Looks good. +1

**Comment by baldimir** [comment]
jenkins retest this

**Comment by tarilabs** [comment]
Also for this, I would merge anyway

<details>

```
org.jbpm.kie.services.test.FilteredKModuleDeploymentServiceTest.testMultipleRemotableInPojoJar
 Error Details

Unable to build KieModule, see the 1 messages above.
 Stack Trace

java.lang.RuntimeException: Unable to build KieModule, see the 1 messages above.
	at org.kie.api.builder.helper.KieModuleDeploymentHelperImpl.internalCreateKieJar(KieModuleDeploymentHelperImpl.java:338)
	at org.kie.api.builder.helper.KieModuleDeploymentHelperImpl.internalCreateAndDeployKjarToMaven(KieModuleDeploymentHelperImpl.java:264)
	at org.kie.api.builder.helper.KieModuleDeploymentHelperImpl.createKieJarAndDeployToMaven(KieModuleDeploymentHelperImpl.java:175)
	at org.jbpm.kie.services.test.FilteredKModuleDeploymentServiceTest.testMultipleRemotableInPojoJar(FilteredKModuleDeploymentServiceTest.java:456)
 Standard Output

2017-07-27 02:32:12,186 [main|org.appformer.maven.integration.MavenRepository] WARN  Unable to resolve artifact: org.uberfire:uberfire-maven-support:2.0.0-20170725.215055-3
2017-07-27 02:32:12,376 [main|org.drools.compiler.kie.builder.impl.KieRepositoryImpl] INFO  KieModule was added: MemoryKieModule[releaseId=org.uberfire:uberfire-maven-support:2.0.0-20170725.215055-3]
2017-07-27 02:32:12,444 [main|org.appformer.maven.integration.MavenRepository] WARN  Unable to resolve artifact: org.uberfire:uberfire-maven-support:2.0.0-20170725.215055-3
2017-07-27 02:32:12,444 [main|org.kie.scanner.MavenClassLoaderResolver] ERROR Dependency artifact not found for: org.uberfire:uberfire-maven-support:2.0.0-20170725.215055-3
2017-07-27 02:32:12,448 [main|org.drools.compiler.kie.builder.impl.AbstractKieProject] WARN  No files found for KieBase defaultKieBase
pom.xml : Unresolved dependency org.uberfire:uberfire-maven-support:2.0.0-20170725.215055-3
```

</details>

**Pull request merged**
