### PR TITLE
[7.48.x] DROOLS-6010 : Not able to use a space within quotes in guided DecisionTable.

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**:  

[DROOLS-6010](https://issues.redhat.com/browse/DROOLS-6010)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
"fatal: repository 'https://github.com/Rikkola/optaweb-employee-rostering.git/' not found"

Jenkins run fdb

**Comment by Rikkola** [comment]
Nice, a green FDB.

**Review by jomarko — CHANGES_REQUESTED** [review]
Please cherry-pick also 'extended coverage' [commit](https://github.com/kiegroup/drools/pull/3371/commits/ce60c486bc04591c4b70cb7525963df0e7080e33). So we align master and 7.48.x PRs.

**Comment by Rikkola** [comment]
@jomarko Well spotted. Redid the cherry-pick for the PR.

**Review by jomarko — APPROVED** [review]
Thank you @Rikkola . Please wait for green jenkins build before merge.

**Review by karreiro — APPROVED** [review]
Thank you, @Rikkola.

**Comment by karreiro** [comment]
Jenkins run fdb.

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Can I get a merge please. FDB and local PR builds passed.

**Pull request merged**
