### PR TITLE
DROOLS-1673 Add tests for uncovered areas for AST nodes in kie-dmn-feel module

### PR DESCRIPTION
**Pull request by baldimir**
- Cherrypick from master
- Master PR: https://github.com/kiegroup/drools/pull/1385

### CODE REVIEW

**Comment by baldimir** [comment]
jenkins retest this

**Comment by psiroky** [comment]
This is failing because of a mess up in the jenkins config. Fixing that now.

**Comment by psiroky** [comment]
jenkins retest this

**Comment by baldimir** [comment]
Downstream fail unrelated to the PR.

**Comment by baldimir** [comment]
jenkins retest this

**Comment by etirelli** [comment]
I manually moved this PR to 7.3.x branch and merged:

https://github.com/kiegroup/drools/commit/6e8ac81a5ae5bc545eac9c0b3c45d5999128434c

Closing this PR.

**Pull request closed without merging**
