### PR TITLE
[DROOLS-6709] Impact Analysis: increase test coverage for property types

### PR DESCRIPTION
**Pull request by tkobayas**
**Ports**
Forward-port to main -> https://github.com/kiegroup/drools/pull/4033

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6709

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Build Chain / Maven Build (windows-latest, 8, 3.8.1) : Not related to this PR
```
2021-11-15T09:42:44.2250706Z [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in org.kie.pmml.compiler.commons.codegenfactories.KiePMMLTruePredicateFactoryTest
2021-11-15T09:42:44.2268733Z [ERROR] getTruePredicateVariableDeclaration(org.kie.pmml.compiler.commons.codegenfactories.KiePMMLTruePredicateFactoryTest)  Time elapsed: 0.002 s  <<< FAILURE!
2021-11-15T09:42:44.2329451Z java.lang.AssertionError
2021-11-15T09:42:44.2331515Z    at org.junit.Assert.fail(Assert.java:87)
2021-11-15T09:42:44.2389265Z    at org.junit.Assert.assertTrue(Assert.java:42)
2021-11-15T09:42:44.2513935Z    at org.junit.Assert.assertTrue(Assert.java:53)
2021-11-15T09:42:44.2521948Z    at org.kie.pmml.compiler.commons.codegenfactories.KiePMMLTruePredicateFactoryTest.getTruePredicateVariableDeclaration(KiePMMLTruePredicateFactoryTest.java:45)
...
```

Linux - Pull Request : Tests were successful. Jenkins timed out at the end.

**Comment by danielezonca** [comment]
> Build Chain / Maven Build (windows-latest, 8, 3.8.1) : Not related to this PR
> 
> ```
> 2021-11-15T09:42:44.2250706Z [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in org.kie.pmml.compiler.commons.codegenfactories.KiePMMLTruePredicateFactoryTest
> 2021-11-15T09:42:44.2268733Z [ERROR] getTruePredicateVariableDeclaration(org.kie.pmml.compiler.commons.codegenfactories.KiePMMLTruePredicateFactoryTest)  Time elapsed: 0.002 s  <<< FAILURE!
> 2021-11-15T09:42:44.2329451Z java.lang.AssertionError
> 2021-11-15T09:42:44.2331515Z    at org.junit.Assert.fail(Assert.java:87)
> 2021-11-15T09:42:44.2389265Z    at org.junit.Assert.assertTrue(Assert.java:42)
> 2021-11-15T09:42:44.2513935Z    at org.junit.Assert.assertTrue(Assert.java:53)
> 2021-11-15T09:42:44.2521948Z    at org.kie.pmml.compiler.commons.codegenfactories.KiePMMLTruePredicateFactoryTest.getTruePredicateVariableDeclaration(KiePMMLTruePredicateFactoryTest.java:45)
> ...
> ```
> 
> Linux - Pull Request : Tests were successful. Jenkins timed out at the end.

@gitgabrio 
It looks like a flaky/broken PMML test in Windows, can you please have a look?

**Review by mariofusco — APPROVED** [review]

**Comment by gitgabrio** [comment]
> > Build Chain / Maven Build (windows-latest, 8, 3.8.1) : Not related to this PR
> > ```
> > 2021-11-15T09:42:44.2250706Z [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in org.kie.pmml.compiler.commons.codegenfactories.KiePMMLTruePredicateFactoryTest
> > 2021-11-15T09:42:44.2268733Z [ERROR] getTruePredicateVariableDeclaration(org.kie.pmml.compiler.commons.codegenfactories.KiePMMLTruePredicateFactoryTest)  Time elapsed: 0.002 s  <<< FAILURE!
> > 2021-11-15T09:42:44.2329451Z java.lang.AssertionError
> > 2021-11-15T09:42:44.2331515Z    at org.junit.Assert.fail(Assert.java:87)
> > 2021-11-15T09:42:44.2389265Z    at org.junit.Assert.assertTrue(Assert.java:42)
> > 2021-11-15T09:42:44.2513935Z    at org.junit.Assert.assertTrue(Assert.java:53)
> > 2021-11-15T09:42:44.2521948Z    at org.kie.pmml.compiler.commons.codegenfactories.KiePMMLTruePredicateFactoryTest.getTruePredicateVariableDeclaration(KiePMMLTruePredicateFactoryTest.java:45)
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Linux - Pull Request : Tests were successful. Jenkins timed out at the end.
> 
> @gitgabrio It looks like a flaky/broken PMML test in Windows, can you please have a look?

@danielezonca All such tests now are broken in Windows

`Error: There were 40 failed tests`

Those tests were introduced on 5th, October - more then one month ago - and there never was a failure on them AFAIK. 
Those tests are based on a simple text formatting and JavaParserUtils:

`       
String text = getFileContent(TEST_01_SOURCE);
Statement expected = JavaParserUtils.parseBlock(String.format(text, variableName));
assertTrue(JavaParserUtils.equalsNode(expected, retrieved));
`
The assertion is not done directly on the raw text, but on `equalsNode`

This method (JavaParserUtils)
`
    public static boolean equalsNode(Node node1, Node node2) {
        return node1.toString().equals(node2.toString());
    }
`

has been introduce 6 months ago exactly to solve windows issue

https://github.com/kiegroup/drools/pull/3621

Before starting experiments, trials, whatever: Is there anything else changed lately in the windows environment or related ?

**Comment by danielezonca** [comment]
@gitgabrio 
Ok thanks for the analysis, I'm quite sure it is a regression introduced by this PR https://github.com/kiegroup/drools/pull/4011 that upgrades JavaParser and maybe the "trick"/approach used for Windows builds is not working anymore

/cc @mariofusco

**Pull request merged**
