### PR TITLE
[DROOLS-6331] avoid multiple executable model generation for the same…

### PR DESCRIPTION
**Pull request by mariofusco**
… type declarations during the build of a multi-kbase project

**JIRA**: https://issues.redhat.com/browse/DROOLS-6331

In reality this not avoid to regenerate the same declared types if they are used by more than one KieBase, but the same applies for all the rules belonging to packages included in more than one KieBase.

Before this improvement I had these results on customer's benchmark

```
Benchmark                                        Mode  Cnt   Score    Error  Units
KjarCompilerBenchmark.buildKjarFromBigProject      ss    5  79.634 ± 10.578   s/op
KjarCompilerBenchmark.buildKjarFromSmallProject    ss    5  37.702 ±  7.072   s/op
```

After this I got

```
Benchmark                                        Mode  Cnt   Score    Error  Units
KjarCompilerBenchmark.buildKjarFromBigProject      ss    5  76.069 ± 11.476   s/op
KjarCompilerBenchmark.buildKjarFromSmallProject    ss    5  18.912 ±  5.071   s/op
```

### CODE REVIEW

**Review by lucamolteni — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute cdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Pull request merged**
