### PR TITLE
DROOLS-4131: Can't use "is contained in the list" for Integer field

### PR DESCRIPTION
**Pull request by jomarko**
Ensemble together with:
- https://github.com/kiegroup/drools-wb/pull/1165

This PR check what is the data type of collection used with the "is containded in the list".
If the type is a numeric one, quotes are not added into the generated drl.

### CODE REVIEW

**Review by Rikkola — APPROVED** [review]

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge together with https://github.com/kiegroup/drools-wb/pull/1165

**Comment by manstis** [comment]
@jomarko Did you want the FDB to complete on https://github.com/kiegroup/drools-wb/pull/1165 first?

**Comment by jomarko** [comment]
@manstis yes, my mistake, I will ask for merge once that build is finished.

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed test:
```
org.jbpm.executor.impl.wih.AsyncContinuationSupportTest.testAsyncModeWithParallelGateway
```

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed tests:
```
- LoginIntegrationTest.loginAndLogout
- ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository
- StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective
- AsyncContinuationSupportTest.testAsyncModeWithParallelGateway
```

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please retest this... PDQ!

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
ok to test.

**Comment by mareknovotny** [comment]
@rsynek I would say sonarcloud analysis is wrong or I don't get why the changed impl and test could result in 

> 0.0% Coverage on New Code (is less than 80%)

**Comment by manstis** [comment]
Merged as this is part of an ensemble already merged.

**Comment by rsynek** [comment]
@mareknovotny +1, this must be some mistake. I was not able to find any warning in the log that would tell why it happened.

**Pull request merged**
