### PR TITLE
GUVNOR-3520: Use Assertj assertEqualsIgnoreWhiteSpace implementation

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko I agree with this in principle; however please note it has broken some tests for ```DumperTest```

**Comment by jomarko** [comment]
@manstis sure, I am looking deeper into it.

**Comment by jomarko** [comment]
@manstis with the last assertj library implementation it works, so I have created https://github.com/jboss-integration/jboss-integration-platform-bom/pull/388 and https://github.com/jboss-integration/jboss-integration-platform-bom/pull/389. However I am a little bit confused. Kiegroup master branch points to jboss-integration-platform-bom 7.0.0.Final. However the repository jboss-integration-platform-bom has just 7.0.2-SNAPSHOT or 8.0.0-SNAPSHOT.

**Comment by manstis** [comment]
@psiroky @mbiarnes Can either of you shed any light on @jomarko question please?

**Comment by psiroky** [comment]
We do not depend on SNAPSHOTs of ip-bom (we have enough SNAPSHOTs deps as it is). Once is a while we do a release of ip-bom and bump the version in kie-parent.

**Comment by jomarko** [comment]
@psiroky sorry for my question, I am still not sure when will be my change done in `jboss-integration-platform-bom` repository available for this `drools` repository.

**Comment by psiroky** [comment]
@jomarko there is no fixed date. This needs to happen:
1) @mbiarnes needs to release a new IP-BOM version from the master branch ( I guess now would be a good time)
2) @mbiarnes will send PR to `droolsjbpm-build-bootstrap` and bump the ip-bom version there
3) We will run full downstream build to make sure nothing gets broken by the ip-bom upgrade
4) If everything is OK, then the PR is merged

**Comment by jomarko** [comment]
@psiroky thank you for the answer.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by psiroky** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@psiroky @mariofusco could we please merge?

**Pull request merged**
