### PR TITLE
[KIE-859] make drools quarkus extension build reproducible

### LINKED ISSUE #859: Make drools quarkus extension build reproducible
Part of https://github.com/apache/incubator-kie-issues/issues/840

### PR DESCRIPTION
**Pull request by mariofusco**
Closes: https://github.com/apache/incubator-kie-issues/issues/859

### CODE REVIEW

**Review by gitgabrio — APPROVED** [review]
@mariofusco Thanks for the PR, LGTM!!!

**Comment by lucamolteni** [comment]
@yurloc  see this

**Comment by yurloc** [comment]
Please add a comment that this workaround can be removed once we upgrade to a Quarkus version that contains this fix: https://github.com/quarkusio/quarkus/pull/38365.

**Review by lucamolteni — APPROVED** [review]
Verified it works on the Mac as well

**Review by porcelli — COMMENTED** [review]
the problem is that it won't work on Windows :)

alternative could be a java class with main and execute with maven:exec ?

other than that... lgtm. maybe consider java

**Comment by mariofusco** [comment]
> Please add a comment that this workaround can be removed once we upgrade to a Quarkus version that contains this fix: [quarkusio/quarkus#38365](https://github.com/quarkusio/quarkus/pull/38365).

@yurloc @lucamolteni done

**Review by gitgabrio — APPROVED** [review]

**Review by baldimir — APPROVED** [review]

**Pull request merged**
