### PR TITLE
[7.23.x] DROOLS-4331 : Error when copying Guided Rule with Bigdecimal

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 1abc4c259ecdc21845a57de504ead33068f0251e)

7.23.x version of: https://github.com/kiegroup/drools/pull/2451

https://issues.jboss.org/browse/DROOLS-4331

### CODE REVIEW

**Comment by Rikkola** [comment]
@manstis @Bonuseto Here you are, the same setup as in master. If you could please review.

**Comment by Bonuseto** [comment]
jenkins execute full downstream build

**Review by manstis — APPROVED** [review]

**Comment by Rikkola** [comment]
jenkins execute downstream build

**Comment by Rikkola** [comment]
Now we might actually have broken 7.23.x or I was just unlucky with the timing.

`18:04:02 /home/jenkins/workspace/KIE/7.23.x/pullrequest/drools-compile-downstream-build-7.23.x/downstream-repos/kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/forms/validation/timerEditor/TimerSettingsValueValidator.java:[23,33] package org.kie.soup.commons.cron does not exist`

jenkins execute downstream build

**Comment by manstis** [comment]
@wmedvede Are all your CRON related PRs merged into `7.23.x`?

See @Rikkola comment above.. might just be bad timing; but I know the PRs for `master` were not all merged at the same time....

**Comment by wmedvede** [comment]
@manstis @Rikkola my PRs were merged Yesterday both in master and 7.23.x, so I think it's a matter of bad timing.  (In master I have one related PR but it only has a test, so don't affect the build)

and now that I recall, yes, in master I believe the PRs wasn't merged in the correct order, but in 7.23.x I believe they was merged ok

**Review by kkufova — APPROVED** [review]

**Comment by Rikkola** [comment]
jenkins compile downstream build

**Comment by Rikkola** [comment]
jenkins execute compile downstream build

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Please merge this. Full build was started to make testing faster, but it keeps randomly failing.

**Pull request merged**
