### PR TITLE
DROOLS-5844: Errors when executing models using imported inputs and/or decisions nodes - BC

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**: https://issues.redhat.com/browse/DROOLS-5844

**referenced Pull Requests**: 

* https://github.com/kiegroup/drools/pull/3460
* https://github.com/kiegroup/drools-wb/pull/1446

These changes affect BUSINESS CENTRAL only. Kogito will be managed in https://issues.redhat.com/browse/KOGITO-4765

A DMN file can refer to another "external" DMN file. The current version of Scesim doesn't support this feature, in particular, is not able to manage Decisions or Inputs inherited from the Imported external DMN file.
An example of a DMN file that uses an Input node inherited from an external file (Traffic Violation):
Screenshot from 2021-03-23 15-16-16

With its related scesim file, which now supports it with the introduced changes in this PR
Screenshot from 2021-03-23 15-15-14

An example of a DMN file that uses a Decision node inherited from an external file (Traffic Violation):
Screenshot from 2021-03-23 15-14-06
and related scesim generated file
Screenshot from 2021-03-23 15-13-22

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins execute compile downstream build

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer.

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by yesamer** [comment]
Jenkins do fdb

**Review by jomarko — APPROVED** [review]

**Comment by yesamer** [comment]
jenkins execute compile downstream build

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins execute full downstream build

**Comment by yesamer** [comment]
Jenkins do fdb

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
Failures seems not related to the PR, and it's not possible to relaunch them

**Pull request merged**
