### PR TITLE
[DROOLS-5030] improve support for different resource types in KieFile…

### PR DESCRIPTION
**Pull request by mariofusco**
…System

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by mariofusco** [comment]
jenkins execute full downstream build

**Comment by danielezonca** [comment]
jenkins execute compile downstream build

**Comment by mariofusco** [comment]
jenkins execute compile downstream build

**Comment by mariofusco** [comment]
jenkins execute compile downstream build

**Comment by danielezonca** [comment]
jenkins execute full downstream build

**Pull request merged**
