### PR TITLE
JBRULES-3157: Add information such as line number or source code in VerifierComponent

### PR DESCRIPTION
**Pull request by jerr**
I rebase my code from droolsjbpm/drools/master.
If I have to do it on another branch or otherwise, feel free to tell me.

Regards,
Jérémie.

### CODE REVIEW

**Comment by etirelli** [comment]
Jerr, there is a problem with your pull request... look at the list of commits it contains at the moment and you will see. A proper pull request will include only the commits that you made and no others. Also, a proper rebase will prevent all the "Merge branch..." commits that create non-linear history.
Let me know when you fixed it and I will apply it, or let me know if you need help with git to create the pull request.
Thanks,
Edson

**Comment by jerr** [comment]
I'm sorry, actually my merge between my master and droolsjbpm/drools/master isn't correct.
I'll try to fix this. I'm not a git expert, but I will try to provide a right pull-request.

Sorry to waste your time.
Best regards,
Jérémie.

**Comment by etirelli** [comment]
Jerr, no problem at all. If I may suggest, take a look at the following link:

https://docs.jboss.org/author/display/ISPN/Contributing+to+Infinispan#ContributingtoInfinispan-SourceControl

We use a similar process to what infinispan uses and the section on "Occasional Contributor" explains very well how to do a pull request with your changes, specially the section "Worked Example".

**Comment by jerr** [comment]
That sounds better.
Thanks for your help.

Jérémie.

**Comment by etirelli** [comment]
So is this ready for merging? 

/cc @Rikkola

**Comment by jerr** [comment]
I didn't add new commit to preserve the Toni code review.
If Toni is ok, it's good for me.

**Comment by Rikkola** [comment]
I'm fine with this.

**Comment by jerr** [comment]
I did a merge with the droolsjbpm/drools/master.
Hope this will help.

Jérémie.

**Comment by etirelli** [comment]
Jerr, 

Sorry about it, my bad for not applying it immediately. I just applied your commits to master. Everything should be fine now. Thanks for sending the pull request. 

Just FYI for future PRs, do not merge with master... just keep it as it was before the merge. 

Edson

**Pull request closed without merging**
