### PR TITLE
Remove unused test code from persistence

### PR DESCRIPTION
**Pull request by baldimir**
The code is unused from year 2011 (looks like it was never used based on repo history). I will execute full downstream build with it to be sure that no other repository is using it.

### CODE REVIEW

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Comment by baldimir** [comment]
jenkins retest this

**Comment by baldimir** [comment]
jenkins retest this

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Comment by mbiarnes** [comment]
jenkins execute full downstream build

**Pull request merged**
