### PR TITLE
[DROOLS-5638] Majority vote operator does not work in mining model

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @jiripetrlik

See https://issues.redhat.com/browse/DROOLS-5638

It turned out that the issue was in the pmml file name.

This is related to https://issues.redhat.com/browse/DROOLS-5376, https://issues.redhat.com/browse/DROOLS-5367 and https://issues.redhat.com/browse/DROOLS-5571 that are becoming urgents.

### CODE REVIEW

**Review by jiripetrlik — APPROVED** [review]
@gitgabrio 
Thank you for the quick fix and your findings!

**Comment by gitgabrio** [comment]
Jenkins run cdb

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by gitgabrio** [comment]
@danielezonca Hi! Could you please merge this, squashing commits? Thanks!

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
