### PR TITLE
[DROOLS-2619] Fix test names to follow surefire and failsafe patterns

### PR DESCRIPTION
**Pull request by barboras7**
@mariofusco I discovered that there are some tests that were not run in Jenkins as they did not follow the correct pattern for names (see https://issues.jboss.org/browse/DROOLS-2619). After my fix, it seems that one of the tests failed. Could you please take a look at the fail? Thanks.

### CODE REVIEW

**Comment by baldimir** [comment]
@barboras7 could you please remove the failing test? Reactive arrays are not supported. Please see here: https://issues.jboss.org/browse/RHDM-200

**Review by baldimir — APPROVED** [review]

**Comment by baldimir** [comment]
jenkins retest this

**Comment by barboras7** [comment]
jenkins retest this

**Comment by baldimir** [comment]
jenkins retest this

**Pull request merged**
