### PR TITLE
[DROOLS-3181] fix VirtualFileSystem discovery

### PR DESCRIPTION
**Pull request by msfm**
- Revert "[DROOLS-3181] fix VirtualFileSystem discovery after changes in eap 6.4.21 (#2118)"
- Use the public API org.jboss.vfs.VFS to obtain VirtualFile from the url path instead of depending on the internal behavior of org.jboss.vfs.protocol.VirtualFileURLConnection

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mariofusco** [comment]
ok to test

**Pull request merged**
