### PR TITLE
RHPAM-2457: Add a reproducer test

### PR DESCRIPTION
**Pull request by jomarko**
Dependent on #2565

### CODE REVIEW

**Comment by jomarko** [comment]
@Rikkola during writing the test I tried to change `RuleModelDRLPersistenceImpl.populateValueList` where I replaced `ListSplitter.split("\"", true, workingValue);` with `final String[] values = ListSplitter.splitPreserveQuotes("\"", true, workingValue);`. It helped in some marshaling tests, however no effect in this unmarshalling one. Not sure if it help you somehow to solve the issue.

**Comment by jomarko** [comment]
@manstis just to point you to the test you asked for https://github.com/kiegroup/drools/pull/2565#discussion_r335863721

**Review by Rikkola — APPROVED** [review]
I think we can add this.

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
