### PR TITLE
DROOLS-4490 adding time(hour, minute, second)

### PR DESCRIPTION
**Pull request by SimonRinguette**
@etirelli We are using the extended TimeFunction. I've added the same shortcut function to the extended function as the one you introduced to the regular TimeFunction:

https://github.com/kiegroup/drools/commit/eb5271769ff6f9326605902ffe861f50faf3f034

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by etirelli** [comment]
@tarilabs can you take a look at this please?

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
```
15:08:46 [ERROR] Failed to execute goal on project employee-rostering-distribution: Could not resolve dependencies for project org.optaweb.employeerostering:employee-rostering-distribution:jar:7.28.0-SNAPSHOT: Could not find artifact org.optaweb.employeerostering:employee-rostering-backend:jar:exec:7.28.0-SNAPSHOT in mirror-central (http://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/nexus/content/groups/public/) -> [Help 1]
15:08:46 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project employee-rostering-distribution: Could not resolve dependencies for project org.optaweb.employeerostering:employee-rostering-distribution:jar:7.28.0-SNAPSHOT: Could not find artifact org.optaweb.employeerostering:employee-rostering-backend:jar:exec:7.28.0-SNAPSHOT in mirror-central (http://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/nexus/content/groups/public/)
15:08:46     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:249)
```

downstream compilation unrelated, waiting for CI and SC

**Pull request merged**
