### PR TITLE
PLANNER-2291 Add OptaPlanner into the FDB

### PR DESCRIPTION
**Pull request by rsynek**
**JIRA**: 

https://issues.redhat.com/browse/PLANNER-2291

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by rsynek** [comment]
@Ginxo I noticed the same failure of the KBCFDB (what an abbreviation!) occurs in other PR too. Does that mean the build is currently broken?

**Comment by danielezonca** [comment]
@rsynek 
Yes drools snapshot is not compatible with kogito until 7.48.0.Final will be published and this PR merged
https://github.com/kiegroup/kogito-runtimes/pull/944
I hope tomorrow will be merged.
If you want to test the full pipeline you can create a pr to kogito with same branch name with the changes of the linked PR to make the build together

**Comment by rsynek** [comment]
Thanks @danielezonca, that makes sense.

**Comment by rsynek** [comment]
@Ginxo I am afraid we will need some disk cleaning magic, please see the last failure of the KBCFDB:
Caused by: java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space

**Comment by rsynek** [comment]
@Ginxo would you please review the changes?

**Review by Ginxo — APPROVED** [review]
@rsynek I am surprised to see the overwritten (optaplanner) from an extended definition file is actually working :clap: 
You can check project tree after executing `build-chain-files-generator -df https://raw.githubusercontent.com/kiegroup/drools/16fca975e230812241893acdf504b397e67f01f7/.ci/kogito-pull-request-config.yaml -o kogito-tooling.png image`
https://www.npmjs.com/package/@kie/build-chain-files-generator
kogito-tooling

**Comment by rsynek** [comment]
Thanks, but is it really working, @Ginxo ? On this PR (and a couple of others) the Kogito Build Chain Full Downstream failed because of some broken or unstable tests in kogito-runtime.

**Pull request merged**
