### PR TITLE
[DROOLS-3775] Implement stateless kieSession runner support in test scenario

### PR DESCRIPTION
**Pull request by danielezonca**
This PR adds runner support for stateless kieSession testing.

@kkufova @Rikkola @gitgabrio @yesamer 

https://issues.jboss.org/browse/DROOLS-3775

PR list:
- https://github.com/kiegroup/drools/pull/2405
- https://github.com/kiegroup/drools-wb/pull/1174

### CODE REVIEW

**Review by gitgabrio — APPROVED** [review]

**Review by yesamer — APPROVED** [review]

**Comment by baldimir** [comment]
@danielezonca Hi Daniele, could you please check the SonarCloud report? There is one tip to use isEmpty instead of .size() > 0. Also based on the report, it looks like that majority of the new code is uncovered with tests. Could you please add more tests so we have it covered more thoroughly?

**Comment by danielezonca** [comment]
@baldimir 
Th

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by kkufova — APPROVED** [review]
Works well. Approving.

:+1:

**Pull request merged**
