### PR TITLE
DROOLS-2274 Add more extended unary test tests

### PR DESCRIPTION
**Pull request by baldimir**
This is also a reproducer for:
- https://issues.jboss.org/browse/DROOLS-2543
- https://issues.jboss.org/browse/DROOLS-2544

@etirelli @tarilabs could you please review? Should I ignore the failing tests till Edson is back from PTO so this can be merged?

### CODE REVIEW

**Comment by tarilabs** [comment]
I can try to take a look at the issues but it depends how much time this can wait before a merge. If it's only failing test, I would say here is helpful. If it's test AND changing some infrastructure code, I would advise better to merge with ignoring the failing ones, to avoid rebase issue later.

**Comment by baldimir** [comment]
@tarilabs this is just new tests. No infrastructure code is changed.

**Comment by tarilabs** [comment]
@baldimir I am taking back my answer of yesterday, as even without infrastructure change in fact we always stumble on merge issue on test themselves, sorry I forgot about that. I suggest you rebase now to resolve current conflict on DMNRuntimeTest and merge, ignoring failing tests concerning DROOLS-2543 and DROOLS-2544.
I am currently working on fixes for DROOLS-2544.
For DROOLS-2543 more info is needed (this is captured in the email thread).

**Comment by baldimir** [comment]
@tarilabs rebased and tests ignored.

**Comment by tarilabs** [comment]
thx, will ask Mario to merge as soon as CI will flag this as green

**Pull request merged**
