### PR TITLE
[DROOLS-6064] Inconsistent behavior when accumulate function returns …

### PR DESCRIPTION
**Pull request by tkobayas**
…null

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6064

**referenced Pull Requests**: 

* https://github.com/kiegroup/droolsjbpm-knowledge/pull/513

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
Hi @mariofusco  , firstly please review this PR. Now I added AccumulateNullPropagationOption for KieSessionConfiguration. Default is false so basically this wouldn't break existing tests. (FDB with "null propagation enabled" was done by https://github.com/kiegroup/drools/pull/3479  There was only one optaplanner failure which Lukas mentioned that it's not likely related to the PR)

Next, do you ask Lukas to test this option with OptaPlanner? If yes, please feel free. 

It can be enabled like this.
```
        KieSessionConfiguration kieSessionConfiguration = KieServices.get().newKieSessionConfiguration();
        kieSessionConfiguration.setOption(AccumulateNullPropagationOption.YES);
        final KieSession kieSession = kieBase.newKieSession(kieSessionConfiguration, null);
```

I'm not pushing this PR to 7.52.0.Final. It's okay to commit to 7.53.0-SNAPSHOT and we may backport this to RHDM 7.11.0 if time permits.

**Review by hellowdan — APPROVED** [review]

**Comment by triceo** [comment]
@tkobayas @mariofusco  Does this particular option bring any benefit? Is there a performance gain, for example?
Because if it changes accumulate behavior without giving anything back, I will simply not enable that option and you do not need to worry about OptaPlanner. :-)

**Comment by tkobayas** [comment]
Hi @triceo , this JIRA is originally raised from a customer who says the current behaviour is inconsistent. Then Mark agreed that propagating null should be a "correct" behaviour (https://issues.redhat.com/browse/DROOLS-6064). I don't think it gives performance benefit. Just about a behaviour change. @mariofusco do you have anything to add?

**Comment by triceo** [comment]
I'll rephrase. Is it OK if I don't do anything? 
Or are you changing the default behavior, so that I need to specifically disable it?

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
