### PR TITLE
[7.52.x] DROOLS-6263: Test Scenario - expected vs actual alert is misleading

### PR DESCRIPTION
**Pull request by yesamer**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins run cdb

**Review by jstastny-cz — APPROVED** [review]
LGTM. Thanks.

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run cdb

**Review by Rikkola — APPROVED** [review]

**Review by karreiro — APPROVED** [review]

**Pull request merged**
