### PR TITLE
[DROOLS-6232] Review drools-mvel test leftovers : 3rd round

### PR DESCRIPTION
**Pull request by tkobayas**
Cleanup drools-mvel test classes/resources

**JIRA**: 

https://issues.redhat.com/browse/DROOLS-6232

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
FDB errors. Not likely related to this PR.

```
org.kie.hacep.LocalStorageStreamingKieSessionTest.getCommandsTest

Failing for the past 1 build (Since Unstable#131 )
Took 1.6 sec.
Error Message
expected:<2> but was:<1>
Stacktrace
java.lang.AssertionError: expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.kie.hacep.LocalStorageStreamingKieSessionTest.getCommandsTest(LocalStorageStreamingKieSessionTest.java:121)
```

```
org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT

Failing for the past 1 build (Since Unstable#131 )
Took 40 sec.
Error Message
Cannot deploy business-monitoring-webapp.war: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"business-monitoring-webapp.war\".WeldStartService" => "Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-000049: Unable to invoke void org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl.postConstruct() on org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl@6e77b61f
    Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke void org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl.postConstruct() on org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl@6e77b61f
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke void org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl.postConstruct() on org.kie.workbench.common.screens.archetype.mgmt.backend.service.ArchetypeServiceImpl@650f042a
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: org.uberfire.java.nio.file.FileSystemNotFoundException: No filesystem for uri (default://system/system) found."}}}}
```

**Comment by tkobayas** [comment]
Jenkins run cdb

**Comment by tkobayas** [comment]
Back to draft because I will need to rebase/rework after merging https://github.com/kiegroup/drools/pull/3502

**Review by lucamolteni — APPROVED** [review]

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
Jenkins run fdb

**Review by mariofusco — APPROVED** [review]

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
Jenkins run fdb

**Review by lucamolteni — APPROVED** [review]

**Review by hellowdan — APPROVED** [review]

**Pull request merged**
