### PR TITLE
DROOLS-7105 DMN upgrade to Antlr 4.10

### PR DESCRIPTION
**Pull request by tarilabs**
to replace https://github.com/kiegroup/drools/pull/4621 as for CI I am afraid we need the same author for multi repo PRs
/cc @Rikkola 

ref https://github.com/quarkusio/quarkus/pull/27298#issuecomment-1216705851

**JIRA**: https://issues.redhat.com/browse/DROOLS-7105

**referenced Pull Requests**:
- (main) https://github.com/kiegroup/drools/pull/4614
- (7.x for alignment) https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2031
- (7.x for alignment) https://github.com/kiegroup/drools/pull/4632
- (7.x for alignment) https://github.com/kiegroup/kie-wb-common/pull/3769
- (7.x for alignment) https://github.com/kiegroup/drools-wb/pull/1552
- (7.x for alignment) https://github.com/kiegroup/kie-wb-distributions/pull/1187

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>
</details>

### CODE REVIEW

**Review by Rikkola — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins run cdb

**Comment by tarilabs** [comment]
cdb failure unrelated:
```
[2022-08-25T10:04:56.069Z] [INFO] Reactor Summary for Business Central - Distributions 7.74.0-SNAPSHOT:
[2022-08-25T10:04:56.069Z] [INFO] 
[2022-08-25T10:04:56.069Z] [INFO] Business Central - Distributions ................... SUCCESS [  3.056 s]
[2022-08-25T10:04:56.069Z] [INFO] Business Central Parent ............................ SUCCESS [  0.202 s]
[2022-08-25T10:04:56.069Z] [INFO] Business Central - Webapp Common ................... SUCCESS [  2.725 s]
[2022-08-25T10:04:56.069Z] [INFO] Business Central Deployment Validation ............. SUCCESS [ 12.408 s]
[2022-08-25T10:04:56.069Z] [INFO] KIE Theme .......................................... SUCCESS [  0.685 s]
[2022-08-25T10:04:56.069Z] [INFO] KIE Theme - Community .............................. SUCCESS [  2.885 s]
[2022-08-25T10:04:56.069Z] [INFO] KIE Theme - Product ................................ SUCCESS [  6.482 s]
[2022-08-25T10:04:56.069Z] [INFO] Business Central - Home Page - Community ........... SUCCESS [ 17.456 s]
[2022-08-25T10:04:56.069Z] [INFO] Business Central - Monitoring Webapp ............... FAILURE [01:03 min]
[2022-08-25T10:04:56.069Z] [INFO] Business Central - Webapp .......................... SUCCESS [01:21 min]
[2022-08-25T10:04:56.069Z] [INFO] Business Central - Distribution Wars Parent ........ SUCCESS [  3.332 s]
[2022-08-25T10:04:56.069Z] [INFO] Business Central - Monitoring Distribution Wars .... SKIPPED
[2022-08-25T10:04:56.069Z] [INFO] Business Central - Distribution Wars ............... SUCCESS [ 50.913 s]
[2022-08-25T10:04:56.069Z] [INFO] jBPM server distribution ........................... SUCCESS [ 13.995 s]
[2022-08-25T10:04:56.069Z] [INFO] business central add-ons distribution .............. SUCCESS [ 38.445 s]
[2022-08-25T10:04:56.069Z] [INFO] Business Central Tests :: Parent ................... SKIPPED
[2022-08-25T10:04:56.069Z] [INFO] Business Central Tests :: REST API ................. SKIPPED
[2022-08-25T10:04:56.069Z] [INFO] KIE (Drools) Workbench Tests :: GUI ................ SKIPPED
[2022-08-25T10:04:56.069Z] [INFO] ------------------------------------------------------------------------
[2022-08-25T10:04:56.069Z] [INFO] BUILD FAILURE
[2022-08-25T10:04:56.069Z] [INFO] ------------------------------------------------------------------------
[2022-08-25T10:04:56.069Z] [INFO] Total time:  02:48 min (Wall Clock)
[2022-08-25T10:04:56.069Z] [INFO] Finished at: 2022-08-25T06:04:54-04:00
[2022-08-25T10:04:56.069Z] [INFO] ------------------------------------------------------------------------
[2022-08-25T10:04:56.069Z] [ERROR] Failed to execute goal org.wildfly.plugins:wildfly-jar-maven-plugin:6.1.2.Final:package (default) on project business-monitoring-webapp: Packaging wildfly failed: InvocationTargetException: java.util.concurrent.ExecutionException: org.jboss.as.cli.CommandFormatException: The command is not available in the current context (e.g. required subsystems or connection to the controller might be unavailable). -> [Help 1]
[2022-08-25T10:04:56.069Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.plugins:wildfly-jar-maven-plugin:6.1.2.Final:package (default) on project business-monitoring-webapp: Packaging wildfly failed
```

**Review by pibizza — APPROVED** [review]
Looks good to me

**Review by baldimir — APPROVED** [review]

**Comment by tarilabs** [comment]
Jenkins run cdb

**Pull request merged**
