### PR TITLE
DROOLS-6013 Drools maintenance of Unit test deprecated classes/methods

### PR DESCRIPTION
**Pull request by tarilabs**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6013

**referenced Pull Requests**: none

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]
Thanks for the PR

**Comment by tarilabs** [comment]
verified locally OK

image

**Review by jomarko — APPROVED** [review]
Thank you @tarilabs

**Review by Rikkola — APPROVED** [review]
Good stuff 👍

**Comment by tarilabs** [comment]
the 3 github based are failing for:
```
Caused by: org.apache.maven.wagon.providers.http.httpclient.conn.HttpHostConnectException: Connect to repository.jboss.org:443 [repository.jboss.org/209.132.182.97] failed: Connection timed out (Connection timed out)
```
which is trying to resolve `org.jboss.pressgang:pressgang-xslt-ns:jar:3.1.3`
which is unrelated to this PR.

the cdb is failing due to:
```
[2021-02-11T10:47:07.077Z] [WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
[2021-02-11T10:47:07.077Z] Unable to process dependency com.google.guava:guava:jar:24.1.1-jre:test due to zip file is empty
```
in the workitem repo which is unrelated to this PR.

I will ask to proceed to merge.

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
