### PR TITLE
[kie-issues-249] Data Index Events changes for allowing historical data

### PR DESCRIPTION
**Pull request by elguardian**
Issue: https://github.com/kiegroup/kie-issues/issues/249

### CODE REVIEW

**Review by porcelli — DISMISSED** [review]
all new files requires the use of Apache headers and not Red Hat

**Review by mariofusco — DISMISSED** [review]
Is it necessary to have this in Drools? It seems very Kogito specific so why not move it there?

**Comment by porcelli** [comment]
@mariofusco I hear you, and it makes sense.

however if you check all events related to process are already here, so I'd argue that we could discuss in a different thread and eventually PR moving the process related content from drools to kogito.

**Comment by elguardian** [comment]
@mariofusco unfortunately is how the design works. the idea is to strip the jbpm engine in the medium term. so for now we cannot change the dependencies just to acommodate this. it is out of the scope of the jira.

**Comment by mariofusco** [comment]
@elguardian @porcelli That's fine, for now it's ok for me. If possible please open another ticket to better isolate this stuff in a second step.

**Review by mariofusco — APPROVED** [review]

**Review by pefernan — APPROVED** [review]
+1

**Review by porcelli — APPROVED** [review]

**Pull request merged**
