### PR TITLE
BXMSPROD-8: refactor to build without jboss-ip-bom

### PR DESCRIPTION
**Pull request by mbiarnes**
disabled enforcer plugin for kie-ci-osgi

disabled maven-jar-plugin

### CODE REVIEW

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/kie-soup/pull/95
https://github.com/kiegroup/appformer/pull/718
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/973
https://github.com/kiegroup/droolsjbpm-knowledge/pull/391
https://github.com/kiegroup/drools/pull/2396
https://github.com/kiegroup/optaplanner/pull/514
https://github.com/kiegroup/jbpm/pull/1503
https://github.com/kiegroup/kie-jpmml-integration/pull/5
https://github.com/kiegroup/droolsjbpm-integration/pull/1849
https://github.com/kiegroup/droolsjbpm-tools/pull/95
https://github.com/kiegroup/kie-uberfire-extensions/pull/85
https://github.com/kiegroup/kie-wb-playground/pull/76
https://github.com/kiegroup/kie-wb-common/pull/2710
https://github.com/kiegroup/drools-wb/pull/1169
https://github.com/kiegroup/optaplanner-wb/pull/339
https://github.com/kiegroup/jbpm-designer/pull/854
https://github.com/kiegroup/jbpm-wb/pull/1364
https://github.com/kiegroup/kie-docs/pull/1645
https://github.com/kiegroup/kie-wb-distributions/pull/940
https://github.com/kiegroup/optaweb-employee-rostering/pull/250

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/kie-soup/pull/95
https://github.com/kiegroup/appformer/pull/718
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/973
https://github.com/kiegroup/droolsjbpm-knowledge/pull/391
https://github.com/kiegroup/drools/pull/2396
https://github.com/kiegroup/optaplanner/pull/514
https://github.com/kiegroup/jbpm/pull/1503
https://github.com/kiegroup/kie-jpmml-integration/pull/5
https://github.com/kiegroup/droolsjbpm-integration/pull/1849
https://github.com/kiegroup/droolsjbpm-tools/pull/95
https://github.com/kiegroup/kie-uberfire-extensions/pull/85
https://github.com/kiegroup/kie-wb-playground/pull/76
https://github.com/kiegroup/kie-wb-common/pull/2710
https://github.com/kiegroup/drools-wb/pull/1169
https://github.com/kiegroup/optaplanner-wb/pull/339
https://github.com/kiegroup/jbpm-designer/pull/854
https://github.com/kiegroup/jbpm-wb/pull/1364
https://github.com/kiegroup/kie-docs/pull/1645
https://github.com/kiegroup/kie-wb-distributions/pull/940
https://github.com/kiegroup/optaweb-employee-rostering/pull/250

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Review by mareknovotny — APPROVED** [review]

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Pull request merged**
