### PR TITLE
DROOLS-3670: Test now() between two date times

### PR DESCRIPTION
**Pull request by jomarko**
@tarilabs could you please have a look? I created the "is office open.dmn"  using our DMN designer I and would expect the decision "is open" will return false but it is returning "null". Am I missing something?

### CODE REVIEW

**Comment by jomarko** [comment]
@tarilabs Should I just add `@Ignore` annotation to the added test so we can merge the PR?

**Comment by tarilabs** [comment]
I would prefer to cherry-pick this commit when I will work for the fix, thx

**Comment by tarilabs** [comment]
I included your commit in https://github.com/kiegroup/drools/pull/2267
I believe you can close this PR as superseeded by the above

**Comment by jomarko** [comment]
@tarilabs thank you.

**Pull request closed without merging**
