### PR TITLE
[DROOLS-6702] Reduce the amount of rule information in PredicateInfor…

### PR DESCRIPTION
**Pull request by tkobayas**
…mation (#3987)

**Ports** 

Forward-port of https://github.com/kiegroup/drools/pull/3987

**JIRA**: 

https://issues.redhat.com/browse/DROOLS-6702

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Comment by tkobayas** [comment]
Kogito Apps Build / Maven Build (ubuntu-latest, 11) (pull_request)
```
2021-11-08T09:26:52.7538676Z [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 43.224 s <<< FAILURE! - in org.kie.kogito.index.postgresql.ProcessDataIndexPostgreSqlIT
2021-11-08T09:26:52.7543015Z [ERROR] org.kie.kogito.index.postgresql.ProcessDataIndexPostgreSqlIT.testProcessInstanceEvents  Time elapsed: 7.477 s  <<< FAILURE!
2021-11-08T09:26:52.7545486Z java.lang.AssertionError:
2021-11-08T09:26:52.7546153Z 1 expectation failed.
2021-11-08T09:26:52.7547244Z JSON path data.UserTaskInstances[0].attachments[0].name doesn't match.
2021-11-08T09:26:52.7548123Z Expected: newAttachmentContent
2021-11-08T09:26:52.7548834Z   Actual: NewTaskAttachmentName
```

(build) kogito-apps
```
[2021-11-08T08:33:16.199Z] [INFO] Running org.kie.kogito.taskassigning.service.SolverExecutorTest
[2021-11-08T08:34:12.510Z] [ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 50.216 s <<< FAILURE! - in org.kie.kogito.taskassigning.service.SolverExecutorTest
[2021-11-08T08:34:12.510Z] [ERROR] org.kie.kogito.taskassigning.service.SolverExecutorTest.stopWithSolverStarted  Time elapsed: 50.008 s  <<< ERROR!
[2021-11-08T08:34:12.510Z] java.util.concurrent.TimeoutException: stopWithSolverStarted() timed out after 50 seconds
[2021-11-08T08:34:12.510Z]      at org.junit.jupiter.engine.extension.TimeoutInvocation.createTimeoutException(TimeoutInvocation.java:70)
```

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
(build) kogito-apps
```
[2021-11-08T11:28:32.844Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 93.786 s <<< FAILURE! - in org.kie.kogito.index.inmemory.ProcessDataIndexInMemoryIT
[2021-11-08T11:28:32.844Z] [ERROR] org.kie.kogito.index.inmemory.ProcessDataIndexInMemoryIT.testProcessInstanceEvents  Time elapsed: 0.018 s  <<< ERROR!
[2021-11-08T11:28:32.844Z] java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[2021-11-08T11:28:32.844Z] Caused by: java.lang.reflect.InvocationTargetException
[2021-11-08T11:28:32.844Z] Caused by: java.lang.RuntimeException: Error waiting for test resource future to finish.
[2021-11-08T11:28:32.844Z] Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to start Quarkus test resource org.kie.kogito.index.quarkus.DataIndexInMemoryQuarkusTestResource@263ef1c1
[2021-11-08T11:28:32.844Z] Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.kie.kogito.index.quarkus.DataIndexInMemoryQuarkusTestResource@263ef1c1
[2021-11-08T11:28:32.844Z] Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
[2021-11-08T11:28:32.844Z] Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
[2021-11-08T11:28:32.844Z] Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
[2021-11-08T11:28:32.844Z] Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [49327] should be listening)
...
[2021-11-08T11:35:19.159Z] [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 71.594 s <<< FAILURE! - in org.kie.kogito.index.ProcessDataIndexInfinispanIT
[2021-11-08T11:35:19.159Z] [ERROR] org.kie.kogito.index.ProcessDataIndexInfinispanIT.testProcessInstanceEvents  Time elapsed: 17.031 s  <<< FAILURE!
[2021-11-08T11:35:19.159Z] java.lang.AssertionError:
[2021-11-08T11:35:19.159Z] 1 expectation failed.
[2021-11-08T11:35:19.159Z] JSON path data.UserTaskInstances[0].attachments.size() doesn't match.
[2021-11-08T11:35:19.159Z] Expected: is <0>
[2021-11-08T11:35:19.159Z]   Actual: null
```

(build) kogito-examples
```
[2021-11-08T11:05:53.686Z] [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 41.378 s <<< FAILURE! - in org.acme.travel.MultiMessagingIT
[2021-11-08T11:05:53.686Z] [ERROR] org.acme.travel.MultiMessagingIT.testProcess  Time elapsed: 13.18 s  <<< FAILURE!
[2021-11-08T11:05:53.686Z] org.opentest4j.AssertionFailedError: expected: <0> but was: <3>
[2021-11-08T11:05:53.686Z]      at org.acme.travel.MultiMessagingIT.testProcess(MultiMessagingIT.java:95)
...
[2021-11-08T11:06:53.528Z] [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 46.503 s <<< FAILURE! - in org.acme.travel.MessagingIT
[2021-11-08T11:06:53.528Z] [ERROR] org.acme.travel.MessagingIT.testProcess  Time elapsed: 14.639 s  <<< FAILURE!
[2021-11-08T11:06:53.528Z] org.opentest4j.AssertionFailedError: expected: <0> but was: <3>
[2021-11-08T11:06:53.528Z]      at org.acme.travel.MessagingIT.testProcess(MessagingIT.java:93)
```
They seem to be flaky tests. Just in case, run again...

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
(build) kogito-apps : Flaky test. Not related to this PR.
```
[2021-11-09T03:41:01.294Z] [ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.353 s <<< FAILURE! - in org.kie.kogito.jobs.service.repository.postgresql.PostgreSqlJobRepositoryIT
[2021-11-09T03:41:01.294Z] [ERROR] org.kie.kogito.jobs.service.repository.postgresql.PostgreSqlJobRepositoryIT.testFindAll  Time elapsed: 0.059 s  <<< FAILURE!
[2021-11-09T03:41:01.294Z] org.opentest4j.AssertionFailedError:
[2021-11-09T03:41:01.294Z]
[2021-11-09T03:41:01.294Z] expected: 1
[2021-11-09T03:41:01.294Z]  but was: 2
[2021-11-09T03:41:01.294Z]
[2021-11-09T03:41:03.916Z] [INFO]
[2021-11-09T03:41:03.916Z] [INFO] Results:
[2021-11-09T03:41:03.916Z] [INFO]
[2021-11-09T03:41:03.916Z] [ERROR] Failures:
[2021-11-09T03:41:03.916Z] [ERROR]   PostgreSqlJobRepositoryIT>BaseJobRepositoryTest.testFindAll:100
[2021-11-09T03:41:03.916Z] expected: 1
[2021-11-09T03:41:03.916Z]  but was: 2
```

**Pull request merged**
