### PR TITLE
[DROOLS-6681] JSON Marshalling/Unmarshalling of Commands behaves diff…

### PR DESCRIPTION
**Pull request by tkobayas**
…erently than JAXB

**Ports** 
This PR is for 7.x.

kie-server fix is not needed for drools main but we may forward port this change for consistency. Also note that kie-soup change  will be done in drools repo in case of main.
 -> https://github.com/kiegroup/drools/pull/4223

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6681

**referenced Pull Requests**: 
* https://github.com/kiegroup/kie-soup/pull/247
* https://github.com/kiegroup/droolsjbpm-integration/pull/2709

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
FDB error. This is an unreliable test. Now it's marked as `@Ignore`.
```
java.lang.AssertionError: expected:<true> but was:<false>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.drools.workbench.screens.testscenario.backend.server.ScenarioRunnerServiceTest.testScenario(ScenarioRunnerServiceTest.java:260)
	at org.drools.workbench.screens.testscenario.backend.server.ScenarioRunnerServiceTest.testIsGithubContributor(ScenarioRunnerServiceTest.java:166)
```

**Comment by tkobayas** [comment]
This PR (kie-soup/drools/droolsjbpm-integration) does:

* Make AgendaFilter work for JSON/XSTREAM
    * JSON : Fix JSONMarshaller to handle `@XmlAnyElement` (`findNameForSerialization`/`findNameForDeserialization`)
    * XSTREAM : Fix FireAllRulesConverter in XStreamXML. Add *AgendaFilter to ALLOWLIST in XStreamUtils
* Support UpdateCommand
    * JAXB, JSON : Accept UpdateCommand in BatchExecutionCommandImpl
    * JSON : Move `@XmlElement` on `handle` from method to field so that jackson can handle it
    * XSTREAM : Add UpdateConverter in XStreamXML
* Fix GetObjectCommand fact-handle for JSON
    * JSON : Move `@XmlElement` on `disconnectedFactHandle` from method to field so that jackson can handle it

Also added unit tests and integration tests accordingly.

**Comment by tkobayas** [comment]
Jenkins run fdb

**Review by mariofusco — APPROVED** [review]

**Comment by tkobayas** [comment]
FDB errors:
```
[2022-02-17T06:26:42.673Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 66.709 s <<< FAILURE! - in org.kie.server.springboot.samples.KeycloakKieServerTest
```
 -> Found in daily build 

```
[2022-02-17T06:40:26.541Z] [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.247 s <<< FAILURE! - in org.kie.workbench.common.services.refactoring.backend.server.indexing.PackageDescrIndexVisitorLogicTest
[2022-02-17T06:40:26.541Z] [ERROR] visitLogicTest(org.kie.workbench.common.services.refactoring.backend.server.indexing.PackageDescrIndexVisitorLogicTest)  Time elapsed: 0.088 s  <<< FAILURE!
[2022-02-17T06:40:26.541Z] java.lang.AssertionError: visit(...) method missing for org.drools.compiler.lang.descr.GroupByDescr
[2022-02-17T06:40:26.541Z]      at org.junit.Assert.fail(Assert.java:89)
[2022-02-17T06:40:26.541Z]      at org.kie.workbench.common.services.refactoring.backend.server.indexing.PackageDescrIndexVisitorLogicTest.visitLogicTest(PackageDescrIndexVisitorLogicTest.java:118)
```
 -> Found in daily build 

```
[2022-02-17T07:43:09.639Z] [ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.103 s <<< FAILURE! - in org.jbpm.process.workitem.archive.ArchiveWorkitemHandlerTest
[2022-02-17T07:43:09.639Z] [ERROR] testNoArchiveSpecified(org.jbpm.process.workitem.archive.ArchiveWorkitemHandlerTest)  Time elapsed: 0.004 s  <<< ERROR!
[2022-02-17T07:43:09.639Z] java.lang.NoClassDefFoundError: javax/persistence/PersistenceException
[2022-02-17T07:43:09.639Z]      at org.jbpm.process.workitem.core.AbstractLogOrThrowWorkItemHandler.canExceptionTriggerSubprocess(AbstractLogOrThrowWorkItemHandler.java:84)

[2022-02-17T07:43:21.331Z] [ERROR] Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.632 s <<< FAILURE! - in org.jbpm.process.workitem.exec.ExecShellScriptWorkItemHandlerTest

[2022-02-17T07:43:26.865Z] [ERROR] Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 5.121 s <<< FAILURE! - in org.jbpm.process.workitem.exec.ExecWorkItemHandlerTest

[2022-02-17T07:43:34.328Z] [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.747 s <<< FAILURE! - in org.jbpm.process.workitem.ftp.FTPUploadWorkItemHandlerTest

[2022-02-17T07:43:40.707Z] [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.634 s <<< FAILURE! - in org.jbpm.process.workitem.jabber.JabberWorkItemHandlerTest

[2022-02-17T07:44:07.115Z] [ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.417 s <<< FAILURE! - in org.jbpm.process.workitem.parser.ParserWorkItemHandlerTest

[2022-02-17T07:44:13.767Z] [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.657 s <<< FAILURE! - in org.jbpm.process.workitem.rss.RSSWorkItemHandlerTest
```
 -> Found in daily build 

```
[2022-02-17T08:53:29.775Z] [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 224.728 s <<< FAILURE! - in org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest
[2022-02-17T08:53:29.775Z] [ERROR] importAndBuildProjectFromStockRepository(org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest)  Time elapsed: 62.646 s  <<< ERROR!
[2022-02-17T08:53:29.775Z] org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.id: add-project-dropdown (tried for 15 second(s) with 500 milliseconds interval)
[2022-02-17T08:53:29.775Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.lambda$importAndBuildProjectFromStockRepository$0(ProjectLibraryIntegrationTest.java:51)
[2022-02-17T08:53:29.775Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importBuildDeployAndCheckArtifact(ProjectLibraryIntegrationTest.java:68)
[2022-02-17T08:53:29.775Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository(ProjectLibraryIntegrationTest.java:49)
[2022-02-17T08:53:29.775Z] Caused by: org.openqa.selenium.NoSuchElementException:
[2022-02-17T08:53:29.775Z] Cannot locate an element using By.id: add-project-dropdown
[2022-02-17T08:53:29.775Z] For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
[2022-02-17T08:53:29.775Z] Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
[2022-02-17T08:53:29.775Z] System info: host: 'eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.49.1.el7.x86_64', java.version: '11.0.13'
[2022-02-17T08:53:29.775Z] Driver info: driver.version: unknown
[2022-02-17T08:53:29.775Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.lambda$importAndBuildProjectFromStockRepository$0(ProjectLibraryIntegrationTest.java:51)
[2022-02-17T08:53:29.775Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importBuildDeployAndCheckArtifact(ProjectLibraryIntegrationTest.java:68)
[2022-02-17T08:53:29.775Z]      at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository(ProjectLibraryIntegrationTest.java:49)
```
 -> Not found in daily build but very likely unrelated to this PR.

So we may think FBD is okay.

**Pull request merged**
