### PR TITLE
DROOLS-4343 Change fact handle id type to long

### PR DESCRIPTION
**Pull request by baldimir**
@mariofusco @etirelli please review. This is based on original PR from @mariofusco, but without the split to base and extended ID which is not needed, because the types are compatible in protobuf [1]. Sorry Mario, I didn't want to base this on your branch because I didn't want to risk having any ID split leftovers there so I just used your changes over master. 

Needs to be merged with:
https://github.com/kiegroup/openshift-drools-hacep/pull/9

[1] https://developers.google.com/protocol-buffers/docs/proto3#updating

### CODE REVIEW

**Comment by baldimir** [comment]
I didn't have time to run all tests locally, so I will fix anything that comes up red from the PR checks.

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Review by mariofusco — APPROVED** [review]

**Comment by baldimir** [comment]
jenkins execute compile downstream build

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Pull request merged**
