### PR TITLE
Replace database profile to add maven's JDBC driver jar to the test c…

### PR DESCRIPTION
**Pull request by ge0ffrey**
…lasspath with surefire's additionalClasspathElement.

### CODE REVIEW

**Comment by ge0ffrey** [comment]
@triceo when this is applied, you should be able to remove the "-P database" from your database jenkins jobs (although I presume it won't hurt if you keep it). The "-Dmaven.jdbc.driver.jar=..." is still needed of course.

**Comment by psiroky** [comment]
+1 to merge. Thanks @ge0ffrey!

**Comment by psiroky** [comment]
I've also tested this with PostgreSQL 9.5 and it works like a charm!

**Comment by ge0ffrey** [comment]
Great :)

**Pull request closed without merging**
