### PR TITLE
DROOLS-4186 : Guided Rules does not output parenthesis in DRL

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-4186

### CODE REVIEW

**Comment by Rikkola** [comment]
@jomarko @manstis if you could review please. I think the safe way to fix this is removing the surrounding brackets. At least the existing unit tests only check the brackets are removed in these cases.

**Comment by Rikkola** [comment]
@jomarko @manstis if you could review please. I think the safe way to fix this is removing the surrounding brackets. At least the existing unit tests only check the brackets are removed in these cases.

**Review by manstis — APPROVED** [review]
Thanks @Rikkola your test is exactly what I was about to suggest on this PR before I scrolled down :-)

**Comment by jomarko** [comment]
No comments to code, however question, the fix is for guided rule templates, as the attached project uses guided rule templates, however I checked simple guided rules, and there is the issue still present, my question is if we should solve also guided rules as part of [DROOLS-4186](https://issues.jboss.org/browse/DROOLS-4186). If not, then I can approve.

**Comment by Rikkola** [comment]
@jomarko I know where I need to fix this, but didn't manage to reproduce with Guided Rules. If you can give me simple ( or less simple ) reproducer I'll do the fix for the other locations.

**Comment by Rikkola** [comment]
@manstis @jomarko I found these 3 locations where we have the same issue ;) I hope I got them all now.

**Comment by Rikkola** [comment]
SonarCloud finds a code smell from an area that I did not edit. The fix it proposes is ok, but not the worst issue in that "code chapter". The class itself could use refactoring, but with the test coverage I know we have for this area I would rather not touch it.

**Review by jomarko — APPROVED** [review]
Works fine in all editors, so approving, however want to ask if the video show an issue or not, if a user put quoted string value list, the generated rule has "double quoted" the string values. is it expected? Really not sure.

https://drive.google.com/open?id=166ek_qoOL4EEyjsP8y7XeP_qcaVVJ7M7

**Comment by Rikkola** [comment]
It probably should not add quotes then, but since it has always done so I'm not sure if we should change it. It could be someone is depending on it. These things tend to be tricky to fix due to backwards compatibility.

**Comment by jomarko** [comment]
@Rikkola thank you for response. feel free to merge.

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Could this be merged please.

**Pull request merged**
