### PR TITLE
DROOLS-1630 DMN support during incremental KieContainer upgrade

### PR DESCRIPTION
**Pull request by tarilabs**

### CODE REVIEW

**Comment by tarilabs** [comment]
( depends on kiegroup/droolsjbpm-knowledge#241 )

**Comment by tarilabs** [comment]
jenkins execute full downstream build

**Comment by tarilabs** [comment]
Downstream build error is unrelated with this change:
```
16:54:57 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project guvnor-rest-backend: Compilation failure
16:54:57 [ERROR] /home/jenkins/workspace/drools-downstream-pullrequests/downstream-repos/guvnor/guvnor-rest/guvnor-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java:[57,34] cannot find symbol
16:54:57 [ERROR] symbol:   class SimpleAsyncExecutorService
16:54:57 [ERROR] location: package org.uberfire.commons.async
```

**Comment by etirelli** [comment]
Approved, assuming, as you said, that the break in the build is not related to these changes.

**Review by etirelli — APPROVED** [review]

**Pull request merged**
