### PR TITLE
DROOLS-3673: Disable inserting rows according to string id

### PR DESCRIPTION
**Pull request by jomarko**
@manstis please have a look, this is a corollary to your kiegroup/drools-wb#1076

### CODE REVIEW

**Review by manstis — APPROVED** [review]

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by jomarko** [comment]
Jenkins please execute full downstream build

**Comment by baldimir** [comment]
Jenkins please execute full downstream build

**Comment by baldimir** [comment]
jenkins execute compile downstream

**Comment by baldimir** [comment]
jenkins execute compile downstream build

**Review by baldimir — APPROVED** [review]

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@kiegroup/gatekeepers ready to merge

**Pull request merged**
