### PR TITLE
[DROOLS-6270] always use secure xstream marshaller in drools

### PR DESCRIPTION
**Pull request by mariofusco**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6270

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
thank you!

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
Failures on kie-server are not related with this change.

**Pull request merged**
