### PR TITLE
[DROOLS-1530] fix double accumulate with join

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
jenkins full downstream build

**Comment by ge0ffrey** [comment]
@psiroky Did I use the correct magic phrase in my comment above? We need it to run optaplanner's tests too with this PR.

**Comment by ge0ffrey** [comment]
jenkins execute full downstream build

**Comment by psiroky** [comment]
@ge0ffrey unfortunately this does not work (yet)

**Pull request merged**
