### PR TITLE
[7.48.x] DROOLS-5848 : CallMethod with ActionFieldFunctions does not compile  

### PR DESCRIPTION
**Pull request by Rikkola**
* DROOLS-5848 : CallMethod with ActionFieldFunctions does not compile

* DROOLS-5848: Extend coverage

(cherry picked from commit 00c9b28010aced286f5b1db3fbec77f148310806)

**Thank you for submitting this pull request**

**JIRA**:  

[DROOLS-5848](https://issues.redhat.com/browse/DROOLS-5848)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by jomarko — APPROVED** [review]

**Comment by Rikkola** [comment]
@danielzhe Hi, this is the same as here https://github.com/kiegroup/drools/pull/3263

**Review by danielzhe — APPROVED** [review]

**Comment by Rikkola** [comment]
Been ages since the tests ran, so better to double check.
Jenkins retest this

**Comment by Rikkola** [comment]
"Required context class hudson.FilePath is missing"

Jenkins run cdb

**Comment by Rikkola** [comment]
"/home/jenkins/workspace/KIE/7.48.x/compile/drools-7.48.x.compile@tmp/durable-30189c13/script.sh: line 1: /home/jenkins/workspace/KIE/7.48.x/compile/drools-7.48.x.compile/trace.sh: No such file or directory" 

Jenkins run cdb

**Comment by Rikkola** [comment]
Jenkins run cdb

**Comment by Rikkola** [comment]
"no space left on device" 🤔 
Jenkins run cdb

**Comment by Rikkola** [comment]
> [2021-02-25T13:24:50.535Z] [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.drools.eclipse: Compilation failure: Compilation failure: 
> [2021-02-25T13:24:50.535Z] [ERROR] /home/jenkins/workspace/KIE/7.48.x/compile/drools-7.48.x.compile/kiegroup_droolsjbpm-tools/drools-eclipse/org.drools.eclipse/src/main/java/org/drools/eclipse/editors/completion/RuleCompletionProcessor.java:[1164] 
> [2021-02-25T13:24:50.535Z] [ERROR] 	context.setInterceptors(dialect.getInterceptors());

Jenkins run cdb

**Comment by Rikkola** [comment]
Jenkins run cdb

**Comment by Rikkola** [comment]
Jenkins run cdb

**Comment by Rikkola** [comment]
```
[2021-03-03T13:34:12.102Z] [ERROR] Message [id=1, kieBase=defaultKieBase, level=ERROR, path=com/myspace/mortgage_app/MortgageApprovalProcess.bpmn, line=-1, column=0
[2021-03-03T13:34:12.102Z] [ERROR]    text=Process Compilation error The method getProperty() is undefined for the type Object]
```

Jenkins run cdb

**Comment by Rikkola** [comment]
```
[2021-03-03T20:42:22.420Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-sheets-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[2021-03-03T20:42:22.420Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-sheets-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
```

jbpm bits broken, let's see if it is random.

**Comment by Rikkola** [comment]
Jenkins run cdb

**Comment by Rikkola** [comment]
Jenkins run fdb

**Pull request merged**
