### PR TITLE
Make KieFileSystem.write() smart enough to write java files under src…

### PR DESCRIPTION
**Pull request by ge0ffrey**
…/main/java/... instead of src/main/resources/...

### CODE REVIEW

**Comment by manstis** [comment]
A test would be nice :)

**Comment by ge0ffrey** [comment]
Test added :)

**Comment by manstis** [comment]
It's not my call - I'm just being nosey on a Friday afternoon - but IMO an assertion that the KieModule's content would be nice (that the path /src/main/java contains the Java file and /src/main/resources contains the DRL...) but I'm happy to be `@Ignore("manstis is irrelevant")` :)

**Comment by ge0ffrey** [comment]
@manstis see my extra commit, that does that assertion for the java class (other tests do it for drl resources already)

**Pull request merged**
