### PR TITLE
DROOLS-5540 Review kie-dmn-backend DMN examples version in codebase

### PR DESCRIPTION
**Pull request by tarilabs**

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
```
Test Result (7 failures / +7)
org.kie.hacep.KafkaTest.basicTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsLeaderTest.processOneSentMessageAsLeaderTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.server.springboot.samples.KieServerTest.testProcessStartAndAbortUsingAlias
org.kie.server.springboot.samples.KieServerTest.testProcessStartAndAbort
org.kie.server.springboot.samples.KieServerTest.testProcessStartAndWorkOnUserTask
```
FDB failures unrelated

**Comment by tarilabs** [comment]
```
12:58:24  [WS-CLEANUP] Deleting project workspace...
12:58:24  [WS-CLEANUP] Deferred wipeout is used...
12:58:24  [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Adding one-line test results to commit status...
Setting status of b3cc2488fd76442f2506cba53828201778b65395 to FAILURE with url https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/compileDownstream/job/new-CDB-drools-master.compile/73/ and message: 'Build finished. No test results found.'
Using context: Linux - Compile Downstream Build (***)
ERROR: script returned exit code 1
Finished: FAILURE
```

FDC unrelated

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
Jenkins test again

**Comment by tarilabs** [comment]
Jenkins execute full downstream compile

**Comment by tarilabs** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins execute compile downstream

**Comment by tarilabs** [comment]
Jenkins execute compile downstream build

**Comment by tarilabs** [comment]
Jenkins execute compile downstream build

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
```
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42893/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerEmptyBody[0: JAXB KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42893/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42893/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerEmptyBody[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:42893/kie-server-services/services/rest/server'}]
org.kie.server.integrationtests.common.KieServerContainerCRUDIntegrationTest.initializationError
org.kie.server.integrationtests.common.KieServerIntegrationTest.initializationError
org.kie.server.integrationtests.common.jms.ContainerJmsResponseHandlerIntegrationTest.initializationError
org.jbpm.springboot.samples.CustomNotificationListenerTest.testProcessEventListenerRegistration
org.kie.hacep.KafkaTest.basicTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsLeaderTest.processOneSentMessageAsLeaderTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
```

the FDB failures are still unrelated.

**Comment by tarilabs** [comment]
@kiegroup/gatekeepers can a gatekeeper kindly merge this one, using squash, please?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
Like it was here https://github.com/kiegroup/drools/pull/3010#issuecomment-665710846
and like it was here https://github.com/kiegroup/drools/pull/3010#issuecomment-667164741
Also 
```
Test Result (1 failure / +1)
A new tenant can be created, who can have their own employees, spots, skills and shifts.basic tenant workflow
```
FDB failures unrelated.

Can a @kiegroup/gatekeepers kindly merge with squash please?

**Pull request merged**
