### PR TITLE
[6.4.x] DROOLS-1286: Guided Decision Table: Unable to specify field type with Condition BRL fragment

### PR DESCRIPTION
**Pull request by karreiro**
## Cherry picked from https://github.com/droolsjbpm/drools/pull/922

See https://issues.jboss.org/browse/DROOLS-1286

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please retest this.

**Review by manstis — APPROVED** [review]
+1 to merge (when green).

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Pull request merged**
