### PR TITLE
Drools 260

### PR DESCRIPTION
**Pull request by calcacuervo**
DROOLS-260. Fix and test.

### CODE REVIEW

**Comment by sotty** [comment]
Great catch! I have cherry-picked it

**Comment by triceo** [comment]
Does this make sense to apply to 6.x as well?

**Comment by mdproctor** [comment]
yes, this should be applied to 6.0 too

**Comment by mdproctor** [comment]
Not sure why this is open. The code seems to be applied to 5.6 and master (6.x). Please confirm and close.

**Comment by etirelli** [comment]
Yes, this was applied. Closing it.

**Pull request closed without merging**
