### PR TITLE
Removed deprecated annotation

### PR DESCRIPTION
**Pull request by pibizza**
This is a fix to remove a compilation problem that appears when we upgrade the hamcrest version.

The hamcrest upgrade is required to remove a potential conflict that is generated by upgrading awaitility version.

The awaitility upgrade is required to properly backport a fix to unstable time sensitive tests.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Comment by pibizza** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
@pibizza you should name the branch the same as on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1882 as now they can't be tested together :(

**Comment by pibizza** [comment]
@mareknovotny this patch can  be actually applied as it is - it does not require to work with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1882. Once this patch is working and applied I can retest the other and see if there are other issues.

**Comment by mareknovotny** [comment]
> @mareknovotny this patch can be actually applied as it is - it does not require to work with [kiegroup/droolsjbpm-build-bootstrap#1882](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1882). Once this patch is working and applied I can retest the other and see if there are other issues.

sure, but it could be faster to merge both changes as one provoked the other. But it is your choice ;)

**Comment by mareknovotny** [comment]
Failed
[org.kie.workbench.common.services.refactoring.backend.server.indexing.PackageDescrIndexVisitorLogicTest.visitLogicTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.x/job/fdb/job/drools-7.x.fdb/25/testReport/org.kie.workbench.common.services.refactoring.backend.server.indexing/PackageDescrIndexVisitorLogicTest/visitLogicTest/history)



<h3>Error Message</h3><pre>visit(...) method missing for org.drools.compiler.lang.descr.GroupByDescr</pre><h3>Stacktrace</h3>

```
java.lang.AssertionError: visit(...) method missing for org.drools.compiler.lang.descr.GroupByDescr
	at org.junit.Assert.fail(Assert.java:89)
	at org.kie.workbench.common.services.refactoring.backend.server.indexing.PackageDescrIndexVisitorLogicTest.visitLogicTest(PackageDescrIndexVisitorLogicTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
</pre>Failed

org.kie.workbench.common.services.refactoring.backend.server.indexing.PackageDescrIndexVisitorLogicTest.visitLogicTest
Failing for the past 4 builds (Since [#22](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.x/job/fdb/job/drools-7.x.fdb/22/) )
[Took 79 ms.](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.x/job/fdb/job/drools-7.x.fdb/25/testReport/org.kie.workbench.common.services.refactoring.backend.server.indexing/PackageDescrIndexVisitorLogicTest/visitLogicTest/history)
Error Message

visit(...) method missing for org.drools.compiler.lang.descr.GroupByDescr

Stacktrace

java.lang.AssertionError: visit(...) method missing for org.drools.compiler.lang.descr.GroupByDescr
	at org.junit.Assert.fail(Assert.java:89)
	at org.kie.workbench.common.services.refactoring.backend.server.indexing.PackageDescrIndexVisitorLogicTest.visitLogicTest(PackageDescrIndexVisitorLogicTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

...

Caused by: java.lang.ClassNotFoundException: com.sun.tools.xjc.ErrorReceiver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
```

**Comment by pibizza** [comment]
I cannot see how this failure can be related to the patch. I have asked @mariofusco to check with me and he agrees. I am going to let the build rerun to see if it was a glitch. I took the opportunity to remove the unused import of the deprecated class.

**Comment by mareknovotny** [comment]
i agree, i could see the same failure/error on PR not related to change in kie-wb-common too

**Pull request merged**
