### PR TITLE
AF-540: moved to appformer generic java data model definitions

### PR DESCRIPTION
**Pull request by porcelli**
This is a mandatory step before merging the repos to form AppFormer single repository.

Related PRs:
https://github.com/AppFormer/uberfire/pull/784
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/487
https://github.com/kiegroup/drools/pull/1397
https://github.com/kiegroup/droolsjbpm-integration/pull/1135
https://github.com/kiegroup/guvnor/pull/484
https://github.com/kiegroup/kie-wb-common/pull/1005
https://github.com/kiegroup/drools-wb/pull/560
https://github.com/kiegroup/optaplanner-wb/pull/205

### CODE REVIEW

**Comment by porcelli** [comment]
please jenkins test this

**Comment by porcelli** [comment]
please jenkins test this

**Comment by psiroky** [comment]
@porcelli the PR build is now taking into account the UF PR. The failing tests seems to be related to changes in this PR, but I am not 100 % sure.

**Comment by porcelli** [comment]
@psiroky thx!

**Comment by porcelli** [comment]
please jenkins test this

**Comment by porcelli** [comment]
please jenkins test this

**Review by manstis — APPROVED** [review]

**Pull request merged**
