### PR TITLE
[BAQE-439] Once more:  Narayana + DBCP integration

### PR DESCRIPTION
**Pull request by rsynek**
This reverts commit f7360042ea205a8a3398e4bbafbcbf65848fd36b.
(reverting the previous revert)

### CODE REVIEW

**Comment by rsynek** [comment]
jenkins execute full downstream build

**Comment by rsynek** [comment]
looks like unstable tests in droolsjbpm-integration.

**Comment by rsynek** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
failed tests are in random failures http://janhrcek.cz/random-failures/#

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
