### PR TITLE
DO NOT MERGE: BOGUS PR TO BE CLOSED DROOLS-1598: implementing additional FEEL functions

### PR DESCRIPTION
**Pull request by etirelli**
@tarilabs I started implementing the additional functions. Once you have the profile configuration implemented, we can move these functions into a profile if we wish.

### CODE REVIEW

**Review by tarilabs — CHANGES_REQUESTED** [review]
-1. Sorry but I'm a bit confused, on my side it display in the chain a commit 32b0069 which looks ~like a cherry pick and re-applying Signavio function in the main profile, instead of isolated in the signavio profile only.

**Comment by etirelli** [comment]
@tarilabs don't look at individual commits, look at the result, because all of these commits will be squashed. Unfortunately, as I told you, I don't know why this PR got messed up, but if you look at the end result, I don't think Signavio functions were applied to the main profile. See here: 

https://github.com/kiegroup/drools/pull/1346/files#diff-644493c3e445a1218fd2d0e9b19e7eb6L25

**Comment by jomarko** [comment]
@etirelli @tarilabs so is this now about merge? @baldimir is sick this week so I could have a look.

**Review by tarilabs — CHANGES_REQUESTED** [review]
@etirelli okay but even if I look on the "final result" I sampled two, if I'm not wrong I'm seeing a DayFunction and a IntegerFunction which are part of the Signavio profile but are also present in the kie-dmn-feel module. I don't think are activated on the main feel builtin function list, but their class definition is still there (inside -feel).

https://github.com/kiegroup/drools/pull/1346/files#diff-9fe05cad29795043b9f03bba7e84addc
https://github.com/kiegroup/drools/pull/1346/files#diff-2db769fa92c3affac3879a2b9b304882

Just to mention a couple sample

**Review by tarilabs — CHANGES_REQUESTED** [review]
Additionally, this brings back in the commits of the PRs:
https://github.com/etirelli/drools/pull/2
https://github.com/etirelli/drools/pull/3
https://github.com/etirelli/drools/pull/4

but it didn't bring back in the commits for the PR:
https://github.com/etirelli/drools/pull/5

**Comment by etirelli** [comment]
Outdated.

**Pull request closed without merging**
