### PR TITLE
Fix for JBRULES-3138

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by etirelli** [comment]
Cristiano, do you have a unit test for this fix? Thanks, Edson

**Comment by cristianonicolai** [comment]
Sure, it's attached here: https://issues.jboss.org/browse/JBRULES-3138

**Comment by etirelli** [comment]
Cristiano, thanks, but since the test case is not ready for commit (i.e., it is not a patch that can be applied), I can't merge the pull request at this point. So, if you can provide the test case with your pull requests, it speeds up the merging process. Otherwise, as soon as me or someone else has the time to isolate the test case, we will add it, merge, and close the ticket. Thanks, Edson.

**Comment by cristianonicolai** [comment]
No worries, I'll update my pull request.

**Comment by etirelli** [comment]
Cristiano, thank you for providing the test case and the fix. Applied to both master and 5.2.x branches.

**Pull request closed without merging**
