### PR TITLE
[7.59.x] RHDM-1816: today() and now() functions not evaluated correctly in Test Scenarios

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**:  https://issues.redhat.com/browse/RHDM-1816

Backport of these two PRs @tarilabs provided to fix the issue: 
- https://github.com/kiegroup/drools/pull/3834
- https://github.com/kiegroup/drools/pull/3840

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
backports do not _require_ Eng approvals, I'm glad to hear however the backport exists 👍

**Comment by RishiRajAnand** [comment]
@yesamer  could you please confirm if this is ready for merge ?

**Comment by yesamer** [comment]
@RishiRajAnand I think we need the QE approval by @jstastny-cz

**Comment by jstastny-cz** [comment]
I am currently reviewing - there's discrepancy between Tester field in Jira and actual reviewers of the original PRs. So I will most probably delegate this PR review.

**Review by pibizza — APPROVED** [review]
Looks good to me.

**Comment by yesamer** [comment]
Thank you @pibizza !
I think now we can merge it @RishiRajAnand.

**Comment by yesamer** [comment]
@tarilabs can you please merge this?

**Comment by tarilabs** [comment]
Both Windows test looks failing, I assume you are requesting a merge as the Windows failure unrelated. Merging.

**Pull request merged**
