### PR TITLE
DROOLS-2147 Fix Type test error

### PR DESCRIPTION
**Pull request by tarilabs**
/cc @etirelli @baldimir

### CODE REVIEW

**Review by etirelli — APPROVED** [review]

**Comment by etirelli** [comment]
Looks good! 

Question, does this work for nested lists? like lists of lists of lists of something?

**Comment by etirelli** [comment]
@tarilabs can you also please trim the string message in that error? when printing the actual value of the object, lets say print only the first 50 characters and then print a '...' at the end if there is more than 50 characters... wdyt?

**Comment by tarilabs** [comment]
Message trimmed "Apache Camel"-style.

**Comment by etirelli** [comment]
@tarilabs sorry, I merged another PR that generated a conflict. Can you please rebase this PR?

**Pull request merged**
