### PR TITLE
[DROOLS-6680] Already expired event entering session remain forever i…

### PR DESCRIPTION
**Pull request by slem1**
…n working memory

**JIRA**: 

[link](https://issues.redhat.com/browse/DROOLS-6680)

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by slem1** [comment]
Hi @mariofusco , is there an issue with my code ? (just see you opened another PR for this),

thanks

**Comment by mariofusco** [comment]
@slem1 There's no issue (except that checking `handle instanceof EventFactHandle` is redundant is if it is expired for sure it is an event), I just propagated the same fix also to our `main` branch since you sent this pull request (that I'm about to merge) against branch `7.x`.

**Comment by slem1** [comment]
@mariofusco ah sorry didn't see yours is targeting the main branch, thank you

**Pull request merged**
