### PR TITLE
Backport of https://github.com/droolsjbpm/drools/pull/660

### PR DESCRIPTION
**Pull request by ge0ffrey**
Please wait until Jenkins verifies it ;)

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Ready to merge now.

**Comment by manstis** [comment]
Likewise (squashed commits)

**Comment by ge0ffrey** [comment]
Squashed. Added journal=null trick.

**Comment by psiroky** [comment]
+1 to merge. Thanks @ge0ffrey!

**Comment by psiroky** [comment]
Merged into 6.4.x.

**Pull request closed without merging**
