### PR TITLE
[7.23.x] DROOLS-4284 : Adding 'The following does not exist:' to LHS of the rule causes exception

### PR DESCRIPTION
**Pull request by Rikkola**
Master version: https://github.com/kiegroup/drools/pull/2422

https://issues.jboss.org/browse/DROOLS-4284

### CODE REVIEW

**Comment by Rikkola** [comment]
@manstis @Bonuseto Good morning. Cherry picking to 7.23.x. If you could please review.

**Review by manstis — APPROVED** [review]

**Comment by Rikkola** [comment]
jenkins execute full downstream build

**Comment by Bonuseto** [comment]
jenkins execute full downstream build

**Review by kkufova — APPROVED** [review]

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers please merge. The full build started just to make manual testing faster, but un the end it never passed

**Pull request merged**
