### PR TITLE
[7.59.x] [DROOLS-6684] fix peers propagation during an insert (#4029) (#4031)

### PR DESCRIPTION
**Pull request by tkobayas**
(cherry picked from commit 49f0e0c9785d854d96f15c4f33cacb4c05a513f4)

**JIRA**: 
* https://issues.redhat.com/browse/RHDM-1865
    * Backport DROOLS-6684 to 7.59.x

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* for a <b>full downstream build</b> 
  * for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  * for <b>github actions</b> job: add the label `run_fdb`

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
GHA windows failures are not related to this PR.
```
2022-01-13T11:42:06.2451894Z [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 134.56 s <<< FAILURE! - in org.kie.dmn.feel.client.showcase.FEELShowcaseIT
...
2022-01-13T12:06:17.3489213Z [ERROR] Tests run: 82, Failures: 2, Errors: 0, Skipped: 4, Time elapsed: 29.811 s <<< FAILURE! - in org.drools.compiler.integrationtests.TimerAndCalendarTest
```

FDB failures:
```
[2022-01-17T13:45:57.845Z] [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 9.56 s <<< FAILURE! - in org.optaplanner.examples.examination.app.ExaminationPerformanceTest
[2022-01-17T13:45:57.845Z] [ERROR] runSpeedTest[1]  Time elapsed: 4.968 s  <<< ERROR!
[2022-01-17T13:45:57.845Z] org.drools.mvel.ConstraintEvaluationException: Error evaluating constraint 'Math.abs($leftPeriodIndex - periodIndex) < ($constraintConfiguration.getPeriodSpreadLength() + 1)' in [Rule "periodSpread" in org/optaplanner/examples/examination/solver/examinationConstraints.drl]
[2022-01-17T13:45:57.845Z]      at org.drools.mvel.MVELConstraint.evaluate(MVELConstraint.java:282)
```
ExaminationPerformanceTest has just amended by https://github.com/kiegroup/optaplanner/pull/1795

```
[2022-01-17T20:57:17.734Z] [ERROR] Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.638 s <<< FAILURE! - in org.drools.workbench.screens.testscenario.backend.server.ScenarioRunnerServiceTest
[2022-01-17T20:57:17.734Z] [ERROR] testIsGithubContributor(org.drools.workbench.screens.testscenario.backend.server.ScenarioRunnerServiceTest)  Time elapsed: 2.626 s  <<< FAILURE!```
```
ScenarioRunnerServiceTest.testIsGithubContributor is flaky. Not related to this PR.

**Comment by tkobayas** [comment]
@mariofusco Please merge this backport PR. Thanks!

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
