### PR TITLE
DROOLS-3355: Improve Assembler/Weaver API

### PR DESCRIPTION
**Pull request by evacchi**
Strictly depends on 
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/351

Must be merged together with
- https://github.com/kiegroup/jbpm/pull/1393

Details:

- implement the updated API in `kie-api` and `kie-internal`
- add a simplified, boilerplate-lighter API for Assemblers, under `org.drools.compiler.builder`. This is now used in Bayes
- preparatory work for jbpm externalization
- bits of refactoring in KnowledgeBuilderImpl: `Map<ResourceType, KieAssemblerService>` has been substituted for a more opaque `ResourceTypePackageRegistry`; heavy assembler-related logic has been moved there

### CODE REVIEW

**Comment by evacchi** [comment]
Jenkins please retest this

**Comment by evacchi** [comment]
Jenkins please retest this

**Comment by mariofusco** [comment]
ok to test

**Comment by evacchi** [comment]
ok to test

**Pull request merged**
