### PR TITLE
(6.4.z) [RHBRMS-3089] clear defined types cache in ProjectClassLoader when a declared type is changed during an incremental compilation

### PR DESCRIPTION
**Pull request by elguardian**
(cherry picked from commit a44f3ec2fd34f2c7fa2b3b8787be2f5339b1a963)

### CODE REVIEW

**Comment by mariofusco** [comment]
ok to test

**Review by baldimir — APPROVED** [review]
Looks ok, backport looks the same as original commit.

**Comment by mariofusco** [comment]
I didn't backport the fix because it didn't work on 6.5.x in a specific case (see IncrementalCompilationTest.testIncrementalCompilationWithRedeclares). The fix that works for 7.x doesn't work on 7. This is because in drools 7.x I modified the building process a lot first to implement the parallel engine, then for the parallel compilation and finally to accommodate the executable model. I tried to surgically take the changes related to this issue that I made on 7 and backport to 6.5.x but I just ended up with a bit mess and had to rollback everything. At the moment my advice is to avoid trying to backport this fix to 6.5.x.

**Comment by mareknovotny** [comment]
@mariofusco ok, thanks for the explanation, I was confused by JIRA, where you acked. So we need to decline everything.

**Pull request closed without merging**
