### PR TITLE
DROOLS-5644: Queries should be not considered on RULE based Test Scenario	

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**: https://issues.redhat.com/browse/RHDM-1448 
https://issues.redhat.com/browse/DROOLS-5644

@danielezonca @jstastny-cz Can you please review and test?
To filter out all `Query` and retain `Rule` only, I based my filter on `rule.getKnowledgeType()` method, which returns an enum `RULE` value in such a case. (`QUERY` is returned in case of a `Query`).

Screenshot from 2020-09-15 13-11-20

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]
LGTM

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Comment by yesamer** [comment]
@kiegroup/gatekeepers Can you please merge it?

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
