### PR TITLE
Query bug test.

### PR DESCRIPTION
**Pull request by tomasdavidorg**
There is a bug in drl file, when queries are commented.

### CODE REVIEW

**Comment by sotty** [comment]
I tried to reproduce it in 5.6 and it seems to work there.. if this is broken in master, could you open a JIRA ticket?
Thanks

**Comment by tomasdavidorg** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=967441

**Comment by mdproctor** [comment]
as this is just a test. We should probably merge it anyway, even if it works now.

**Comment by mariofusco** [comment]
I couldn't reproduce this problem on the master, so I am assuming this has been fixed by a previous commit. I merged this test case in a more concise way.

**Pull request closed without merging**
