### PR TITLE
DROOLS-3848 DMN Years and Months internals expect value is Comparable

### PR DESCRIPTION
**Pull request by tarilabs**
@etirelli @baldimir @jiripetrlik

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by etirelli** [comment]
@tarilabs question: if the engine receives a Period object as input (either input node, or as parameter to a decision service/bkm call), does it handle it properly with this change?

**Comment by tarilabs** [comment]
to a bkm call @etirelli ?

btw answer is "should" as `Period` implements `ChronoPeriod` but while I'm at this I will add test for this (inputdata and Decision service, but no idea how to invoke manually a bkm call from the runtime?)

**Comment by tarilabs** [comment]
Jenkins execute full downstream build

**Comment by tarilabs** [comment]
Downstream test error unrelated

```
Test Result (6 failures / +1)
org.jbpm.test.functional.timer.ConcurrentGlobalTimerServiceTest.testSessionPerProcessInstance
org.drools.workbench.services.verifier.plugin.client.DecisionTableAnalyzerMultipleIssuesFromFileTest.testBidimensionalGapAnalysis
org.drools.workbench.services.verifier.plugin.client.DecisionTableAnalyzerMultipleIssuesFromFileTest.testMissingRangeAndRedundantRows
org.drools.workbench.services.verifier.plugin.client.DecisionTableAnalyzerMultipleIssuesFromFileTest.testMissingRangeAndConflictingRows
org.drools.workbench.services.verifier.plugin.client.DecisionTableAnalyzerMultipleIssuesFromFileTest.testMissingRangeAndSubsumptantRows
org.drools.workbench.services.verifier.plugin.client.DecisionTableAnalyzerMultipleIssuesFromFileTest.testMissingRangeAndMissingColumns
```

**Review by baldimir — APPROVED** [review]

**Review by etirelli — APPROVED** [review]

**Pull request merged**
