### PR TITLE
Memory leak when using dynamicFacts

### PR DESCRIPTION
**Pull request by Thebas**
You are adding handles
addPropertyChangeListener

dynamicFacts.add( handle );

but you're trying to remove objects.
This HashMap grows indefinitely until heap is exhausted.
Make it dynamicFacts.remove( handle );

**Thank you for submitting this pull request**

**NOTE!:** Double check the target branch for this PR.
The default is `main` so it will target Drools 8 / Kogito / Optaplanner 8.
If this PR is not strictly related to drools and kogito project in `drools.git`, it should probably target `7.x`as a branch

**Ports** If a forward-port or a backport is needed, paste the forward port PR here

[link](https://www.example.com)

**JIRA**: _(please edit the JIRA link if it exists)_

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>

* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Thebas** [comment]
Unit tests should catch this.

**Comment by triceo** [comment]
ok to test

**Review by mariofusco — APPROVED** [review]

**Comment by Thebas** [comment]
Hello! This issue is still in latest versions of the kie-server(7).
Any possibility of releasing it on the version 7.X ?

Thank you!

**Comment by Thebas** [comment]
https://github.com/kiegroup/drools/commit/c2c82988c02fdee1576855b2edececd1795f2c3a

Hello! When do you think this bugfix will be released? It is essential for our use case (European Commission).
It is not available here yet: https://quay.io/repository/kiegroup/kie-server-showcase?tab=tags&tag=latest
7.75.0 should contain it correct?
@mariofusco @triceo @kie-ci

**Pull request merged**
