### PR TITLE
RHDM-478_7.5.x

### PR DESCRIPTION
**Pull request by lanceleverich**
RHDM-478 PMML assets are not compiled by kie-maven-plugin
* Copied kie.conf for the kie-pmml project to the test/resources/META-INF directory
* Moved kie.conf for the drools-pmml project to the test/resources/META-INF directory

### CODE REVIEW

**Comment by mariofusco** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by lanceleverich** [comment]
Jenkins execute full downstream build

**Comment by lanceleverich** [comment]
Can I get this PR merged? None of the test failures appear to be connected to the code that is in this PR.

**Comment by lanceleverich** [comment]
This PR is no longer needed

**Pull request closed without merging**
