### PR TITLE
[DROOLS-1200] Multibyte bind variable name fails with java dialect

### PR DESCRIPTION
**Pull request by tkobayas**
- Unit test

### CODE REVIEW

**Comment by baldimir** [comment]
Hi, thanks for the test. I tried it and it fails also for me. 

One question though. Would it be possible to move it somewhere else please? The Misc2Test class is pretty huge now. We have a new class for unicode tests here [1]. Maybe that can be a good fit for this test. What do you think? 

Thanks, 

Tibor

[1] https://github.com/droolsjbpm/drools/blob/master/drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/UnicodeTest.java

**Comment by tkobayas** [comment]
Hi Tibor,

I wasn't aware of the "UnicodeTest", thanks! I changed the commit to put it in UnicodeTest.

**Comment by baldimir** [comment]
Hi Toshiya, great, thanks! :)

**Comment by baldimir** [comment]
+1

**Comment by mariofusco** [comment]
Test case incorporated and fixed by https://github.com/droolsjbpm/drools/commit/9781eb38089de0c5a1d644a36edef732be7e0e59

**Pull request closed without merging**
