### PR TITLE
RHDM-1688 DROOLS-6267 DMN DT Analysis Collect 1NF as Warning

### PR DESCRIPTION
**Pull request by tarilabs**
backport to `7.52.x` of https://github.com/kiegroup/drools/pull/3526

**JIRA**: https://issues.redhat.com/browse/DROOLS-6267

**referenced Pull Requests**: none

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by hellowdan — APPROVED** [review]

**Comment by tarilabs** [comment]
Why no jenkins is unknown to me🤷‍♂️

Jenkins test again

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
Helloooo? Jenkiiiins??

Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by tarilabs** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by Ginxo** [comment]
jenkins retest this

**Comment by Ginxo** [comment]
jenkins retest this

**Comment by Ginxo** [comment]
jenkins retest this

**Comment by Ginxo** [comment]
jenkins retest this

**Comment by Ginxo** [comment]
jenkins retest this

**Comment by Ginxo** [comment]
jenkins retest this

**Comment by Ginxo** [comment]
@tarilabs @mareknovotny our drools job was only considering `master` target branch. `7.52.x` added to pipeline configuration and to "Github pull request builder" plugin whitelist

**Comment by tarilabs** [comment]
*cough* `allowlist` *cough* :) 

thank you @Ginxo for fixing this, is really appreciated!

**Comment by mareknovotny** [comment]
i see, thanks @Ginxo 

@tarilabs that field in Jenkins job configuration is called like @Ginxo wrote ;) we can't reference it like you suggested to confuse each other ;)

**Comment by Ginxo** [comment]
`You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.` This is happening more frequent that we would like to. I'm starting to think we will have to add an sleep option from build chain CLI in order to avoid this kind of problems otherwise the tool is faster than Github API expects to be by someone/something using them.
Retriggering...

**Comment by Ginxo** [comment]
jenkins retest this

**Comment by Ginxo** [comment]
> _cough_ `allowlist` _cough_ :)
> 
> thank you @Ginxo for fixing this, is really appreciated!

I would prefer `allowlist` but it's the way the plugin defines it :disappointed:

**Comment by tarilabs** [comment]
I guess I can now safely ask for this merge, now, right? 
image

**Comment by tarilabs** [comment]
cdb failure unrelated
```
09:25:27  [INFO]  [kiegroup/droolsjbpm-knowledge] Checking out 'https://github.com/kiegroup/droolsjbpm-knowledge:7.52.x'  into 'bc/kiegroup_droolsjbpm_knowledge'
09:25:28  [INFO]  [kiegroup/droolsjbpm-knowledge] Checked out.
09:25:28  [INFO]  [kiegroup/drools] Checking out project
09:25:29  [ERROR]  You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.
```
https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/7.52.x/job/compile/job/drools-7.52.x.compile/21/

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
