### PR TITLE
DROOLS-2252: Increase coverage of marshaling from accumulate

### PR DESCRIPTION
**Pull request by jomarko**
Dependent on #1700 , @manstis please have a look.

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko I don't mind the additional check, so feel free to rebase and resubmit; however ```assertDSLEscaping(..)``` checks every line in the ```WHEN``` part is starts with ```>```

**Comment by jomarko** [comment]
@manstis I agree that `assertDSLEscaping` asserts every line starts with '>' but I also think that `assertDSLEscaping` pass, if there are no lines, so I think my test enhancement makes sense, WDYT?

**Comment by manstis** [comment]
@jomarko Like I said; I don't mind the additional check - and you're right it is an enhancement :-)

**Comment by jomarko** [comment]
@manstis This PR is ready for merge.

**Review by manstis — APPROVED** [review]

**Pull request merged**
